import Collatz.Research.FirstDescent.Batch001
import Collatz.Research.FirstDescent.Batch002
import Collatz.Research.FirstDescent.Batch003
import Collatz.Research.FirstDescent.Batch004
import Collatz.Research.FirstDescent.Batch005
import Collatz.Research.FirstDescent.Batch006
import Collatz.Research.FirstDescent.Batch007
import Collatz.Research.FirstDescent.Batch008
import Collatz.Research.FirstDescent.Batch009
import Collatz.Research.FirstDescent.Batch010
import Collatz.Research.FirstDescent.Batch011
import Collatz.Research.FirstDescent.Batch012
import Collatz.Research.FirstDescent.Batch013
import Collatz.Research.FirstDescent.Batch014
import Collatz.Research.FirstDescent.Batch015
import Collatz.Research.FirstDescent.Batch016
import Collatz.Research.FirstDescent.Batch017
import Collatz.Research.FirstDescent.Batch018
import Collatz.Research.FirstDescent.Batch019
import Collatz.Research.FirstDescent.Batch020
import Collatz.Research.FirstDescent.Batch021
import Collatz.Research.FirstDescent.Batch022
import Collatz.Research.FirstDescent.Batch023
import Collatz.Research.FirstDescent.Batch024
import Collatz.Research.FirstDescent.Batch025
import Collatz.Research.FirstDescent.Batch026
import Collatz.Research.FirstDescent.Batch027
import Collatz.Research.FirstDescent.Batch028
import Collatz.Research.FirstDescent.Batch029
import Collatz.Research.FirstDescent.Batch030
import Collatz.Research.FirstDescent.Batch031
import Collatz.Research.FirstDescent.Batch032
import Collatz.Research.FirstDescent.Batch033
import Collatz.Research.FirstDescent.Batch034
import Collatz.Research.FirstDescent.Batch035
import Collatz.Research.FirstDescent.Batch036
import Collatz.Research.FirstDescent.Batch037
import Collatz.Research.FirstDescent.Batch038
import Collatz.Research.FirstDescent.Batch039
import Collatz.Research.FirstDescent.Batch040
import Collatz.Research.FirstDescent.Batch041
import Collatz.Research.FirstDescent.Batch042
import Collatz.Research.FirstDescent.Batch043
import Collatz.Research.FirstDescent.Batch044
import Collatz.Research.FirstDescent.Batch045
import Collatz.Research.FirstDescent.Batch046
import Collatz.Research.FirstDescent.Batch047
import Collatz.Research.FirstDescent.Batch048
import Collatz.Research.FirstDescent.Batch049
import Collatz.Research.FirstDescent.Batch050
import Collatz.Research.FirstDescent.Batch051
import Collatz.Research.FirstDescent.Batch052
import Collatz.Research.FirstDescent.Batch053
import Collatz.Research.FirstDescent.Batch054
import Collatz.Research.FirstDescent.Batch055
import Collatz.Research.FirstDescent.Batch056
import Collatz.Research.FirstDescent.Batch057
import Collatz.Research.FirstDescent.Batch058
import Collatz.Research.FirstDescent.Batch059
import Collatz.Research.FirstDescent.Batch060
import Collatz.Research.FirstDescent.Batch061
import Collatz.Research.FirstDescent.Batch062
import Collatz.Research.FirstDescent.Batch063
import Collatz.Research.FirstDescent.Batch064
import Collatz.Research.FirstDescent.Batch065
import Collatz.Research.FirstDescent.Batch066
import Collatz.Research.FirstDescent.Batch067
import Collatz.Research.FirstDescent.Batch068
import Collatz.Research.FirstDescent.Batch069
import Collatz.Research.FirstDescent.Batch070
import Collatz.Research.FirstDescent.Batch071
import Collatz.Research.FirstDescent.Batch072
import Collatz.Research.FirstDescent.Batch073
import Collatz.Research.FirstDescent.Batch074
import Collatz.Research.FirstDescent.Batch075
import Collatz.Research.FirstDescent.Batch076
import Collatz.Research.FirstDescent.Batch077
import Collatz.Research.FirstDescent.Batch078
import Collatz.Research.FirstDescent.Batch079
import Collatz.Research.FirstDescent.Batch080
import Collatz.Research.FirstDescent.Batch081
import Collatz.Research.FirstDescent.Batch082
import Collatz.Research.FirstDescent.Batch083
import Collatz.Research.FirstDescent.Batch084
import Collatz.Research.FirstDescent.Batch085
import Collatz.Research.FirstDescent.Batch086
import Collatz.Research.FirstDescent.Batch087
import Collatz.Research.FirstDescent.Batch088
import Collatz.Research.FirstDescent.Batch089
import Collatz.Research.FirstDescent.Batch090
import Collatz.Research.FirstDescent.Batch091
import Collatz.Research.FirstDescent.Batch092
import Collatz.Research.FirstDescent.Batch093
import Collatz.Research.FirstDescent.Batch094
import Collatz.Research.FirstDescent.Batch095
import Collatz.Research.FirstDescent.Batch096
import Collatz.Research.FirstDescent.Batch097
import Collatz.Research.FirstDescent.Batch098
import Collatz.Research.FirstDescent.Batch099
import Collatz.Research.FirstDescent.Batch100
import Collatz.Research.FirstDescent.Batch101
import Collatz.Research.FirstDescent.Batch102
import Collatz.Research.FirstDescent.Batch103
import Collatz.Research.FirstDescent.Batch104
import Collatz.Research.FirstDescent.Batch105
import Collatz.Research.FirstDescent.Batch106
import Collatz.Research.FirstDescent.Batch107
import Collatz.Research.FirstDescent.Batch108
import Collatz.Research.FirstDescent.Batch109
import Collatz.Research.FirstDescent.Batch110
import Collatz.Research.FirstDescent.Batch111
import Collatz.Research.FirstDescent.Batch112
import Collatz.Research.FirstDescent.Batch113
import Collatz.Research.FirstDescent.Batch114
import Collatz.Research.FirstDescent.Batch115
import Collatz.Research.FirstDescent.Batch116
import Collatz.Research.FirstDescent.Batch117
import Collatz.Research.FirstDescent.Batch118
import Collatz.Research.FirstDescent.Batch119
import Collatz.Research.FirstDescent.Batch120
import Collatz.Research.FirstDescent.Batch121
import Collatz.Research.FirstDescent.Batch122
import Collatz.Research.FirstDescent.Batch123
import Collatz.Research.FirstDescent.Batch124
import Collatz.Research.FirstDescent.Batch125
import Collatz.Research.FirstDescent.Batch126
import Collatz.Research.FirstDescent.Batch127
import Collatz.Research.FirstDescent.Batch128
import Collatz.Research.FirstDescent.Batch129
import Collatz.Research.FirstDescent.Batch130
import Collatz.Research.FirstDescent.Batch131
import Collatz.Research.FirstDescent.Batch132
import Collatz.Research.FirstDescent.Batch133
import Collatz.Research.FirstDescent.Batch134
import Collatz.Research.FirstDescent.Batch135
import Collatz.Research.FirstDescent.Batch136
import Collatz.Research.FirstDescent.Batch137
import Collatz.Research.FirstDescent.Batch138
import Collatz.Research.FirstDescent.Batch139
import Collatz.Research.FirstDescent.Batch140
import Collatz.Research.FirstDescent.Batch141
import Collatz.Research.FirstDescent.Batch142
import Collatz.Research.FirstDescent.Batch143
import Collatz.Research.FirstDescent.Batch144
import Collatz.Research.FirstDescent.Batch145
import Collatz.Research.FirstDescent.Batch146
import Collatz.Research.FirstDescent.Batch147
import Collatz.Research.FirstDescent.Batch148
import Collatz.Research.FirstDescent.Batch149
import Collatz.Research.FirstDescent.Batch150
import Collatz.Research.FirstDescent.Batch151
import Collatz.Research.FirstDescent.Batch152
import Collatz.Research.FirstDescent.Batch153
import Collatz.Research.FirstDescent.Batch154
import Collatz.Research.FirstDescent.Batch155
import Collatz.Research.FirstDescent.Batch156
import Collatz.Research.FirstDescent.Batch157
import Collatz.Research.FirstDescent.Batch158
import Collatz.Research.FirstDescent.Batch159
import Collatz.Research.FirstDescent.Batch160
import Collatz.Research.FirstDescent.Batch161
import Collatz.Research.FirstDescent.Batch162
import Collatz.Research.FirstDescent.Batch163
import Collatz.Research.FirstDescent.Batch164
import Collatz.Research.FirstDescent.Batch165
import Collatz.Research.FirstDescent.Batch166
import Collatz.Research.FirstDescent.Batch167
import Collatz.Research.FirstDescent.Batch168
import Collatz.Research.FirstDescent.Batch169
import Collatz.Research.FirstDescent.Batch170
import Collatz.Research.FirstDescent.Batch171
import Collatz.Research.FirstDescent.Batch172
import Collatz.Research.FirstDescent.Batch173
import Collatz.Research.FirstDescent.Batch174
import Collatz.Research.FirstDescent.Batch175
import Collatz.Research.FirstDescent.Batch176
import Collatz.Research.FirstDescent.Batch177
import Collatz.Research.FirstDescent.Batch178
import Collatz.Research.FirstDescent.Batch179
import Collatz.Research.FirstDescent.Batch180
import Collatz.Research.FirstDescent.Batch181
import Collatz.Research.FirstDescent.Batch182
import Collatz.Research.FirstDescent.Batch183
import Collatz.Research.FirstDescent.Batch184
import Collatz.Research.FirstDescent.Batch185
import Collatz.Research.FirstDescent.Batch186
import Collatz.Research.FirstDescent.Batch187
import Collatz.Research.FirstDescent.Batch188
import Collatz.Research.FirstDescent.Batch189
import Collatz.Research.FirstDescent.Batch190
import Collatz.Research.FirstDescent.Batch191
import Collatz.Research.FirstDescent.Batch192
import Collatz.Research.FirstDescent.Batch193
import Collatz.Research.FirstDescent.Batch194
import Collatz.Research.FirstDescent.Batch195
import Collatz.Research.FirstDescent.Batch196
import Collatz.Research.FirstDescent.Batch197
import Collatz.Research.FirstDescent.Batch198
import Collatz.Research.FirstDescent.Batch199
import Collatz.Research.FirstDescent.Batch200
import Collatz.Research.FirstDescent.Batch201
import Collatz.Research.FirstDescent.Batch202
import Collatz.Research.FirstDescent.Batch203
import Collatz.Research.FirstDescent.Batch204
import Collatz.Research.FirstDescent.Batch205
import Collatz.Research.FirstDescent.Batch206
import Collatz.Research.FirstDescent.Batch207
import Collatz.Research.FirstDescent.Batch208
import Collatz.Research.FirstDescent.Batch209
import Collatz.Research.FirstDescent.Batch210
import Collatz.Research.FirstDescent.Batch211
import Collatz.Research.FirstDescent.Batch212
import Collatz.Research.FirstDescent.Batch213
import Collatz.Research.FirstDescent.Batch214
import Collatz.Research.FirstDescent.Batch215
import Collatz.Research.FirstDescent.Batch216
import Collatz.Research.FirstDescent.Batch217
import Collatz.Research.FirstDescent.Batch218
import Collatz.Research.FirstDescent.Batch219
import Collatz.Research.FirstDescent.Batch220
import Collatz.Research.FirstDescent.Batch221
import Collatz.Research.FirstDescent.Batch222
import Collatz.Research.FirstDescent.Batch223
import Collatz.Research.FirstDescent.Batch224
import Collatz.Research.FirstDescent.Batch225
import Collatz.Research.FirstDescent.Batch226
import Collatz.Research.FirstDescent.Batch227
import Collatz.Research.FirstDescent.Batch228
import Collatz.Research.FirstDescent.Batch229
import Collatz.Research.FirstDescent.Batch230
import Collatz.Research.FirstDescent.Batch231
import Collatz.Research.FirstDescent.Batch232
import Collatz.Research.FirstDescent.Batch233
import Collatz.Research.FirstDescent.Batch234
import Collatz.Research.FirstDescent.Batch235
import Collatz.Research.FirstDescent.Batch236
import Collatz.Research.FirstDescent.Batch237
import Collatz.Research.FirstDescent.Batch238
import Collatz.Research.FirstDescent.Batch239
import Collatz.Research.FirstDescent.Batch240
import Collatz.Research.FirstDescent.Batch241
import Collatz.Research.FirstDescent.Batch242
import Collatz.Research.FirstDescent.Batch243
import Collatz.Research.FirstDescent.Batch244
import Collatz.Research.FirstDescent.Batch245
import Collatz.Research.FirstDescent.Batch246
import Collatz.Research.FirstDescent.Batch247
import Collatz.Research.FirstDescent.Batch248
import Collatz.Research.FirstDescent.Batch249
import Collatz.Research.FirstDescent.Batch250
import Collatz.Research.FirstDescent.Batch251
import Collatz.Research.FirstDescent.Batch252
import Collatz.Research.FirstDescent.Batch253
import Collatz.Research.FirstDescent.Batch254
import Collatz.Research.FirstDescent.Batch255
import Collatz.Research.FirstDescent.Batch256
import Collatz.Research.FirstDescent.Batch257
import Collatz.Research.FirstDescent.Batch258
import Collatz.Research.FirstDescent.Batch259
import Collatz.Research.FirstDescent.Batch260
import Collatz.Research.FirstDescent.Batch261
import Collatz.Research.FirstDescent.Batch262
import Collatz.Research.FirstDescent.Batch263
import Collatz.Research.FirstDescent.Batch264
import Collatz.Research.FirstDescent.Batch265
import Collatz.Research.FirstDescent.Batch266
import Collatz.Research.FirstDescent.Batch267
import Collatz.Research.FirstDescent.Batch268
import Collatz.Research.FirstDescent.Batch269
import Collatz.Research.FirstDescent.Batch270
import Collatz.Research.FirstDescent.Batch271
import Collatz.Research.FirstDescent.Batch272
import Collatz.Research.FirstDescent.Batch273
import Collatz.Research.FirstDescent.Batch274
import Collatz.Research.FirstDescent.Batch275
import Collatz.Research.FirstDescent.Batch276
import Collatz.Research.FirstDescent.Batch277
import Collatz.Research.FirstDescent.Batch278
import Collatz.Research.FirstDescent.Batch279
import Collatz.Research.FirstDescent.Batch280
import Collatz.Research.FirstDescent.Batch281
import Collatz.Research.FirstDescent.Batch282
import Collatz.Research.FirstDescent.Batch283
import Collatz.Research.FirstDescent.Batch284
import Collatz.Research.FirstDescent.Batch285
import Collatz.Research.FirstDescent.Batch286
import Collatz.Research.FirstDescent.Batch287
import Collatz.Research.FirstDescent.Batch288
import Collatz.Research.FirstDescent.Batch289
import Collatz.Research.FirstDescent.Batch290
import Collatz.Research.FirstDescent.Batch291
import Collatz.Research.FirstDescent.Batch292
import Collatz.Research.FirstDescent.Batch293
import Collatz.Research.FirstDescent.Batch294
import Collatz.Research.FirstDescent.Batch295
import Collatz.Research.FirstDescent.Batch296
import Collatz.Research.FirstDescent.Batch297
import Collatz.Research.FirstDescent.Batch298
import Collatz.Research.FirstDescent.Batch299
import Collatz.Research.FirstDescent.Batch300
