import MathlibAttack.Papers.Core

/-!
Mathlib-backed Lean notes for Takehiko Mori, "Application of Operator Theory for the Collatz Conjecture", arXiv:2411.08084 [2024].

Title: Application of Operator Theory for the Collatz Conjecture

Abstract (truncated):
The Collatz map (or the $3n{+}1$-map) $f$ is defined on positive integers by setting $f(n)$ equal to $3n+1$ when $n$ is odd and $n/2$ when $n$ is even. The Collatz conjecture states that starting from any positive integer $n$, some iterate of $f$ takes value $1$. In this study, we discuss formulations of the Collatz conjecture by $C^{*}$-algebras in the following three ways: (1) single operator, (2) two operators, and (3) Cuntz algebra. For the $C^{*}$-algebra generated by each of these, we consider the condition that it has no non-trivial reducing subspaces. For (1), we prove that the condition implies the Collatz conjecture. In the cases (2) and (3), we prove that the condition is equivalent to the Collatz conjecture. For similar maps, we introduce equivalence relations by them and generalize connections between the Collatz conjecture and irreducibility of associated $C^{*}$-algebras.

Uses Mathlib (`ℚ`, `omega`, positivity-style facts via Core).
Status: `mainStatement` records the paper claim; only named lemmas are proved.
Source: https://arxiv.org/abs/2411.08084
-/

namespace MathlibAttack.Papers.Arxiv2411_08084

open MathlibAttack.Papers

def citation : String := "Takehiko Mori, \"Application of Operator Theory for the Collatz Conjecture\", arXiv:2411.08084 [2024]."

/-- Recorded claim shell (generalization); paper theorem not proved.
Placeholder equals the Collatz conjecture proposition. -/
def mainStatement : Prop := CollatzConjecture

theorem step_one_eq : step 1 = 4 := step_one
theorem step_two_eq : step 2 = 1 := step_two

end MathlibAttack.Papers.Arxiv2411_08084
