import MathlibAttack.Papers.Core

/-!
Mathlib-backed Lean notes for Kyo Jin Ihn, "Modular Arithmetic Study on Ascending and Descending Operations Related with Collatz Conjecture", arXiv:2311.12038 [2023].

Title: Modular Arithmetic Study on Ascending and Descending Operations Related with Collatz Conjecture

Abstract (truncated):
Sequence of numbers generated by the recurrence relation based on the Collatz conjecture is investigated. An arithmetic operation on the Collatz conjecture is called descending operation, and ascending operation is carried out reversely to the descending operation. Study on the 3x+1 problem against every integer is relevant to that of descending operation against every odd. Any odds can be generated by ascending operations against odds not multiple of 3, and vise versa. Ascending operations against an odd not a multiple of 3 can generate infinite number of odds in the next generation. The odds multiple of 3 are terminal numbers of sequences that no further ascending operations are possible. Descending operations against the odds 1,5,21,.. reach 1, and otherwise reach the odds greater than or equal to 5. No two odds except 1 in each sequence are the same, and the each descending sequence 

Uses Mathlib (`ℚ`, `omega`, positivity-style facts via Core).
Status: `mainStatement` records the paper claim; only named lemmas are proved.
Source: https://arxiv.org/abs/2311.12038
-/

namespace MathlibAttack.Papers.Arxiv2311_12038

open MathlibAttack.Papers

def citation : String := "Kyo Jin Ihn, \"Modular Arithmetic Study on Ascending and Descending Operations Related with Collatz Conjecture\", arXiv:2311.12038 [2023]."

/-- Recorded claim shell (logic); paper theorem not proved.
Placeholder equals the Collatz conjecture proposition. -/
def mainStatement : Prop := CollatzConjecture

theorem step_one_eq : step 1 = 4 := step_one
theorem step_two_eq : step 2 = 1 := step_two

end MathlibAttack.Papers.Arxiv2311_12038
