import MathlibAttack.Papers.Core

/-!
Mathlib-backed Lean notes for Mikhail Neklyudov, "Functional analysis approach to the Collatz conjecture", arXiv:2106.11859 [2021].

Title: Functional analysis approach to the Collatz conjecture

Abstract (truncated):
We investigate the problems related to the Collatz map $T$ from the point of view of functional analysis. We associate with $T$ certain linear operator $\mathcal{T}$ and show that cycles and (hypothetical) diverging trajectory (generated by $T$) correspond to certain classes of fixed points of operator $\mathcal{T}$. Furthermore, we demonstrate connection between dynamical properties of operator $\mathcal{T}$ and map $T$. We prove that absence of nontrivial cycles of $T$ leads to hypercyclicity of operator $\mathcal{T}$. In the second part we show that the index of operator $Id-\mathcal{T}\in\mathcal{L}(H^2(D))$ gives upper estimate on the number of cycles of $T$. For the proof we consider the adjoint operator $\mathcal{F}=\mathcal{T}^*$ \[ \mathcal{F}: g\to g(z^2)+\frac{z^{-\frac{1}{3}}}{3}\left(g(z^{\frac{2}{3}})+e^{\frac{2πi}{3}}g(z^{\frac{2}{3}}e^{\frac{2πi}{3}})+e^{\frac{4πi}{3}}g(z

Uses Mathlib (`ℚ`, `omega`, positivity-style facts via Core).
Status: `mainStatement` records the paper claim; only named lemmas are proved.
Source: https://arxiv.org/abs/2106.11859
-/

namespace MathlibAttack.Papers.Arxiv2106_11859

open MathlibAttack.Papers

def citation : String := "Mikhail Neklyudov, \"Functional analysis approach to the Collatz conjecture\", arXiv:2106.11859 [2021]."

/-- Recorded cycle-exclusion shell (paper theorem not proved). -/
def mainStatement : Prop :=
  ∀ n : ℕ, 1 < n → ∀ k : ℕ, 0 < k → orbit k n = n →
    ∃ j : ℕ, j ≤ k ∧ orbit j n = 1

/-- Checked: the trivial 1-cycle returns. -/
theorem orbit_one_cycle : orbit 3 1 = 1 :=
  MathlibAttack.Papers.orbit_one_returns

end MathlibAttack.Papers.Arxiv2106_11859
