import MathlibAttack.Papers.Core

/-!
Mathlib-backed Lean notes for Leonel da Silveira Lobo Sternberg, "Predictable trajectories of the reduced Collatz iteration and a possible pathway to the proof of the Collatz conjecture (Version 2)", arXiv:2209.14230 [2022].

Title: Predictable trajectories of the reduced Collatz iteration and a possible pathway to the proof of the Collatz conjecture (Version 2)

Abstract (truncated):
I show here that there are three different kinds of iterations for the reduced Collatz algorithm; depending on whether the root of the number is odd or even. There is only one kind of iteration if the root is odd and two kinds if the root is even. I also show that iterations on numbers with odd roots will cause an increase in value and eventually lead to an even rooted number. The iterations on even rooted numbers will subsequently cause a decrease in values. Because increase in values during the odd root iterations are bounded, I conclude that the Collatz iteration cannot veer to infinity. Since the sequence generated by the Collatz iteration is infinite and the values of the numbers do not veer to infinity it must either cycle and/or converge. I postulate that any cycling must occur with alternating types of iterations: e.g. odd rooted iterations which cause the values of the numbers t

Uses Mathlib (`ℚ`, `omega`, positivity-style facts via Core).
Status: `mainStatement` records the paper claim; only named lemmas are proved.
Source: https://arxiv.org/abs/2209.14230
-/

namespace MathlibAttack.Papers.Arxiv2209_14230

open MathlibAttack.Papers

def citation : String := "Leonel da Silveira Lobo Sternberg, \"Predictable trajectories of the reduced Collatz iteration and a possible pathway to the proof of the Collatz conjecture (Version 2)\", arXiv:2209.14230 [2022]."

/-- Recorded cycle-exclusion shell (paper theorem not proved). -/
def mainStatement : Prop :=
  ∀ n : ℕ, 1 < n → ∀ k : ℕ, 0 < k → orbit k n = n →
    ∃ j : ℕ, j ≤ k ∧ orbit j n = 1

/-- Checked: the trivial 1-cycle returns. -/
theorem orbit_one_cycle : orbit 3 1 = 1 :=
  MathlibAttack.Papers.orbit_one_returns

end MathlibAttack.Papers.Arxiv2209_14230
