import Collatz.Basic
import Collatz.Accelerated
import Collatz.Core.Arith
import Collatz.Core.Minimum
import Collatz.Core.Pigeonhole
import Collatz.Core.Sum
import Collatz.Core.Reach
import Collatz.Search.Descent
import Collatz.Search.StoppingTime
import Collatz.Search.Verify
import Collatz.Structure.AccCycle
import Collatz.Structure.Congruence
import Collatz.Structure.Cycle
import Collatz.Structure.Density
import Collatz.Structure.Divergence
import Collatz.Structure.Minimal
import Collatz.Structure.Obstruction
import Collatz.Structure.Predecessor
import Collatz.Structure.ShortCycles
import Collatz.Strategy.Pillars
import Collatz.Strategy.Reductions
import Collatz.Strategy.Terras
import Collatz.Registry
import Collatz.Papers.Lagarias1985
import Collatz.Papers.Lagarias2003Bibliography
import Collatz.Papers.Everett1977
import Collatz.Papers.Terras1976
import Collatz.Papers.Tao2022
import Collatz.Papers.KrasikovLagarias2003
import Collatz.Papers.Conway1972
import Collatz.Papers.Template
