import Collatz.Basic
import Collatz.Accelerated
import Collatz.Core.Arith
import Collatz.Core.Minimum
import Collatz.Core.Pigeonhole
import Collatz.Core.Sum
import Collatz.Core.Reach
import Collatz.Search.Descent
import Collatz.Search.StoppingTime
import Collatz.Search.Sieved
import Collatz.Search.Verify
import Collatz.Structure.AccCycle
import Collatz.Structure.AccDivergence
import Collatz.Structure.AffineBound
import Collatz.Structure.AffineBoundSharp
import Collatz.Structure.CycleLength
import Collatz.Structure.CycleLengthSharp
import Collatz.Structure.CycleModThree
import Collatz.Structure.CycleMinClass
import Collatz.Structure.CycleMaxClass
import Collatz.Structure.CycleSum
import Collatz.Structure.CycleValuation
import Collatz.Structure.CycleOddCount
import Collatz.Structure.CycleExtremes
import Collatz.Structure.Congruence
import Collatz.Structure.Cycle
import Collatz.Structure.Density
import Collatz.Structure.Divergence
import Collatz.Structure.Minimal
import Collatz.Structure.MinimalHeavy
import Collatz.Structure.OrbitMin
import Collatz.Structure.HeavySet
import Collatz.Structure.OrbitMinSieve
import Collatz.Structure.ForcedSteps
import Collatz.Structure.Records
import Collatz.Structure.Obstruction
import Collatz.Structure.Predecessor
import Collatz.Structure.ShortCycles
import Collatz.Strategy.Pillars
import Collatz.Strategy.Reductions
import Collatz.Strategy.Terras
import Collatz.Chains.Descent
import Collatz.Chains.Targets
import Collatz.Chains.Cycles
import Collatz.Chains.Modular
import Collatz.Chains.Parity
import Collatz.Chains.Index
import Collatz.Chains.CycleTargets
import Collatz.Chains.Arithmetic
import Collatz.Chains.Sharp
import Collatz.Chains.MinClass
import Collatz.Chains.Valuation
import Collatz.Chains.OddCount
import Collatz.Chains.MaxClass
import Collatz.Chains.Heavy
import Collatz.Chains.OrbitMin
import Collatz.Chains.OrbitSieve
import Collatz.Chains.SumChains
import Collatz.Registry
import Collatz.Papers.Lagarias1985
import Collatz.Papers.Lagarias2003Bibliography
import Collatz.Papers.Everett1977
import Collatz.Papers.Terras1976
import Collatz.Papers.Tao2022
import Collatz.Papers.KrasikovLagarias2003
import Collatz.Papers.Conway1972
import Collatz.Papers.Template
