import Collatz.Strategy.FirstLight1024Chunks.C04

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_05 :
    checkInterval 135 10240 2048 = true := by decide

theorem prefix_12288 : checkInterval 135 0 12288 = true :=
  checkInterval_append 135 0 10240 2048
    prefix_10240 block_05

end Collatz.FirstLight1024Chunks
