import Collatz.Strategy.FirstLight1024Chunks.C05

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_06 :
    checkInterval 135 12288 2048 = true := by decide

theorem prefix_14336 : checkInterval 135 0 14336 = true :=
  checkInterval_append 135 0 12288 2048
    prefix_12288 block_06

end Collatz.FirstLight1024Chunks
