import Collatz.Strategy.FirstLight1024Chunks.C11

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_12 :
    checkInterval 135 24576 2048 = true := by decide

theorem prefix_26624 : checkInterval 135 0 26624 = true :=
  checkInterval_append 135 0 24576 2048
    prefix_24576 block_12

end Collatz.FirstLight1024Chunks
