import Collatz.Strategy.FirstLight1024Chunks.C12

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_13 :
    checkInterval 135 26624 2048 = true := by decide

theorem prefix_28672 : checkInterval 135 0 28672 = true :=
  checkInterval_append 135 0 26624 2048
    prefix_26624 block_13

end Collatz.FirstLight1024Chunks
