import Collatz.Strategy.FirstLight1024Chunks.C20

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_21 :
    checkInterval 135 43008 2048 = true := by decide

theorem prefix_45056 : checkInterval 135 0 45056 = true :=
  checkInterval_append 135 0 43008 2048
    prefix_43008 block_21

end Collatz.FirstLight1024Chunks
