import Collatz.Strategy.FirstLight1024Chunks.C23

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_24 :
    checkInterval 135 49152 2048 = true := by decide

theorem prefix_51200 : checkInterval 135 0 51200 = true :=
  checkInterval_append 135 0 49152 2048
    prefix_49152 block_24

end Collatz.FirstLight1024Chunks
