import Collatz.Strategy.FirstLight1024Chunks.C27

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_28 :
    checkInterval 135 57344 2048 = true := by decide

theorem prefix_59392 : checkInterval 135 0 59392 = true :=
  checkInterval_append 135 0 57344 2048
    prefix_57344 block_28

end Collatz.FirstLight1024Chunks
