import Collatz.Strategy.FirstLight1024Chunks.C40

/-! Generated by scripts/generate_first_light_1024.py.
One kernel-checked block and the resulting cumulative prefix.
Separate compiler processes bound reduction memory. -/
namespace Collatz.FirstLight1024Chunks
open FirstLightScan

set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option Elab.async false

private theorem block_41 :
    checkInterval 135 83968 2048 = true := by decide

theorem prefix_86016 : checkInterval 135 0 86016 = true :=
  checkInterval_append 135 0 83968 2048
    prefix_83968 block_41

end Collatz.FirstLight1024Chunks
