import CollatzTargetDensity.BinaryProfileCertificates

#print CollatzTargetDensity.BinaryProfileReturn.histogram
#print CollatzTargetDensity.BinaryProfileReturn.checkpoint
#check CollatzTargetDensity.BinaryProfileReturn.no_strict_checkpoint_descent
#check CollatzTargetDensity.BinaryProfileReturn.no_nonincreasing_checkpoint_potential

#print axioms CollatzTargetDensity.BinaryProfileReturn.pathCheck_sound
#print axioms CollatzTargetDensity.BinaryProfileReturn.Chunk.successor
#print axioms CollatzTargetDensity.BinaryProfileReturn.chain_le
#print axioms CollatzTargetDensity.BinaryProfileReturn.chain_lt
#print axioms CollatzTargetDensity.BinaryProfileReturn.checked_return_not_strict
#print axioms CollatzTargetDensity.BinaryProfileReturn.checked_return_not_nonincreasing
#print axioms CollatzTargetDensity.BinaryProfileReturn.small_return_checked
#print axioms CollatzTargetDensity.BinaryProfileReturn.sparse_return_checked
#print axioms CollatzTargetDensity.BinaryProfileReturn.returns_up_to_five_checked
#print axioms CollatzTargetDensity.BinaryProfileReturn.return_checked_of_width
#print axioms CollatzTargetDensity.BinaryProfileReturn.no_strict_checkpoint_descent
#print axioms CollatzTargetDensity.BinaryProfileReturn.no_nonincreasing_checkpoint_potential
