import CollatzTargetDensity.DescentVsConvergence

#print CollatzTargetDensity.DescentVsConvergence.badFirstDrop
#check CollatzTargetDensity.DescentVsConvergence.bad_first_drop_positive_density
#check CollatzTargetDensity.DescentVsConvergence.first_drop_implies_convergence_iff_collatz
#check CollatzTargetDensity.DescentVsConvergence.avoids_eq_bad_of_least

#print axioms CollatzTargetDensity.DescentVsConvergence.step_double
#print axioms CollatzTargetDensity.DescentVsConvergence.double_bad
#print axioms CollatzTargetDensity.DescentVsConvergence.double_bad_first_drop
#print axioms CollatzTargetDensity.DescentVsConvergence.count_bad_half_le_first_drop
#print axioms CollatzTargetDensity.DescentVsConvergence.bad_first_drop_positive_density
#print axioms CollatzTargetDensity.DescentVsConvergence.first_drop_implies_convergence_iff_collatz
#print axioms CollatzTargetDensity.DescentVsConvergence.avoids_subset_bad
#print axioms CollatzTargetDensity.DescentVsConvergence.avoids_eq_bad_of_least
#print axioms CollatzTargetDensity.DescentVsConvergence.successor_predecessors_not_subset_higher_tail
