import CollatzTargetDensity.CountingMeasureCheck
import CollatzTargetDensity.AtomicRecurrence

#print Erdos1135.Terras.accelerated
#print CollatzTargetDensity.CountingMeasureCheck.cycleIndicator
#print CollatzTargetDensity.CountingMeasureCheck.visitMean
#print CollatzTargetDensity.AtomicRecurrence.AtomicPowerBound
#check CollatzTargetDensity.CountingMeasureCheck.no_uniform_counting_mean_bound
#check CollatzTargetDensity.CountingMeasureCheck.no_integrable_visitMean_limit
#check CollatzTargetDensity.AtomicRecurrence.collatz_of_atomic_power_bound_and_cycles
#check CollatzTargetDensity.AtomicRecurrence.atomic_power_constant_gt_one

#print axioms CollatzTargetDensity.CountingMeasureCheck.iterate_pow_two
#print axioms CollatzTargetDensity.CountingMeasureCheck.mean_tendsto_of_eventually_eq
#print axioms CollatzTargetDensity.CountingMeasureCheck.visitMean_pow_two_tendsto
#print axioms CollatzTargetDensity.CountingMeasureCheck.cycleIndicator_summable
#print axioms CollatzTargetDensity.CountingMeasureCheck.no_summable_visitMean_limit
#print axioms CollatzTargetDensity.CountingMeasureCheck.cycleIndicator_integrable_count
#print axioms CollatzTargetDensity.CountingMeasureCheck.no_integrable_visitMean_limit
#print axioms CollatzTargetDensity.CountingMeasureCheck.ensembleMean_powerSeeds_tendsto
#print axioms CollatzTargetDensity.CountingMeasureCheck.no_uniform_counting_mean_bound
#print axioms CollatzTargetDensity.CountingMeasureCheck.ensembleMean_three_seeds
#print axioms CollatzTargetDensity.AtomicRecurrence.orbit_atom_le
#print axioms CollatzTargetDensity.AtomicRecurrence.bounded_orbit_of_atomic_power_bound
#print axioms CollatzTargetDensity.AtomicRecurrence.periodic_hit_of_bounded_orbit
#print axioms CollatzTargetDensity.AtomicRecurrence.collatz_of_atomic_power_bound_and_cycles
#print axioms CollatzTargetDensity.AtomicRecurrence.atomic_power_constant_gt_one
