import CollatzTargetDensity.FiniteCutoff

#print Erdos1135.ND.PositiveDensity.ndExplicitRootIntervalHeight
#print Erdos1135.ND.PositiveDensity.ndExplicitRootPublicCutoff
#check Erdos1135.ND.PositiveDensity.NDGeom2ShiftedWideSymmetricRootSideUniformFloorState.targetCount_from_bounded_roots_and_explicit_start
#check CollatzTargetDensity.FiniteCutoff.cutoff_above_least_bad
#check CollatzTargetDensity.FiniteCutoff.positive_density_with_empty_initial_interval
#check CollatzTargetDensity.FiniteCutoff.no_unconditional_activation_by_threshold

#print axioms Erdos1135.ND.PositiveDensity.NDGeom2ShiftedWideSymmetricRootSideUniformFloorState.targetCount_from_explicit_start
#print axioms Erdos1135.ND.PositiveDensity.NDGeom2ShiftedWideSymmetricRootSideUniformFloorState.targetCount_from_bounded_roots_and_explicit_start
#print axioms CollatzTargetDensity.FiniteCutoff.explicit_cutoff_gt_root
#print axioms CollatzTargetDensity.FiniteCutoff.cutoff_above_least_bad
#print axioms CollatzTargetDensity.FiniteCutoff.avoidsAndHitsOne_sound
#print axioms CollatzTargetDensity.FiniteCutoff.rangeAvoidCheck_sound
#print axioms CollatzTargetDensity.FiniteCutoff.range_avoids_3082_checked
#print axioms CollatzTargetDensity.FiniteCutoff.no_predecessor_3082_below_1027
#print axioms CollatzTargetDensity.FiniteCutoff.reaches_one_1027
#print axioms CollatzTargetDensity.FiniteCutoff.positive_density_with_empty_initial_interval
#print axioms CollatzTargetDensity.FiniteCutoff.no_unconditional_activation_by_threshold
