import CollatzTargetDensity.FixedCostGenerators

#print CollatzTargetDensity.FixedCostGenerators.generator
#print CollatzTargetDensity.FixedCostGenerators.geometricProduct
#print CollatzTargetDensity.FixedCostGenerators.count
#check CollatzTargetDensity.FixedCostGenerators.pmf_eq_generator_value
#check CollatzTargetDensity.FixedCostGenerators.uniform_generator_value_lower
#check CollatzTargetDensity.FixedCostGenerators.central_zero_with_positive_value

#print axioms CollatzTargetDensity.FixedCostGenerators.two_pow_period
#print axioms CollatzTargetDensity.FixedCostGenerators.polynomialBoundary_explicit
#print axioms CollatzTargetDensity.FixedCostGenerators.value_succ
#print axioms CollatzTargetDensity.FixedCostGenerators.pmf_unroll
#print axioms CollatzTargetDensity.FixedCostGenerators.pmf_period_equation
#print axioms CollatzTargetDensity.FixedCostGenerators.geometricProduct_pos
#print axioms CollatzTargetDensity.FixedCostGenerators.geometricProduct_le_one
#print axioms CollatzTargetDensity.FixedCostGenerators.geometricProduct_ge_two_thirds
#print axioms CollatzTargetDensity.FixedCostGenerators.normalizer_mul_pmf_eq_value
#print axioms CollatzTargetDensity.FixedCostGenerators.pmf_eq_generator_value
#print axioms CollatzTargetDensity.FixedCostGenerators.sum_value_eq_normalizer
#print axioms CollatzTargetDensity.FixedCostGenerators.uniform_generator_value_lower
#print axioms CollatzTargetDensity.FixedCostGenerators.count_succ
#print axioms CollatzTargetDensity.FixedCostGenerators.count_succ_explicit
#print axioms CollatzTargetDensity.FixedCostGenerators.recursiveCount_eq_count
#print axioms CollatzTargetDensity.FixedCostGenerators.count_two_two_four
#print axioms CollatzTargetDensity.FixedCostGenerators.count_twelve_twelve_seven
#print axioms CollatzTargetDensity.FixedCostGenerators.count_twelve_twelve_one_pos
#print axioms CollatzTargetDensity.FixedCostGenerators.central_zero_with_positive_value
