import CollatzTargetDensity.HarmonicProofGap

#print CollatzTargetDensity.GeneratorPredecessors.sources
#print CollatzTargetDensity.GeneratorPredecessors.harmonicMass
#check CollatzTargetDensity.HarmonicTargets.uniform_raw_logCountingRatio_lower
#check CollatzTargetDensity.HarmonicTargets.least_bad_forces_harmonic_tail

#print axioms CollatzTargetDensity.GeneratorCostTail.evalAt_three_quarters_le
#print axioms CollatzTargetDensity.GeneratorCostTail.value_eq_short_add_tail
#print axioms CollatzTargetDensity.GeneratorCostTail.tailValue_le_tilted
#print axioms CollatzTargetDensity.GeneratorCostTail.tailValue_five_mul_le
#print axioms CollatzTargetDensity.GeneratorCostTail.eventually_shortValue_lower
#print axioms CollatzTargetDensity.GeneratorCostTail.shortValue_eq_cutoffValue
#print axioms CollatzTargetDensity.GeneratorCostTail.cutoffValue_X_pow_mul
#print axioms CollatzTargetDensity.GeneratorCostTail.shortValue_succ
#print axioms CollatzTargetDensity.GeneratorPredecessors.label
#print axioms CollatzTargetDensity.GeneratorPredecessors.child_affine
#print axioms CollatzTargetDensity.GeneratorPredecessors.child_residue
#print axioms CollatzTargetDensity.GeneratorPredecessors.child_syracuse
#print axioms CollatzTargetDensity.GeneratorPredecessors.sources_spec
#print axioms CollatzTargetDensity.GeneratorPredecessors.branches_disjoint
#print axioms CollatzTargetDensity.GeneratorPredecessors.harmonicMass_succ
#print axioms CollatzTargetDensity.GeneratorPredecessors.branch_weight_le
#print axioms CollatzTargetDensity.GeneratorPredecessors.harmonicMass_lower
#print axioms CollatzTargetDensity.GeneratorPredecessors.uniform_harmonicMass_lower
#print axioms CollatzTargetDensity.GeneratorPredecessors.depth_sources_disjoint
#print axioms CollatzTargetDensity.GeneratorPredecessors.sum_harmonicMass_le_prefix
#print axioms CollatzTargetDensity.GeneratorPredecessors.uniform_harmonicPrefix_lower
#print axioms CollatzTargetDensity.HarmonicTargets.logCount_eq_prefix
#print axioms CollatzTargetDensity.HarmonicTargets.finite_harmonic_le_logCount
#print axioms CollatzTargetDensity.HarmonicTargets.sum_harmonicMass_le_raw_logCount
#print axioms CollatzTargetDensity.HarmonicTargets.bounded_nonperiodic_raw_seed
#print axioms CollatzTargetDensity.HarmonicTargets.uniform_raw_logCount_lower
#print axioms CollatzTargetDensity.HarmonicTargets.ratio_lower_of_exponential_prefixes
#print axioms CollatzTargetDensity.HarmonicTargets.uniform_raw_logCountingRatio_lower
#print axioms CollatzTargetDensity.HarmonicTargets.least_bad_forces_harmonic_tail
#print axioms CollatzTargetDensity.HarmonicTargets.reciprocal_eventually_lt_log_bound
