import CollatzTargetDensity.TwoTopologyExample

#print CollatzTargetDensity.InverseBoundary.rationalRemainder
#print CollatzTargetDensity.InverseBoundary.realBoundary
#print CollatzTargetDensity.TwoTopologyExample.q
#check CollatzTargetDensity.InverseBoundary.same_rational_remainders_two_limits
#check CollatzTargetDensity.InverseBoundary.inverse_real_tsum
#check CollatzTargetDensity.TwoTopologyExample.explicit_distinct_limits

#print axioms CollatzTargetDensity.InverseBoundary.scale_succ
#print axioms CollatzTargetDensity.InverseBoundary.remainder_succ
#print axioms CollatzTargetDensity.InverseBoundary.remainder_eq_start_add_inverseSum
#print axioms CollatzTargetDensity.InverseBoundary.log_scale
#print axioms CollatzTargetDensity.InverseBoundary.remainder_eq_exp_correction
#print axioms CollatzTargetDensity.InverseBoundary.remainder_tendsto_realBoundary
#print axioms CollatzTargetDensity.InverseBoundary.uniform_remainder_bound
#print axioms CollatzTargetDensity.InverseBoundary.inverse_terms_summable
#print axioms CollatzTargetDensity.InverseBoundary.inverseSum_tendsto
#print axioms CollatzTargetDensity.InverseBoundary.inverse_real_tsum
#print axioms CollatzTargetDensity.InverseBoundary.remainder_not_tendsto_zero
#print axioms CollatzTargetDensity.InverseBoundary.scale2_succ
#print axioms CollatzTargetDensity.InverseBoundary.remainder2_succ
#print axioms CollatzTargetDensity.InverseBoundary.remainder2_eq_start_add_inverseSum
#print axioms CollatzTargetDensity.InverseBoundary.valuationTotal_ge_steps
#print axioms CollatzTargetDensity.InverseBoundary.norm_remainder2_le
#print axioms CollatzTargetDensity.InverseBoundary.remainder2_tendsto_zero
#print axioms CollatzTargetDensity.InverseBoundary.inverseSum2_tendsto
#print axioms CollatzTargetDensity.InverseBoundary.rationalRemainder_real
#print axioms CollatzTargetDensity.InverseBoundary.rationalRemainder_padic
#print axioms CollatzTargetDensity.InverseBoundary.same_rational_remainders_two_limits
#print axioms CollatzTargetDensity.TwoTopologyExample.real_bounds
#print axioms CollatzTargetDensity.TwoTopologyExample.norm_two_adic_le
#print axioms CollatzTargetDensity.TwoTopologyExample.explicit_distinct_limits
#print axioms CollatzTargetDensity.TwoTopologyExample.no_unconditional_transfer_of_zero_limit
