import CollatzTargetDensity.SyracuseEnergyClasses

#print CollatzTargetDensity.SyracuseEnergy.collisionEnergy
#check CollatzTargetDensity.SyracuseEnergy.FiniteL2.three_class_overlap
#check CollatzTargetDensity.SyracuseEnergy.syrac_overlap_le_seventh
#check CollatzTargetDensity.SyracuseEnergy.collisionEnergy_step_le_nine_sevenths
#check CollatzTargetDensity.SyracuseEnergy.collisionEnergy_succ_le_nine_sevenths_pow
#check CollatzTargetDensity.SyracuseEnergy.collisionEnergy_le_nine_sevenths_pow
#check CollatzTargetDensity.nine_sevenths_target_density

#print axioms CollatzTargetDensity.SyracuseEnergy.FiniteL2.three_class_overlap
#print axioms CollatzTargetDensity.SyracuseEnergy.lift_covers_class_one
#print axioms CollatzTargetDensity.SyracuseEnergy.lift_affine_four
#print axioms CollatzTargetDensity.SyracuseEnergy.pmf_affine_four_recurrence
#print axioms CollatzTargetDensity.SyracuseEnergy.residueThree_affine_four
#print axioms CollatzTargetDensity.SyracuseEnergy.syracPMF_zero_class
#print axioms CollatzTargetDensity.SyracuseEnergy.syracPMF_class_two_norm
#print axioms CollatzTargetDensity.SyracuseEnergy.syrac_overlap_le_seventh
#print axioms CollatzTargetDensity.SyracuseEnergy.collisionEnergy_step_le_nine_sevenths
#print axioms CollatzTargetDensity.SyracuseEnergy.collisionEnergy_succ_le_nine_sevenths_pow
#print axioms CollatzTargetDensity.SyracuseEnergy.collisionEnergy_le_nine_sevenths_pow
#print axioms CollatzTargetDensity.nine_sevenths_target_density
