import CollatzTargetDensity.MixingFloorCountermodel
import CollatzTargetDensity.SyracuseCoreMinorant
import CollatzTargetDensity.SyracuseCylinderSpread

#print axioms CollatzTargetDensity.MixingFloorCountermodel.minimum_lower
#print axioms CollatzTargetDensity.MixingFloorCountermodel.minimum_attained
#print axioms CollatzTargetDensity.MixingFloorCountermodel.normalized
#print axioms CollatzTargetDensity.MixingFloorCountermodel.projective
#print axioms CollatzTargetDensity.MixingFloorCountermodel.fast_mixing
#print axioms CollatzTargetDensity.SyracuseMinorant.prefix_family_selected_le_density
#print axioms CollatzTargetDensity.SyracuseMinorant.prefix_family_positive_error_polynomial
#print axioms CollatzTargetDensity.SyracuseMinorant.filtered_kernel_positive_contraction
#print axioms CollatzTargetDensity.SyracuseMinorant.filtered_kernel_positive_error_polynomial
#print axioms CollatzTargetDensity.SyracuseMinorant.backward_mark_positive_error_polynomial
#print axioms CollatzTargetDensity.SyracuseMinorant.exists_fixed_positive_core_cylinder_finite
#print axioms CollatzTargetDensity.SyracuseMinorant.coreMark_positive_error_rate
#print axioms CollatzTargetDensity.SyracuseMinorant.exists_positive_syracuse_cylinder
#print axioms CollatzTargetDensity.SyracuseMinorant.bounded_inverse_into_cylinder
#print axioms CollatzTargetDensity.SyracuseMinorant.exists_uniform_positive_syracuse_density
#print axioms CollatzTargetDensity.SyracuseMinorant.syracuse_uniform_atom_lower_bound
