import Collatz.Research.CoefficientDescent.Horizon
import Collatz.Research.CoefficientDescent.Transfer
import Collatz.Research.CoefficientDescent.Intervals
import Collatz.Research.CoefficientDescent.Examples
import Collatz.Research.CoefficientDescent.Universal
