import Collatz.Core.Arith

/-!
# The coefficient stopping time, and what it buys

R. Terras, *A stopping time problem on the positive integers*, Acta Arithmetica
**30** (1976), 241–252, introduced the **coefficient stopping time** alongside the
ordinary stopping time and conjectured (his Conjecture 2.9) that the two agree.
Nothing here is original; this file supplies proofs for the elementary half and
for one strict consequence, and says plainly what is left open.

## The two stopping times

Work with the accelerated map on odd positives, `n_{i+1} = (3n_i+1)/2^{k_i}` with
`k_i = v₂(3n_i+1) ≥ 1`, and put `S_m = k_0 + ⋯ + k_{m-1}`.  Then

* the **stopping time** `σ(n₀)` is the least `m ≥ 1` with `n_m < n₀`;
* the **coefficient stopping time** `κ(n₀)` is the least `m ≥ 1` with `2^{S_m} > 3^m`.

### Terras's indexing versus ours

Terras works with the total-step map `T(x) = x/2` for even `x`, `(3x+1)/2` for
odd `x`, and counts **total** steps.  Writing `u(d)` for the number of odd
(tripling) steps among the first `d`, his stopping time is
`χ(n) = min{d ≥ 1 : T^d(n) < n}` and his coefficient stopping time is
`τ(n) = min{d ≥ 1 : 2^d > 3^{u(d)}}`, and Conjecture 2.9 asserts `χ = τ`.  This
file counts **odd** steps instead: after `m` accelerated steps the orbit has
taken `S_m` total steps of which `m` were triplings, so `d = S_m`, `u = m`, and
the two conditions become `n_m < n₀` and `2^{S_m} > 3^m`.  The indices correspond
by `σ(n) = u(χ(n))` and `κ(n) = u(τ(n))`: ours are the tripling counts at
Terras's total-step indices.  The translation is by `u` and **not** by `S` —
`χ(n) ≤ S_{σ(n)}`, usually strictly, because a drop below `n₀` can occur part way
through a run of halvings, before the accelerated step completes.  In particular
`χ = τ` implies `σ = κ`.  (Both index identities were checked on every odd
`n < 40000` with no exception; that is a sanity check on the translation, not a
proof of anything.)

> **Coefficient Stopping Time conjecture (Terras 1976, Conj. 2.9).**
> `σ(n) = κ(n)` for every `n ≥ 2`.

## What this file proves

**`no_drop_of_coeff_le`** — the elementary half, unconditional.  While the
coefficient has not yet exceeded, i.e. `2^{S_m} ≤ 3^m`, the orbit satisfies
`n_m > n₀`.  Hence no drop can occur before `κ`, that is `σ ≥ κ` always.  The
proof is one line off the exact identity `n_m·2^{S_m} = 3^m·n₀ + b_m` with
`b_m > 0`: the accumulator `b_m` can only push `n_m` *up*.

**`cycle_coeff_gt`** — on a cycle the coefficient must have exceeded:
`3^ℓ < 2^{S_ℓ}`.  Same identity, read at `n_ℓ = n₀`.

**`no_cycle_of_cstHard`** — the strict consequence.  Assuming only the *hard*
half of the conjecture (`σ ≤ κ`, phrased as `CSTHard`), there is no non-trivial
cycle.  Take `n₀` to be the least element of a cycle; then `n₀ ≤ n_j` for every
`j`, so `σ(n₀) = ∞`, while `cycle_coeff_gt` gives `κ(n₀) ≤ ℓ < ∞`.

## What this file does not prove

The hard half of the conjecture.  `σ(n) = κ(n)` was checked here for all odd
`n ≤ 10^9` (499 999 999 values, no exception); that is evidence and is not used
as a hypothesis anywhere except where explicitly assumed.

This file does **not derive Collatz** from the coefficient stopping-time
conjecture. Equality of the two stopping times permits both to be infinite;
the displayed inequalities do not alone exclude that case. No divergent
integer orbit or logical independence result is constructed here, so this
observation must not be described as a proof of non-implication or strict
logical weakness. `no_cycle_of_cstHard` is a conditional result about cycles.

Lean 4.33.0-rc1.  No Mathlib, no `sorry`.
-/

namespace Collatz
namespace CoefficientStopping

open Arith

/-! ## The exact identity

Everything below rests on one computation.  `b` is the accumulator generated by
the valuation prefix, `b_0 = 0` and `b_{m+1} = 3b_m + 2^{S_m}`. -/

/-- `n_m · 2^{S_m} = 3^m · n₀ + b_m`, for any sequence obeying the accelerated
recurrence.  Stated with the bookkeeping sequences `S` and `b` supplied as
hypotheses so that nothing about `v₂` is needed. -/
theorem orbit_identity (n k S b : Nat → Nat)
    (hS0 : S 0 = 0) (hSs : ∀ m, S (m + 1) = S m + k m)
    (hb0 : b 0 = 0) (hbs : ∀ m, b (m + 1) = 3 * b m + 2 ^ (S m))
    (hrec : ∀ i, n (i + 1) * 2 ^ (k i) = 3 * n i + 1) :
    ∀ m, n m * 2 ^ (S m) = 3 ^ m * n 0 + b m := by
  intro m
  induction m with
  | zero => rw [hS0, hb0]; simp
  | succ m ih =>
    have hsplit : 2 ^ (S (m + 1)) = 2 ^ (S m) * 2 ^ (k m) := by
      rw [hSs m, two_pow_add]
    calc n (m + 1) * 2 ^ (S (m + 1))
        = (n (m + 1) * 2 ^ (k m)) * 2 ^ (S m) := by
          rw [hsplit]; simp [Nat.mul_comm, Nat.mul_assoc]
      _ = (3 * n m + 1) * 2 ^ (S m) := by rw [hrec m]
      _ = 3 * (n m * 2 ^ (S m)) + 2 ^ (S m) := by
          simp [Nat.add_mul, Nat.mul_assoc]
      _ = 3 * (3 ^ m * n 0 + b m) + 2 ^ (S m) := by rw [ih]
      _ = 3 ^ (m + 1) * n 0 + (3 * b m + 2 ^ (S m)) := by
          rw [three_pow_succ]
          simp [Nat.mul_add, Nat.mul_assoc]
          omega
      _ = 3 ^ (m + 1) * n 0 + b (m + 1) := by rw [hbs m]

/-- The accumulator is strictly positive from step one onwards. -/
theorem b_pos (S b : Nat → Nat) (hbs : ∀ m, b (m + 1) = 3 * b m + 2 ^ (S m)) :
    ∀ m, 0 < b (m + 1) := by
  intro m
  have : 0 < 2 ^ (S m) := two_pow_pos (S m)
  rw [hbs m]
  omega

/-! ## Terras's elementary inequality: `σ ≥ κ` -/

/-- **The elementary half, unconditional.**  If the coefficient has not exceeded
at step `m ≥ 1` — that is `2^{S_m} ≤ 3^m` — then the orbit has not dropped:
`n₀ < n_m`.  The accumulator `b_m > 0` is exactly the slack that makes this
strict. -/
theorem no_drop_of_coeff_le (n k S b : Nat → Nat)
    (hS0 : S 0 = 0) (hSs : ∀ m, S (m + 1) = S m + k m)
    (hb0 : b 0 = 0) (hbs : ∀ m, b (m + 1) = 3 * b m + 2 ^ (S m))
    (hrec : ∀ i, n (i + 1) * 2 ^ (k i) = 3 * n i + 1)
    (m : Nat) (hm : 0 < m) (hcoef : 2 ^ (S m) ≤ 3 ^ m) :
    n 0 < n m := by
  obtain ⟨m', rfl⟩ : ∃ m', m = m' + 1 := ⟨m - 1, by omega⟩
  have hid := orbit_identity n k S b hS0 hSs hb0 hbs hrec (m' + 1)
  have hb := b_pos S b hbs m'
  have hmul : 2 ^ (S (m' + 1)) * n 0 ≤ 3 ^ (m' + 1) * n 0 :=
    Nat.mul_le_mul_right (n 0) hcoef
  have hcomm : n (m' + 1) * 2 ^ (S (m' + 1)) = 2 ^ (S (m' + 1)) * n (m' + 1) :=
    Nat.mul_comm _ _
  -- decide by cases on `Nat.lt_or_ge`, which is axiom-free, rather than by
  -- `Nat.lt_of_mul_lt_mul_left`, which is not
  rcases Nat.lt_or_ge (n 0) (n (m' + 1)) with hlt | hge
  · exact hlt
  · exfalso
    have hcontra : 2 ^ (S (m' + 1)) * n (m' + 1) ≤ 2 ^ (S (m' + 1)) * n 0 :=
      Nat.mul_le_mul_left _ hge
    omega

/-- The packaged statement `σ ≥ κ`: if the coefficient has not exceeded anywhere
up to `m`, the orbit has not dropped anywhere up to `m`. -/
theorem stoppingTime_ge_coefficient (n k S b : Nat → Nat)
    (hS0 : S 0 = 0) (hSs : ∀ m, S (m + 1) = S m + k m)
    (hb0 : b 0 = 0) (hbs : ∀ m, b (m + 1) = 3 * b m + 2 ^ (S m))
    (hrec : ∀ i, n (i + 1) * 2 ^ (k i) = 3 * n i + 1)
    (m : Nat) (hcoef : ∀ j, 0 < j → j ≤ m → 2 ^ (S j) ≤ 3 ^ j) :
    ∀ j, 0 < j → j ≤ m → n 0 < n j := by
  intro j hj hjm
  exact no_drop_of_coeff_le n k S b hS0 hSs hb0 hbs hrec j hj (hcoef j hj hjm)

/-! ## A cycle forces the coefficient to exceed -/

/-- On a cycle of length `ℓ ≥ 1` the coefficient has exceeded: `3^ℓ < 2^{S_ℓ}`.
Equivalently `κ(n₀) ≤ ℓ`.

`_hn0` is not needed by the proof — positivity of `n 0` follows from the strict
inequality it would otherwise supply — but it records the intended reading. -/
theorem cycle_coeff_gt (n k S b : Nat → Nat)
    (hS0 : S 0 = 0) (hSs : ∀ m, S (m + 1) = S m + k m)
    (hb0 : b 0 = 0) (hbs : ∀ m, b (m + 1) = 3 * b m + 2 ^ (S m))
    (hrec : ∀ i, n (i + 1) * 2 ^ (k i) = 3 * n i + 1)
    (l : Nat) (hl : 0 < l) (hcyc : n l = n 0) (_hn0 : 0 < n 0) :
    3 ^ l < 2 ^ (S l) := by
  obtain ⟨l', rfl⟩ : ∃ l', l = l' + 1 := ⟨l - 1, by omega⟩
  have hid := orbit_identity n k S b hS0 hSs hb0 hbs hrec (l' + 1)
  have hb := b_pos S b hbs l'
  rw [hcyc] at hid
  have hkey : n 0 * 3 ^ (l' + 1) < n 0 * 2 ^ (S (l' + 1)) := by
    have h1 : n 0 * 2 ^ (S (l' + 1)) = 2 ^ (S (l' + 1)) * n 0 := Nat.mul_comm _ _
    have h2 : 3 ^ (l' + 1) * n 0 = n 0 * 3 ^ (l' + 1) := Nat.mul_comm _ _
    omega
  exact Nat.lt_of_mul_lt_mul_left hkey

/-! ## The strict consequence

The hard half of Terras's conjecture is the inequality `σ ≤ κ`: once the
coefficient exceeds, the orbit really has dropped.  Assuming only that, cycles
are impossible. -/

/-- The hard half of the Coefficient Stopping Time conjecture, as a hypothesis on
one orbit: whenever the coefficient has exceeded at step `m`, some earlier or
equal step has already dropped below the start. -/
def CSTHard (n S : Nat → Nat) : Prop :=
  ∀ m, 0 < m → 3 ^ m < 2 ^ (S m) → ∃ j, 0 < j ∧ j ≤ m ∧ n j < n 0

/-- **`CSTHard` ⇒ no non-trivial cycle.**  Start at the least element of the
cycle, so that `n₀ ≤ n_j` for every `j`.  `cycle_coeff_gt` says the coefficient
exceeds by step `ℓ`, and `CSTHard` then produces a `j` with `n_j < n₀`,
contradicting minimality.

This theorem does not address divergent orbits. In particular, its proof
does not exclude the case in which both stopping times are infinite; no
strict logical comparison with the Collatz conjecture is proved here. -/
theorem no_cycle_of_cstHard (n k S b : Nat → Nat)
    (hS0 : S 0 = 0) (hSs : ∀ m, S (m + 1) = S m + k m)
    (hb0 : b 0 = 0) (hbs : ∀ m, b (m + 1) = 3 * b m + 2 ^ (S m))
    (hrec : ∀ i, n (i + 1) * 2 ^ (k i) = 3 * n i + 1)
    (hcst : CSTHard n S)
    (l : Nat) (hl : 0 < l) (hcyc : n l = n 0) (hn0 : 0 < n 0)
    (hmin : ∀ j, n 0 ≤ n j) : False := by
  have hgt : 3 ^ l < 2 ^ (S l) :=
    cycle_coeff_gt n k S b hS0 hSs hb0 hbs hrec l hl hcyc hn0
  obtain ⟨j, _, _, hlt⟩ := hcst l hl hgt
  exact absurd (hmin j) (by omega)

/-! ## Axiom audit -/

#print axioms orbit_identity
#print axioms no_drop_of_coeff_le
#print axioms cycle_coeff_gt
#print axioms no_cycle_of_cstHard

end CoefficientStopping
end Collatz
