import Collatz.Accelerated
import Collatz.Core.Arith

/-!
# The affine Heisenberg monoid, and the commutator that is not a word

The free monoid on `{odd, even}` is the wrong object: `word_realizable` says it
is the full shift, and `wC_inj` says its affine representation is faithful, so
there are no extra relations among Collatz words.  This file presents a
*larger* monoid in which those words sit, generated by the two Collatz maps
together with a translation, and records the exact conjugation laws of that
translation module.

## The object

An element of `H` is a triple `(a, L, c)` standing for the affine map

    x  ↦  (3^a · x + c) / 2^L

on the module of numerators (the denominator is kept as an exponent, so every
identity below is a `Nat` equation).  Multiplication is composition, apply-right
first:

    (a,L,c) * (a',L',c')  =  (a+a', L+L',  3^a · c' + 2^{L'} · c).

This is not the free monoid on two letters.  It is the semidirect product of
the Parikh monoid `ℕ²` (the exponents) with the translation module `ℕ` (the
`c`-slot), and it has a third generator `τ t = (0,0,t)` that no Collatz word
represents: a word of length `0` is the identity `c = 0`.

The Collatz generators, and the expStep even deformation, are

* `e     = (0,1,0)`     — even map `x ↦ x/2`,
* `o d   = (1,0,d)`     — odd map `x ↦ 3x+d`,
* `eExp  = (1,1,0)`     — expStep even map `x ↦ 3x/2`.

## What is proved

* The multiplication is associative with unit `(0,0,0)` (`mul_assoc`).
* Translations are a bimodule: left multiplication by `u` scales a translation
  by `3^{u.a}`, right multiplication by `v` scales it by `2^{v.L}`
  (`addTrans_mul_left`, `addTrans_mul_right`).
* Seed commutator: `mul (o d) e` and `mul e (o d)` have the same exponents and
  differ in the `c`-slot by exactly `d` (`seed_commutator`).  Homogeneous of
  degree one in `d`.
* **Main theorem** (`middle_commutator`): inserting that commutator between a
  prefix `u` and a suffix `v` contributes `3^{u.a} · 2^{v.L} · d` to the
  numerator, at *every* start `n`.  The defect `K u v d` is independent of
  `n`; the `n`-cancellation is the content.
* Conjugation: `mul (tau t) e = mul e (tau (2*t))` and
  `mul (o d) (tau t) = mul (tau (3*t)) (o d)`.  The even law **fails** for
  `eExp` (`tau_conj_even_fails_expStep`).
* The dynamical (parity-selected) step is not this module action
  (`dynamical_step_not_module`).

None of these is a comparison of `2^L` against `3^a`.  No residue covering is
used.  No Collatz claim is made.
-/

namespace Collatz
namespace DeviceSemigroup

/-! ## The monoid -/

/-- Upper-triangular affine datum: the map `x ↦ (3^a · x + c) / 2^L`. -/
structure H where
  a : Nat
  L : Nat
  c : Nat
deriving DecidableEq, Repr

/-- Composition, apply-right first. -/
def mul (u v : H) : H :=
  ⟨u.a + v.a, u.L + v.L, 3 ^ u.a * v.c + 2 ^ v.L * u.c⟩

@[simp] theorem mul_a (u v : H) : (mul u v).a = u.a + v.a := rfl
@[simp] theorem mul_L (u v : H) : (mul u v).L = u.L + v.L := rfl
@[simp] theorem mul_c (u v : H) : (mul u v).c = 3 ^ u.a * v.c + 2 ^ v.L * u.c := rfl

def one : H := ⟨0, 0, 0⟩

@[simp] theorem one_a : one.a = 0 := rfl
@[simp] theorem one_L : one.L = 0 := rfl
@[simp] theorem one_c : one.c = 0 := rfl

@[simp] theorem one_mul (u : H) : mul one u = u := by
  cases u
  simp [mul, one]

@[simp] theorem mul_one (u : H) : mul u one = u := by
  cases u
  simp [mul, one]

/-- **Associativity.**  The affine Heisenberg product is a monoid. -/
theorem mul_assoc (u v w : H) : mul (mul u v) w = mul u (mul v w) := by
  cases u; cases v; cases w
  simp [mul, Nat.pow_add, Nat.mul_add, Nat.add_assoc, Nat.mul_assoc,
    Nat.mul_left_comm, Nat.mul_comm]

/-! ## Generators -/

/-- Even Collatz generator: `x ↦ x/2`. -/
def e : H := ⟨0, 1, 0⟩

/-- Odd `3x+d` generator: `x ↦ 3x+d`. -/
def o (d : Nat) : H := ⟨1, 0, d⟩

/-- Translation by `t` in the numerator.  No Collatz word equals `tau 1`. -/
def tau (t : Nat) : H := ⟨0, 0, t⟩

/-- expStep even generator: `x ↦ 3x/2`. -/
def eExp : H := ⟨1, 1, 0⟩

@[simp] theorem e_spec : e = ⟨0, 1, 0⟩ := rfl
@[simp] theorem o_spec (d : Nat) : o d = ⟨1, 0, d⟩ := rfl
@[simp] theorem tau_spec (t : Nat) : tau t = ⟨0, 0, t⟩ := rfl
@[simp] theorem eExp_spec : eExp = ⟨1, 1, 0⟩ := rfl

/-! ## Action on the numerator module -/

/-- Numerator of the affine map at start `n`: `3^a · n + c`. -/
def num (u : H) (n : Nat) : Nat := 3 ^ u.a * n + u.c

@[simp] theorem num_mk (a L c n : Nat) : num ⟨a, L, c⟩ n = 3 ^ a * n + c := rfl

/-- **Module action.**  A frozen word acts linearly on translations, with slope
`3^a` independent of the start and of `c`. -/
theorem num_add (u : H) (n t : Nat) :
    num u (n + t) = num u n + 3 ^ u.a * t := by
  cases u
  simp [num, Nat.mul_add]
  omega

/-- The composition law on numerators, denominators kept explicit. -/
theorem num_mul (u v : H) (n : Nat) :
    num (mul u v) n = 3 ^ u.a * num v n + 2 ^ v.L * u.c := by
  cases u; cases v
  simp [num, mul, Nat.pow_add, Nat.mul_add, Nat.mul_assoc]
  omega

/-! ## Translation bimodule -/

/-- Act on the `c`-slot by a translation.  This is the module `ℕ` sitting over
the Parikh monoid. -/
def addTrans (u : H) (t : Nat) : H := ⟨u.a, u.L, u.c + t⟩

@[simp] theorem addTrans_spec (u : H) (t : Nat) :
    addTrans u t = ⟨u.a, u.L, u.c + t⟩ := rfl

theorem addTrans_zero (u : H) : addTrans u 0 = u := by
  cases u; rfl

theorem addTrans_add (u : H) (t₁ t₂ : Nat) :
    addTrans (addTrans u t₁) t₂ = addTrans u (t₁ + t₂) := by
  cases u; simp [addTrans, Nat.add_assoc]

/-- Right multiplication scales a translation by `2^{L(v)}`. -/
theorem addTrans_mul_right (u v : H) (t : Nat) :
    mul (addTrans u t) v = addTrans (mul u v) (2 ^ v.L * t) := by
  cases u; cases v
  simp [addTrans, mul, Nat.mul_add, Nat.add_assoc]

/-- Left multiplication scales a translation by `3^{a(u)}`. -/
theorem addTrans_mul_left (u v : H) (t : Nat) :
    mul u (addTrans v t) = addTrans (mul u v) (3 ^ u.a * t) := by
  cases u; cases v
  simp [addTrans, mul, Nat.mul_add, Nat.add_assoc]
  omega

/-! ## Presentation relations -/

/-- **Even conjugation.**  Halving doubles a translation that is moved past it:
`τ t · e = e · τ (2t)`.  This is the statement that the even branch is pure
scaling by `1/2` on the translation module. -/
theorem tau_conj_even (t : Nat) : mul (tau t) e = mul e (tau (2 * t)) := by
  simp [mul, tau, e]

/-- **Odd conjugation.**  The `3x+d` branch triples a translation:
`(o d) · τ t = τ (3t) · (o d)`.  Independent of `d`. -/
theorem tau_conj_odd (d t : Nat) : mul (o d) (tau t) = mul (tau (3 * t)) (o d) := by
  simp [mul, tau, o]
  omega

/-- **Seed commutator.**  `o d` and `e` fail to commute by a pure translation of
size `d`, independent of every start.  Stated as an `addTrans` identity so there
is no `Nat` subtraction. -/
theorem seed_commutator (d : Nat) :
    mul (o d) e = addTrans (mul e (o d)) d := by
  simp [addTrans, mul, o, e]
  omega

/-- The two generator products share exponents `(1,1)` and differ in `c` by `d`. -/
theorem seed_exponents (d : Nat) :
    (mul (o d) e).a = 1 ∧ (mul (o d) e).L = 1 ∧
      (mul e (o d)).a = 1 ∧ (mul e (o d)).L = 1 ∧
      (mul (o d) e).c = (mul e (o d)).c + d := by
  simp [mul, o, e]
  omega

/-! ## The commutator defect `K` -/

/-- **Commutator defect of a split.**  Prefix `u`, suffix `v`, odd additive `d`.
The value does not mention the start: theorem `middle_commutator` says this is
exactly the numerator defect at every `n`. -/
def K (u v : H) (d : Nat) : Nat := 3 ^ u.a * 2 ^ v.L * d

/-- Evaluation of `K` at a start — the same number, so independence of `n` is
definitional. -/
def K_at (u v : H) (d : Nat) (_n : Nat) : Nat := K u v d

theorem K_independent (u v : H) (d n n' : Nat) :
    K_at u v d n = K_at u v d n' := rfl

theorem oe_spec (d : Nat) : mul (o d) e = ⟨1, 1, 2 * d⟩ := by
  simp [mul, o, e]

theorem eo_spec (d : Nat) : mul e (o d) = ⟨1, 1, d⟩ := by
  simp [mul, o, e]

theorem oe_mul_v (d : Nat) (v : H) :
    mul (mul (o d) e) v = ⟨v.a + 1, v.L + 1, 3 * v.c + 2 ^ (v.L + 1) * d⟩ := by
  cases v
  simp [mul, o, e, Nat.pow_succ, Nat.add_comm, Nat.mul_assoc, Nat.mul_comm]

theorem eo_mul_v (d : Nat) (v : H) :
    mul (mul e (o d)) v = ⟨v.a + 1, v.L + 1, 3 * v.c + 2 ^ v.L * d⟩ := by
  cases v
  simp [mul, o, e, Nat.add_comm, Nat.mul_comm]

/-- Doubling the denominator doubles the transported translation. -/
theorem two_pow_succ_mul (k d : Nat) :
    2 ^ (k + 1) * d = 2 ^ k * d + 2 ^ k * d := by
  rw [Nat.pow_succ, Nat.mul_assoc]
  have hd : 2 * d = d + d := by omega
  rw [hd, Nat.mul_add]

/-- Prefix scaling of the doubled translation. -/
theorem prefix_scale (ua vL vc d : Nat) :
    3 ^ ua * (3 * vc + 2 ^ (vL + 1) * d)
      = 3 ^ ua * (3 * vc + 2 ^ vL * d) + 3 ^ ua * 2 ^ vL * d := by
  rw [two_pow_succ_mul, ← Nat.add_assoc, Nat.mul_add, Nat.mul_assoc]

/-- **Main theorem — insertion of the commutator.**

Writing `oe` for `mul (o d) e` and `eo` for `mul e (o d)`, the two frozen words
`mul u (mul oe v)` and `mul u (mul eo v)` have identical exponents, and their
numerators at an arbitrary start `n` differ by
`K u v d = 3^{a(u)} · 2^{L(v)} · d`.

The start `n` cancels: the commutator is a constant translation, scaled by the
prefix's tripling and the suffix's doubling.  This is not a restatement of
`2^L ? 3^a`, and it is homogeneous of degree one in `d`. -/
theorem middle_commutator (u v : H) (d n : Nat) :
    num (mul u (mul (mul (o d) e) v)) n
      = num (mul u (mul (mul e (o d)) v)) n + K u v d := by
  rw [oe_mul_v, eo_mul_v]
  cases u
  case mk ua _uL uc =>
    have h := prefix_scale ua v.L v.c d
    simp only [num, mul, K]
    rw [h]
    simp [Nat.add_assoc, Nat.add_left_comm, Nat.add_comm]

/-- Numerator form of the seed, at an arbitrary start. -/
theorem seed_num (d n : Nat) :
    num (mul (o d) e) n = num (mul e (o d)) n + d := by
  have h := middle_commutator one one d n
  simp [K] at h
  simpa [one_mul, mul_one] using h

/-! ## expStep and the dynamical diagonal -/

/-- The even conjugation law is false for expStep's even generator.  Witness
`t = 1`: left side has `c = 2`, right side has `c = 6`. -/
theorem tau_conj_even_fails_expStep :
    mul (tau 1) eExp ≠ mul eExp (tau (2 * 1)) := by
  decide

/-- expStep's even letter is not Collatz's even letter. -/
theorem eExp_ne_e : eExp ≠ e := by
  decide

/-- `3x+d` still uses Collatz's even generator, so even conjugation is `d`-blind
and holds uniformly.  The `d`-content lives in `K`, not in `tau_conj_even`. -/
theorem tau_conj_even_any_d (_d t : Nat) :
    mul (tau t) e = mul e (tau (2 * t)) :=
  tau_conj_even t

/-- The parity-selected dynamical step is not the frozen-word module action.
A single odd step acts on numerators by `+ 3t`; the dynamical map at `7` and
`8` does not. -/
theorem dynamical_step_not_module :
    ¬ ∀ n t : Nat, acceleratedStep (n + t) = acceleratedStep n + 3 * t := by
  intro h
  have := h 7 1
  simp [acceleratedStep] at this

/-- Package: the object, the insertion theorem, the even-conjugation law, and
the two filters. -/
theorem round_summary :
    (∀ u v d n, num (mul u (mul (mul (o d) e) v)) n
        = num (mul u (mul (mul e (o d)) v)) n + K u v d)
      ∧ (∀ t, mul (tau t) e = mul e (tau (2 * t)))
      ∧ (∀ d t, mul (o d) (tau t) = mul (tau (3 * t)) (o d))
      ∧ (mul (tau 1) eExp ≠ mul eExp (tau 2))
      ∧ (¬ ∀ n t : Nat, acceleratedStep (n + t) = acceleratedStep n + 3 * t) :=
  ⟨middle_commutator, tau_conj_even, tau_conj_odd,
    tau_conj_even_fails_expStep, dynamical_step_not_module⟩

end DeviceSemigroup
end Collatz

section AxiomAudit
open Collatz.DeviceSemigroup
#print axioms middle_commutator
#print axioms tau_conj_even
#print axioms tau_conj_even_fails_expStep
#print axioms dynamical_step_not_module
end AxiomAudit
