import Collatz.Strategy.StairThree
import Collatz.Structure.AccCycle

/-!
# Halbeisen–Hungerbühler 1997, and what it means for Rounds XI–XXIV

*Optimal bounds for the length of rational Collatz cycles*, L. Halbeisen and
N. Hungerbühler, Elem. Math. 52 (1997).  Read in full this round.  It settles
several questions this repository has been treating as open, and it does so
against us.

## What the paper already contains

Their `φ : S → ℕ` on `0-1` words is defined by

`φ(⟨⟩) = 0`,  `φ(s0) = φ(s)`,  `φ(s1) = 3φ(s) + 2^{l(s)}`.

**That is `AffineExact.affineC`, character for character.**  Further:

| their result | this repository |
|---|---|
| formula (3), `φ(s) = Σ_j s_j 3^{s_{j+1}+⋯+s_l} 2^{j−1}` | the positional formula, `AccumulatorAutomaton.C_eq_Crel` |
| formula (4), `φ(s s̄) = 3^{n(s̄)}φ(s) + 2^{l(s)}φ(s̄)` | the cocycle law, `AccumulatorArith.affineC_add` |
| Lemma 2 (Lagarias), `x₀ = φ(s)/(2^{l} − 3^{n})` | `CycleAccumulator.cycle_eq_div` |
| **Lemma 4**: partial sums of `s` dominate those of `t` ⟹ `φ(s) > φ(t)` | **`AffineExchange.Crel_mono` / `window_mono`** — and their proof is the same adjacent transposition as `AffineExchange.C_exchange` |
| **Lemma 5 + Corollary 1**: the minimiser is the Beatty word `s̃ᵢ = ⌈in/l⌉ − ⌈(i−1)n/l⌉`, with `M_{l,n}` explicit | Round XIII's extremal-ordering work, but **not** in this exact optimal form |

So the affine-accumulator programme of Rounds XVII–XIX, and much of Rounds XI–XIII,
is Lagarias 1985 and Halbeisen–Hungerbühler 1997.  Recorded here so the repository
stops rediscovering it.

## What their criterion is

`M_{l,n} := min { φ(s) : s ∈ S_{l,n} }` is attained at the Beatty word, and

`M_{l,n} / (2^l − 3^n) ≤ x₀`

for every cycle of shape `(l, n)`.  Hence their criterion: if Collatz is verified
below `m`, and `M_{l,n} ≤ m·(2^l − 3^n)` for all `n` and all `l < L`, then every
cycle avoiding `1` has length at least `L`.  With verification to
`2.12 × 10^14` they obtain **length ≥ 102 225 496** — against this repository's
`length_ge_6809`, four orders of magnitude behind.

## Consequence for Round XXIII–XXIV: the staircase is almost certainly not new

`M_{l,n}` is the **exact** minimum of `φ` over the shape `(l, n)`, so *every* valid
constraint relating a cycle's minimum to `(l, n)` is implied by it.  The staircase
bounds of Rounds XXIII–XXIV are such constraints — derived from distinctness and
coprimality of the elements, both of which hold for the rational cycles their
theorem covers.  **They are therefore implied by, and no stronger than,
Halbeisen–Hungerbühler.**  The honest verdict on the question "is the staircase
refinement known": it is subsumed, and the horizon numbers `31.5 m` and `170 m`
are improvements only over the repository's own weaker starting point.

## What is formalised here

The Beatty word without division, as a running remainder (`beattyRem`,
`beattyBit`) — the same word as `⌈in/l⌉ − ⌈(i−1)n/l⌉` but generated by
`r ↦ r + n`, subtracting `l` and emitting `1` on overflow.  `beattyBit_le_one`
and `beatty_count` prove it is a `0-1` word of weight exactly `n`, which is what
makes it an element of `S_{l,n}`.

`hhMin` is `M_{l,n}` by Corollary 1.  `HHExtremal` names their Lemma 5 —
that `hhMin` really is the minimum — as an explicit hypothesis, **not proved
here**, and `hh_criterion` derives their cycle-length criterion from it.

## The gap, stated plainly

Lemma 5 was the one piece not formalised, and is now proved in `HHLemmaFive`
(`hhExtremal_holds`), so `hh_criterion` and `hh_no_cycle_below` are unconditional
once that theorem discharges their hypothesis (`HHBridge.hh_criterion'` is the
discharged form).  The account that follows is how the gap stood before it
closed.  Its proof needs the rotation argument
`σ_{k₀}` on words together with Lemma 4, and Lemma 4 *is* available here as
`AffineExchange.Crel_mono`.  So the remaining work is the rotation step, and it is
ordinary.  Closing it would give this repository the sharp criterion in place of
its own, and would replace `length_ge_6809` by something in the range of `10^8`.

That is a real target, and unlike everything in Rounds XVII–XXIV it is a target
whose answer is already known to be reachable.
-/

namespace Collatz
namespace HalbeisenHungerbuhler

open Reach AccCycle

/-! ## The Beatty word, division-free -/

/-- The running remainder: add `n`, subtract `l` on overflow.  **Starts at `l − 1`,
not `0`** — that is what produces the *ceiling* word `⌈in/l⌉ − ⌈(i−1)n/l⌉` that
Halbeisen–Hungerbühler's `s̃` actually is.  Starting at `0` gives the floor word,
which is a different (indeed reversed) extremal word; see the correction note in
`RESEARCH.md`. -/
def beattyRem (l n : Nat) : Nat → Nat
  | 0 => l - 1
  | i + 1 => if l ≤ beattyRem l n i + n then beattyRem l n i + n - l else beattyRem l n i + n

/-- The `i`-th letter of the Beatty word `s̃ᵢ = ⌈in/l⌉ − ⌈(i−1)n/l⌉`. -/
def beattyBit (l n : Nat) (i : Nat) : Nat :=
  if l ≤ beattyRem l n i + n then 1 else 0

/-- Weight of the first `i` letters. -/
def beattyCount (l n : Nat) : Nat → Nat
  | 0 => 0
  | i + 1 => beattyBit l n i + beattyCount l n i

@[simp] theorem beattyBit_le_one (l n i : Nat) : beattyBit l n i ≤ 1 := by
  unfold beattyBit
  split <;> omega

/-- The running remainder stays below `l`. -/
theorem beattyRem_lt {l n : Nat} (hl : 0 < l) (hnl : n ≤ l) : ∀ i, beattyRem l n i < l := by
  intro i
  induction i with
  | zero => show l - 1 < l; omega
  | succ i ih =>
    show (if l ≤ beattyRem l n i + n then beattyRem l n i + n - l else beattyRem l n i + n) < l
    split <;> omega

/-- **The invariant.**  `remainder + l · weight = i · n`, so the word is exactly the
Beatty word of slope `n / l`. -/
theorem beatty_invariant {l n : Nat} (hl : 0 < l) (hnl : n ≤ l) : ∀ i : Nat,
    beattyRem l n i + l * beattyCount l n i = (l - 1) + i * n := by
  intro i
  induction i with
  | zero => show l - 1 + l * 0 = l - 1 + 0 * n; omega
  | succ i ih =>
    have hlt := beattyRem_lt hl hnl i
    show beattyRem l n (i + 1) + l * (beattyBit l n i + beattyCount l n i)
        = (l - 1) + (i + 1) * n
    have e2 : (i + 1) * n = i * n + n := by rw [Nat.add_mul, Nat.one_mul]
    unfold beattyRem beattyBit
    split
    · have e : l * (1 + beattyCount l n i) = l + l * beattyCount l n i := by
        rw [Nat.mul_add, Nat.mul_one]
      omega
    · have e : l * (0 + beattyCount l n i) = l * beattyCount l n i := by
        rw [Nat.zero_add]
      omega

/-- **The word has weight exactly `n`.**  At `i = l` the invariant reads
`remainder + l · weight = l · n` with the remainder below `l`, which pins the
weight. -/
theorem beatty_count_eq {l n : Nat} (hl : 0 < l) (hnl : n ≤ l) :
    beattyCount l n l = n := by
  have h := beatty_invariant hl hnl l
  have hr := beattyRem_lt hl hnl l
  rcases Nat.lt_trichotomy (beattyCount l n l) n with hlt | heq | hgt
  · exfalso
    have hb : l * (beattyCount l n l + 1) ≤ l * n := Nat.mul_le_mul_left _ (by omega)
    have e : l * (beattyCount l n l + 1) = l * beattyCount l n l + l := by
      rw [Nat.mul_add, Nat.mul_one]
    omega
  · exact heq
  · exfalso
    have hb : l * (n + 1) ≤ l * beattyCount l n l := Nat.mul_le_mul_left _ (by omega)
    have e : l * (n + 1) = l * n + l := by rw [Nat.mul_add, Nat.mul_one]
    omega

/-! ## `M_{l,n}` -/

/-- `M_{l,n} = Σ_{j=1}^{l} s̃_j · 2^{j−1} · 3^{n − ⌈jn/l⌉}`, Corollary 1 of the
paper, written with the running weight in place of the ceiling. -/
def hhMin (l n : Nat) : Nat → Nat
  | 0 => 0
  | j + 1 => beattyBit l n j * 2 ^ j * 3 ^ (n - beattyCount l n (j + 1)) + hhMin l n j

/-! ## Their criterion, with Lemma 5 named

**Correction to the previous reading of this file.**  Their inequality (11) is

`min C ≤ M_{l,n} / (2^l − 3^n)`,

an **upper** bound on the cycle minimum, not a lower one.  The reason is that
`M_{l,n} = φ(s̃)` is the *largest* value the rotation-minimum of `φ` can take over
`S_{l,n}`: Lemma 5 proves `φ(s̃) ≥ min_{t' ∈ σ(t)} φ(t')` for **every** `t`.  Since a
cycle's minimum element is `min_σ φ(σ)/(2^l − 3^n)`, it is at most `M_{l,n}` over the
gap.

That direction is what makes the criterion an exclusion: if `M_{l,n}` over the gap
is **below** the verified bound `m`, then any cycle of that shape has an element
below `m`, hence reaches `1`. -/

/-- **Halbeisen–Hungerbühler Lemma 5**, in the direction their Theorem 4 uses:
for a cycle whose minimum is `x`, the gap times `x` is at most `M_{l,n}`.
Not proved *here* — it is proved in `HHLemmaFive` as `hhExtremal_holds`, by the
rotation argument together with their Lemma 4, which is available as
`AffineExchange.Crel_mono`.  It is kept as an explicit hypothesis below so the
criterion's dependence stays visible; `HHBridge.hh_criterion'` is the discharged
form. -/
def HHExtremal : Prop :=
  ∀ x L : Nat, 0 < x → AccIsCycleOf x L → (∀ k : Nat, x ≤ acceleratedOrbit k x) →
    (2 ^ L - 3 ^ oddCount x L) * x ≤ hhMin L (oddCount x L) L

/-- **Theorem 4, the optimal criterion.**  If `M_{L,n}` over the gap falls below `m`,
then every cycle of length `L` has minimum strictly below `m`.  Quantified over all
`L < 102 225 496` with `m = 2.12 × 10^14`, this is their cycle-length bound. -/
theorem hh_criterion (hext : HHExtremal) {x L m : Nat} (hx : 0 < x)
    (hcyc : AccIsCycleOf x L) (hmin : ∀ k : Nat, x ≤ acceleratedOrbit k x)
    (hgap : 0 < 2 ^ L - 3 ^ oddCount x L)
    (hsmall : hhMin L (oddCount x L) L < (2 ^ L - 3 ^ oddCount x L) * m) :
    x < m := by
  have h := hext x L hx hcyc hmin
  have hlt : (2 ^ L - 3 ^ oddCount x L) * x < (2 ^ L - 3 ^ oddCount x L) * m := by omega
  exact Nat.lt_of_mul_lt_mul_left hlt

/-- **The exclusion.**  A cycle whose minimum would have to lie below the verified
bound cannot avoid `1`: it contains a point already known to reach `1`. -/
theorem hh_no_cycle_below (hext : HHExtremal) {x L m : Nat} (hx : 0 < x)
    (hcyc : AccIsCycleOf x L) (hmin : ∀ k : Nat, x ≤ acceleratedOrbit k x)
    (hgap : 0 < 2 ^ L - 3 ^ oddCount x L)
    (hsmall : hhMin L (oddCount x L) L < (2 ^ L - 3 ^ oddCount x L) * m)
    (hverified : ∀ y : Nat, 0 < y → y < m → ∃ k : Nat, acceleratedOrbit k y = 1) :
    ∃ k : Nat, acceleratedOrbit k x = 1 :=
  hverified x hx (hh_criterion hext hx hcyc hmin hgap hsmall)

/-! ## What the authors themselves say about the wall

Their final remarks, verbatim in substance:

> All estimates on the length of Collatz cycles given so far are valid for
> **rational** Collatz cycles although they have been stated originally for integer
> Collatz cycles.  But since we have seen that the minimum of rational cycles grows
> at least linearly in terms of their length, **such an approach cannot be
> successful to prove (A)**.  The only chance to achieve further progress would
> hence involve number theoretical arguments.

That is `ProductCeiling.product_bound_vacuous` and `HorizonSharp`, stated by the
authors in 1997.  The linear growth they cite is their Remark 1,
`1/20 ≤ M_{l,n(l)} / (n · 3^n) ≤ 7/10`.  **The wall this repository mapped over
Rounds XX–XXII was published thirty years ago**, and the escape they name —
"number theoretical arguments" — is the Baker route of Round XXII.

Their Lemma 9 is the number-theoretic step they suggest:
`gcd(φ(t) : t ∈ σ(s)) = gcd(φ(s), 2^{l} − 3^{n})`, which is exactly the object
`RepetitionDescent` and `DeltaSpectrum` study here as `δ`. -/

end HalbeisenHungerbuhler
end Collatz
