import Collatz.Strategy.HHLemmaFive

/-!
# What each wall costs

`HHLemmaFive` made the Halbeisen–Hungerbühler criterion unconditional, and then
showed it reproduces the repository's existing bound `6809` rather than beating
it.  That invites the operational question this file answers: **exactly how large
a verified range would each length cost?**

## The threshold

The criterion kills a length `L` when `hhMin L n L < (2 ^ L − 3 ^ n) · c` for
every admissible `n`.  Rearranged, `L` is killed exactly when

`c > hhMin L n L / (2 ^ L − 3 ^ n)`,

a rational **depending only on `L` and `n`** — the same separation
`ExclusionRatio` performs for the product bound.  `hhKills` is the test and
`hhKills_mono` is its monotonicity in the range.

Measured (exact rational arithmetic, at `n = nmax L`, the largest `n` with
`3 ^ n < 2 ^ L`; that `n` maximises the threshold — checked against *all*
admissible `n` for every `L < 60` and at `L = 485, 1539, 2593`, with no
exception):

| `L` | `n` | verified range needed |
|---|---|---|
| `485` | `306` | `72 059` |
| `1539` | `971` | `238 671` |
| `2593` | `1636` | `420 842` |
| `3647` | `2301` | `620 859` |
| `4701` | `2966` | `841 478` |
| `5755` | `3631` | **`1 086 055`** |
| `6809` | `4296` | **`1 358 718`** |
| `7863` | `4961` | `1 664 599` |
| `9971` | `6291` | `2 403 661` |
| `14187` | `8951` | `4 733 176` |
| `24727` | `15601` | `206 178 000` |

## Two things this makes visible

**The repository's verified range is tuned to the wall.**  `1 086 464` exceeds
the price of `5755` — `1 086 055` — by `409`, and falls short of `6809`'s price
by a factor of `1.2506`.  That is not a coincidence; it is the smallest round
range that clears the previous ladder step.

**The sharp criterion really is a better exchange rate**, which is what proving
Lemma 5 bought.  The product bound needs `c = 3 072 000` to reach `6809` and
`12 288 000` to reach `14187`; the sharp criterion needs `1 358 718` and
`4 733 176` — cheaper by `2.26×` and `2.60×`.  The gain is in the rate, not in
the current bound.

**So the next unconditional step is priced.**  Verifying Collatz to `1 358 718`
— a `1.2506×` extension of a range this repository has already widened twice —
moves the cycle-length bound from `6809` to `7863`.  That is arithmetic, not
insight, and it is written down here so the cost is known before it is paid.

## The price in closed form, and why the ladder can never be paid off

The table can be replaced by a formula.  Write `x = L/a ≈ log₂ 3`.  Then

`term_j = 3 ^ (a−1−j) · 2 ^ ⌊jx⌋ ≈ 3 ^ (a−1) · (2^x/3) ^ j · 2 ^ (−{jx})`,

and `2^x/3 → 1`, so the terms are nearly equal and only the fractional-part factor
survives.  Since `{j log₂ 3}` equidistributes, its average is
`∫₀¹ 2^(−t) dt = 1/(2 ln 2)`, giving `hhMin ≈ 3 ^ a · a / (6 ln 2)` and

**`price(L) ≈ a / (6 ln 2 · δ)`,  `δ = 1 − 3^a/2^L`.**

`1/(6 ln 2) = 0.2404491733…`  This is a **limit, not an exact constant**: the
measured `price·δ/a` runs `0.24060, 0.24042, 0.24039, 0.24045, 0.24045` at
`L = 485, 1539, 9971, 125743, 301994`, converging to it from a first digit that is
already right.  The formula reproduces every exactly-computed price to within
`0.03 %`, and it needs no `hhMin` evaluation — which is what makes the ladder
computable past `L = 10^5`, where the `O(L)` bignum sum stops being feasible.

On the ladder itself the formula sharpens further.  For a convergent with
denominator `a_k`, continued-fraction theory gives `δ ≈ ln 2 / a_{k+1}`, so

**`price(L_k) ≈ a_k · a_{k+1} / (6 ln 2)`.**

**Hence the ladder can never be paid off.**  Convergent denominators satisfy
`a_{k+1} ≥ a_k + a_{k−1}`, so `a_k → ∞` and `price(L_k) → ∞` — *whatever* the
partial quotients of `log₂ 3` turn out to be, an open question this argument does
not need.  So:

> For any fixed verified range `c`, the criterion kills only **finitely many**
> lengths `L`, and fails on the whole infinite one-sided convergent ladder.

No amount of verification closes that gap.  Excluding cycles outright needs an
argument that is not a threshold in `c` at all — which is the real content of the
`(6809, 4296)` wall, and the reason raising the range is a treadmill rather than a
route.

## The published bound, reproduced

The ladder is **not dense**, and that is what makes the exchange rate lumpy.  Its
blocks are generated by consecutive convergents: a block based at an odd-index
convergent `(P, Q)` steps by the next convergent `(P′, Q′)`, giving rungs
`(P + kP′, Q + kQ′)` for `k = 0 … t`, where `t` is the next partial quotient of
`log₂ 3` and the block lands exactly on the following convergent.  Since the
partial quotients include `23` and `55`, some blocks are long and some steps are
enormous:

| block | rungs |
|---|---|
| base `(485, 306)`, step `(1054, 665)`, `t = 23` | `485, 1539, …, 24727` |
| base `(24727, 15601)`, `t = 2` | `24727, 75235, 125743` |
| base `(125743, 79335)`, `t = 1` | `125743, 301994` |
| base `(301994, 190537)`, `t = 1` | `301994, 17087915` |
| base `(17087915, 10781274)`, `t = 3` | `17087915, 102225496, 187363077, …` |

**There is no dangerous rung at all between `301 994` and `17 087 915`** — the
ladder steps straight over `10^6` and `10^7`.  Paying a rung's price therefore
buys everything up to the *next* rung, however far away that is.

This reproduces the published result exactly.  Halbeisen–Hungerbühler report
`L_max = 102 225 496` with `m = 2.12 × 10^14`, and the closed form gives
`price(17 087 915) = 2.124 × 10^14` — **that is their `m`**.  It pays for every
rung through `17 087 915` (Eliahou's bound), and the next rung is
`17 087 915 + 85 137 581 = 102 225 496`, which is consequently the first survivor
and their `L_max`.  The formula was derived here independently of the paper and
lands on its two constants.

## A claim checked and withdrawn

It was suggested that the wall sits where the entropy of the extremal gap
sequences, `log₂ C(a, L−a)`, crosses `log₂ G`.  There is no such crossing.  Along
the ladder the two run `295.2` vs `476`, `945.4` vs `1530`, … , `4199.7` vs
`6799` at the wall itself, `6152.7` vs `9961` after it — entropy stays below bit
length by a near-constant ratio `≈ 0.62` throughout, with nothing distinguishing
`6809`.  The comparison describes the whole ladder equally and explains no wall.
-/

namespace Collatz
namespace HHThreshold

open HalbeisenHungerbuhler

/-- The criterion's test at one `(L, n)`: does verified range `c` kill this
length?  This is `hh_criterion`'s hypothesis `hsmall`, made decidable. -/
def hhKills (c L n : Nat) : Bool :=
  decide (hhMin L n L < (2 ^ L - 3 ^ n) * c)

/-- **The test is monotone in the verified range.**  Widening the range never
loses a length. -/
theorem hhKills_mono {c c' L n : Nat} (hcc : c ≤ c') (h : hhKills c L n = true) :
    hhKills c' L n = true := by
  rw [hhKills, decide_eq_true_eq] at h ⊢
  exact Nat.lt_of_lt_of_le h (Nat.mul_le_mul_left _ hcc)

/-- The criterion in threshold form: if the range kills `(L, n)` and the cycle
has that many odd steps, its minimum lies below the range. -/
theorem lt_of_hhKills {x L c : Nat} (hx : 0 < x) (hcyc : AccCycle.AccIsCycleOf x L)
    (hmin : ∀ k : Nat, x ≤ acceleratedOrbit k x)
    (hgap : 0 < 2 ^ L - 3 ^ oddCount x L)
    (h : hhKills c L (oddCount x L) = true) : x < c := by
  rw [hhKills, decide_eq_true_eq] at h
  exact HHBridge.hh_criterion' hx hcyc hmin hgap h

/-! ## The ladder, at its first two rungs

The prices in the table above, checked in the kernel where the numerals are
small enough to be worth checking.  `485` is killed at its stated price and not
one below it. -/

set_option exponentiation.threshold 1000 in
set_option maxRecDepth 4000000 in
set_option maxHeartbeats 4000000 in
theorem kills_485 : hhKills 72059 485 306 = true := by decide

set_option exponentiation.threshold 1000 in
set_option maxRecDepth 4000000 in
set_option maxHeartbeats 4000000 in
theorem not_kills_485 : hhKills 72058 485 306 = false := by decide

end HHThreshold
end Collatz
