import Collatz.Strategy.SegmentMonoid
import Collatz.Strategy.BottomUnreachable
import Collatz.Structure.Density

/-!
# Round XII, Branch B — the high-scale word model, and the exact reach of its budget

Round XII's Branch A is empty (`BottomUnreachable`): a counterexample never takes a
value below `1086464`.  This file owns the only surviving branch — the **high-scale
rigid regime** — and settles it.

## 1.  What "rigid word model" means, exactly

Read the affine law multiplicatively around a hypothetical accelerated cycle of period
`L`, odd count `a`, minimum `n`.  `CouplingNormal.cycle_total_coupling` is
`3^a·n + C_L = 2^L·n`, and `CouplingDecay.step_even` / `step_odd` factor the same
statement as a product over the odd points `y_1 … y_a`:

> `2^L / 3^a  =  ∏_{t<a} (1 + 1/(3·y_t))`.

Every `y_t ≥ n`, so the whole dependence on the *values* is squeezed into a window
whose width is controlled by `n` alone:

> **`1  <  2^L / 3^a  ≤  (1 + 1/(3n))^a`.**

That is the exact word model: the pair `(L, a)` — a pure word statistic — is the only
data left, and the dynamics enters only through the width of the window.  Two
consequences, and they point in opposite directions.

* **The limit is empty.**  As `n → ∞` the window collapses to `2^L = 3^a`, which has no
  solution with `L, a ≥ 1`.  So the *idealised* rigid word equation is contradictory —
  and this is exactly why the route looks promising.
* **The limit is never attained.**  The entire content is the width `≈ a/(3n)`, and
  linearising the product gives the repository's own `SegmentMonoid.cycle_frontier`,

  > **`3·n·(2^L − 3^a)  ≤  a·2^L`.**

  So the high-scale word model *is* the frontier inequality.  Round XII's prediction is
  **confirmed**: the budget architecture reduces to the frontier filter.  See
  `counterexample_word_budget` below, which is that reduction in Lean.

## 2.  The exact reach of the filter, and why it is finite

The reduction would be harmless if the filter were strong.  It is not, and the reason
is exact rather than heuristic.

Write `δ = L − a·log₂3`.  The filter says `1 − 2^(−δ) ≤ a/(3n)`, i.e. roughly
`δ ≤ a/(3n·ln2)`.  The left side is a Diophantine quantity bounded by `log₂3`; the
right side **grows linearly in `a`**.  So the filter is monotone in the *wrong*
direction: longer cycles are easier to admit, not harder, and past a finite threshold
it admits everything.

`budget_slack` below is that statement, proved outright: **once `2n ≤ a`, the frontier
inequality holds automatically** for every ladder pair `(L,a)` (a pair with
`3^a < 2^L ≤ 3^(a+1)`, i.e. `a` maximal for `L`).  No dynamics is used — it is a fact
about the integers.  Instantiating at the verified range (`n ≥ 1086464`) gives
`budget_vacuous_at_2172928`: the strongest word-only budget a counterexample admits
excludes **nothing** with `a ≥ 2 172 928`.

**The constant `2n` is exactly sharp**, and the reason is one line.  Clearing the
inequality, `3n(2^L − 3^a) ≤ a·2^L` is *equivalent* to

> `2^L / 3^a  ≤  3n / (3n − a)`,  i.e.  `δ ≤ log₂(3n/(3n−a))`  with  `δ = L − a·log₂3`.

For a ladder pair `δ < log₂3` always, and `log₂(3n/(3n−a)) ≥ log₂3` iff `3n/(3n−a) ≥ 3`
iff `a ≥ 2n`.  So `a ≥ 2n` is *precisely* the point at which the right-hand side
overtakes the largest defect a ladder pair can have.  Below it the filter still bites;
at or above it, never.  This is `budget_slack`, and there is no better constant.

> **Correction, recorded.**  A first pass computed the threshold from the *linearised*
> bound `δ ≤ a/(3n·ln2)` and reported `L ≤ 5 672 137`.  That criterion is strictly
> stronger than the real one (`−ln(1−x) ≥ x`), so it overcounts exclusions; a second
> implementation using the exact criterion found **zero** failures anywhere in
> `[5·10⁶, 5.8·10⁶)`.  The two implementations disagreed, the exact one is right, and
> the linearised number is withdrawn.  The correct universal threshold is `a ≥ 2n`,
> which is the constant proved below.

COMPUTATIONAL (exact criterion, `Decimal` at 50 digits, `L < 3.5·10⁶`): the largest
ladder pair actually excluded at `n = 1086464` is `L = 3 441 922`, against the proved
universal threshold `a = 2n = 2 172 928`, i.e. `L ≈ 3 444 009`.  The proved constant is
sharp to `0.06 %`.  `2 031 130` of the `3 444 009` lengths below the threshold are
excluded and the rest pass, so the filter is not even dense below its own reach.

## 3.  The survivor set is generated by the convergents of `log₂3`

COMPUTATIONAL (exact integers, `L ≤ 12000`): the survivors of `3nG ≤ a·2^L` at
`n = 1086464` are exactly

`(4701,2966) (5755,3631) (6809,4296) (7863,4961) (8917,5626) (9402,5932)`
`(9971,6291) (10456,6597) (11025,6956) (11510,7262)`

reproducing `SegmentMonoid`'s list independently.  Their structure is not a
coincidence and is worth recording: with

`p/q = 485/306` and `p'/q' = 1054/665` — the two consecutive convergents of `log₂3`
straddling it (`485 − 306·log₂3 = +1.475·10^(−3)`, `1054 − 665·log₂3 = −6.30·10^(−5)`) —

**every survivor is `u·(1054,665) + v·(485,306)` with `u ≥ 4`, `v ∈ {1,2}`**, verified
for all ten.  The frontier ladder's own spacings (`A(c)` records at `1636, 2301, 2966,
3631, 4296, 4961`, spaced by exactly `665`; frontier `L` spaced by `1054`) are the same
two convergents.  So `RealizableFrontier6809`'s "staircase" is literally the continued
fraction of `log₂3`, and the word model adds no arithmetic to it.

## 4.  The filter is strictly weaker than the certificate

`RealizableFrontier6809.length_ge_6809` excludes `L = 4701`.  The word budget does not:
`budget_admits_4701` verifies `3·1086464·2^4701 ≤ 3·1086464·3^2966 + 2966·2^4701` in the
kernel.  So

> **word budget  ⊊  frontier certificate**, by two risers (`4701` and `5755`).

The gap is exactly the information the certificate uses and the budget throws away: the
Beatty ceiling `Bcap` reads the *ordering* of the parity word, while `(L,a)` is only its
*content*.  A word-only model is therefore strictly below the tool already in the
repository, and cannot improve it.

## 5.  High-scale exactness: the *parity* alphabet is the full shift

*(Header corrected.  An earlier draft said "the octave alphabet is the full shift",
which the body already contradicts and which `OctaveWord.no_O0_after_O0` refutes
outright: `octave_word_free` proves freedom of the **parity** word by Terras, while the
octave letters `E/O0/O1` depend on the mantissa and do have a forbidden block.  Both
theorems are true; the gloss was not.)*

Section XX asks whether large `x` makes local transitions deterministic at the octave
level.  It does the opposite, and exactly so.  `octave_word_free` below: for every
`j ≤ k` and every target residue, the octave `[2^k, 2^(k+1))` contains a point with that
residue mod `2^j`, hence — by `Density.oddCount_mod` — with **any prescribed parity word
of length `j`**.  The witness is explicit: `2^k + (r % 2^j)`.

COMPUTATIONAL (exhaustive): the octave `[2^k, 2^(k+1))` realises all `2^j` parity words
of length `j` at `(k,j) = (12,6), (21,8), (14,10)` and at the boundary `(10,10)` —
`64/64`, `256/256`, `1024/1024`, `1024/1024`, no exceptions; the witness formula
`2^k + (r % 2^j)` was checked against the true orbit on random `(j,k,r)`.

So on the **parity alphabet** the high-scale symbolic system is the *full shift*: no
word is forbidden, there is no proper SCC decomposition, and in particular no
"recurrent component above `B`" to eliminate.  This strengthens
`ScaleLadder.no_finite_scale_invariant` (which produces *one* infinite admissible path)
to: *every* word is admissible.

The scoping matters, and cuts the other way too.  There *is* a genuine forbidden block
in the repository — `Octave.no_O0_after_O0`: in the three-letter octave-**increment**
alphabet `{E, O0, O1}` the block `O0 E^m O0` never occurs.  But that alphabet is
finite, so `ScaleLadder.no_finite_scale_invariant` applies to it verbatim: its
transition graph has a repeated vertex, hence a cycle, hence an infinite admissible
path, and acyclicity is unattainable there by theorem.  The two facts close the pincer:

> **The alphabet with forbidden words is finite and provably cannot be made acyclic;
> the alphabet that could carry unbounded information has no forbidden words at all.**

Section XXXVIII's target is therefore unattainable, and the question "what unbounded
coordinate supplies well-foundedness?" has no answer here — the obstruction is not a
missing coordinate but the presence of every transition on the only alphabet rich
enough to matter.

## Assets consumed

Only asset (a), the verified range, and only inside `counterexample_word_budget` (via
`RealizableFrontier6809.ge_verified_1086464`).  `budget_slack`, `octave_representative`
and `octave_word_free` are `d`-free integer facts and are *not* refuted by the genuine
cycles of `3x−1` (min `17`, `5`), `3x+5` (`5,19,23,187,347`), `3x+7` (`5`) or `3x+13`
(`131`) — nor should they be: they are negative results about a filter, and a filter
that admits those cycles is behaving correctly.  Indeed the `d = 5` cycle at `n = 5`
(`L = 2`, `a = 1`, `G = 1`) satisfies its own budget `3nG ≤ d·a·2^L` as `15 ≤ 20`.
-/

namespace Collatz
namespace HighScaleWord

open Reach AccCycle SegmentMonoid RealizableFrontier6809

/-! ## 1.  The word budget of a counterexample: the frontier filter, again -/

/-- **The high-scale word model, in Lean.**  A counterexample cycle, at its own
minimum, satisfies the frontier inequality with the *verified range* in place of the
unknown minimum:

`3 · 1086464 · (2^L − 3^a)  ≤  a · 2^L`.

Both inputs are already in the repository — `SegmentMonoid.cycle_frontier` and
`RealizableFrontier6809.ge_verified_1086464` — and that is the point: the Round XII
budget architecture, run at full strength on the only surviving branch, produces
exactly the frontier filter and nothing else. -/
theorem counterexample_word_budget {n L : Nat} (hn : 0 < n) (h : AccIsCycleOf n L)
    (hmin : ∀ j : Nat, n ≤ acceleratedOrbit j n) (hnr : ¬ ReachesOne n) :
    3 * 1086464 * (2 ^ L - 3 ^ oddCount n L) ≤ oddCount n L * 2 ^ L := by
  have hc : 1086464 ≤ n := ge_verified_1086464 hn hnr ⟨0, acceleratedOrbit_zero n⟩
  have hstep : 3 * 1086464 * (2 ^ L - 3 ^ oddCount n L)
      ≤ 3 * n * (2 ^ L - 3 ^ oddCount n L) :=
    Nat.mul_le_mul_right _ (Nat.mul_le_mul_left 3 hc)
  exact Nat.le_trans hstep (cycle_frontier hn h hmin)

/-! ## 2.  The reach of the filter is finite -/

/-- **The budget is automatically satisfied once `2n ≤ a`.**

Pure arithmetic: no dynamics, no `d = 1`.  For a *ladder pair* — one with
`2^L ≤ 3^(a+1)`, i.e. `a` the largest odd count compatible with the length — the gap
obeys `3·(2^L − 3^a) ≤ 2·2^L`, so `3n·(2^L − 3^a) ≤ 2n·2^L ≤ a·2^L`.

This is the exact reason the word model cannot be a cycle-half mechanism: the budget
`a/(3n)` grows linearly in the length while the Diophantine defect it has to beat is
bounded by `log₂3`.  The filter therefore has **finite reach**. -/
theorem budget_slack {n L a : Nat} (hlad : 2 ^ L ≤ 3 ^ (a + 1)) (ha : 2 * n ≤ a) :
    3 * n * (2 ^ L - 3 ^ a) ≤ a * 2 ^ L := by
  have hsucc : (3:Nat) ^ (a + 1) = 3 * 3 ^ a := by
    rw [Nat.pow_succ]; exact Nat.mul_comm _ _
  have hkey : 3 * (2 ^ L - 3 ^ a) ≤ 2 * 2 ^ L := by
    rw [hsucc] at hlad; omega
  calc 3 * n * (2 ^ L - 3 ^ a)
      = n * (3 * (2 ^ L - 3 ^ a)) := by
        rw [Nat.mul_assoc]; exact Nat.mul_left_comm 3 n _
    _ ≤ n * (2 * 2 ^ L) := Nat.mul_le_mul_left n hkey
    _ = (2 * n) * 2 ^ L := by rw [← Nat.mul_assoc, Nat.mul_comm n 2]
    _ ≤ a * 2 ^ L := Nat.mul_le_mul_right _ ha

/-- **The counterexample's own word budget excludes nothing past `a = 2 172 928`.**
Instantiating `budget_slack` at the verified range: for every ladder pair with at
least `2·1086464` odd steps, the inequality of `counterexample_word_budget` holds for
free, so it eliminates no length.

The constant is sharp: `3n(2^L − 3^a) ≤ a·2^L` is equivalent to
`2^L/3^a ≤ 3n/(3n−a)`, whose right side reaches `3` — the largest value `2^L/3^a` can
take on a ladder pair — exactly at `a = 2n`. -/
theorem budget_vacuous_at_2172928 {L a : Nat} (hlad : 2 ^ L ≤ 3 ^ (a + 1))
    (ha : 2172928 ≤ a) : 3 * 1086464 * (2 ^ L - 3 ^ a) ≤ a * 2 ^ L :=
  budget_slack hlad (by omega)

/-- Contrapositive, and the statement of finite reach: if the word budget *does*
exclude a ladder pair, then that pair has fewer than `2n` odd steps. -/
theorem excluded_of_short {n L a : Nat} (hlad : 2 ^ L ≤ 3 ^ (a + 1))
    (hex : ¬ (3 * n * (2 ^ L - 3 ^ a) ≤ a * 2 ^ L)) : a < 2 * n := by
  rcases Nat.lt_or_ge a (2 * n) with hlt | hge
  · exact hlt
  · exact absurd (budget_slack hlad hge) hex

/-- **The word budget, cleared of subtraction.**  `3n(2^L − 3^a) ≤ a·2^L` is
*equivalent* to `(3n − a)·2^L ≤ 3n·3^a`, i.e. to `2^L/3^a ≤ 3n/(3n−a)`.  This is the
exact word equation of the high-scale model: a pure comparison between the pair `(L,a)`
and the single number `n`. -/
theorem budget_cleared {n a P Q : Nat} (hQP : Q ≤ P) (ha : a ≤ 3 * n) :
    3 * n * (P - Q) ≤ a * P ↔ (3 * n - a) * P ≤ 3 * n * Q := by
  have e1 : 3 * n * (P - Q) = 3 * n * P - 3 * n * Q := Nat.mul_sub _ _ _
  have e2 : (3 * n - a) * P = 3 * n * P - a * P := Nat.sub_mul _ _ _
  have h1 : 3 * n * Q ≤ 3 * n * P := Nat.mul_le_mul_left _ hQP
  have h2 : a * P ≤ 3 * n * P := Nat.mul_le_mul_right _ ha
  rw [e1, e2]
  omega

/-- **`a = 2n` is exactly where the budget degenerates.**  At `a = 2n` the frontier
inequality is *equivalent* to the ladder condition `2^L ≤ 3^(a+1)` — it says nothing
beyond "`a` is the largest odd count compatible with `L`", which every ladder pair
satisfies by construction.

Above `2n` it is implied (`budget_slack`); below `2n` it is strictly stronger.  So
`budget_slack`'s constant is not an artefact of the proof: `2n` is the precise point at
which the word-only budget stops carrying information. -/
theorem budget_iff_ladder_at_2n {n L a : Nat} (hn : 0 < n) (ha : a = 2 * n)
    (hQP : (3:Nat) ^ a ≤ 2 ^ L) :
    3 * n * (2 ^ L - 3 ^ a) ≤ a * 2 ^ L ↔ 2 ^ L ≤ 3 ^ (a + 1) := by
  have hle : a ≤ 3 * n := by omega
  have hsub : 3 * n - a = n := by omega
  have hsucc : (3:Nat) ^ (a + 1) = 3 * 3 ^ a := by
    rw [Nat.pow_succ]; exact Nat.mul_comm _ _
  have key : 3 * n * 3 ^ a = n * (3 * 3 ^ a) := by
    rw [Nat.mul_assoc]; exact Nat.mul_left_comm 3 n (3 ^ a)
  rw [budget_cleared hQP hle, hsub, hsucc, key]
  exact ⟨fun h => Nat.le_of_mul_le_mul_left h hn, fun h => Nat.mul_le_mul_left n h⟩

/-! ## 2b.  The filter is strictly weaker than the certificate -/

set_option maxRecDepth 40000 in
set_option exponentiation.threshold 8000 in
/-- **The word budget admits `L = 4701`.**  The additive form of
`counterexample_word_budget` at the first ladder pair, checked in the kernel:
`3·1086464·2^4701 ≤ 3·1086464·3^2966 + 2966·2^4701`.

But `RealizableFrontier6809.length_ge_6809` *excludes* `L = 4701`.  So the word-only
budget is **strictly weaker** than the certificate already in the repository — by two
risers, `4701` and `5755`.  The missing information is the *ordering* of the parity
word, which `Bcap` reads and `(L,a)` cannot. -/
theorem budget_admits_4701 :
    3 * 1086464 * 2 ^ 4701 ≤ 3 * 1086464 * 3 ^ 2966 + 2966 * 2 ^ 4701 := by decide

set_option maxRecDepth 40000 in
set_option exponentiation.threshold 8000 in
/-- Sharpness at the previous riser: the budget *does* exclude `L = 3647`, so `4701` is
genuinely where it stops and not an artefact of where the check was run.

COMPUTATIONAL (exact integers, two independent implementations, zero mismatches): the
survivors below `L = 12000` are exactly the ten pairs listed in the header, the first
being `(4701, 2966)`; every `L ≤ 12000` has exactly one `a` with
`3^a < 2^L ≤ 3^(a+1)`, so the ladder hypothesis of `budget_slack` is not a restriction. -/
theorem budget_excludes_3647 :
    ¬ (3 * 1086464 * 2 ^ 3647 ≤ 3 * 1086464 * 3 ^ 2301 + 2301 * 2 ^ 3647) := by decide

/-! ## 3.  The octave alphabet is the full shift -/

/-- **Every residue class mod `2^j` meets every octave at or above scale `j`.**
Explicit witness `2^k + (r % 2^j)`. -/
theorem octave_representative {j k : Nat} (hjk : j ≤ k) (r : Nat) :
    ∃ m : Nat, 2 ^ k ≤ m ∧ m < 2 ^ (k + 1) ∧ m % 2 ^ j = r % 2 ^ j := by
  have hr : r % 2 ^ j < 2 ^ j := Nat.mod_lt _ (Nat.lt_of_lt_of_le Nat.zero_lt_one
    (Arith.one_le_two_pow j))
  refine ⟨2 ^ k + r % 2 ^ j, Nat.le_add_right _ _, ?_, ?_⟩
  · have hjk' : (2:Nat) ^ j ≤ 2 ^ k := Arith.two_pow_le_two_pow hjk
    have hk : (2:Nat) ^ (k + 1) = 2 ^ k + 2 ^ k := by
      rw [Nat.pow_succ]; omega
    omega
  · have hsplit : (2:Nat) ^ k = 2 ^ j * 2 ^ (k - j) := by
      rw [← Nat.pow_add]
      have hj : j + (k - j) = k := by omega
      rw [hj]
    rw [hsplit, Nat.add_comm, Nat.add_mul_mod_self_left]
    exact Nat.mod_eq_of_lt hr

/-- **Above any threshold, the octave-level symbolic system is the full shift.**
For every scale `k ≥ j` and every target `r`, the octave `[2^k, 2^(k+1))` contains a
point whose parity word of length `j` is the parity word of `r`.

So no parity word is forbidden at high scale: there is no proper SCC decomposition of
the octave transition system, and therefore no "recurrent component above `B`" to
eliminate.  High scale makes the symbolic dynamics *maximally nondeterministic*, not
deterministic — the opposite of what section XX hoped. -/
theorem octave_word_free {j k : Nat} (hjk : j ≤ k) (r : Nat) :
    ∃ m : Nat, 2 ^ k ≤ m ∧ m < 2 ^ (k + 1) ∧ oddCount m j = oddCount r j := by
  obtain ⟨m, hlo, hhi, hmod⟩ := octave_representative hjk r
  refine ⟨m, hlo, hhi, ?_⟩
  rw [Density.oddCount_mod m j, Density.oddCount_mod r j, hmod]

/-- The same statement above the verified range: for every window length `j`, every
parity word of length `j` is realised by a point of size at least `1086464`.  A
counterexample's confinement to the high scale forbids no word at all. -/
theorem word_free_above_verified (j r : Nat) :
    ∃ m : Nat, 1086464 ≤ m ∧ oddCount m j = oddCount r j := by
  obtain ⟨m, hlo, _, hw⟩ := octave_word_free (Nat.le_max_left j 21) r
  exact ⟨m, Nat.le_trans (by decide) (Nat.le_trans
    (Arith.two_pow_le_two_pow (Nat.le_max_right j 21)) hlo), hw⟩

/-! ## Axiom audit -/

#print axioms counterexample_word_budget
#print axioms budget_admits_4701
#print axioms budget_excludes_3647
#print axioms budget_cleared
#print axioms budget_iff_ladder_at_2n
#print axioms budget_slack
#print axioms budget_vacuous_at_2172928
#print axioms excluded_of_short
#print axioms octave_representative
#print axioms octave_word_free
#print axioms word_free_above_verified

end HighScaleWord
end Collatz
