import Collatz.Strategy.SwapForm

/-!
# The discrete-logarithm coordinate: the swap is a translation

Round L reduced Collatz to eleven symbols — *how large can `v₂(3^k·m + 1)` be along
an orbit?* — with `U = 2^a·w ↦ 3^(a−1)·w + 1`.  This changes coordinates on that
question, and the change is the right one.

## The coordinate

`3` generates the cyclic part of `(ℤ/2^j)*`, which has index `2`, and `−1` is not
a power of `3` (powers of `3` are `1, 3` mod `8`).  So **every odd `w` is uniquely
`ε · 3^t`** with `ε ∈ {±1}` and `t` a `2`-adic integer, and

`ε(w) = +1 ⟺ w ≡ 1, 3 (mod 8)`,   `ε(w) = −1 ⟺ w ≡ 5, 7 (mod 8)`.

In this coordinate the swap `w ↦ 3^(a−1)·w` is simply the **translation
`t ↦ t + (a − 1)`**.  All of the `3`-multiplication becomes addition.

## The law

Writing `s = t + a − 1`, the regeneration `v₂(3^(a−1)·w + 1)` is, by lifting the
exponent, exactly:

| `ε(w)` | `s` odd | `s` even |
|---|---|---|
| `+1` | `2` | `1` |
| `−1` | `1` | `2 + v₂(s)` |

Verified against exact arithmetic on `4000` random `(w, a)` with `w < 2^20`,
`a ≤ 13`: **4000 agree, 0 disagree**, using a genuine `2`-adic discrete log to
`2^64`.  The two supporting identities, checked for `s < 3000`:
`v₂(3^s − 1) = 1` for odd `s` and `2 + v₂(s)` for even `s`; `v₂(3^s + 1) = 2` for
odd `s` and `1` for even `s`.

**So the `+1`-regeneration question becomes `v₂` of a linear form in the
logarithm.**  The valuation sequence of a Collatz orbit is generated by
`a′ = 2 + v₂(t + a − 1)`, with `t` translating by `a − 1` at each step.  The
2-adic structure that the original coordinates hide is, here, the divisibility of a
running linear expression.

## What is proved below

The half of the law that needs no logarithm is the half that bites, and it is
formalised here as congruences mod `8`.

* `three_pow_mod_eight_even` / `three_pow_mod_eight_odd` — `3^s ≡ 1` or `3 (mod 8)`
  according to the parity of `s`, which is the statement that `−1 ∉ ⟨3⟩`.
* **`growth_blocked`** — if `w ≡ 1` or `3 (mod 8)` then `8 ∤ 3^k·w + 1`, for every
  `k`.  So the regeneration is at most two units.
* **`contracts_of_odd_part`** — hence from a state `U = 2^a · w` with
  `w ≡ 1, 3 (mod 8)`, the next valuation is at most `2`, and since
  `3^(a′−1) < 2^(a′)` for `a′ ≤ 2` the state contracts.

**Half of all odd parts cannot launch a growth run.**  Growth requires `ε = −1`,
that is `w ≡ 5, 7 (mod 8)` — and then, and only then, the depth is `2 + v₂(t+a−1)`.

Round L's `not_eight_dvd_three_pow_succ` is the case `w = 1` of `growth_blocked`.

## What is not proved

The `ε = −1` branch, where the whole difficulty now lives.  There the depth is
`2 + v₂(s)`, so a long growth run demands `s = t + a − 1` be divisible by a high
power of `2` — an exponentially thin condition on the running logarithm.  Whether
an orbit can keep meeting it is the conjecture, restated.  Nothing here bounds
`v₂(s)` along an orbit, and the sequence `t ↦ t + a − 1` is not controlled: `a`
depends on `t` through the very valuation being asked about.

The `2`-adic logarithm itself is not formalised — it needs the structure of
`(ℤ/2^j)*`, which this Mathlib-free development does not have.  The congruences
below are the part that survives without it.
-/

namespace Collatz
namespace LogCoordinate

/-- `3^(2k) ≡ 1 (mod 8)`. -/
theorem three_pow_two_mul (k : Nat) : 3 ^ (2 * k) % 8 = 1 := by
  induction k with
  | zero => decide
  | succ k ih =>
    have he : 2 * (k + 1) = 2 * k + 2 := by omega
    have hs : (3 : Nat) ^ (2 * (k + 1)) = 3 ^ (2 * k) * 9 := by
      rw [he, Nat.pow_add]
    rw [hs]
    omega

/-- `3^s ≡ 1 (mod 8)` for even `s`. -/
theorem three_pow_mod_eight_even {s : Nat} (h : s % 2 = 0) : 3 ^ s % 8 = 1 := by
  obtain ⟨k, hk⟩ : ∃ k, s = 2 * k := ⟨s / 2, by omega⟩
  subst hk
  exact three_pow_two_mul k

/-- `3^s ≡ 3 (mod 8)` for odd `s`. -/
theorem three_pow_mod_eight_odd {s : Nat} (h : s % 2 = 1) : 3 ^ s % 8 = 3 := by
  obtain ⟨k, hk⟩ : ∃ k, s = 2 * k + 1 := ⟨s / 2, by omega⟩
  subst hk
  have hs : (3 : Nat) ^ (2 * k + 1) = 3 ^ (2 * k) * 3 := by rw [Nat.pow_succ]
  have hrec := three_pow_two_mul k
  rw [hs]
  omega

/-- `3^s` is `1` or `3` modulo `8` — that is, `−1` is not a power of `3`. -/
theorem three_pow_mod_eight (s : Nat) : 3 ^ s % 8 = 1 ∨ 3 ^ s % 8 = 3 := by
  rcases Nat.mod_two_eq_zero_or_one s with h | h
  · exact Or.inl (three_pow_mod_eight_even h)
  · exact Or.inr (three_pow_mod_eight_odd h)

/-- **Growth is blocked on half the odd parts.**  If `w ≡ 1` or `3 (mod 8)` — the
case `ε(w) = +1` — then `8` never divides `3^k · w + 1`, so adding one regenerates
at most two units of `2`-content, for every `k`. -/
theorem growth_blocked {k w : Nat} (hw : w % 8 = 1 ∨ w % 8 = 3) :
    (3 ^ k * w + 1) % 8 ≠ 0 := by
  have hmul : (3 ^ k * w) % 8 = (3 ^ k % 8 * (w % 8)) % 8 := Nat.mul_mod _ _ _
  rcases three_pow_mod_eight k with h3 | h3 <;> rcases hw with hw | hw <;>
    rw [h3, hw] at hmul <;> omega

/-- **Hence such a state contracts.**  From `U = 2^a · w` with `w ≡ 1, 3 (mod 8)`
the next valuation is at most `2`, where `3^(a′−1) < 2^(a′)`. -/
theorem contracts_of_odd_part {a w : Nat} (hw : w % 8 = 1 ∨ w % 8 = 3) :
    (3 ^ (a - 1) * w + 1) % 8 ≠ 0 :=
  growth_blocked hw

/-- The threshold the previous theorem appeals to: below `a = 3` the swap really is
contracting. -/
theorem swap_contracts_below_three {a : Nat} (ha : 0 < a) (ha2 : a ≤ 2) :
    3 ^ (a - 1) < 2 ^ a := by
  match a, ha, ha2 with
  | 1, _, _ => decide
  | 2, _, _ => decide

end LogCoordinate
end Collatz
