import Collatz.Strategy.StairGeneric

/-!
# The dual staircase: how the steps themselves are generated

`Strategy.StairGeneric` takes a step `(m, n)` — a pair with `n = fexp m` and
`3 ^ m` just above `2 ^ n` — and drains `gapAt` until it breaks.  The break points
it produces are the *cliffs* of the certificate ladder.  Each level so far needed
its own `Step` instance, supplied by a kernel comparison on an ever-larger
literal.

This file removes that.  The steps are generated by the **same kind of
recurrence, on the dual quantity**

    lgapAt a = 3 ^ a − 2 ^ (fexp a),

how far `3 ^ a` sits *above* `2 ^ (fexp a)`.  Adding a cliff index `M` to a step
index `a` drains `lgapAt` by `2 ^ (fexp a) · gapAt M` each time, and the exact
statement is subtraction-free:

    3 ^ (a+M) + 2 ^ (fexp a) · gapAt M
        = 2 ^ (fexp a) · (2 · 2 ^ (fexp M)) + lgapAt a · 3 ^ M     (`key_identity`)

— true for **all** `a` and `M`, with no hypothesis at all.  Everything else is
reading it in one direction or the other.

## The two staircases interlock

* `StairGeneric.gap_step` drains `gapAt` under `+ m` for a step `m`, and where it
  exhausts is the next **cliff**.
* `lgap_step` here drains `lgapAt` under `+ M` for a cliff `M`, and where it
  exhausts is the next **step**.

Run alternately from `(665, 15601)`:

```
lgap staircase, M = 15601 :  665 → 16266 → 31867,  exhausts       (steps)
gap  staircase, m = 31867 : 15601 → 47468 → 79335,  exhausts      (cliffs)
lgap staircase, M = 79335 : 31867 → 111202,        exhausts       (steps)
                                   ↳ 190537 is the next cliff
```

Every `fexp` value in that diagram is *derived* from the recurrences.  The
deepest, `fexp 190537 = 301993`, is obtained from `lower_break` and never from a
comparison at `301 994` bits.

## What it buys

The level-3 cliff, `a = 190537`, has normalised gap `6.451 · 10⁻⁸` — two orders
below level 2.  A certificate whose reach passes it needs a verified range above
**`492 286 389 612`**, about `4.9 · 10¹¹`.
-/

namespace Collatz
namespace StairLower

open RealizableBound StairGap StairGeneric

/-! ## The dual gap -/

/-- `lgapAt a = 3 ^ a − 2 ^ (fexp a)`, the distance from `3 ^ a` down to the
power of two below it. -/
def lgapAt (a : Nat) : Nat := 3 ^ a - 2 ^ fexp a

theorem lgapAt_add (a : Nat) : lgapAt a + 2 ^ fexp a = 3 ^ a := by
  have := fexp_le a
  unfold lgapAt
  omega

/-- The two gaps partition the dyadic block: `gapAt a + lgapAt a = 2 ^ (fexp a)`. -/
theorem gap_add_lgap (a : Nat) : gapAt a + lgapAt a = 2 ^ fexp a := by
  have h1 := lgapAt_add a
  have h2 : gapAt a + 3 ^ a = 2 * 2 ^ fexp a := gapAt_add a
  omega

theorem gapAt_add' (M : Nat) : 3 ^ M + gapAt M = 2 * 2 ^ fexp M := by
  have := gapAt_add M
  omega

theorem lgapAt_eq {a F : Nat} (h : fexp a = F) : lgapAt a = 3 ^ a - 2 ^ F := by
  unfold lgapAt; rw [h]

/-! ## The identity

Unconditional: it holds for every `a` and `M`, and both branches below are just
readings of it. -/

/-- **The coupled identity.**  No hypothesis. -/
theorem key_identity (a M : Nat) :
    3 ^ (a + M) + 2 ^ fexp a * gapAt M
      = 2 ^ fexp a * (2 * 2 ^ fexp M) + lgapAt a * 3 ^ M := by
  have hL := lgapAt_add a
  have hG := gapAt_add' M
  have e1 : (3:Nat) ^ (a + M) = 3 ^ a * 3 ^ M := Nat.pow_add 3 a M
  have e2 : (3:Nat) ^ a * 3 ^ M = lgapAt a * 3 ^ M + 2 ^ fexp a * 3 ^ M := by
    rw [← hL, Nat.add_mul]
  have e3 : (2:Nat) ^ fexp a * (2 * 2 ^ fexp M)
      = 2 ^ fexp a * 3 ^ M + 2 ^ fexp a * gapAt M := by
    rw [← hG, Nat.mul_add]
  omega

theorem pow_split_lower (a M : Nat) :
    (2:Nat) ^ (fexp a + fexp M + 1) = 2 ^ fexp a * (2 * 2 ^ fexp M) := by
  rw [show fexp a + fexp M + 1 = fexp a + (fexp M + 1) from by omega, Nat.pow_add,
    Nat.pow_succ, Nat.mul_comm (2 ^ fexp M) 2]

/-- The upper half, needed in both branches. -/
theorem lt_pow_shift (a M : Nat) : (3:Nat) ^ (a + M) < 2 ^ (fexp a + fexp M + 2) := by
  have e1 : (3:Nat) ^ (a + M) = 3 ^ a * 3 ^ M := Nat.pow_add 3 a M
  have e2 : (2:Nat) ^ (fexp a + fexp M + 2) = 2 ^ (fexp a + 1) * 2 ^ (fexp M + 1) := by
    rw [show fexp a + fexp M + 2 = (fexp a + 1) + (fexp M + 1) from by omega, Nat.pow_add]
  have hpos : 0 < (3:Nat) ^ M := by
    have := Nat.one_le_pow M 3 (by omega); omega
  have h1 : (3:Nat) ^ a * 3 ^ M < 2 ^ (fexp a + 1) * 3 ^ M :=
    Nat.mul_lt_mul_of_pos_right (lt_fexp a) hpos
  have h2 : (2:Nat) ^ (fexp a + 1) * 3 ^ M ≤ 2 ^ (fexp a + 1) * 2 ^ (fexp M + 1) :=
    Nat.mul_le_mul (Nat.le_refl _) (Nat.le_of_lt (lt_fexp M))
  omega

/-! ## The two branches -/

/-- **The drain still has room**: `fexp` adds `fexp M + 1`. -/
theorem lower_step {a M : Nat} (h : 2 ^ fexp a * gapAt M ≤ lgapAt a * 3 ^ M) :
    fexp (a + M) = fexp a + fexp M + 1 := by
  refine RouteCap.fexp_eq_of ?_ (lt_pow_shift a M)
  have hk := key_identity a M
  have hs := pow_split_lower a M
  omega

/-- **The drain is exhausted**: `fexp` adds only `fexp M`, and `a + M` is the
next cliff rather than the next step. -/
theorem lower_break {a M : Nat} (h : lgapAt a * 3 ^ M < 2 ^ fexp a * gapAt M) :
    fexp (a + M) = fexp a + fexp M := by
  refine RouteCap.fexp_eq_of ?_ ?_
  · have e1 : (3:Nat) ^ (a + M) = 3 ^ a * 3 ^ M := Nat.pow_add 3 a M
    have e2 : (2:Nat) ^ (fexp a + fexp M) = 2 ^ fexp a * 2 ^ fexp M := Nat.pow_add 2 _ _
    have := Nat.mul_le_mul (fexp_le a) (fexp_le M)
    omega
  · have hk := key_identity a M
    have hs : (2:Nat) ^ (fexp a + fexp M + 1) = 2 ^ fexp a * (2 * 2 ^ fexp M) :=
      pow_split_lower a M
    omega

/-- **The dual recurrence, exactly.** -/
theorem lgap_step {a M : Nat} (h : 2 ^ fexp a * gapAt M ≤ lgapAt a * 3 ^ M) :
    lgapAt (a + M) + 2 ^ fexp a * gapAt M = lgapAt a * 3 ^ M := by
  have hf := lower_step h
  have hdef : lgapAt (a + M) = 3 ^ (a + M) - 2 ^ fexp (a + M) := rfl
  have hle : (2:Nat) ^ fexp (a + M) ≤ 3 ^ (a + M) := fexp_le (a + M)
  have hk := key_identity a M
  have hs := pow_split_lower a M
  rw [hf] at hdef hle
  omega

/-- **Step generation.**  A cliff `M` and a step `a` with drain to spare produce
the next step `a + M`, with no comparison at the new scale. -/
theorem step_of_lower {a M : Nat} (h : 2 ^ fexp a * gapAt M < lgapAt a * 3 ^ M) :
    Step (a + M) (fexp a + fexp M + 1) := by
  refine ⟨?_, ?_⟩
  · have hk := key_identity a M
    have hs := pow_split_lower a M
    omega
  · have := lt_pow_shift a M
    have e : fexp a + fexp M + 1 + 1 = fexp a + fexp M + 2 := by omega
    rw [e]
    exact this

/-! ## The staircase indices are convergent denominators, as the repository knew

Round LXXV.28 literature-checked this construction.  It is **Eliahou's tool**:
his 1993 bound of `17 087 915` on cycle length comes from the continued fraction
of `log₂ 3`, and RESEARCH.md's own convergent table (Round LXXIV) already records
`q₉ = 15 601`, `q₁₃ = 190 537` ("Lagarias's bound") and `q₁₅ = 10 781 274`
("Eliahou's `k(2^40)`"), with the note that *the known Collatz cycle-length
bounds are literally numerators of convergents of `log₂ 3`*.

The indices this file derives independently — `665`, `15601`, `31867`, `79335`,
`190537` — are exactly those denominators and their semiconvergents.  So the
recurrences here re-derive a known object from a different direction (exact
integer identities rather than approximation theory), which is worth something as
formalisation and nothing as mathematics.  In particular
`range_gt_492286389612` sits at `a = 190537`, which is `q₁₃`.

Recording it here so the connection is visible from the construction rather than
only from a research-log table eight thousand lines long. -/

/-! ## The chain, run

Every `fexp` below is derived.  The only kernel computations are the four drain
comparisons and one witness. -/

theorem fexp_665 : fexp 665 = 1054 :=
  RouteCap.fexp_eq_of (Nat.le_of_lt StairGap.two_pow_lt_three_pow)
    StairGap.three_pow_lt_two_pow

theorem fexp_31867 : fexp 31867 = 50508 :=
  RouteCap.fexp_eq_of (Nat.le_of_lt step2.lo) step2.hi

theorem fexp_16266 : fexp 16266 = 25781 := by
  have h := StairGap.fexp_16266
  rw [StairGap.fexp_15601] at h
  omega

/-! ### `665 → 16266 → 31867` : the level-2 step, generated -/

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem drain_665 : 2 ^ fexp 665 * gapAt 15601 < lgapAt 665 * 3 ^ 15601 := by
  rw [fexp_665, StairGap.gapAt_15601, lgapAt_eq fexp_665]
  decide

/-- `16266` is a staircase step, produced by the dual recurrence from `665` and
the cliff `15601`. -/
theorem step_16266 : Step 16266 25781 := by
  have h := step_of_lower drain_665
  rw [fexp_665, StairGap.fexp_15601] at h
  exact h

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem drain_16266 : 2 ^ fexp 16266 * gapAt 15601 < lgapAt 16266 * 3 ^ 15601 := by
  rw [fexp_16266, StairGap.gapAt_15601, lgapAt_eq fexp_16266]
  decide

/-- **`Step 31867 50508`, derived.**  `StairGeneric.step2` proved the same thing
by comparing `2 ^ 50508` with `3 ^ 31867` directly; this obtains it from the
recurrence instead, and the same route reaches every later level. -/
theorem step_31867 : Step 31867 50508 := by
  have h := step_of_lower drain_16266
  rw [fexp_16266, StairGap.fexp_15601] at h
  exact h

/-! ### `31867 → 111202`, then the level-3 cliff `190537` -/

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem drain_31867 : 2 ^ fexp 31867 * gapAt 79335 < lgapAt 31867 * 3 ^ 79335 := by
  rw [fexp_31867, StairGeneric.gapAt_79335, lgapAt_eq fexp_31867]
  decide

theorem fexp_111202 : fexp 111202 = 176251 := by
  have h := lower_step (Nat.le_of_lt drain_31867)
  rw [show (31867:Nat) + 79335 = 111202 from by omega, fexp_31867,
    StairGeneric.fexp_79335] at h
  omega

theorem lgapAt_111202 : lgapAt 111202 = 3 ^ 111202 - 2 ^ 176251 :=
  lgapAt_eq fexp_111202

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem break_111202 : lgapAt 111202 * 3 ^ 79335 < 2 ^ fexp 111202 * gapAt 79335 := by
  rw [fexp_111202, StairGeneric.gapAt_79335, lgapAt_111202]
  decide

/-- **`fexp 190537 = 301993`, derived.**  The drain from `31867` exhausts at
`111202 + 79335`, so `fexp` advances by only `fexp 79335` there and `190537` is a
cliff, not a step.  No comparison at `301 994` bits is made. -/
theorem fexp_190537 : fexp 190537 = 301993 := by
  have h := lower_break break_111202
  rw [show (111202:Nat) + 79335 = 190537 from by omega, fexp_111202,
    StairGeneric.fexp_79335] at h
  omega

theorem lo_190537 : (2:Nat) ^ 301993 ≤ 3 ^ 190537 := by
  have := fexp_le 190537; rw [fexp_190537] at this; exact this

theorem hi_190537 : (3:Nat) ^ 190537 < 2 ^ (301993 + 1) := by
  have := lt_fexp 190537; rw [fexp_190537] at this; exact this

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem wit_190537 :
    6 * 492286389612 * (2 * 2 ^ 301993 - 3 ^ 190537) ≤ 190537 * 3 ^ 190537 := by decide

/-- **The level-3 cliff.**  A certificate whose reach passes `190537` needs a
verified range above `492 286 389 612` — about `4.9 · 10¹¹`, against the
`3 380 808` that reaches `8286`.  The normalised gap there is `6.451 · 10⁻⁸`. -/
theorem range_gt_492286389612 {c A : Nat} (hA : 190537 < A)
    (hcert : ∀ i : Nat, i < A → Bcap i + 3 ^ i * c < 2 * 2 ^ fexp i * c) :
    492286389612 < c :=
  RouteCap.range_gt_of_reach hA lo_190537 hi_190537 wit_190537 hcert

/-! ## The alternation never stalls

The two chains have complementary entry conditions.  Writing `n = fexp m`, so
that `StairGeneric.delta m n` and `lgapAt m` are the same number:

* the **gap chain** advances from `M` iff `3 ^ M · lgapAt m < 2 ^ (fexp m) · gapAt M`
  (this is `StairGeneric.NoBreak m (fexp m) M`);
* the **lgap chain** advances from `m` iff `2 ^ (fexp m) · gapAt M ≤ lgapAt m · 3 ^ M`.

These are negations of each other.  So **exactly one of the two chains advances,
always** — `alternation_live` below is `Nat.lt_or_ge` after unfolding, and needs
no hypothesis.

Previous rounds listed "the alternation might stall" as the open problem and
guessed it needed the continued fraction of `log₂ 3`.  It does not: the two
conditions partition, and the only genuinely arithmetic input is that neither gap
ever vanishes, which is `3 ^ a` never being a power of two — parity, one line. -/

/-- `0 < fexp a` for `a ≥ 1`. -/
theorem fexp_pos {a : Nat} (ha : 0 < a) : 0 < fexp a := by
  obtain ⟨b, rfl⟩ : ∃ b, a = b + 1 := ⟨a - 1, by omega⟩
  have h3 : (3:Nat) ≤ 3 ^ (b + 1) := by
    have h1 : (1:Nat) ≤ 3 ^ b := Nat.one_le_pow b 3 (by omega)
    have h2 : (3:Nat) ^ (b + 1) = 3 ^ b * 3 := Nat.pow_succ 3 b
    omega
  rcases Nat.eq_zero_or_pos (fexp (b + 1)) with h | h
  · exfalso
    have := lt_fexp (b + 1)
    rw [h] at this
    have : (2:Nat) ^ (0 + 1) = 2 := by decide
    omega
  · exact h

theorem two_pow_even {k : Nat} (hk : 0 < k) : 2 ^ k % 2 = 0 := by
  obtain ⟨j, rfl⟩ : ∃ j, k = j + 1 := ⟨k - 1, by omega⟩
  rw [Nat.pow_succ]
  omega

/-- **`3 ^ a` is never a power of two.**  The one arithmetic input the whole
alternation needs, and it is parity. -/
theorem lgapAt_pos {a : Nat} (ha : 0 < a) : 0 < lgapAt a := by
  have hle := fexp_le a
  have hodd : (3:Nat) ^ a % 2 = 1 := Arith.three_pow_odd a
  have heven : (2:Nat) ^ fexp a % 2 = 0 := two_pow_even (fexp_pos ha)
  unfold lgapAt
  omega

/-- `gapAt` is positive at every index, directly from `lt_fexp`. -/
theorem gapAt_pos (a : Nat) : 0 < gapAt a := by
  have h := lt_fexp a
  have h2 : (2:Nat) ^ (fexp a + 1) = 2 * 2 ^ fexp a := by rw [Nat.pow_succ]; omega
  unfold gapAt
  omega

/-- **Every `m ≥ 1` is a staircase step.**  The `Step` structure is not a special
property of `665` and `31867`; those are only the indices where `delta / 3 ^ m`
is small. -/
theorem step_self {m : Nat} (hm : 0 < m) : Step m (fexp m) := by
  refine ⟨?_, lt_fexp m⟩
  have h := lgapAt_pos hm
  have hle := fexp_le m
  unfold lgapAt at h
  omega

/-- **The two chains partition.**  Unconditional. -/
theorem alternation_live (m M : Nat) :
    StairGeneric.NoBreak m (fexp m) M ∨ 2 ^ fexp m * gapAt M ≤ lgapAt m * 3 ^ M := by
  unfold StairGeneric.NoBreak StairGeneric.delta
  have hcomm : (3:Nat) ^ M * (3 ^ m - 2 ^ fexp m) = lgapAt m * 3 ^ M := by
    unfold lgapAt; exact Nat.mul_comm _ _
  rw [hcomm]
  exact Nat.lt_or_ge (lgapAt m * 3 ^ M) (2 ^ fexp m * gapAt M)

/-! ## Strict decrease along whichever chain runs -/

/-- Along a gap chain the normalised gap strictly decreases. -/
theorem gap_strict_decrease {m n a : Nat} (h : Step m n)
    (hb : StairGeneric.NoBreak m n a) :
    gapAt (a + m) * 3 ^ a < gapAt a * 3 ^ (a + m) := by
  have hd : 0 < StairGeneric.delta m n := by
    have := h.lo; unfold StairGeneric.delta; omega
  have hs := StairGeneric.gap_step h hb
  have h3a : 0 < (3:Nat) ^ a := by
    have := Nat.one_le_pow a 3 (by omega); omega
  have hpos : 0 < 3 ^ a * StairGeneric.delta m n := Nat.mul_pos h3a hd
  have hmul : (2:Nat) ^ n * gapAt a ≤ 3 ^ m * gapAt a :=
    Nat.mul_le_mul (Nat.le_of_lt h.lo) (Nat.le_refl _)
  have h1 : gapAt (a + m) < 3 ^ m * gapAt a := by omega
  have h2 : gapAt (a + m) * 3 ^ a < 3 ^ m * gapAt a * 3 ^ a :=
    Nat.mul_lt_mul_of_pos_right h1 h3a
  have hpow : (3:Nat) ^ (a + m) = 3 ^ a * 3 ^ m := Nat.pow_add 3 a m
  have hre : (3:Nat) ^ m * gapAt a * 3 ^ a = gapAt a * (3 ^ a * 3 ^ m) := by
    rw [Nat.mul_comm (3 ^ m) (gapAt a), Nat.mul_assoc, Nat.mul_comm (3 ^ m) (3 ^ a)]
  rw [hpow]
  omega

/-- Along an lgap chain the normalised dual gap strictly decreases. -/
theorem lgap_strict_decrease {a M : Nat}
    (h : 2 ^ fexp a * gapAt M ≤ lgapAt a * 3 ^ M) :
    lgapAt (a + M) * 3 ^ a < lgapAt a * 3 ^ (a + M) := by
  have hs := lgap_step h
  have hG := gapAt_pos M
  have h2f : 0 < (2:Nat) ^ fexp a := by
    have := Nat.one_le_pow (fexp a) 2 (by omega); omega
  have hpos : 0 < 2 ^ fexp a * gapAt M := Nat.mul_pos h2f hG
  have h3a : 0 < (3:Nat) ^ a := by
    have := Nat.one_le_pow a 3 (by omega); omega
  have h1 : lgapAt (a + M) < lgapAt a * 3 ^ M := by omega
  have h2 : lgapAt (a + M) * 3 ^ a < lgapAt a * 3 ^ M * 3 ^ a :=
    Nat.mul_lt_mul_of_pos_right h1 h3a
  have hpow : (3:Nat) ^ (a + M) = 3 ^ a * 3 ^ M := Nat.pow_add 3 a M
  have hre : lgapAt a * 3 ^ M * 3 ^ a = lgapAt a * (3 ^ a * 3 ^ M) := by
    rw [Nat.mul_assoc, Nat.mul_comm (3 ^ M) (3 ^ a)]
  rw [hpow]
  omega

/-- **Progress, unconditionally.**  For every `m ≥ 1` and every `M`, one of the
two chains advances and strictly decreases its normalised quantity.  Neither
quantity can reach zero (`lgapAt_pos`, `gapAt_pos`), so the alternation runs
forever. -/
theorem progress {m M : Nat} (hm : 0 < m) :
    gapAt (M + m) * 3 ^ M < gapAt M * 3 ^ (M + m)
      ∨ lgapAt (m + M) * 3 ^ m < lgapAt m * 3 ^ (m + M) := by
  rcases alternation_live m M with h | h
  · exact Or.inl (gap_strict_decrease (step_self hm) h)
  · exact Or.inr (lgap_strict_decrease h)

end StairLower
end Collatz
