import Collatz.Strategy.StairGeneric

/-!
# The dual staircase: how the steps themselves are generated

`Strategy.StairGeneric` takes a step `(m, n)` — a pair with `n = fexp m` and
`3 ^ m` just above `2 ^ n` — and drains `gapAt` until it breaks.  The break points
it produces are the *cliffs* of the certificate ladder.  Each level so far needed
its own `Step` instance, supplied by a kernel comparison on an ever-larger
literal.

This file removes that.  The steps are generated by the **same kind of
recurrence, on the dual quantity**

    lgapAt a = 3 ^ a − 2 ^ (fexp a),

how far `3 ^ a` sits *above* `2 ^ (fexp a)`.  Adding a cliff index `M` to a step
index `a` drains `lgapAt` by `2 ^ (fexp a) · gapAt M` each time, and the exact
statement is subtraction-free:

    3 ^ (a+M) + 2 ^ (fexp a) · gapAt M
        = 2 ^ (fexp a) · (2 · 2 ^ (fexp M)) + lgapAt a · 3 ^ M     (`key_identity`)

— true for **all** `a` and `M`, with no hypothesis at all.  Everything else is
reading it in one direction or the other.

## The two staircases interlock

* `StairGeneric.gap_step` drains `gapAt` under `+ m` for a step `m`, and where it
  exhausts is the next **cliff**.
* `lgap_step` here drains `lgapAt` under `+ M` for a cliff `M`, and where it
  exhausts is the next **step**.

Run alternately from `(665, 15601)`:

```
lgap staircase, M = 15601 :  665 → 16266 → 31867,  exhausts       (steps)
gap  staircase, m = 31867 : 15601 → 47468 → 79335,  exhausts      (cliffs)
lgap staircase, M = 79335 : 31867 → 111202,        exhausts       (steps)
                                   ↳ 190537 is the next cliff
```

Every `fexp` value in that diagram is *derived* from the recurrences.  The
deepest, `fexp 190537 = 301993`, is obtained from `lower_break` and never from a
comparison at `301 994` bits.

## What it buys

The level-3 cliff, `a = 190537`, has normalised gap `6.451 · 10⁻⁸` — two orders
below level 2.  A certificate whose reach passes it needs a verified range above
**`492 286 389 612`**, about `4.9 · 10¹¹`.
-/

namespace Collatz
namespace StairLower

open RealizableBound StairGap StairGeneric

/-! ## The dual gap -/

/-- `lgapAt a = 3 ^ a − 2 ^ (fexp a)`, the distance from `3 ^ a` down to the
power of two below it. -/
def lgapAt (a : Nat) : Nat := 3 ^ a - 2 ^ fexp a

theorem lgapAt_add (a : Nat) : lgapAt a + 2 ^ fexp a = 3 ^ a := by
  have := fexp_le a
  unfold lgapAt
  omega

/-- The two gaps partition the dyadic block: `gapAt a + lgapAt a = 2 ^ (fexp a)`. -/
theorem gap_add_lgap (a : Nat) : gapAt a + lgapAt a = 2 ^ fexp a := by
  have h1 := lgapAt_add a
  have h2 : gapAt a + 3 ^ a = 2 * 2 ^ fexp a := gapAt_add a
  omega

theorem gapAt_add' (M : Nat) : 3 ^ M + gapAt M = 2 * 2 ^ fexp M := by
  have := gapAt_add M
  omega

theorem lgapAt_eq {a F : Nat} (h : fexp a = F) : lgapAt a = 3 ^ a - 2 ^ F := by
  unfold lgapAt; rw [h]

/-! ## The identity

Unconditional: it holds for every `a` and `M`, and both branches below are just
readings of it. -/

/-- **The coupled identity.**  No hypothesis. -/
theorem key_identity (a M : Nat) :
    3 ^ (a + M) + 2 ^ fexp a * gapAt M
      = 2 ^ fexp a * (2 * 2 ^ fexp M) + lgapAt a * 3 ^ M := by
  have hL := lgapAt_add a
  have hG := gapAt_add' M
  have e1 : (3:Nat) ^ (a + M) = 3 ^ a * 3 ^ M := Nat.pow_add 3 a M
  have e2 : (3:Nat) ^ a * 3 ^ M = lgapAt a * 3 ^ M + 2 ^ fexp a * 3 ^ M := by
    rw [← hL, Nat.add_mul]
  have e3 : (2:Nat) ^ fexp a * (2 * 2 ^ fexp M)
      = 2 ^ fexp a * 3 ^ M + 2 ^ fexp a * gapAt M := by
    rw [← hG, Nat.mul_add]
  omega

theorem pow_split_lower (a M : Nat) :
    (2:Nat) ^ (fexp a + fexp M + 1) = 2 ^ fexp a * (2 * 2 ^ fexp M) := by
  rw [show fexp a + fexp M + 1 = fexp a + (fexp M + 1) from by omega, Nat.pow_add,
    Nat.pow_succ, Nat.mul_comm (2 ^ fexp M) 2]

/-- The upper half, needed in both branches. -/
theorem lt_pow_shift (a M : Nat) : (3:Nat) ^ (a + M) < 2 ^ (fexp a + fexp M + 2) := by
  have e1 : (3:Nat) ^ (a + M) = 3 ^ a * 3 ^ M := Nat.pow_add 3 a M
  have e2 : (2:Nat) ^ (fexp a + fexp M + 2) = 2 ^ (fexp a + 1) * 2 ^ (fexp M + 1) := by
    rw [show fexp a + fexp M + 2 = (fexp a + 1) + (fexp M + 1) from by omega, Nat.pow_add]
  have hpos : 0 < (3:Nat) ^ M := by
    have := Nat.one_le_pow M 3 (by omega); omega
  have h1 : (3:Nat) ^ a * 3 ^ M < 2 ^ (fexp a + 1) * 3 ^ M :=
    Nat.mul_lt_mul_of_pos_right (lt_fexp a) hpos
  have h2 : (2:Nat) ^ (fexp a + 1) * 3 ^ M ≤ 2 ^ (fexp a + 1) * 2 ^ (fexp M + 1) :=
    Nat.mul_le_mul (Nat.le_refl _) (Nat.le_of_lt (lt_fexp M))
  omega

/-! ## The two branches -/

/-- **The drain still has room**: `fexp` adds `fexp M + 1`. -/
theorem lower_step {a M : Nat} (h : 2 ^ fexp a * gapAt M ≤ lgapAt a * 3 ^ M) :
    fexp (a + M) = fexp a + fexp M + 1 := by
  refine RouteCap.fexp_eq_of ?_ (lt_pow_shift a M)
  have hk := key_identity a M
  have hs := pow_split_lower a M
  omega

/-- **The drain is exhausted**: `fexp` adds only `fexp M`, and `a + M` is the
next cliff rather than the next step. -/
theorem lower_break {a M : Nat} (h : lgapAt a * 3 ^ M < 2 ^ fexp a * gapAt M) :
    fexp (a + M) = fexp a + fexp M := by
  refine RouteCap.fexp_eq_of ?_ ?_
  · have e1 : (3:Nat) ^ (a + M) = 3 ^ a * 3 ^ M := Nat.pow_add 3 a M
    have e2 : (2:Nat) ^ (fexp a + fexp M) = 2 ^ fexp a * 2 ^ fexp M := Nat.pow_add 2 _ _
    have := Nat.mul_le_mul (fexp_le a) (fexp_le M)
    omega
  · have hk := key_identity a M
    have hs : (2:Nat) ^ (fexp a + fexp M + 1) = 2 ^ fexp a * (2 * 2 ^ fexp M) :=
      pow_split_lower a M
    omega

/-- **The dual recurrence, exactly.** -/
theorem lgap_step {a M : Nat} (h : 2 ^ fexp a * gapAt M ≤ lgapAt a * 3 ^ M) :
    lgapAt (a + M) + 2 ^ fexp a * gapAt M = lgapAt a * 3 ^ M := by
  have hf := lower_step h
  have hdef : lgapAt (a + M) = 3 ^ (a + M) - 2 ^ fexp (a + M) := rfl
  have hle : (2:Nat) ^ fexp (a + M) ≤ 3 ^ (a + M) := fexp_le (a + M)
  have hk := key_identity a M
  have hs := pow_split_lower a M
  rw [hf] at hdef hle
  omega

/-- **Step generation.**  A cliff `M` and a step `a` with drain to spare produce
the next step `a + M`, with no comparison at the new scale. -/
theorem step_of_lower {a M : Nat} (h : 2 ^ fexp a * gapAt M < lgapAt a * 3 ^ M) :
    Step (a + M) (fexp a + fexp M + 1) := by
  refine ⟨?_, ?_⟩
  · have hk := key_identity a M
    have hs := pow_split_lower a M
    omega
  · have := lt_pow_shift a M
    have e : fexp a + fexp M + 1 + 1 = fexp a + fexp M + 2 := by omega
    rw [e]
    exact this

/-! ## The chain, run

Every `fexp` below is derived.  The only kernel computations are the four drain
comparisons and one witness. -/

theorem fexp_665 : fexp 665 = 1054 :=
  RouteCap.fexp_eq_of (Nat.le_of_lt StairGap.two_pow_lt_three_pow)
    StairGap.three_pow_lt_two_pow

theorem fexp_31867 : fexp 31867 = 50508 :=
  RouteCap.fexp_eq_of (Nat.le_of_lt step2.lo) step2.hi

theorem fexp_16266 : fexp 16266 = 25781 := by
  have h := StairGap.fexp_16266
  rw [StairGap.fexp_15601] at h
  omega

/-! ### `665 → 16266 → 31867` : the level-2 step, generated -/

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem drain_665 : 2 ^ fexp 665 * gapAt 15601 < lgapAt 665 * 3 ^ 15601 := by
  rw [fexp_665, StairGap.gapAt_15601, lgapAt_eq fexp_665]
  decide

/-- `16266` is a staircase step, produced by the dual recurrence from `665` and
the cliff `15601`. -/
theorem step_16266 : Step 16266 25781 := by
  have h := step_of_lower drain_665
  rw [fexp_665, StairGap.fexp_15601] at h
  exact h

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem drain_16266 : 2 ^ fexp 16266 * gapAt 15601 < lgapAt 16266 * 3 ^ 15601 := by
  rw [fexp_16266, StairGap.gapAt_15601, lgapAt_eq fexp_16266]
  decide

/-- **`Step 31867 50508`, derived.**  `StairGeneric.step2` proved the same thing
by comparing `2 ^ 50508` with `3 ^ 31867` directly; this obtains it from the
recurrence instead, and the same route reaches every later level. -/
theorem step_31867 : Step 31867 50508 := by
  have h := step_of_lower drain_16266
  rw [fexp_16266, StairGap.fexp_15601] at h
  exact h

/-! ### `31867 → 111202`, then the level-3 cliff `190537` -/

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem drain_31867 : 2 ^ fexp 31867 * gapAt 79335 < lgapAt 31867 * 3 ^ 79335 := by
  rw [fexp_31867, StairGeneric.gapAt_79335, lgapAt_eq fexp_31867]
  decide

theorem fexp_111202 : fexp 111202 = 176251 := by
  have h := lower_step (Nat.le_of_lt drain_31867)
  rw [show (31867:Nat) + 79335 = 111202 from by omega, fexp_31867,
    StairGeneric.fexp_79335] at h
  omega

theorem lgapAt_111202 : lgapAt 111202 = 3 ^ 111202 - 2 ^ 176251 :=
  lgapAt_eq fexp_111202

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem break_111202 : lgapAt 111202 * 3 ^ 79335 < 2 ^ fexp 111202 * gapAt 79335 := by
  rw [fexp_111202, StairGeneric.gapAt_79335, lgapAt_111202]
  decide

/-- **`fexp 190537 = 301993`, derived.**  The drain from `31867` exhausts at
`111202 + 79335`, so `fexp` advances by only `fexp 79335` there and `190537` is a
cliff, not a step.  No comparison at `301 994` bits is made. -/
theorem fexp_190537 : fexp 190537 = 301993 := by
  have h := lower_break break_111202
  rw [show (111202:Nat) + 79335 = 190537 from by omega, fexp_111202,
    StairGeneric.fexp_79335] at h
  omega

theorem lo_190537 : (2:Nat) ^ 301993 ≤ 3 ^ 190537 := by
  have := fexp_le 190537; rw [fexp_190537] at this; exact this

theorem hi_190537 : (3:Nat) ^ 190537 < 2 ^ (301993 + 1) := by
  have := lt_fexp 190537; rw [fexp_190537] at this; exact this

set_option maxRecDepth 200000 in
set_option exponentiation.threshold 400000 in
theorem wit_190537 :
    6 * 492286389612 * (2 * 2 ^ 301993 - 3 ^ 190537) ≤ 190537 * 3 ^ 190537 := by decide

/-- **The level-3 cliff.**  A certificate whose reach passes `190537` needs a
verified range above `492 286 389 612` — about `4.9 · 10¹¹`, against the
`3 380 808` that reaches `8286`.  The normalised gap there is `6.451 · 10⁻⁸`. -/
theorem range_gt_492286389612 {c A : Nat} (hA : 190537 < A)
    (hcert : ∀ i : Nat, i < A → Bcap i + 3 ^ i * c < 2 * 2 ^ fexp i * c) :
    492286389612 < c :=
  RouteCap.range_gt_of_reach hA lo_190537 hi_190537 wit_190537 hcert

end StairLower
end Collatz
