#!/usr/bin/env python3
"""Reproduce unique residue certificates; Lean, not Python, certifies the claims.

Run without arguments to generate files and independent probe results.
Use --verify to kernel check all 300 batches; --commit additionally commits
only those checked batches. Existing unrelated workspace edits are excluded.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / 'Collatz/Research/DescentAtlas'
DEPTH = 14
BATCHES = 300
PER_BATCH = 8


def trajectory(n, depth):
    count = 0
    values = [n]
    for _ in range(depth):
        count += n % 2
        n = (3*n+1)//2 if n % 2 else n//2
        values.append(n)
    return count, n, values


def candidates():
    result = []
    for r in range(3, 2**DEPTH, 2):
        a, b, _ = trajectory(r, DEPTH)
        if 3**a < 2**DEPTH and b < r:
            result.append((r, a, b))
    return result


def certificate(r, a, b):
    return f'''/-- Exact parity count, endpoint, and contracting multiplier for residue {r}. -/
theorem data_{r} : oddCount {r} {DEPTH} = {a} ∧
    acceleratedOrbit {DEPTH} {r} = {b} ∧ {3**a} < {2**DEPTH} := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_{r} (m : Nat) :
    acceleratedOrbit {DEPTH} ({2**DEPTH} * m + {r}) = {3**a} * m + {b} := by
  have h := Congruence.accOrbit_pow_two_mul_add {DEPTH} m {r}
  rw [data_{r}.1, data_{r}.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_{r} (m : Nat) :
    acceleratedOrbit {DEPTH} ({2**DEPTH} * m + {r}) < {2**DEPTH} * m + {r} := by
  apply descent_of_endpoint
  · rw [data_{r}.1]; exact data_{r}.2.2
  · rw [data_{r}.2.1]; decide

'''


def generate():
    BASE.mkdir(parents=True, exist_ok=True)
    chosen = candidates()[:BATCHES*PER_BATCH]
    assert len(chosen) == BATCHES*PER_BATCH
    files = []
    for i in range(BATCHES):
        path = BASE / f'Batch{i+1:03}.lean'
        header = f'''import Collatz.Research.DescentAtlas.Core

/-! Batch {i+1}: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch{i+1:03}
open Collatz.Research.DescentAtlas

'''
        path.write_text(header + ''.join(certificate(*v) for v in chosen[i*8:(i+1)*8])
                        + f'end Collatz.Research.DescentAtlas.Batch{i+1:03}\n')
        files.append(path)
    (BASE/'All.lean').write_text('import Collatz.Research.DescentAtlas.Obstructions\n' + ''.join(
        f'import Collatz.Research.DescentAtlas.Batch{i+1:03}\n' for i in range(BATCHES)))
    return chosen, files


def probe(chosen, files):
    # Independent substitution tests check the affine implementation on varied indices.
    tests = 0
    for r, a, b in chosen:
        for m in [0, 1, 2, 17, 1024, 10**12]:
            n = 2**DEPTH*m+r
            _, actual, _ = trajectory(n, DEPTH)
            assert actual == 3**a*m+b and actual < n
            tests += 1
    levels = []
    for k in range(1, 19):
        survivors = contracting = descending = 0
        for r in range(2**k):
            a, b, values = trajectory(r, k)
            contracting += 3**a < 2**k
            descending += 3**a < 2**k and b < r
            count = 0
            survives = True
            for j, v in enumerate(values[:-1], 1):
                count += v % 2
                if 3**count < 2**j:
                    survives = False
                    break
            survivors += survives
        levels.append(dict(depth=k, residues=2**k, contracting=contracting,
                           strict_representative_descent=descending,
                           no_contracting_prefix=survivors))
    # Universal descent exploration on actual integers, distinct from coefficient tests.
    worst = (0, 0)
    for start in range(2, 100001):
        n = start
        for steps in range(1, 1001):
            n = (3*n+1)//2 if n % 2 else n//2
            if n < start:
                worst = max(worst, (steps, start))
                break
        else:
            raise AssertionError(('no descent within fuel', start))
    report = dict(depth=DEPTH, batches=BATCHES, certificates=len(chosen),
                  available_odd_classes=len(candidates()), affine_tests=tests,
                  finite_descent_test=dict(limit=100000, fuel=1000,
                                           max_steps=worst[0], witness=worst[1]),
                  levels=levels, residues=[r for r, _, _ in chosen],
                  generated_lean_lines=sum(len(p.read_text().splitlines()) for p in files),
                  hashes={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest()
                          for p in files},
                  status='Python tests passed; Lean verification recorded separately')
    (BASE/'probe.json').write_text(json.dumps(report, indent=2)+'\n')
    return report


def run(args):
    subprocess.run(args, cwd=ROOT, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify', action='store_true')
    parser.add_argument('--commit', action='store_true')
    opts = parser.parse_args()
    chosen, files = generate()
    report = probe(chosen, files)
    print(json.dumps({k:report[k] for k in ['certificates','generated_lean_lines','affine_tests',
                                         'finite_descent_test']}), flush=True)
    if opts.verify or opts.commit:
        run(['lake','build','Collatz.Research.DescentAtlas.Core'])
        for i, path in enumerate(files, 1):
            try:
                run(['lake','env','lean',str(path.relative_to(ROOT))])
            except subprocess.CalledProcessError as e:
                print(e.stdout.decode(), flush=True)
                raise
            if opts.commit:
                paths = [str(path.relative_to(ROOT))]
                if i == 1:
                    paths += ['scripts/descent_atlas.py',
                              'Collatz/Research/DescentAtlas/Core.lean']
                run(['git','add','--',*paths])
                run(['git','commit','-m',f'proof: certify descent atlas batch {i:03} (8 infinite classes)',
                     '--only','--',*paths])
            if i % 10 == 0:
                print(f'Kernel checked {i}/{BATCHES} batches', flush=True)
        (BASE/'verification.json').write_text(json.dumps(dict(
            checked_batches=BATCHES, checked_certificates=len(chosen),
            method='lake env lean; kernel decide; no native_decide',
            toolchain=(ROOT/'lean-toolchain').read_text().strip()),indent=2)+'\n')


if __name__ == '__main__':
    main()
