#!/usr/bin/env python3
"""Generate a serial chain of bounded-memory Lean interval certificates.

Every module checks one interval and proves the enlarged prefix from the prior
module. Compiler exit releases reduction memory between blocks. Python supplies
only scaffolding; Lean checks all arithmetic and every orbit. --check detects drift.
"""
import argparse
from pathlib import Path

THRESHOLD = 99730
CHUNK = 2048
SMALL_HORIZON = 135
ROOT = Path(__file__).resolve().parents[1]


def render_files():
    files = {}
    starts = list(range(0, THRESHOLD, CHUNK))
    for i, start in enumerate(starts):
        length = min(CHUNK, THRESHOLD - start)
        end = start + length
        previous = ('Collatz.Strategy.FirstLightIntervals' if i == 0 else
                    f'Collatz.Strategy.FirstLight1024Chunks.C{i-1:02d}')
        lines = [f'import {previous}', '',
                 '/-! Generated by scripts/generate_first_light_1024.py.',
                 'One kernel-checked block and the resulting cumulative prefix.',
                 'Separate compiler processes bound reduction memory. -/',
                 'namespace Collatz.FirstLight1024Chunks',
                 'open FirstLightScan', '',
                 'set_option maxRecDepth 200000',
                 'set_option maxHeartbeats 0',
                 'set_option Elab.async false', '',
                 f'private theorem block_{i:02d} :',
                 f'    checkInterval {SMALL_HORIZON} {start} {length} = true := by decide', '',
                 f'theorem prefix_{end} : checkInterval {SMALL_HORIZON} 0 {end} = true :=']
        if i == 0:
            lines += [f'  block_{i:02d}']
        else:
            lines += [f'  checkInterval_append {SMALL_HORIZON} 0 {start} {length}',
                      f'    prefix_{start} block_{i:02d}']
        lines += ['', 'end Collatz.FirstLight1024Chunks', '']
        files[f'Collatz/Strategy/FirstLight1024Chunks/C{i:02d}.lean'] = '\n'.join(lines)
    files['Collatz/Strategy/FirstLight1024.lean'] = '\n'.join([
        'import Collatz.Strategy.FirstLightGapCheck',
        f'import Collatz.Strategy.FirstLight1024Chunks.C{len(starts)-1:02d}', '',
        '/-!', '# First-crossing descent through 1024 steps', '',
        'Generated by scripts/generate_first_light_1024.py. The chain of interval',
        'certificates is verified in separate compiler processes. The first-crossing',
        'horizon remains an explicit hypothesis; no universal descent is asserted.', '-/',
        'namespace Collatz.FirstLight1024',
        'open FirstLightDescent FirstLightScan', '',
        '/-- Every exceptional start has a first-crossing descent by step 135. -/',
        'theorem small_starts_99730 : ∀ n : Fin 99730, 1<n.val →',
        '    ∃ k : Fin 136, FirstLight n.val k.val ∧ acceleratedOrbit k.val n.val < n.val := by',
        '  intro n hn',
        '  exact checkInterval_sound 135 0 99730 FirstLight1024Chunks.prefix_99730',
        '    n.val (by omega) n.isLt hn', '',
        '/-- No bound on n: every first coefficient crossing by 1024 is a descent. -/',
        'theorem descent_at_first_light_le_1024 {n k : Nat} (hn : 1<n)',
        '    (hk : k≤1024) (hfirst : FirstLight n k) : acceleratedOrbit k n < n := by',
        '  apply FirstLightCertificates.descent_of_certificates 1024 99730',
        '    (FirstLightGapCheck.check_sound 1024 99730 FirstLightGapCheck.gap_1024) _ hn hk hfirst',
        '  intro m hm',
        '  obtain ⟨j, hj, hd⟩ := small_starts_99730 m hm',
        '  exact ⟨⟨j.val, by have := j.isLt; omega⟩, hj, hd⟩', '',
        'end Collatz.FirstLight1024', '',
    ])
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files = render_files()
    for relative, expected in files.items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f'Generated source differs: {relative}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
    print(f'{"Checked" if args.check else "Wrote"} {len(files)} generated files.')


if __name__ == '__main__':
    main()
