#!/usr/bin/env python3
"""Search uniform inverse Collatz covers and emit data for Lean to check.

A leaf supplies an inverse valuation word. A ternary branch reads one more
digit of the root. Python discovers the witnesses; Lean checks their validity,
residue, valuation budget, size bound, and coverage of every possible root.
"""
import argparse
from functools import lru_cache
from pathlib import Path


def search(k, depth, budget, factor):
    modulus = 3**k

    @lru_cache(maxsize=None)
    def paths(a, precision):
        limit = precision - k
        best = {}

        def walk(n, word, total):
            if word and 2**total <= factor * 3**len(word):
                r = n % modulus
                if r not in best or (len(word), total, word) < (
                    len(best[r]), sum(best[r]), best[r]
                ):
                    best[r] = word
            if len(word) == limit or n % 3 == 0:
                return
            for v in range(1 if n % 3 == 2 else 2, budget - total + 1, 2):
                # Even the cheapest remaining steps cannot meet the size bound.
                if 2 ** (total + v + limit - len(word) - 1) > factor * 3**limit:
                    continue
                walk((2**v * n - 1) // 3, word + (v,), total + v)

        if limit > 0:
            walk(a, (), 0)
        return best

    stats = {"leaves": 0, "branches": 0, "max_depth": 0, "max_steps": 0}

    def tree(a, precision, target):
        word = paths(a, precision).get(target)
        if word is not None:
            stats["leaves"] += 1
            stats["max_depth"] = max(stats["max_depth"], len(word))
            stats["max_steps"] = max(stats["max_steps"], sum(word))
            return ".leaf [" + ", ".join(map(str, word)) + "]"
        if precision == k + depth:
            raise ValueError(f"uncovered root {a} mod {3**precision}, target {target}")
        stats["branches"] += 1
        children = [tree(a + j * 3**precision, precision + 1, target) for j in range(3)]
        return ".split (" + ") (".join(children) + ")"

    result = [(tree(1, 1, r), tree(2, 1, r)) for r in range(modulus)]
    return result, stats


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--k", type=int, default=2)
    parser.add_argument("--depth", type=int, default=6)
    parser.add_argument("--budget", type=int, default=19)
    parser.add_argument("--factor", type=int, default=720)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if min(args.k, args.depth, args.budget, args.factor) < 1:
        parser.error("k, depth, budget, and factor must be positive")
    result, stats = search(args.k, args.depth, args.budget, args.factor)
    print({"k": args.k, "factor": args.factor, "budget": args.budget, **stats}, flush=True)
    if args.output:
        text = ["import Collatz.Strategy.InverseCover\n",
                "/-! Generated by scripts/inverse_cover_certificate.py.\n",
                f"Parameters: k={args.k}, depth={args.depth}, budget={args.budget}, factor={args.factor}.\n",
                "Every certificate below is checked by Lean's kernel. -/\n\n",
                f"namespace Collatz.InverseCoverMod{3**args.k}\n",
                "open InverseCover\n\n"]
        for r, (one, two) in enumerate(result):
            for b, cert in [(1, one), (2, two)]:
                name = f"cert_{r}_{b}"
                text.append(f"def {name} : HitCert := {cert}\n\n")
                text.append(f"theorem {name}_checked : check {args.k} {r} {args.factor} {args.budget} {b} 1 {name} = true := by decide\n\n")
        text.append(f"theorem exists_checked (r b : Nat) (hr : r < {3**args.k}) (hb : b = 1 ∨ b = 2) :\n")
        text.append(f"    ∃ c : HitCert, check {args.k} r {args.factor} {args.budget} b 1 c = true := by\n")
        modulus = 3**args.k
        text.append("  have hrs : " + " ∨ ".join(f"r = {r}" for r in range(modulus)) + " := by omega\n")
        text.append("  rcases hrs with " + " | ".join("rfl" for _ in range(modulus)) + "\n")
        for r in range(modulus):
            text.append("  · rcases hb with rfl | rfl\n")
            for b in (1, 2):
                text.append(f"    · exact ⟨cert_{r}_{b}, cert_{r}_{b}_checked⟩\n")
        text.append("\n")
        text.append(f"end Collatz.InverseCoverMod{3**args.k}\n")
        args.output.write_text("".join(text))


if __name__ == "__main__":
    main()
