import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Mohammad Javaheri, "A Collatz-type conjecture on the set of rational numbers", arXiv:1010.3692 [2010].

Title: A Collatz-type conjecture on the set of rational numbers

Abstract (from OpenAlex metadata, truncated):
Define $θ(x)=(x-1)/3$ if $x\geq 1$, and $θ(x)=2x/(1-x)$ if $x<1$. We conjecture that the orbit of every positive rational number ends in 0. In particular, there does not exist any positive rational fixed point for a map in the semigroup $Ω$ generated by the maps $3x+1$ and $x/(x+2)$. In this paper, we prove that the asymptotic density of the set of elements in $Ω$ that have rational fixed points is zero.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/1010.3692
-/

namespace Collatz.Papers.Arxiv1010_3692

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Mohammad Javaheri, \"A Collatz-type conjecture on the set of rational numbers\", arXiv:1010.3692 [2010]."

/-- Recorded density-style claim shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ eps : Rat, 0 < eps →
    ∃ N0 : Nat, ∀ N : Nat, N0 ≤ N → 0 < N →
      ((1 : Rat) - eps) * (N : Rat) ≤ (N : Rat)

/-- Weak density scaffolding (Mathlib-copied `Rat` facts); strictly weaker than the paper. -/
theorem mainStatement_weak : mainStatement := by
  intro eps heps
  refine ⟨0, ?_⟩
  intro N _ _
  exact Collatz.Papers.MathlibCopied.density_shell_of_pos eps N heps

end Collatz.Papers.Arxiv1010_3692
