import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Leonel da Silveira Lobo Sternberg, "Predictable trajectories of the reduced Collatz iteration and a possible pathway to the proof of the Collatz conjecture (Version 2)", arXiv:2209.14230 [2022].

Title: Predictable trajectories of the reduced Collatz iteration and a possible pathway to the proof of the Collatz conjecture (Version 2)

Abstract (from OpenAlex metadata, truncated):
I show here that there are three different kinds of iterations for the reduced Collatz algorithm; depending on whether the root of the number is odd or even. There is only one kind of iteration if the root is odd and two kinds if the root is even. I also show that iterations on numbers with odd roots will cause an increase in value and eventually lead to an even rooted number. The iterations on even rooted numbers will subsequently cause a decrease in values. Because increase in values during the odd root iterations are bounded, I conclude that the Collatz iteration cannot veer to infinity. Since the sequence generated by the Collatz iteration is infinite and the values of the numbers do not veer to infinity it must either cycle and/or converge. I postulate that any cycling must occur with alternating types of iterations: e.g. odd rooted iterations which cause the values of the numbers to increase followed by even rooted iterations which causes the values to decrease. I show here that 

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2209.14230
-/

namespace Collatz.Papers.Arxiv2209_14230

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Leonel da Silveira Lobo Sternberg, \"Predictable trajectories of the reduced Collatz iteration and a possible pathway to the proof of the Collatz conjecture (Version 2)\", arXiv:2209.14230 [2022]."

/-- Recorded main claim shell (cycle); not proved.
States that any accelerated return to `n > 1` has already visited `1`. -/
def mainStatement : Prop :=
  ∀ n : Nat, n > 1 → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial 1-cycle returns to 1. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩


end Collatz.Papers.Arxiv2209_14230
