import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Monks, Keenan, Monks, Kenneth G., Monks, Kenneth M., Monks, Maria, "Strongly sufficient sets and the distribution of arithmetic sequences in the 3x+1 graph", arXiv:1204.3904 [2012].

Title: Strongly sufficient sets and the distribution of arithmetic sequences in the 3x+1 graph

Abstract (from OpenAlex metadata, truncated):
The 3x+1 Conjecture asserts that the T-orbit of every positive integer contains 1, where T maps x\mapsto x/2 for x even and x\mapsto (3x+1)/2 for x odd. A set S of positive integers is sufficient if the orbit of each positive integer intersects the orbit of some member of S. In a previous paper it was shown that every arithmetic sequence is sufficient.
  In this paper we further investigate the concept of sufficiency. We construct sufficient sets of arbitrarily low asymptotic density in the natural numbers. We determine the structure of the groups generated by the maps x\mapsto x/2 and x\mapsto (3x+1)/2 modulo b for b relatively prime to 6, and study the action of these groups on the directed graph associated to the 3x+1 dynamical system. From this we obtain information about the distribution of arithmetic sequences and obtain surprising new results about certain arithmetic sequences. Fo

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/1204.3904
-/

namespace Collatz.Papers.Arxiv1204_3904

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Monks, Keenan et al., \"Strongly sufficient sets and the distribution of arithmetic sequences in the 3x+1 graph\", arXiv:1204.3904 [2012]."

/-- Recorded density-style claim shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ eps : Rat, 0 < eps →
    ∃ N0 : Nat, ∀ N : Nat, N0 ≤ N → 0 < N →
      ((1 : Rat) - eps) * (N : Rat) ≤ (N : Rat)

/-- Weak density scaffolding (Mathlib-copied `Rat` facts); strictly weaker than the paper. -/
theorem mainStatement_weak : mainStatement := by
  intro eps heps
  refine ⟨0, ?_⟩
  intro N _ _
  exact Collatz.Papers.MathlibCopied.density_shell_of_pos eps N heps

end Collatz.Papers.Arxiv1204_3904
