import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Eric Sakk, "Symbolic Dynamic Formulation for the Collatz Conjecture: II. Quasi-Global Behavior", arXiv:2506.02510 [2025].

Title: Symbolic Dynamic Formulation for the Collatz Conjecture: II. Quasi-Global Behavior

Abstract (from OpenAlex metadata, truncated):
In this work, we continue the development of a symbolic dynamical formulation for the Collatz mapping. This formulation has been previously demonstrated to induce a ternary alphabet for characterizing the behavior of trajectories generated by this mapping. While the previous installation of this series focused on local and quasi-global behaviors, this work presents more quasi-global results that contribute to further understanding of the Collatz mapping.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2506.02510
-/

namespace Collatz.Papers.Arxiv2506_02510

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Eric Sakk, \"Symbolic Dynamic Formulation for the Collatz Conjecture: II. Quasi-Global Behavior\", arXiv:2506.02510 [2025]."

/-- Recorded main claim shell (structural); the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Arxiv2506_02510
