import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Kyo Jin Ihn, "Modular Arithmetic Study on Ascending and Descending Operations Related with Collatz Conjecture", arXiv:2311.12038 [2023].

Title: Modular Arithmetic Study on Ascending and Descending Operations Related with Collatz Conjecture

Abstract (from OpenAlex metadata, truncated):
Sequence of numbers generated by the recurrence relation based on the Collatz conjecture is investigated. An arithmetic operation on the Collatz conjecture is called descending operation, and ascending operation is carried out reversely to the descending operation. Study on the 3x+1 problem against every integer is relevant to that of descending operation against every odd. Any odds can be generated by ascending operations against odds not multiple of 3, and vise versa. Ascending operations against an odd not a multiple of 3 can generate infinite number of odds in the next generation. The odds multiple of 3 are terminal numbers of sequences that no further ascending operations are possible. Descending operations against the odds 1,5,21,.. reach 1, and otherwise reach the odds greater than or equal to 5. No two odds except 1 in each sequence are the same, and the each descending sequence is unique. Every descending sequence can start from terminal numbers, and reaches ultimately the ori

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2311.12038
-/

namespace Collatz.Papers.Arxiv2311_12038

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Kyo Jin Ihn, \"Modular Arithmetic Study on Ascending and Descending Operations Related with Collatz Conjecture\", arXiv:2311.12038 [2023]."

/-- Recorded main claim shell (logic); the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Arxiv2311_12038
