import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Robert Tremblay, "The 3x+1 Conjecture is false", arXiv:2104.10681 [2021].

Title: The 3x+1 Conjecture is false

Abstract (from OpenAlex metadata, truncated):
We will prove that there are trajectories generated by the functions at the origin of the 3x+1 and 5x+1 problems which are divergent. The iterative application of these functions on the set of positive integers allows us to determine that nearly 17% of all these integers, in the 5x+1 problem, belong to divergent trajectories. Regarding the 3x+1 problem, this percentage becomes very small, suggesting that all positive integers are part of converging trajectories. Despite this appearance, we will prove that this percentage will never be zero and that there will be an infinity of integers belonging to divergent trajectories, thus leading to the conclusion that the 3x+1 conjecture is false.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2104.10681
-/

namespace Collatz.Papers.Arxiv2104_10681

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Robert Tremblay, \"The 3x+1 Conjecture is false\", arXiv:2104.10681 [2021]."

/-- Recorded claim shell (structural); the paper's theorem is not proved.
Placeholder equals the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Arxiv2104_10681
