import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Ivan Slapničar, "There are no cycles in the $3n+1$ sequence", arXiv:1706.08399 [2017].

Title: There are no cycles in the $3n+1$ sequence

Abstract (from OpenAlex metadata, truncated):
In 1937, Lothar Collatz conjectured that the sequence generated by the rule $f(n)=3n+1$ for $n\in\mathbb{N}$ odd, $f(n)=n/2$ for $n\in\mathbb{N}$ even, starting in any positive integer $n$ produces $1$. This is equivalent to (1) there are no cycles except the trivial one, (1-4-2-1), and (2) there is no infinite sequence. We prove (1) using graph theory and linear algebra.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/1706.08399
-/

namespace Collatz.Papers.Arxiv1706_08399

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Ivan Slapni\u010dar, \"There are no cycles in the $3n+1$ sequence\", arXiv:1706.08399 [2017]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩


end Collatz.Papers.Arxiv1706_08399
