import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for John Cooper Faile, "Density of Collatz Trajectories", arXiv:2010.07294 [2020].

Title: Density of Collatz Trajectories

Abstract (from OpenAlex metadata, truncated):
In this paper I present a new method of studying the densities of the Collatz trajectories generated by a set $S \subset \mathbb{N}$. This method is used to furnish an alternative proof that $d(\{y \in \mathbb{N} : \exists k \text{ where } T^k(y) < cy\}) = 1$ for all $c > 0$. Finally, I briefly discuss how the ideas presented in this paper could be used to improve the result that $d(\{y \in \mathbb{N} : \exists k \text{ where } T^k(y) < y^c\}) = 1$ for $c > \log_4 3$.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2010.07294
-/

namespace Collatz.Papers.Arxiv2010_07294

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "John Cooper Faile, \"Density of Collatz Trajectories\", arXiv:2010.07294 [2020]."

/-- Recorded density-style claim shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ eps : Rat, 0 < eps →
    ∃ N0 : Nat, ∀ N : Nat, N0 ≤ N → 0 < N →
      ((1 : Rat) - eps) * (N : Rat) ≤ (N : Rat)

/-- Weak density scaffolding (Mathlib-copied `Rat` facts); strictly weaker than the paper. -/
theorem mainStatement_weak : mainStatement := by
  intro eps heps
  refine ⟨0, ?_⟩
  intro N _ _
  exact Collatz.Papers.MathlibCopied.density_shell_of_pos eps N heps


end Collatz.Papers.Arxiv2010_07294
