import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Takehiko Mori, "Application of Operator Theory for the Collatz Conjecture", arXiv:2411.08084 [2024].

Title: Application of Operator Theory for the Collatz Conjecture

Abstract (from OpenAlex metadata, truncated):
The Collatz map (or the $3n{+}1$-map) $f$ is defined on positive integers by setting $f(n)$ equal to $3n+1$ when $n$ is odd and $n/2$ when $n$ is even. The Collatz conjecture states that starting from any positive integer $n$, some iterate of $f$ takes value $1$. In this study, we discuss formulations of the Collatz conjecture by $C^{*}$-algebras in the following three ways: (1) single operator, (2) two operators, and (3) Cuntz algebra. For the $C^{*}$-algebra generated by each of these, we consider the condition that it has no non-trivial reducing subspaces. For (1), we prove that the condition implies the Collatz conjecture. In the cases (2) and (3), we prove that the condition is equivalent to the Collatz conjecture. For similar maps, we introduce equivalence relations by them and generalize connections between the Collatz conjecture and irreducibility of associated $C^{*}$-algebras.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2411.08084
-/

namespace Collatz.Papers.Arxiv2411_08084

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Takehiko Mori, \"Application of Operator Theory for the Collatz Conjecture\", arXiv:2411.08084 [2024]."

/-- Recorded main claim shell (generalization); the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Arxiv2411_08084
