import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Rafael O. Ruggiero, "The relationship between stopping time and number of odd terms in Collatz sequences", arXiv:1911.01229 [2019].

Title: The relationship between stopping time and number of odd terms in Collatz sequences

Abstract (from OpenAlex metadata, truncated):
The Collatz sequence for a given natural number $N$ is generated by repeatedly applying the map $N$ $\rightarrow$ $3N+1$ if $N$ is odd and $N$ $\rightarrow$ $N/2$ if $N$ is even. One elusive open problem in Mathematics is whether all such sequences end in 1 (Collatz conjecture), the alternative being the possibility of cycles or of unbounded sequences. In this paper, we present a formula relating the stopping time and the number of odd terms in a Collatz sequence, obtained numerically and tested for all numbers up to $10^7$ and for random numbers up to $2^{128.000}$. This result is presented as a conjecture, and with the hope that it could be useful for constructing a proof of the Collatz conjecture.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/1911.01229
-/

namespace Collatz.Papers.Arxiv1911_01229

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Rafael O. Ruggiero, \"The relationship between stopping time and number of odd terms in Collatz sequences\", arXiv:1911.01229 [2019]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩


end Collatz.Papers.Arxiv1911_01229
