import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Robert Tremblay, "Generalized 3x+1 Mappings : convergence and divergence", arXiv:1910.11798 [2019].

Title: Generalized 3x+1 Mappings : convergence and divergence

Abstract (from OpenAlex metadata, truncated):
Discussion about the convergence and divergence of trajectories generated by certain functions derived from generalized 3x+1 mappings

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/1910.11798
-/

namespace Collatz.Papers.Arxiv1910_11798

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Robert Tremblay, \"Generalized 3x+1 Mappings : convergence and divergence\", arXiv:1910.11798 [2019]."

/-- Recorded claim shell (generalization); the paper's theorem is not proved.
Placeholder equals the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Arxiv1910_11798
