import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Mikhail Neklyudov, "Functional analysis approach to the Collatz conjecture", arXiv:2106.11859 [2021].

Title: Functional analysis approach to the Collatz conjecture

Abstract (from OpenAlex metadata, truncated):
We investigate the problems related to the Collatz map $T$ from the point of view of functional analysis. We associate with $T$ certain linear operator $\mathcal{T}$ and show that cycles and (hypothetical) diverging trajectory (generated by $T$) correspond to certain classes of fixed points of operator $\mathcal{T}$. Furthermore, we demonstrate connection between dynamical properties of operator $\mathcal{T}$ and map $T$. We prove that absence of nontrivial cycles of $T$ leads to hypercyclicity of operator $\mathcal{T}$. In the second part we show that the index of operator $Id-\mathcal{T}\in\mathcal{L}(H^2(D))$ gives upper estimate on the number of cycles of $T$. For the proof we consider the adjoint operator $\mathcal{F}=\mathcal{T}^*$ \[ \mathcal{F}: g\to g(z^2)+\frac{z^{-\frac{1}{3}}}{3}\left(g(z^{\frac{2}{3}})+e^{\frac{2πi}{3}}g(z^{\frac{2}{3}}e^{\frac{2πi}{3}})+e^{\frac{4πi}{3}}g(z^{\frac{2}{3}}e^{\frac{4πi}{3}})\right), \] first introduced by Berg, Meinardus in \cite{BM1994}, an

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2106.11859
-/

namespace Collatz.Papers.Arxiv2106_11859

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Mikhail Neklyudov, \"Functional analysis approach to the Collatz conjecture\", arXiv:2106.11859 [2021]."

/-- Recorded main claim shell (cycle); not proved.
States that any accelerated return to `n > 1` has already visited `1`. -/
def mainStatement : Prop :=
  ∀ n : Nat, n > 1 → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial 1-cycle returns to 1. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩


end Collatz.Papers.Arxiv2106_11859
