import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Bork, Manfred, "On the nonexistence of cycles for the Collatz function", arXiv:1208.2556 [2012].

Title: On the nonexistence of cycles for the Collatz function

Abstract (from arXiv metadata, truncated):
The Collatz function is defined as C(n) = n / 2 if n is even and C(n) = 3n + 1 if n is odd. The Collatz conjecture states that every sequence generated by the Collatz function ends with the cycle (4, 2, 1) after a finite number of iterations. In this paper it is shown that there exists no other cycle for the Collatz function.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/1208.2556
-/

namespace Collatz.Papers.Arxiv1208_2556

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Bork, Manfred, \"On the nonexistence of cycles for the Collatz function\", arXiv:1208.2556 [2012]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Arxiv1208_2556
