import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Mercedes Orús–Lacort, Christophe Jouis, "Analyzing Collatz Conjecture Using the Mathematical Complete Induction Method", arXiv:2205.00174 [2022].

Title: Analyzing Collatz Conjecture Using the Mathematical Complete Induction Method

Abstract (from OpenAlex metadata, truncated):
In this paper, we demonstrate the Collatz conjecture using the mathematical complete induction method. We show that this conjecture is satisfied for the first values of natural numbers, and in analyzing the sequence generated by odd numbers, we can deduce a formula for the general term of the Collatz sequence for any odd natural number n after several iterations. This formula is used in one case that we analyze using the mathematical complete induction method in the process of demonstrating the conjecture.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/2205.00174
-/

namespace Collatz.Papers.Arxiv2205_00174

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Mercedes Or\u00fas\u2013Lacort and Christophe Jouis, \"Analyzing Collatz Conjecture Using the Mathematical Complete Induction Method\", arXiv:2205.00174 [2022]."

/-- Recorded main claim shell (structural); the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Arxiv2205_00174
