import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Mondal, Nabarun, Ghosh, Partha P., "A General Class of Collatz Sequence and Ruin Problem", arXiv:1203.2229 [2012].

Title: A General Class of Collatz Sequence and Ruin Problem

Abstract (from arXiv metadata, truncated):
In this paper we show the probabilistic convergence of the original Collatz (3n + 1) (or Hotpo) sequence to unity. A generalized form of the Collatz sequence (GCS) is proposed subsequently. Unlike Hotpo, an instance of a GCS can converge to integers other than unity. A GCS can be generated using the concept of an abstract machine performing arithmetic operations on different numerical bases. Original Collatz sequence is then proved to be a special case of GCS on base 2. The stopping time of GCS sequences is shown to possess remarkable statistical behavior. We conjecture that the Collatz convergence elicits existence of attractor points in digital chaos generated by arithmetic operations on numbers. We also model Collatz convergence as a classical ruin problem on the digits of a number in a base in which the abstract machine is computing and establish its statistical behavior. Finally an 

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://arxiv.org/abs/1203.2229
-/

namespace Collatz.Papers.Arxiv1203_2229

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Mondal, Nabarun and Ghosh, Partha P., \"A General Class of Collatz Sequence and Ruin Problem\", arXiv:1203.2229 [2012]."

/-- Recorded main claim shell (verification); paper bound not proved here.
A checked miniature verification for `n < 8` is given below. -/
def mainStatement : Prop :=
  ∃ B : Nat, 1 < B ∧ ∀ n : Nat, 0 < n → n < B → ∃ k : Nat, Collatz.orbit k n = 1

/-- Miniature verification: every positive `n < 8` reaches `1`. -/
theorem mainStatement_weak : mainStatement := by
  refine ⟨8, by omega, Collatz.Papers.MathlibCopied.verifies_below_eight⟩

end Collatz.Papers.Arxiv1203_2229
