import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Edward G. Belaga and Maurice Mignotte, "The Collatz Problem and Its Generalizations: Experimental Data. Table 1. Primitive Cycles of (3n + d)−mappings", 2007.

Title: The Collatz Problem and Its Generalizations: Experimental Data. Table 1. Primitive Cycles of (3n + d)−mappings

Abstract (from harvested metadata, truncated):
"We study here experimentally, and display the detailed tables of the cyclic structures of dynamical system D_d generated by iterations of the functions T_d acting, for all d ã 1 relatively prime to 6, on positive integers : T_d(n) = n \over 2, if n is even; otherwise T_d(n) =(3n+d) \over 2 In the case d = 1, the properties of the system D =D_1 are the subject of the well-known Collatz, or 3n+1, conjecture. According to Jeff Lagarias, 1990, a cycle of the system D_d is called primitive if its members have no common divisor >1. For every one of 6667 systems D_d, 1?d?19999, we calculate its complete, as we argue, list of primitive cycles. Our calculations confirm, in particular, two long-standing conjectures of Lagarias, 1990, and suggest the plausibility of, and fully confirm several new...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.13140/2.1.3893.9203
-/

namespace Collatz.Papers.Journal_10_13140_2_1_3893_9203

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Edward G. Belaga and Maurice Mignotte, \"The Collatz Problem and Its Generalizations: Experimental Data. Table 1. Primitive Cycles of (3n + d)−mappings\", HAL (Le Centre pour la Communication Scientifique Directe), DOI:10.13140/2.1.3893.9203 [2007]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_13140_2_1_3893_9203
