import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Changmin Wei, "A Complete and Rigorous Proof of the Collatz Conjecture with Lean4 Formal Verification", 2026.

Title: A Complete and Rigorous Proof of the Collatz Conjecture with Lean4 Formal Verification

Abstract (from harvested metadata, truncated):
This paper presents a complete, verifiable, and rigorous pure mathematical proof ofthe Collatz conjecture (the 3x+1 problem), based on asymptotic analysis of discreteiterative dynamical systems, the boundedness axiom of infinite orbits, and a strictcontradiction method. The standard statement of the Collatz conjecture is as follows:for any positive integer initial value � ∈ ℕ+, the infinite sequence generated by theCollatz iterative map {��(�)}�≥0 inevitably converges to the trivial cycle 4 → 2 → 1 andeventually terminates at 1. This work fully adopts the core methodology applied to theproof of the Jacobian conjecture:negating infinite escaping orbits + excludingnon-trivial periodic structur...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.5281/zenodo.22161112
-/

namespace Collatz.Papers.Journal_10_5281_zenodo_22161112

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Changmin Wei, \"A Complete and Rigorous Proof of the Collatz Conjecture with Lean4 Formal Verification\", Zenodo (CERN European Organization for Nuclear Research), DOI:10.5281/zenodo.22161112 [2026]."

/-- Recorded density-style claim shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ eps : Rat, 0 < eps →
    ∃ N0 : Nat, ∀ N : Nat, N0 ≤ N → 0 < N →
      ((1 : Rat) - eps) * (N : Rat) ≤ (N : Rat)

/-- Weak density scaffolding (Mathlib-copied `Rat` facts); strictly weaker than the paper. -/
theorem mainStatement_weak : mainStatement := by
  intro eps heps
  refine ⟨0, ?_⟩
  intro N _ _
  exact Collatz.Papers.MathlibCopied.density_shell_of_pos eps N heps

end Collatz.Papers.Journal_10_5281_zenodo_22161112
