import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Hamaji, Shinsuke, "A Direct Relocation Proof of the Collatz Conjecture via a Four-Dimensional Natural Number System", 2025.

Title: A Direct Relocation Proof of the Collatz Conjecture via a Four-Dimensional Natural Number System

Abstract (from harvested metadata, truncated):
Abstract An Indirect Structural Proof (ISP) of the Collatz Conjecture (CC) operates through CM (Child Mappings), guaranteeing that every natural number reaches CR (Child Roots), while maintaining injectivity in PM (Parent Mappings), such as the CR $\leftrightarrow$ CI (Child Images) orbits. Dimensional patterns based on the one-dimensional infinite sequence absolutely generated by Peano’s successor function ``$+1$'' function as a relocatable local structure; however, they fail to provide a configuration space capable of hosting the Infinitely Branching (IB) required by the parent–child architecture of CC. In contrast, by constraining the starting point (e.g., $0$ or $1$), the spatial degrees...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.5281/zenodo.17518224
-/

namespace Collatz.Papers.Journal_10_5281_zenodo_17518224

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Hamaji, Shinsuke, \"A Direct Relocation Proof of the Collatz Conjecture via a Four-Dimensional Natural Number System\", Zenodo, DOI:10.5281/zenodo.17518224 [2025]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_5281_zenodo_17518224
