import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Jason Mullings, "A Resonance--Spectral Approach to the Collatz Problem: Empirical Universality and Analytic Constraints.", 2026.

Title: A Resonance--Spectral Approach to the Collatz Problem: Empirical Universality and Analytic Constraints.

Abstract (from harvested metadata, truncated):
The paper presents a novel framework for analyzing the Collatz Conjecture. Rather than attempting a traditional number-theoretic or combinatorial proof, the author translates the dynamical system into a functional-analytic/signal-processing domain. Specifically, the paper maps the sequence of multiplicative factors of a Collatz trajectory into a cumulative phase, which then generates an absolutely convergent "dyadic phase series". The core of the paper involves comparing the complex modulus of this series to a reference spectrum generated by the known attractor cycle using a Huber-weighted log-spectral distance (the "resonance scalar". The author posits that the Collatz conjecture is equivalent to bounding this asymptotic resonance below an empirically derived threshold. Crucially, the...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.5281/zenodo.20042345
-/

namespace Collatz.Papers.Journal_10_5281_zenodo_20042345

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Jason Mullings, \"A Resonance--Spectral Approach to the Collatz Problem: Empirical Universality and Analytic Constraints.\", Zenodo (CERN European Organization for Nuclear Research), DOI:10.5281/zenodo.20042345 [2026]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_5281_zenodo_20042345
