import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Giovanny Fuentes, "The Collatz Conjecture “The Nonexistence of Divergent Orbits, through a Dynamic Diophantine Linear Analysis of Codification”", 2024.

Title: The Collatz Conjecture “The Nonexistence of Divergent Orbits, through a Dynamic Diophantine Linear Analysis of Codification”

Abstract (from harvested metadata, truncated):
We define the function $Col: \mathbb{N} \to \mathbb{N}$ as the Collatz function, given by $3n + 1$ if $n$ is odd and $\displaystyle\frac{n}{2}$ if $n$ is even \cite{Lagarias1990}. The conjecture postulates that for any positive integer, at some point, its iteration will reach 1, or equivalently, every orbit will fall into the periodic cycle $\{4, 2, 1\}$. Two conditions would invalidate the conjecture: the existence of a divergent orbit or the presence of another cycle. In 2019 Terence Tao \cite{tao} proved that almost all orbits converge to the trivial cycle of $\{1,4,2\}$, in this work we will prove the non-existence of divergent orbits. The central idea is to decompose the dynamic system $Col$ into a binary dynamic system, generated by different compositions of two functions. This...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.20944/preprints202408.0985.v2
-/

namespace Collatz.Papers.Journal_10_20944_preprints202408_0985_v2

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Giovanny Fuentes, \"The Collatz Conjecture “The Nonexistence of Divergent Orbits, through a Dynamic Diophantine Linear Analysis of Codification”\", Preprints.org, DOI:10.20944/preprints202408.0985.v2 [2024]."

/-- Recorded density-style claim shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ eps : Rat, 0 < eps →
    ∃ N0 : Nat, ∀ N : Nat, N0 ≤ N → 0 < N →
      ((1 : Rat) - eps) * (N : Rat) ≤ (N : Rat)

/-- Weak density scaffolding (Mathlib-copied `Rat` facts); strictly weaker than the paper. -/
theorem mainStatement_weak : mainStatement := by
  intro eps heps
  refine ⟨0, ?_⟩
  intro N _ _
  exact Collatz.Papers.MathlibCopied.density_shell_of_pos eps N heps

end Collatz.Papers.Journal_10_20944_preprints202408_0985_v2
