import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Andrew Gleibman, "Maximal Length of a Collatz Sequence", 2023.

Title: Maximal Length of a Collatz Sequence

Abstract (from harvested metadata, truncated):
This is a continuation of our paper "Reformulating Collatz Conjecture Without Numerical Concepts", which provides a way to replace all numerical calculations, applied in the formulation of this conjecture, by simple symbol processing rules. We provide a simple and intuitive proof that there is no limit for the length of possible sequences, composed of odd numbers generated by the Collatz algorithm.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.31219/osf.io/854g3
-/

namespace Collatz.Papers.Journal_10_31219_osf_io_854g3

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Andrew Gleibman, \"Maximal Length of a Collatz Sequence\", DOI:10.31219/osf.io/854g3 [2023]."

/-- Recorded main claim shell (verification); paper bound not proved here.
A checked miniature verification for `n < 8` is given below. -/
def mainStatement : Prop :=
  ∃ B : Nat, 1 < B ∧ ∀ n : Nat, 0 < n → n < B → ∃ k : Nat, Collatz.orbit k n = 1

/-- Miniature verification: every positive `n < 8` reaches `1`. -/
theorem mainStatement_weak : mainStatement := by
  refine ⟨8, by omega, Collatz.Papers.MathlibCopied.verifies_below_eight⟩

end Collatz.Papers.Journal_10_31219_osf_io_854g3
