import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Amarachukwu Nwankpa, "A Proof of the Collatz Conjecture via Finite State Machine Analysis and Structural Confinement", 2025.

Title: A Proof of the Collatz Conjecture via Finite State Machine Analysis and Structural Confinement

Abstract (from harvested metadata, truncated):
The Collatz Conjecture, a long-standing open problem in number theory, asserts that every positive integer sequence generated by the Collatz function eventually reaches the 4-2-1 cycle. This paper presents a deterministic proof by modeling the Collatz dynamics using a 17-state finite state machine (FSM) derived from a structured partition of the integers. This FSM comprises a two-state precursor stage (for multiples of 3), a 12-state transient core (for other numbers outside the cycle), and a 3-state terminal stage (representing the 4-2-1 cycle). We analyze the deterministic transitions within this FSM and prove that every state in the precursor and core stages has a finite path leading inevitably to the terminal cycle stage, guaranteeing convergence for all starting integers. Our...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.20944/preprints202503.0929.v6
-/

namespace Collatz.Papers.Journal_10_20944_preprints202503_0929_v6

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Amarachukwu Nwankpa, \"A Proof of the Collatz Conjecture via Finite State Machine Analysis and Structural Confinement\", Preprints.org, DOI:10.20944/preprints202503.0929.v6 [2025]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_20944_preprints202503_0929_v6
