import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Lorenz Halbeısen and Norbert Hungerbühler, "Optimal bounds for the length of rational Collatz cycles", 1997.

Title: Optimal bounds for the length of rational Collatz cycles

Abstract (from harvested metadata, truncated):
. We consider the arithmetics of Collatz cycles in Q[(2)]. In particular, we prove optimal estimates for the length of a cycle in terms of its minimum. As an application, we derive an improved version of Eliahou's criterion, and we show that the length of (integer) Collatz cycles which do not contain 1, is at least 102 225 496 provided the Collatz conjecture is verified for all initial values x 0 212 366 032 807 211. 1. Introduction For x 2 IR let g 0 (x) = x 2 and g 1 (x) = 3x+1 2 . Let Q[(2)] denote the local ring of fractions of ZZ at the prime ideal (2), i.e. the domain of all rational numbers having (written in least terms) an odd denominator. A number p q 2 Q[(2)] with q odd is considered even or odd according to the parity of the numerator p. Then the Collatz sequence generated by...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.4064/aa-78-3-227-239
-/

namespace Collatz.Papers.Journal_10_4064_aa_78_3_227_239

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Lorenz Halbeısen and Norbert Hungerbühler, \"Optimal bounds for the length of rational Collatz cycles\", Acta Arithmetica, DOI:10.4064/aa-78-3-227-239 [1997]."

/-- Recorded main claim shell (verification); paper bound not proved here.
A checked miniature verification for `n < 8` is given below. -/
def mainStatement : Prop :=
  ∃ B : Nat, 1 < B ∧ ∀ n : Nat, 0 < n → n < B → ∃ k : Nat, Collatz.orbit k n = 1

/-- Miniature verification: every positive `n < 8` reaches `1`. -/
theorem mainStatement_weak : mainStatement := by
  refine ⟨8, by omega, Collatz.Papers.MathlibCopied.verifies_below_eight⟩

end Collatz.Papers.Journal_10_4064_aa_78_3_227_239
