import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for J. G. Polli et al., "Stochastic-like characteristics of arithmetic dynamical systems: the Collatz hailstone sequences", 2024.

Title: Stochastic-like characteristics of arithmetic dynamical systems: the Collatz hailstone sequences

Abstract (from harvested metadata, truncated):
Abstract The numerical hailstone sequences, or orbits, generated by the Collatz map have been disclosed to present relevant features commonly associated with complex systems. It is so despite the extreme simplicity of the arithmetic dynamical system iteration rule. Indeed, for a positive integer n , the Collatz map f reads f ( n ) = n / 2 ( f ( n ) = 3 n + 1 ) for n even (odd). Seeking to elucidate this surprising fact, here we unveil distinct characteristics of stochastic-like behavior for collections of Collatz orbits by considering methods commonly employed to temporal series, as cryptography tests, power-spectrum, detrended fluctuation, auto-correlation and entropy measure. Besides confirming previous predictions that the Collatz orbits display some global properties of geometric...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.1088/2632-072x/ad271f
-/

namespace Collatz.Papers.Journal_10_1088_2632_072x_ad271f

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "J. G. Polli et al., \"Stochastic-like characteristics of arithmetic dynamical systems: the Collatz hailstone sequences\", Journal of Physics Complexity, DOI:10.1088/2632-072x/ad271f [2024]."

/-- Recorded density-style claim shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ eps : Rat, 0 < eps →
    ∃ N0 : Nat, ∀ N : Nat, N0 ≤ N → 0 < N →
      ((1 : Rat) - eps) * (N : Rat) ≤ (N : Rat)

/-- Weak density scaffolding (Mathlib-copied `Rat` facts); strictly weaker than the paper. -/
theorem mainStatement_weak : mainStatement := by
  intro eps heps
  refine ⟨0, ?_⟩
  intro N _ _
  exact Collatz.Papers.MathlibCopied.density_shell_of_pos eps N heps

end Collatz.Papers.Journal_10_1088_2632_072x_ad271f
