import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Giovanni Ferraiuolo, "Modular Confinement of the Collatz Sequence in Z×9: The Subgroup ⟨4⟩, the Beating Pattern {1, 4, 7}, and Collision Orbits with Powers of Two", 2026.

Title: Modular Confinement of the Collatz Sequence in Z×9: The Subgroup ⟨4⟩, the Beating Pattern {1, 4, 7}, and Collision Orbits with Powers of Two

Abstract (from harvested metadata, truncated):
We study the behaviour of the Collatz iteration through the lens of the digital-root projection R: N → {1,...,9}, defined by R(n) = n mod 9. We prove three results: (i) Modular Confinement Lemma: every Collatz orbit starting outside the multiples of 3 remains permanently confined to Z×9 = {1,2,4,5,7,8}, the unique subgroup of order 6 generated by 2 in (Z/9Z)×; (ii) Beating Pattern Theorem: the odd Collatz step n → 3n+1 sends every odd integer into the order-3 subgroup ⟨4⟩ = {1,4,7}, with the three values equidistributed at frequency exactly 1/3, verified computationally on 5×10^7 odd integers with zero anomalies; (iii) Power-of-Two Collision Formula: odd integers n satisfying 3n+1 = 2^k are...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.5281/zenodo.20020962
-/

namespace Collatz.Papers.Journal_10_5281_zenodo_20020962

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Giovanni Ferraiuolo, \"Modular Confinement of the Collatz Sequence in Z×9: The Subgroup ⟨4⟩, the Beating Pattern {1, 4, 7}, and Collision Orbits with Powers of Two\", Zenodo (CERN European Organization for Nuclear Research), DOI:10.5281/zenodo.20020962 [2026]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_5281_zenodo_20020962
