import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for redero, julian and redero, julian, "Proof of the Collatz Conjecture by Residual Reduction and Effective Certification of 64 Admissible Affine Families", 2026.

Title: Proof of the Collatz Conjecture by Residual Reduction and Effective Certification of 64 Admissible Affine Families

Abstract (from harvested metadata, truncated):
We present a finite-certificate formulation of a residual reduction scheme for theCollatz map. The construction reduces the residual dynamics to primitive sources, the 64admissible affine families modulo 192, the family associated with 104, and a finite rigidlayer generated by first-exit lateral branches. The active and base layers are finite anddirectly checkable. The rigid layer is not claimed here to be closed by a purely analyticargument; its closure is delegated to a finite archive of rigid and reinjection certificatestogether with a strict verifier. The preliminary global-entry reduction is analytic: everypositive integer eventually enters the residual layer considered here. The remain...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.5281/zenodo.19539051
-/

namespace Collatz.Papers.Journal_10_5281_zenodo_19539051

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "redero, julian and redero, julian, \"Proof of the Collatz Conjecture by Residual Reduction and Effective Certification of 64 Admissible Affine Families\", Zenodo, DOI:10.5281/zenodo.19539051 [2026]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_5281_zenodo_19539051
