import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Olinto de Oliveira Santos, "Proving the Collatz Conjecture with Binaries Numbers", 2018.

Title: Proving the Collatz Conjecture with Binaries Numbers

Abstract (from harvested metadata, truncated):
The objective of this article is to demonstrate the Collatz Conjecture through the Sets and Binary Numbers Theory, in this manner: 2n + 2n-1+...1. This study shows that there are subsequences of odd numbers within the Collatz sequences, and that by proving the proposition is true for these subsequences, it is subsequently proven that the entire proposition is correct. It is also proven that a sequence which begins with a natural number is generated by a set of operations: Multiplication by 3, addition of 1 and division by 2n. This set of operations shall be called “Movement” in this study, and may be increasing when n=1, and decreasing for n ≥ 2. The numbers in 2n form generate decreasing sequences in which the 3n+1 operation does not occur. One of the important discoveries is how to...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.11648/j.pamj.20180705.12
-/

namespace Collatz.Papers.Journal_10_11648_j_pamj_20180705_12

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Olinto de Oliveira Santos, \"Proving the Collatz Conjecture with Binaries Numbers\", Pure and Applied Mathematics Journal, DOI:10.11648/j.pamj.20180705.12 [2018]."

/-- Recorded main claim shell (structural); the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Journal_10_11648_j_pamj_20180705_12
