import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Anatoliy, Cherkasenko, "Proving the correctness of the Collatz hypothesis", 2025.

Title: Proving the correctness of the Collatz hypothesis

Abstract (from harvested metadata, truncated):
Proof of the correctness of the Collatz conjecture is topical research, as it represents one of the many unsolved problems in mathematics. Understanding the properties of this sequence has important implications for other areas of mathematics, such as number theory or graph theory. The aim of the study was to prove the Collatz hypothesis as a theorem. The research methodology included the analysis of numerical sequences, the use of mathematical induction, recursive, combinatorial methods and computer modelling. The study analysed the properties of sequences generated by the Collatz hypothesis, particularly their recursive properties. The study determined that each odd number has a unique “potential” that affects the behaviour of the sequence. The correlation between even and odd numbers...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.52754/16948645_2025_4(1)_8
-/

namespace Collatz.Papers.Journal_10_52754_16948645_2025_4_1_8

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Anatoliy, Cherkasenko, \"Proving the correctness of the Collatz hypothesis\", Вестник Ошского государственного университета. Математика. Физика. Техника, DOI:10.52754/16948645_2025_4(1)_8 [2025]."

/-- Recorded main claim shell (verification); paper bound not proved here.
A checked miniature verification for `n < 8` is given below. -/
def mainStatement : Prop :=
  ∃ B : Nat, 1 < B ∧ ∀ n : Nat, 0 < n → n < B → ∃ k : Nat, Collatz.orbit k n = 1

/-- Miniature verification: every positive `n < 8` reaches `1`. -/
theorem mainStatement_weak : mainStatement := by
  refine ⟨8, by omega, Collatz.Papers.MathlibCopied.verifies_below_eight⟩

end Collatz.Papers.Journal_10_52754_16948645_2025_4_1_8
