import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Hiroki Sayama, "An Artificial Life View of the Collatz Problem", 2011.

Title: An Artificial Life View of the Collatz Problem

Abstract (from harvested metadata, truncated):
This letter presents a new, artificial-life-based view of the Collatz problem, a well-known mathematical problem about the behavior of a series of positive integers generated by a simple arithmetical rule. The Collatz conjecture asserts that this series always falls into a 4 → 2 → 1 cycle regardless of its initial values. No formal proof has been given yet. In this letter, the behavior of the series is considered an ecological process of artificial organisms (1s in bit strings). The Collatz conjecture is then reinterpreted as the competition between population growth and extinction. This new interpretation has made it possible to analytically calculate the growth and extinction speeds of bit strings. The results indicate that the extinction is always faster than the growth, providing an...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.1162/artl_c_00024
-/

namespace Collatz.Papers.Journal_10_1162_artl_c_00024

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Hiroki Sayama, \"An Artificial Life View of the Collatz Problem\", Artificial Life, DOI:10.1162/artl_c_00024 [2011]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_1162_artl_c_00024
