import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Shaun V. Ault and Matthew Cliatt, "Arithmetic Sequences and Blocks of Powers of Two in the Collatz Array", 2020.

Title: Arithmetic Sequences and Blocks of Powers of Two in the Collatz Array

Abstract (from harvested metadata, truncated):
In this short paper, we examine a curious feature of the Collatz function. When the sequences generated by the Collatz function on consecutive integer initial points are arranged into an array, certain arithmetic sequences show up with common differences given by products of twos and threes. The common differences themselves are further related by a formula that depends on even versus odd input. While we do not solve the Collatz Conjecture by this observation, we present our findings as interesting mathematical results in their own rights.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.35834/2020/3201032
-/

namespace Collatz.Papers.Journal_10_35834_2020_3201032

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Shaun V. Ault and Matthew Cliatt, \"Arithmetic Sequences and Blocks of Powers of Two in the Collatz Array\", Missouri Journal of Mathematical Sciences, DOI:10.35834/2020/3201032 [2020]."

/-- Recorded main claim shell (structural); the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Journal_10_35834_2020_3201032
