import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Rahimi, Al, "Inverse Structure, Regular Languages, and Automaticity in the Collatz Dynamics", 2026.

Title: Inverse Structure, Regular Languages, and Automaticity in the Collatz Dynamics

Abstract (from harvested metadata, truncated):
We study the Collatz dynamics via the induced map on odd integers and its inverse graph. By quotienting out powers of two, the forward dynamics become deterministic on odd states, while the inverse dynamics exhibit infinite growth. We show that each inverse cone of odd predecessors is a single infinite linear vine generated by a simple recursion. We prove that these predecessor sets correspond exactly to regular languages and that the full inverse Syracuse graph admits an automatic presentation. This reframes the Collatz problem as a termination question for a fixed infinite-state program whose inverse semantics are finite-state and structurally simple.

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.6084/m9.figshare.31288393
-/

namespace Collatz.Papers.Journal_10_6084_m9_figshare_31288393

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Rahimi, Al, \"Inverse Structure, Regular Languages, and Automaticity in the Collatz Dynamics\", figshare, DOI:10.6084/m9.figshare.31288393 [2026]."

/-- Recorded main claim shell (structural); the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Journal_10_6084_m9_figshare_31288393
