import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Amarachukwu Nwankpa, "The Collatz Conjecture: Conquered by a Finite State Machine and Structural Confinement", 2025.

Title: The Collatz Conjecture: Conquered by a Finite State Machine and Structural Confinement

Abstract (from harvested metadata, truncated):
The Collatz Conjecture, a long-standing open problem in number theory, asserts that every positive integer sequence generated by the Collatz function eventually reaches the 4-2-1 cycle. This paper presents a rigorous proof by introducing a structured state-space framework that classifies all positive integers into five mutually exclusive sets: the Cycle, ROM3, Precursor, Immediate Successor, and Reachable sets. This classification fully encapsulates all possible Collatz trajectories, enabling a systematic analysis of their behavior. We establish that all sequences are bounded and, once within this structured state space, follow deterministic transitions that guarantee convergence to the uniq...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.20944/preprints202503.0929.v3
-/

namespace Collatz.Papers.Journal_10_20944_preprints202503_0929_v3

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Amarachukwu Nwankpa, \"The Collatz Conjecture: Conquered by a Finite State Machine and Structural Confinement\", DOI:10.20944/preprints202503.0929.v3 [2025]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_20944_preprints202503_0929_v3
