import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Alexandros Kalafatelis, "Uniform-Window Shell Kernels for the Syracuse Map: Renewal Structure and a Primitive-Frequency Obstruction", 2026.

Title: Uniform-Window Shell Kernels for the Syracuse Map: Renewal Structure and a Primitive-Frequency Obstruction

Abstract (from harvested metadata, truncated):
We study shell kernels for the odd-to-odd Syracuse dynamics generated by uniformly distributed initial windows. For backstepped first-passage shells, we prove short-time localization, derive an exact inverse-affine representation of the fixed-time kernel, and reduce the shell-slice discrepancy to weighted primitive-frequency correlations. We also prove a quantitative boundary-layer estimate and identify a formal renewal model for the corresponding shell mechanism. On the arithmetic side, we obtain an exact block decomposition for the primitive-frequency transfer operator, prove that no naive operator gap is available, and reduce the unresolved step to explicit incomplete principal-unit expon...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.20944/preprints202604.0411.v1
-/

namespace Collatz.Papers.Journal_10_20944_preprints202604_0411_v1

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Alexandros Kalafatelis, \"Uniform-Window Shell Kernels for the Syracuse Map: Renewal Structure and a Primitive-Frequency Obstruction\", Preprints.org, DOI:10.20944/preprints202604.0411.v1 [2026]."

/-- Recorded main claim shell (verification); paper bound not proved here.
A checked miniature verification for `n < 8` is given below. -/
def mainStatement : Prop :=
  ∃ B : Nat, 1 < B ∧ ∀ n : Nat, 0 < n → n < B → ∃ k : Nat, Collatz.orbit k n = 1

/-- Miniature verification: every positive `n < 8` reaches `1`. -/
theorem mainStatement_weak : mainStatement := by
  refine ⟨8, by omega, Collatz.Papers.MathlibCopied.verifies_below_eight⟩

end Collatz.Papers.Journal_10_20944_preprints202604_0411_v1
