import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Amarachukwu Nwankpa, "A Proof of the Collatz Conjecture via Complete Set Classification and Unique Cycle Analysis", 2025.

Title: A Proof of the Collatz Conjecture via Complete Set Classification and Unique Cycle Analysis

Abstract (from harvested metadata, truncated):
The Collatz Conjecture, a deceptively simple problem in number theory, has remained unsolved for decades. This paper presents a rigorous proof of the Collatz Conjecture by demonstrating that all positive integer sequences generated by the Collatz function eventually reach the trivial 4-2-1 cycle. Our proof employs a novel, structurally driven approach based on a complete classification of positive integers into five mutually exclusive sets—namely, the Cycle, ROM3, Precursor, Immediate Successor, and Reachable sets—thus defining a complete state space for Collatz dynamics. We show that, when viewed as trajectories within this structured state space, all sequences are bounded and converge to t...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.20944/preprints202503.0929.v2
-/

namespace Collatz.Papers.Journal_10_20944_preprints202503_0929_v2

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Amarachukwu Nwankpa, \"A Proof of the Collatz Conjecture via Complete Set Classification and Unique Cycle Analysis\", DOI:10.20944/preprints202503.0929.v2 [2025]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_20944_preprints202503_0929_v2
