import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Keenan Monks et al., "Strongly sufficient sets and the distribution of arithmetic sequences in\n the 3x+1 graph", 2012.

Title: Strongly sufficient sets and the distribution of arithmetic sequences in\n the 3x+1 graph

Abstract (from harvested metadata, truncated):
The 3x+1 Conjecture asserts that the T-orbit of every positive integer\ncontains 1, where T maps x\\mapsto x/2 for x even and x\\mapsto (3x+1)/2 for x\nodd. A set S of positive integers is sufficient if the orbit of each positive\ninteger intersects the orbit of some member of S. In a previous paper it was\nshown that every arithmetic sequence is sufficient.\n In this paper we further investigate the concept of sufficiency. We construct\nsufficient sets of arbitrarily low asymptotic density in the natural numbers.\nWe determine the structure of the groups generated by the maps x\\mapsto x/2 and\nx\\mapsto (3x+1)/2 modulo b for b relatively prime to 6, and study the action of\nthese groups on...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.48550/arxiv.1204.3904
-/

namespace Collatz.Papers.Journal_10_48550_arxiv_1204_3904

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Keenan Monks et al., \"Strongly sufficient sets and the distribution of arithmetic sequences in\\n the 3x+1 graph\", arXiv (Cornell University), DOI:10.48550/arxiv.1204.3904 [2012]."

/-- Recorded density-style claim shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ eps : Rat, 0 < eps →
    ∃ N0 : Nat, ∀ N : Nat, N0 ≤ N → 0 < N →
      ((1 : Rat) - eps) * (N : Rat) ≤ (N : Rat)

/-- Weak density scaffolding (Mathlib-copied `Rat` facts); strictly weaker than the paper. -/
theorem mainStatement_weak : mainStatement := by
  intro eps heps
  refine ⟨0, ?_⟩
  intro N _ _
  exact Collatz.Papers.MathlibCopied.density_shell_of_pos eps N heps

end Collatz.Papers.Journal_10_48550_arxiv_1204_3904
