import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Zaldy Carreon De Leon Jr, "Collatz Conjecture and the Primary Number Ratio: Prelude to a Predictive Model", 2024.

Title: Collatz Conjecture and the Primary Number Ratio: Prelude to a Predictive Model

Abstract (from harvested metadata, truncated):
The Collatz Conjecture is a longstanding problem in mathematics that posits that regardless of the starting positive integer, the sequence generated by repeatedly applying the iterative function will ultimately converge to 1. Despite its apparent simplicity, the conjecture has remained unsolved for decades, leaving many to wonder whether it is a fundamental property of mathematics or an illusion. This study explores the connection between the Collatz Conjecture and prime numbers, examining the frequency of prime numbers in Collatz sequences and their impact on the behavior and properties of the sequences. The analysis reveals that prime numbers often act as "stopping points" in the sequences...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.2139/ssrn.4829163
-/

namespace Collatz.Papers.Journal_10_2139_ssrn_4829163

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Zaldy Carreon De Leon Jr, \"Collatz Conjecture and the Primary Number Ratio: Prelude to a Predictive Model\", DOI:10.2139/ssrn.4829163 [2024]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_2139_ssrn_4829163
