import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Jia Wang and Xin Li, "Fractal Property for A Novel Function generated by Generalized Approximate 3x+1 Functions", 2014.

Title: Fractal Property for A Novel Function generated by Generalized Approximate 3x+1 Functions

Abstract (from harvested metadata, truncated):
(No abstract in harvested metadata; statement recorded from title/venue only.)

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.2991/mce-14.2014.82
-/

namespace Collatz.Papers.Journal_10_2991_mce_14_2014_82

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Jia Wang and Xin Li, \"Fractal Property for A Novel Function generated by Generalized Approximate 3x+1 Functions\", Advances in intelligent systems research/Advances in Intelligent Systems Research, DOI:10.2991/mce-14.2014.82 [2014]."

/-- Recorded generalization-style claim shell; the paper's theorem is not proved here.
This placeholder is the standard Collatz conjecture proposition. -/
def mainStatement : Prop := Collatz.CollatzConjecture

/-- Checked bridge facts only. -/
theorem step_one_eq : Collatz.step 1 = 4 := Collatz.step_one

theorem step_two_eq : Collatz.step 2 = 1 := Collatz.step_two

/-- Checked: every power of two reaches `1` (Mathlib-copied parity/division facts). -/
theorem powers_of_two_reach_one (k : Nat) :
    ∃ t : Nat, Collatz.orbit t (2 ^ k) = 1 :=
  Collatz.Papers.MathlibCopied.orbit_pow_two_reaches_one k

end Collatz.Papers.Journal_10_2991_mce_14_2014_82
