import Collatz.Basic
import Collatz.Papers.MathlibCopied

/-!
Lean notes for Bozhilov, Dobri, "On the coprimality of consecutive odd members in Collatz Sequences and its implication for cycle formation", 2025.

Title: On the coprimality of consecutive odd members in Collatz Sequences and its implication for cycle formation

Abstract (from harvested metadata, truncated):
The Collatz conjecture posits that for any positive integer n, the sequence generated by the rules n -> n/2 if n is even and n -> 3n + 1 if n is odd always reaches the cycle 4 -> 2 -> 1. This paper presents a novel observation: consecutive odd numbers in a Collatz sequence are coprime, i.e., their greatest common divisor is 1. We prove this property using basic arithmetic and demonstrate that it imposes a significant constraint on the sequence dynamics, particularly for large numbers. Specifically, the requirement of coprimality creates a "pressure" for the next odd number to be smaller than its predecessor, as larger numbers increase the likelihood of common divisors. This tendency toward decrease makes the existence of alternative cycles (distinct from 4 -> 2 -> 1) increasingly...

Status: statement recorded under `mainStatement`.
Only the named checked lemmas below are kernel-proved.
This file does not claim a complete formalization of the paper.

Source: https://doi.org/10.17632/ptjr6vzm8y
-/

namespace Collatz.Papers.Journal_10_17632_ptjr6vzm8y

/-- Exact bibliographic citation tracked by this file. -/
def citation : String :=
  "Bozhilov, Dobri, \"On the coprimality of consecutive odd members in Collatz Sequences and its implication for cycle formation\", Mendeley Data, DOI:10.17632/ptjr6vzm8y [2025]."

/-- Recorded nontrivial-cycle exclusion shell; the paper's theorem is not proved. -/
def mainStatement : Prop :=
  ∀ n : Nat, 1 < n → ∀ k : Nat, 0 < k → Collatz.orbit k n = n →
    ∃ j : Nat, j ≤ k ∧ Collatz.orbit j n = 1

/-- Checked: the trivial cycle through `1` returns after three steps. -/
theorem orbit_one_returns : Collatz.orbit 3 1 = 1 :=
  (Collatz.Papers.MathlibCopied.trivial_cycle).1

theorem step_branches_on_cycle :
    Collatz.step 1 = 4 ∧ Collatz.step 4 = 2 ∧ Collatz.step 2 = 1 := by
  have h := Collatz.Papers.MathlibCopied.trivial_cycle
  exact ⟨h.2.1, h.2.2.1, h.2.2.2⟩

end Collatz.Papers.Journal_10_17632_ptjr6vzm8y
