import Collatz.Research.DescentAtlas.Core

/-! Batch 287: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch287
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 6441. -/
theorem data_6441 : oddCount 6441 14 = 7 ∧
    acceleratedOrbit 14 6441 = 860 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6441 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6441) = 2187 * m + 860 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6441
  rw [data_6441.1, data_6441.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6441 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6441) < 16384 * m + 6441 := by
  apply descent_of_endpoint
  · rw [data_6441.1]; exact data_6441.2.2
  · rw [data_6441.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6443. -/
theorem data_6443 : oddCount 6443 14 = 8 ∧
    acceleratedOrbit 14 6443 = 2582 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6443 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6443) = 6561 * m + 2582 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6443
  rw [data_6443.1, data_6443.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6443 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6443) < 16384 * m + 6443 := by
  apply descent_of_endpoint
  · rw [data_6443.1]; exact data_6443.2.2
  · rw [data_6443.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6445. -/
theorem data_6445 : oddCount 6445 14 = 4 ∧
    acceleratedOrbit 14 6445 = 32 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6445 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6445) = 81 * m + 32 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6445
  rw [data_6445.1, data_6445.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6445 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6445) < 16384 * m + 6445 := by
  apply descent_of_endpoint
  · rw [data_6445.1]; exact data_6445.2.2
  · rw [data_6445.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6449. -/
theorem data_6449 : oddCount 6449 14 = 7 ∧
    acceleratedOrbit 14 6449 = 863 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6449 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6449) = 2187 * m + 863 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6449
  rw [data_6449.1, data_6449.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6449 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6449) < 16384 * m + 6449 := by
  apply descent_of_endpoint
  · rw [data_6449.1]; exact data_6449.2.2
  · rw [data_6449.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6451. -/
theorem data_6451 : oddCount 6451 14 = 7 ∧
    acceleratedOrbit 14 6451 = 863 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6451 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6451) = 2187 * m + 863 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6451
  rw [data_6451.1, data_6451.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6451 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6451) < 16384 * m + 6451 := by
  apply descent_of_endpoint
  · rw [data_6451.1]; exact data_6451.2.2
  · rw [data_6451.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6453. -/
theorem data_6453 : oddCount 6453 14 = 4 ∧
    acceleratedOrbit 14 6453 = 32 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6453 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6453) = 81 * m + 32 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6453
  rw [data_6453.1, data_6453.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6453 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6453) < 16384 * m + 6453 := by
  apply descent_of_endpoint
  · rw [data_6453.1]; exact data_6453.2.2
  · rw [data_6453.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6457. -/
theorem data_6457 : oddCount 6457 14 = 8 ∧
    acceleratedOrbit 14 6457 = 2587 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6457 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6457) = 6561 * m + 2587 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6457
  rw [data_6457.1, data_6457.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6457 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6457) < 16384 * m + 6457 := by
  apply descent_of_endpoint
  · rw [data_6457.1]; exact data_6457.2.2
  · rw [data_6457.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6459. -/
theorem data_6459 : oddCount 6459 14 = 8 ∧
    acceleratedOrbit 14 6459 = 2591 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6459 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6459) = 6561 * m + 2591 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6459
  rw [data_6459.1, data_6459.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6459 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6459) < 16384 * m + 6459 := by
  apply descent_of_endpoint
  · rw [data_6459.1]; exact data_6459.2.2
  · rw [data_6459.2.1]; decide

end Collatz.Research.DescentAtlas.Batch287
