import Collatz.Research.DescentAtlas.Core

/-! Batch 73: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch073
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1621. -/
theorem data_1621 : oddCount 1621 14 = 5 ∧
    acceleratedOrbit 14 1621 = 26 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1621 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1621) = 243 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1621
  rw [data_1621.1, data_1621.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1621 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1621) < 16384 * m + 1621 := by
  apply descent_of_endpoint
  · rw [data_1621.1]; exact data_1621.2.2
  · rw [data_1621.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1623. -/
theorem data_1623 : oddCount 1623 14 = 7 ∧
    acceleratedOrbit 14 1623 = 218 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1623 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1623) = 2187 * m + 218 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1623
  rw [data_1623.1, data_1623.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1623 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1623) < 16384 * m + 1623 := by
  apply descent_of_endpoint
  · rw [data_1623.1]; exact data_1623.2.2
  · rw [data_1623.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1625. -/
theorem data_1625 : oddCount 1625 14 = 7 ∧
    acceleratedOrbit 14 1625 = 218 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1625 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1625) = 2187 * m + 218 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1625
  rw [data_1625.1, data_1625.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1625 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1625) < 16384 * m + 1625 := by
  apply descent_of_endpoint
  · rw [data_1625.1]; exact data_1625.2.2
  · rw [data_1625.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1629. -/
theorem data_1629 : oddCount 1629 14 = 6 ∧
    acceleratedOrbit 14 1629 = 74 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1629 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1629) = 729 * m + 74 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1629
  rw [data_1629.1, data_1629.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1629 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1629) < 16384 * m + 1629 := by
  apply descent_of_endpoint
  · rw [data_1629.1]; exact data_1629.2.2
  · rw [data_1629.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1631. -/
theorem data_1631 : oddCount 1631 14 = 7 ∧
    acceleratedOrbit 14 1631 = 218 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1631 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1631) = 2187 * m + 218 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1631
  rw [data_1631.1, data_1631.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1631 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1631) < 16384 * m + 1631 := by
  apply descent_of_endpoint
  · rw [data_1631.1]; exact data_1631.2.2
  · rw [data_1631.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1633. -/
theorem data_1633 : oddCount 1633 14 = 6 ∧
    acceleratedOrbit 14 1633 = 73 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1633 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1633) = 729 * m + 73 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1633
  rw [data_1633.1, data_1633.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1633 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1633) < 16384 * m + 1633 := by
  apply descent_of_endpoint
  · rw [data_1633.1]; exact data_1633.2.2
  · rw [data_1633.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1635. -/
theorem data_1635 : oddCount 1635 14 = 6 ∧
    acceleratedOrbit 14 1635 = 74 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1635 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1635) = 729 * m + 74 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1635
  rw [data_1635.1, data_1635.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1635 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1635) < 16384 * m + 1635 := by
  apply descent_of_endpoint
  · rw [data_1635.1]; exact data_1635.2.2
  · rw [data_1635.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1637. -/
theorem data_1637 : oddCount 1637 14 = 6 ∧
    acceleratedOrbit 14 1637 = 74 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1637 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1637) = 729 * m + 74 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1637
  rw [data_1637.1, data_1637.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1637 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1637) < 16384 * m + 1637 := by
  apply descent_of_endpoint
  · rw [data_1637.1]; exact data_1637.2.2
  · rw [data_1637.2.1]; decide

end Collatz.Research.DescentAtlas.Batch073
