import Collatz.Research.DescentAtlas.Core

/-! Batch 224: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch224
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5027. -/
theorem data_5027 : oddCount 5027 14 = 7 ∧
    acceleratedOrbit 14 5027 = 674 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5027 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5027) = 2187 * m + 674 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5027
  rw [data_5027.1, data_5027.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5027 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5027) < 16384 * m + 5027 := by
  apply descent_of_endpoint
  · rw [data_5027.1]; exact data_5027.2.2
  · rw [data_5027.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5029. -/
theorem data_5029 : oddCount 5029 14 = 6 ∧
    acceleratedOrbit 14 5029 = 224 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5029 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5029) = 729 * m + 224 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5029
  rw [data_5029.1, data_5029.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5029 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5029) < 16384 * m + 5029 := by
  apply descent_of_endpoint
  · rw [data_5029.1]; exact data_5029.2.2
  · rw [data_5029.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5035. -/
theorem data_5035 : oddCount 5035 14 = 8 ∧
    acceleratedOrbit 14 5035 = 2018 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5035 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5035) = 6561 * m + 2018 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5035
  rw [data_5035.1, data_5035.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5035 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5035) < 16384 * m + 5035 := by
  apply descent_of_endpoint
  · rw [data_5035.1]; exact data_5035.2.2
  · rw [data_5035.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5037. -/
theorem data_5037 : oddCount 5037 14 = 8 ∧
    acceleratedOrbit 14 5037 = 2020 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5037 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5037) = 6561 * m + 2020 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5037
  rw [data_5037.1, data_5037.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5037 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5037) < 16384 * m + 5037 := by
  apply descent_of_endpoint
  · rw [data_5037.1]; exact data_5037.2.2
  · rw [data_5037.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5039. -/
theorem data_5039 : oddCount 5039 14 = 7 ∧
    acceleratedOrbit 14 5039 = 674 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5039 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5039) = 2187 * m + 674 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5039
  rw [data_5039.1, data_5039.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5039 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5039) < 16384 * m + 5039 := by
  apply descent_of_endpoint
  · rw [data_5039.1]; exact data_5039.2.2
  · rw [data_5039.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5041. -/
theorem data_5041 : oddCount 5041 14 = 4 ∧
    acceleratedOrbit 14 5041 = 25 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5041 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5041) = 81 * m + 25 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5041
  rw [data_5041.1, data_5041.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5041 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5041) < 16384 * m + 5041 := by
  apply descent_of_endpoint
  · rw [data_5041.1]; exact data_5041.2.2
  · rw [data_5041.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5043. -/
theorem data_5043 : oddCount 5043 14 = 4 ∧
    acceleratedOrbit 14 5043 = 25 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5043 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5043) = 81 * m + 25 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5043
  rw [data_5043.1, data_5043.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5043 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5043) < 16384 * m + 5043 := by
  apply descent_of_endpoint
  · rw [data_5043.1]; exact data_5043.2.2
  · rw [data_5043.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5045. -/
theorem data_5045 : oddCount 5045 14 = 4 ∧
    acceleratedOrbit 14 5045 = 25 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5045 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5045) = 81 * m + 25 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5045
  rw [data_5045.1, data_5045.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5045 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5045) < 16384 * m + 5045 := by
  apply descent_of_endpoint
  · rw [data_5045.1]; exact data_5045.2.2
  · rw [data_5045.2.1]; decide

end Collatz.Research.DescentAtlas.Batch224
