import Collatz.Research.DescentAtlas.Core

/-! Batch 241: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch241
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5407. -/
theorem data_5407 : oddCount 5407 14 = 7 ∧
    acceleratedOrbit 14 5407 = 722 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5407 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5407) = 2187 * m + 722 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5407
  rw [data_5407.1, data_5407.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5407 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5407) < 16384 * m + 5407 := by
  apply descent_of_endpoint
  · rw [data_5407.1]; exact data_5407.2.2
  · rw [data_5407.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5409. -/
theorem data_5409 : oddCount 5409 14 = 6 ∧
    acceleratedOrbit 14 5409 = 242 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5409 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5409) = 729 * m + 242 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5409
  rw [data_5409.1, data_5409.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5409 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5409) < 16384 * m + 5409 := by
  apply descent_of_endpoint
  · rw [data_5409.1]; exact data_5409.2.2
  · rw [data_5409.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5411. -/
theorem data_5411 : oddCount 5411 14 = 7 ∧
    acceleratedOrbit 14 5411 = 724 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5411 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5411) = 2187 * m + 724 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5411
  rw [data_5411.1, data_5411.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5411 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5411) < 16384 * m + 5411 := by
  apply descent_of_endpoint
  · rw [data_5411.1]; exact data_5411.2.2
  · rw [data_5411.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5413. -/
theorem data_5413 : oddCount 5413 14 = 7 ∧
    acceleratedOrbit 14 5413 = 724 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5413 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5413) = 2187 * m + 724 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5413
  rw [data_5413.1, data_5413.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5413 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5413) < 16384 * m + 5413 := by
  apply descent_of_endpoint
  · rw [data_5413.1]; exact data_5413.2.2
  · rw [data_5413.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5415. -/
theorem data_5415 : oddCount 5415 14 = 6 ∧
    acceleratedOrbit 14 5415 = 241 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5415 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5415) = 729 * m + 241 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5415
  rw [data_5415.1, data_5415.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5415 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5415) < 16384 * m + 5415 := by
  apply descent_of_endpoint
  · rw [data_5415.1]; exact data_5415.2.2
  · rw [data_5415.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5417. -/
theorem data_5417 : oddCount 5417 14 = 8 ∧
    acceleratedOrbit 14 5417 = 2170 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5417 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5417) = 6561 * m + 2170 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5417
  rw [data_5417.1, data_5417.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5417 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5417) < 16384 * m + 5417 := by
  apply descent_of_endpoint
  · rw [data_5417.1]; exact data_5417.2.2
  · rw [data_5417.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5419. -/
theorem data_5419 : oddCount 5419 14 = 7 ∧
    acceleratedOrbit 14 5419 = 724 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5419 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5419) = 2187 * m + 724 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5419
  rw [data_5419.1, data_5419.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5419 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5419) < 16384 * m + 5419 := by
  apply descent_of_endpoint
  · rw [data_5419.1]; exact data_5419.2.2
  · rw [data_5419.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5421. -/
theorem data_5421 : oddCount 5421 14 = 7 ∧
    acceleratedOrbit 14 5421 = 728 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5421 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5421) = 2187 * m + 728 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5421
  rw [data_5421.1, data_5421.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5421 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5421) < 16384 * m + 5421 := by
  apply descent_of_endpoint
  · rw [data_5421.1]; exact data_5421.2.2
  · rw [data_5421.2.1]; decide

end Collatz.Research.DescentAtlas.Batch241
