import Collatz.Research.DescentAtlas.Core

/-! Batch 117: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch117
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 2625. -/
theorem data_2625 : oddCount 2625 14 = 4 ∧
    acceleratedOrbit 14 2625 = 13 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2625 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2625) = 81 * m + 13 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2625
  rw [data_2625.1, data_2625.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2625 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2625) < 16384 * m + 2625 := by
  apply descent_of_endpoint
  · rw [data_2625.1]; exact data_2625.2.2
  · rw [data_2625.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2627. -/
theorem data_2627 : oddCount 2627 14 = 4 ∧
    acceleratedOrbit 14 2627 = 13 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2627 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2627) = 81 * m + 13 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2627
  rw [data_2627.1, data_2627.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2627 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2627) < 16384 * m + 2627 := by
  apply descent_of_endpoint
  · rw [data_2627.1]; exact data_2627.2.2
  · rw [data_2627.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2629. -/
theorem data_2629 : oddCount 2629 14 = 6 ∧
    acceleratedOrbit 14 2629 = 118 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2629 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2629) = 729 * m + 118 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2629
  rw [data_2629.1, data_2629.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2629 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2629) < 16384 * m + 2629 := by
  apply descent_of_endpoint
  · rw [data_2629.1]; exact data_2629.2.2
  · rw [data_2629.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2631. -/
theorem data_2631 : oddCount 2631 14 = 8 ∧
    acceleratedOrbit 14 2631 = 1055 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2631 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2631) = 6561 * m + 1055 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2631
  rw [data_2631.1, data_2631.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2631 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2631) < 16384 * m + 2631 := by
  apply descent_of_endpoint
  · rw [data_2631.1]; exact data_2631.2.2
  · rw [data_2631.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2633. -/
theorem data_2633 : oddCount 2633 14 = 7 ∧
    acceleratedOrbit 14 2633 = 352 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2633 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2633) = 2187 * m + 352 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2633
  rw [data_2633.1, data_2633.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2633 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2633) < 16384 * m + 2633 := by
  apply descent_of_endpoint
  · rw [data_2633.1]; exact data_2633.2.2
  · rw [data_2633.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2635. -/
theorem data_2635 : oddCount 2635 14 = 6 ∧
    acceleratedOrbit 14 2635 = 118 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2635 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2635) = 729 * m + 118 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2635
  rw [data_2635.1, data_2635.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2635 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2635) < 16384 * m + 2635 := by
  apply descent_of_endpoint
  · rw [data_2635.1]; exact data_2635.2.2
  · rw [data_2635.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2637. -/
theorem data_2637 : oddCount 2637 14 = 6 ∧
    acceleratedOrbit 14 2637 = 118 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2637 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2637) = 729 * m + 118 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2637
  rw [data_2637.1, data_2637.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2637 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2637) < 16384 * m + 2637 := by
  apply descent_of_endpoint
  · rw [data_2637.1]; exact data_2637.2.2
  · rw [data_2637.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2639. -/
theorem data_2639 : oddCount 2639 14 = 7 ∧
    acceleratedOrbit 14 2639 = 353 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2639 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2639) = 2187 * m + 353 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2639
  rw [data_2639.1, data_2639.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2639 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2639) < 16384 * m + 2639 := by
  apply descent_of_endpoint
  · rw [data_2639.1]; exact data_2639.2.2
  · rw [data_2639.2.1]; decide

end Collatz.Research.DescentAtlas.Batch117
