import Collatz.Research.DescentAtlas.Core

/-! Batch 265: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch265
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5945. -/
theorem data_5945 : oddCount 5945 14 = 7 ∧
    acceleratedOrbit 14 5945 = 794 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5945 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5945) = 2187 * m + 794 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5945
  rw [data_5945.1, data_5945.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5945 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5945) < 16384 * m + 5945 := by
  apply descent_of_endpoint
  · rw [data_5945.1]; exact data_5945.2.2
  · rw [data_5945.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5947. -/
theorem data_5947 : oddCount 5947 14 = 6 ∧
    acceleratedOrbit 14 5947 = 265 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5947 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5947) = 729 * m + 265 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5947
  rw [data_5947.1, data_5947.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5947 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5947) < 16384 * m + 5947 := by
  apply descent_of_endpoint
  · rw [data_5947.1]; exact data_5947.2.2
  · rw [data_5947.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5951. -/
theorem data_5951 : oddCount 5951 14 = 8 ∧
    acceleratedOrbit 14 5951 = 2384 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5951 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5951) = 6561 * m + 2384 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5951
  rw [data_5951.1, data_5951.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5951 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5951) < 16384 * m + 5951 := by
  apply descent_of_endpoint
  · rw [data_5951.1]; exact data_5951.2.2
  · rw [data_5951.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5953. -/
theorem data_5953 : oddCount 5953 14 = 5 ∧
    acceleratedOrbit 14 5953 = 89 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5953 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5953) = 243 * m + 89 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5953
  rw [data_5953.1, data_5953.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5953 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5953) < 16384 * m + 5953 := by
  apply descent_of_endpoint
  · rw [data_5953.1]; exact data_5953.2.2
  · rw [data_5953.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5955. -/
theorem data_5955 : oddCount 5955 14 = 7 ∧
    acceleratedOrbit 14 5955 = 796 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5955 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5955) = 2187 * m + 796 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5955
  rw [data_5955.1, data_5955.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5955 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5955) < 16384 * m + 5955 := by
  apply descent_of_endpoint
  · rw [data_5955.1]; exact data_5955.2.2
  · rw [data_5955.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5957. -/
theorem data_5957 : oddCount 5957 14 = 5 ∧
    acceleratedOrbit 14 5957 = 89 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5957 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5957) = 243 * m + 89 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5957
  rw [data_5957.1, data_5957.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5957 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5957) < 16384 * m + 5957 := by
  apply descent_of_endpoint
  · rw [data_5957.1]; exact data_5957.2.2
  · rw [data_5957.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5959. -/
theorem data_5959 : oddCount 5959 14 = 8 ∧
    acceleratedOrbit 14 5959 = 2387 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5959 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5959) = 6561 * m + 2387 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5959
  rw [data_5959.1, data_5959.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5959 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5959) < 16384 * m + 5959 := by
  apply descent_of_endpoint
  · rw [data_5959.1]; exact data_5959.2.2
  · rw [data_5959.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5961. -/
theorem data_5961 : oddCount 5961 14 = 8 ∧
    acceleratedOrbit 14 5961 = 2389 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5961 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5961) = 6561 * m + 2389 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5961
  rw [data_5961.1, data_5961.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5961 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5961) < 16384 * m + 5961 := by
  apply descent_of_endpoint
  · rw [data_5961.1]; exact data_5961.2.2
  · rw [data_5961.2.1]; decide

end Collatz.Research.DescentAtlas.Batch265
