import Collatz.Research.DescentAtlas.Core

/-! Batch 269: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch269
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 6029. -/
theorem data_6029 : oddCount 6029 14 = 3 ∧
    acceleratedOrbit 14 6029 = 10 ∧ 27 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6029 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6029) = 27 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6029
  rw [data_6029.1, data_6029.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6029 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6029) < 16384 * m + 6029 := by
  apply descent_of_endpoint
  · rw [data_6029.1]; exact data_6029.2.2
  · rw [data_6029.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6033. -/
theorem data_6033 : oddCount 6033 14 = 8 ∧
    acceleratedOrbit 14 6033 = 2420 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6033 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6033) = 6561 * m + 2420 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6033
  rw [data_6033.1, data_6033.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6033 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6033) < 16384 * m + 6033 := by
  apply descent_of_endpoint
  · rw [data_6033.1]; exact data_6033.2.2
  · rw [data_6033.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6035. -/
theorem data_6035 : oddCount 6035 14 = 8 ∧
    acceleratedOrbit 14 6035 = 2420 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6035 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6035) = 6561 * m + 2420 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6035
  rw [data_6035.1, data_6035.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6035 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6035) < 16384 * m + 6035 := by
  apply descent_of_endpoint
  · rw [data_6035.1]; exact data_6035.2.2
  · rw [data_6035.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6037. -/
theorem data_6037 : oddCount 6037 14 = 8 ∧
    acceleratedOrbit 14 6037 = 2429 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6037 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6037) = 6561 * m + 2429 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6037
  rw [data_6037.1, data_6037.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6037 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6037) < 16384 * m + 6037 := by
  apply descent_of_endpoint
  · rw [data_6037.1]; exact data_6037.2.2
  · rw [data_6037.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6039. -/
theorem data_6039 : oddCount 6039 14 = 7 ∧
    acceleratedOrbit 14 6039 = 809 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6039 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6039) = 2187 * m + 809 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6039
  rw [data_6039.1, data_6039.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6039 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6039) < 16384 * m + 6039 := by
  apply descent_of_endpoint
  · rw [data_6039.1]; exact data_6039.2.2
  · rw [data_6039.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6041. -/
theorem data_6041 : oddCount 6041 14 = 7 ∧
    acceleratedOrbit 14 6041 = 809 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6041 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6041) = 2187 * m + 809 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6041
  rw [data_6041.1, data_6041.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6041 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6041) < 16384 * m + 6041 := by
  apply descent_of_endpoint
  · rw [data_6041.1]; exact data_6041.2.2
  · rw [data_6041.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6045. -/
theorem data_6045 : oddCount 6045 14 = 8 ∧
    acceleratedOrbit 14 6045 = 2423 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6045 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6045) = 6561 * m + 2423 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6045
  rw [data_6045.1, data_6045.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6045 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6045) < 16384 * m + 6045 := by
  apply descent_of_endpoint
  · rw [data_6045.1]; exact data_6045.2.2
  · rw [data_6045.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6047. -/
theorem data_6047 : oddCount 6047 14 = 8 ∧
    acceleratedOrbit 14 6047 = 2422 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6047 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6047) = 6561 * m + 2422 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6047
  rw [data_6047.1, data_6047.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6047 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6047) < 16384 * m + 6047 := by
  apply descent_of_endpoint
  · rw [data_6047.1]; exact data_6047.2.2
  · rw [data_6047.2.1]; decide

end Collatz.Research.DescentAtlas.Batch269
