import Collatz.Research.DescentAtlas.Core

/-! Batch 144: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch144
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 3223. -/
theorem data_3223 : oddCount 3223 14 = 4 ∧
    acceleratedOrbit 14 3223 = 16 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3223 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3223) = 81 * m + 16 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3223
  rw [data_3223.1, data_3223.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3223 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3223) < 16384 * m + 3223 := by
  apply descent_of_endpoint
  · rw [data_3223.1]; exact data_3223.2.2
  · rw [data_3223.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3225. -/
theorem data_3225 : oddCount 3225 14 = 8 ∧
    acceleratedOrbit 14 3225 = 1295 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3225 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3225) = 6561 * m + 1295 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3225
  rw [data_3225.1, data_3225.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3225 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3225) < 16384 * m + 3225 := by
  apply descent_of_endpoint
  · rw [data_3225.1]; exact data_3225.2.2
  · rw [data_3225.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3235. -/
theorem data_3235 : oddCount 3235 14 = 7 ∧
    acceleratedOrbit 14 3235 = 433 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3235 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3235) = 2187 * m + 433 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3235
  rw [data_3235.1, data_3235.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3235 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3235) < 16384 * m + 3235 := by
  apply descent_of_endpoint
  · rw [data_3235.1]; exact data_3235.2.2
  · rw [data_3235.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3237. -/
theorem data_3237 : oddCount 3237 14 = 7 ∧
    acceleratedOrbit 14 3237 = 433 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3237 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3237) = 2187 * m + 433 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3237
  rw [data_3237.1, data_3237.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3237 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3237) < 16384 * m + 3237 := by
  apply descent_of_endpoint
  · rw [data_3237.1]; exact data_3237.2.2
  · rw [data_3237.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3243. -/
theorem data_3243 : oddCount 3243 14 = 7 ∧
    acceleratedOrbit 14 3243 = 434 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3243 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3243) = 2187 * m + 434 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3243
  rw [data_3243.1, data_3243.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3243 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3243) < 16384 * m + 3243 := by
  apply descent_of_endpoint
  · rw [data_3243.1]; exact data_3243.2.2
  · rw [data_3243.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3245. -/
theorem data_3245 : oddCount 3245 14 = 6 ∧
    acceleratedOrbit 14 3245 = 145 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3245 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3245) = 729 * m + 145 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3245
  rw [data_3245.1, data_3245.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3245 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3245) < 16384 * m + 3245 := by
  apply descent_of_endpoint
  · rw [data_3245.1]; exact data_3245.2.2
  · rw [data_3245.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3247. -/
theorem data_3247 : oddCount 3247 14 = 8 ∧
    acceleratedOrbit 14 3247 = 1301 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3247 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3247) = 6561 * m + 1301 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3247
  rw [data_3247.1, data_3247.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3247 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3247) < 16384 * m + 3247 := by
  apply descent_of_endpoint
  · rw [data_3247.1]; exact data_3247.2.2
  · rw [data_3247.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3249. -/
theorem data_3249 : oddCount 3249 14 = 6 ∧
    acceleratedOrbit 14 3249 = 145 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3249 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3249) = 729 * m + 145 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3249
  rw [data_3249.1, data_3249.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3249 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3249) < 16384 * m + 3249 := by
  apply descent_of_endpoint
  · rw [data_3249.1]; exact data_3249.2.2
  · rw [data_3249.2.1]; decide

end Collatz.Research.DescentAtlas.Batch144
