import Collatz.Research.DescentAtlas.Core

/-! Batch 152: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch152
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 3415. -/
theorem data_3415 : oddCount 3415 14 = 8 ∧
    acceleratedOrbit 14 3415 = 1370 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3415 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3415) = 6561 * m + 1370 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3415
  rw [data_3415.1, data_3415.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3415 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3415) < 16384 * m + 3415 := by
  apply descent_of_endpoint
  · rw [data_3415.1]; exact data_3415.2.2
  · rw [data_3415.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3417. -/
theorem data_3417 : oddCount 3417 14 = 7 ∧
    acceleratedOrbit 14 3417 = 458 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3417 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3417) = 2187 * m + 458 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3417
  rw [data_3417.1, data_3417.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3417 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3417) < 16384 * m + 3417 := by
  apply descent_of_endpoint
  · rw [data_3417.1]; exact data_3417.2.2
  · rw [data_3417.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3419. -/
theorem data_3419 : oddCount 3419 14 = 8 ∧
    acceleratedOrbit 14 3419 = 1370 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3419 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3419) = 6561 * m + 1370 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3419
  rw [data_3419.1, data_3419.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3419 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3419) < 16384 * m + 3419 := by
  apply descent_of_endpoint
  · rw [data_3419.1]; exact data_3419.2.2
  · rw [data_3419.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3421. -/
theorem data_3421 : oddCount 3421 14 = 8 ∧
    acceleratedOrbit 14 3421 = 1376 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3421 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3421) = 6561 * m + 1376 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3421
  rw [data_3421.1, data_3421.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3421 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3421) < 16384 * m + 3421 := by
  apply descent_of_endpoint
  · rw [data_3421.1]; exact data_3421.2.2
  · rw [data_3421.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3423. -/
theorem data_3423 : oddCount 3423 14 = 8 ∧
    acceleratedOrbit 14 3423 = 1372 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3423 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3423) = 6561 * m + 1372 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3423
  rw [data_3423.1, data_3423.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3423 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3423) < 16384 * m + 3423 := by
  apply descent_of_endpoint
  · rw [data_3423.1]; exact data_3423.2.2
  · rw [data_3423.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3425. -/
theorem data_3425 : oddCount 3425 14 = 7 ∧
    acceleratedOrbit 14 3425 = 458 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3425 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3425) = 2187 * m + 458 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3425
  rw [data_3425.1, data_3425.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3425 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3425) < 16384 * m + 3425 := by
  apply descent_of_endpoint
  · rw [data_3425.1]; exact data_3425.2.2
  · rw [data_3425.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3427. -/
theorem data_3427 : oddCount 3427 14 = 4 ∧
    acceleratedOrbit 14 3427 = 17 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3427 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3427) = 81 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3427
  rw [data_3427.1, data_3427.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3427 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3427) < 16384 * m + 3427 := by
  apply descent_of_endpoint
  · rw [data_3427.1]; exact data_3427.2.2
  · rw [data_3427.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3429. -/
theorem data_3429 : oddCount 3429 14 = 4 ∧
    acceleratedOrbit 14 3429 = 17 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3429 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3429) = 81 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3429
  rw [data_3429.1, data_3429.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3429 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3429) < 16384 * m + 3429 := by
  apply descent_of_endpoint
  · rw [data_3429.1]; exact data_3429.2.2
  · rw [data_3429.2.1]; decide

end Collatz.Research.DescentAtlas.Batch152
