import Collatz.Research.DescentAtlas.Core

/-! Batch 263: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch263
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5903. -/
theorem data_5903 : oddCount 5903 14 = 6 ∧
    acceleratedOrbit 14 5903 = 263 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5903 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5903) = 729 * m + 263 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5903
  rw [data_5903.1, data_5903.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5903 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5903) < 16384 * m + 5903 := by
  apply descent_of_endpoint
  · rw [data_5903.1]; exact data_5903.2.2
  · rw [data_5903.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5905. -/
theorem data_5905 : oddCount 5905 14 = 8 ∧
    acceleratedOrbit 14 5905 = 2369 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5905 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5905) = 6561 * m + 2369 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5905
  rw [data_5905.1, data_5905.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5905 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5905) < 16384 * m + 5905 := by
  apply descent_of_endpoint
  · rw [data_5905.1]; exact data_5905.2.2
  · rw [data_5905.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5909. -/
theorem data_5909 : oddCount 5909 14 = 3 ∧
    acceleratedOrbit 14 5909 = 10 ∧ 27 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5909 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5909) = 27 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5909
  rw [data_5909.1, data_5909.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5909 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5909) < 16384 * m + 5909 := by
  apply descent_of_endpoint
  · rw [data_5909.1]; exact data_5909.2.2
  · rw [data_5909.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5911. -/
theorem data_5911 : oddCount 5911 14 = 8 ∧
    acceleratedOrbit 14 5911 = 2369 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5911 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5911) = 6561 * m + 2369 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5911
  rw [data_5911.1, data_5911.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5911 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5911) < 16384 * m + 5911 := by
  apply descent_of_endpoint
  · rw [data_5911.1]; exact data_5911.2.2
  · rw [data_5911.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5917. -/
theorem data_5917 : oddCount 5917 14 = 7 ∧
    acceleratedOrbit 14 5917 = 791 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5917 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5917) = 2187 * m + 791 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5917
  rw [data_5917.1, data_5917.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5917 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5917) < 16384 * m + 5917 := by
  apply descent_of_endpoint
  · rw [data_5917.1]; exact data_5917.2.2
  · rw [data_5917.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5919. -/
theorem data_5919 : oddCount 5919 14 = 8 ∧
    acceleratedOrbit 14 5919 = 2371 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5919 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5919) = 6561 * m + 2371 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5919
  rw [data_5919.1, data_5919.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5919 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5919) < 16384 * m + 5919 := by
  apply descent_of_endpoint
  · rw [data_5919.1]; exact data_5919.2.2
  · rw [data_5919.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5921. -/
theorem data_5921 : oddCount 5921 14 = 8 ∧
    acceleratedOrbit 14 5921 = 2375 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5921 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5921) = 6561 * m + 2375 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5921
  rw [data_5921.1, data_5921.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5921 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5921) < 16384 * m + 5921 := by
  apply descent_of_endpoint
  · rw [data_5921.1]; exact data_5921.2.2
  · rw [data_5921.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5923. -/
theorem data_5923 : oddCount 5923 14 = 5 ∧
    acceleratedOrbit 14 5923 = 88 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5923 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5923) = 243 * m + 88 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5923
  rw [data_5923.1, data_5923.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5923 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5923) < 16384 * m + 5923 := by
  apply descent_of_endpoint
  · rw [data_5923.1]; exact data_5923.2.2
  · rw [data_5923.2.1]; decide

end Collatz.Research.DescentAtlas.Batch263
