import Collatz.Research.DescentAtlas.Core

/-! Batch 49: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch049
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1089. -/
theorem data_1089 : oddCount 1089 14 = 6 ∧
    acceleratedOrbit 14 1089 = 49 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1089 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1089) = 729 * m + 49 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1089
  rw [data_1089.1, data_1089.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1089 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1089) < 16384 * m + 1089 := by
  apply descent_of_endpoint
  · rw [data_1089.1]; exact data_1089.2.2
  · rw [data_1089.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1091. -/
theorem data_1091 : oddCount 1091 14 = 6 ∧
    acceleratedOrbit 14 1091 = 49 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1091 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1091) = 729 * m + 49 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1091
  rw [data_1091.1, data_1091.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1091 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1091) < 16384 * m + 1091 := by
  apply descent_of_endpoint
  · rw [data_1091.1]; exact data_1091.2.2
  · rw [data_1091.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1093. -/
theorem data_1093 : oddCount 1093 14 = 5 ∧
    acceleratedOrbit 14 1093 = 17 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1093 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1093) = 243 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1093
  rw [data_1093.1, data_1093.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1093 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1093) < 16384 * m + 1093 := by
  apply descent_of_endpoint
  · rw [data_1093.1]; exact data_1093.2.2
  · rw [data_1093.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1099. -/
theorem data_1099 : oddCount 1099 14 = 5 ∧
    acceleratedOrbit 14 1099 = 17 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1099 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1099) = 243 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1099
  rw [data_1099.1, data_1099.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1099 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1099) < 16384 * m + 1099 := by
  apply descent_of_endpoint
  · rw [data_1099.1]; exact data_1099.2.2
  · rw [data_1099.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1101. -/
theorem data_1101 : oddCount 1101 14 = 8 ∧
    acceleratedOrbit 14 1101 = 445 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1101 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1101) = 6561 * m + 445 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1101
  rw [data_1101.1, data_1101.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1101 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1101) < 16384 * m + 1101 := by
  apply descent_of_endpoint
  · rw [data_1101.1]; exact data_1101.2.2
  · rw [data_1101.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1103. -/
theorem data_1103 : oddCount 1103 14 = 7 ∧
    acceleratedOrbit 14 1103 = 148 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1103 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1103) = 2187 * m + 148 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1103
  rw [data_1103.1, data_1103.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1103 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1103) < 16384 * m + 1103 := by
  apply descent_of_endpoint
  · rw [data_1103.1]; exact data_1103.2.2
  · rw [data_1103.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1105. -/
theorem data_1105 : oddCount 1105 14 = 8 ∧
    acceleratedOrbit 14 1105 = 445 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1105 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1105) = 6561 * m + 445 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1105
  rw [data_1105.1, data_1105.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1105 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1105) < 16384 * m + 1105 := by
  apply descent_of_endpoint
  · rw [data_1105.1]; exact data_1105.2.2
  · rw [data_1105.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1109. -/
theorem data_1109 : oddCount 1109 14 = 3 ∧
    acceleratedOrbit 14 1109 = 2 ∧ 27 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1109 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1109) = 27 * m + 2 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1109
  rw [data_1109.1, data_1109.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1109 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1109) < 16384 * m + 1109 := by
  apply descent_of_endpoint
  · rw [data_1109.1]; exact data_1109.2.2
  · rw [data_1109.2.1]; decide

end Collatz.Research.DescentAtlas.Batch049
