import Collatz.Research.DescentAtlas.Core

/-! Batch 33: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch033
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 739. -/
theorem data_739 : oddCount 739 14 = 4 ∧
    acceleratedOrbit 14 739 = 4 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_739 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 739) = 81 * m + 4 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 739
  rw [data_739.1, data_739.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_739 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 739) < 16384 * m + 739 := by
  apply descent_of_endpoint
  · rw [data_739.1]; exact data_739.2.2
  · rw [data_739.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 741. -/
theorem data_741 : oddCount 741 14 = 7 ∧
    acceleratedOrbit 14 741 = 101 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_741 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 741) = 2187 * m + 101 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 741
  rw [data_741.1, data_741.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_741 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 741) < 16384 * m + 741 := by
  apply descent_of_endpoint
  · rw [data_741.1]; exact data_741.2.2
  · rw [data_741.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 747. -/
theorem data_747 : oddCount 747 14 = 7 ∧
    acceleratedOrbit 14 747 = 100 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_747 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 747) = 2187 * m + 100 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 747
  rw [data_747.1, data_747.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_747 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 747) < 16384 * m + 747 := by
  apply descent_of_endpoint
  · rw [data_747.1]; exact data_747.2.2
  · rw [data_747.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 749. -/
theorem data_749 : oddCount 749 14 = 7 ∧
    acceleratedOrbit 14 749 = 101 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_749 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 749) = 2187 * m + 101 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 749
  rw [data_749.1, data_749.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_749 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 749) < 16384 * m + 749 := by
  apply descent_of_endpoint
  · rw [data_749.1]; exact data_749.2.2
  · rw [data_749.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 753. -/
theorem data_753 : oddCount 753 14 = 4 ∧
    acceleratedOrbit 14 753 = 4 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_753 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 753) = 81 * m + 4 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 753
  rw [data_753.1, data_753.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_753 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 753) < 16384 * m + 753 := by
  apply descent_of_endpoint
  · rw [data_753.1]; exact data_753.2.2
  · rw [data_753.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 757. -/
theorem data_757 : oddCount 757 14 = 7 ∧
    acceleratedOrbit 14 757 = 103 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_757 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 757) = 2187 * m + 103 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 757
  rw [data_757.1, data_757.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_757 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 757) < 16384 * m + 757 := by
  apply descent_of_endpoint
  · rw [data_757.1]; exact data_757.2.2
  · rw [data_757.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 761. -/
theorem data_761 : oddCount 761 14 = 6 ∧
    acceleratedOrbit 14 761 = 34 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_761 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 761) = 729 * m + 34 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 761
  rw [data_761.1, data_761.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_761 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 761) < 16384 * m + 761 := by
  apply descent_of_endpoint
  · rw [data_761.1]; exact data_761.2.2
  · rw [data_761.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 765. -/
theorem data_765 : oddCount 765 14 = 8 ∧
    acceleratedOrbit 14 765 = 308 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_765 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 765) = 6561 * m + 308 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 765
  rw [data_765.1, data_765.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_765 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 765) < 16384 * m + 765 := by
  apply descent_of_endpoint
  · rw [data_765.1]; exact data_765.2.2
  · rw [data_765.2.1]; decide

end Collatz.Research.DescentAtlas.Batch033
