import Collatz.Research.DescentAtlas.Core

/-! Batch 170: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch170
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 3821. -/
theorem data_3821 : oddCount 3821 14 = 7 ∧
    acceleratedOrbit 14 3821 = 512 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3821 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3821) = 2187 * m + 512 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3821
  rw [data_3821.1, data_3821.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3821 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3821) < 16384 * m + 3821 := by
  apply descent_of_endpoint
  · rw [data_3821.1]; exact data_3821.2.2
  · rw [data_3821.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3825. -/
theorem data_3825 : oddCount 3825 14 = 4 ∧
    acceleratedOrbit 14 3825 = 19 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3825 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3825) = 81 * m + 19 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3825
  rw [data_3825.1, data_3825.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3825 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3825) < 16384 * m + 3825 := by
  apply descent_of_endpoint
  · rw [data_3825.1]; exact data_3825.2.2
  · rw [data_3825.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3827. -/
theorem data_3827 : oddCount 3827 14 = 8 ∧
    acceleratedOrbit 14 3827 = 1534 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3827 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3827) = 6561 * m + 1534 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3827
  rw [data_3827.1, data_3827.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3827 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3827) < 16384 * m + 3827 := by
  apply descent_of_endpoint
  · rw [data_3827.1]; exact data_3827.2.2
  · rw [data_3827.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3833. -/
theorem data_3833 : oddCount 3833 14 = 8 ∧
    acceleratedOrbit 14 3833 = 1538 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3833 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3833) = 6561 * m + 1538 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3833
  rw [data_3833.1, data_3833.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3833 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3833) < 16384 * m + 3833 := by
  apply descent_of_endpoint
  · rw [data_3833.1]; exact data_3833.2.2
  · rw [data_3833.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3841. -/
theorem data_3841 : oddCount 3841 14 = 4 ∧
    acceleratedOrbit 14 3841 = 19 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3841 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3841) = 81 * m + 19 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3841
  rw [data_3841.1, data_3841.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3841 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3841) < 16384 * m + 3841 := by
  apply descent_of_endpoint
  · rw [data_3841.1]; exact data_3841.2.2
  · rw [data_3841.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3843. -/
theorem data_3843 : oddCount 3843 14 = 7 ∧
    acceleratedOrbit 14 3843 = 514 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3843 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3843) = 2187 * m + 514 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3843
  rw [data_3843.1, data_3843.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3843 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3843) < 16384 * m + 3843 := by
  apply descent_of_endpoint
  · rw [data_3843.1]; exact data_3843.2.2
  · rw [data_3843.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3845. -/
theorem data_3845 : oddCount 3845 14 = 6 ∧
    acceleratedOrbit 14 3845 = 172 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3845 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3845) = 729 * m + 172 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3845
  rw [data_3845.1, data_3845.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3845 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3845) < 16384 * m + 3845 := by
  apply descent_of_endpoint
  · rw [data_3845.1]; exact data_3845.2.2
  · rw [data_3845.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3847. -/
theorem data_3847 : oddCount 3847 14 = 7 ∧
    acceleratedOrbit 14 3847 = 514 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3847 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3847) = 2187 * m + 514 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3847
  rw [data_3847.1, data_3847.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3847 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3847) < 16384 * m + 3847 := by
  apply descent_of_endpoint
  · rw [data_3847.1]; exact data_3847.2.2
  · rw [data_3847.2.1]; decide

end Collatz.Research.DescentAtlas.Batch170
