import Collatz.Research.DescentAtlas.Core

/-! Batch 107: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch107
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 2403. -/
theorem data_2403 : oddCount 2403 14 = 8 ∧
    acceleratedOrbit 14 2403 = 971 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2403 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2403) = 6561 * m + 971 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2403
  rw [data_2403.1, data_2403.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2403 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2403) < 16384 * m + 2403 := by
  apply descent_of_endpoint
  · rw [data_2403.1]; exact data_2403.2.2
  · rw [data_2403.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2405. -/
theorem data_2405 : oddCount 2405 14 = 8 ∧
    acceleratedOrbit 14 2405 = 971 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2405 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2405) = 6561 * m + 971 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2405
  rw [data_2405.1, data_2405.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2405 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2405) < 16384 * m + 2405 := by
  apply descent_of_endpoint
  · rw [data_2405.1]; exact data_2405.2.2
  · rw [data_2405.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2409. -/
theorem data_2409 : oddCount 2409 14 = 7 ∧
    acceleratedOrbit 14 2409 = 323 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2409 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2409) = 2187 * m + 323 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2409
  rw [data_2409.1, data_2409.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2409 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2409) < 16384 * m + 2409 := by
  apply descent_of_endpoint
  · rw [data_2409.1]; exact data_2409.2.2
  · rw [data_2409.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2411. -/
theorem data_2411 : oddCount 2411 14 = 8 ∧
    acceleratedOrbit 14 2411 = 967 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2411 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2411) = 6561 * m + 967 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2411
  rw [data_2411.1, data_2411.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2411 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2411) < 16384 * m + 2411 := by
  apply descent_of_endpoint
  · rw [data_2411.1]; exact data_2411.2.2
  · rw [data_2411.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2415. -/
theorem data_2415 : oddCount 2415 14 = 7 ∧
    acceleratedOrbit 14 2415 = 323 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2415 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2415) = 2187 * m + 323 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2415
  rw [data_2415.1, data_2415.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2415 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2415) < 16384 * m + 2415 := by
  apply descent_of_endpoint
  · rw [data_2415.1]; exact data_2415.2.2
  · rw [data_2415.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2417. -/
theorem data_2417 : oddCount 2417 14 = 3 ∧
    acceleratedOrbit 14 2417 = 4 ∧ 27 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2417 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2417) = 27 * m + 4 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2417
  rw [data_2417.1, data_2417.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2417 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2417) < 16384 * m + 2417 := by
  apply descent_of_endpoint
  · rw [data_2417.1]; exact data_2417.2.2
  · rw [data_2417.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2421. -/
theorem data_2421 : oddCount 2421 14 = 3 ∧
    acceleratedOrbit 14 2421 = 4 ∧ 27 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2421 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2421) = 27 * m + 4 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2421
  rw [data_2421.1, data_2421.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2421 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2421) < 16384 * m + 2421 := by
  apply descent_of_endpoint
  · rw [data_2421.1]; exact data_2421.2.2
  · rw [data_2421.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2427. -/
theorem data_2427 : oddCount 2427 14 = 8 ∧
    acceleratedOrbit 14 2427 = 973 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2427 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2427) = 6561 * m + 973 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2427
  rw [data_2427.1, data_2427.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2427 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2427) < 16384 * m + 2427 := by
  apply descent_of_endpoint
  · rw [data_2427.1]; exact data_2427.2.2
  · rw [data_2427.2.1]; decide

end Collatz.Research.DescentAtlas.Batch107
