import Collatz.Research.DescentAtlas.Core

/-! Batch 177: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch177
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 3969. -/
theorem data_3969 : oddCount 3969 14 = 8 ∧
    acceleratedOrbit 14 3969 = 1592 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3969 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3969) = 6561 * m + 1592 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3969
  rw [data_3969.1, data_3969.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3969 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3969) < 16384 * m + 3969 := by
  apply descent_of_endpoint
  · rw [data_3969.1]; exact data_3969.2.2
  · rw [data_3969.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3971. -/
theorem data_3971 : oddCount 3971 14 = 5 ∧
    acceleratedOrbit 14 3971 = 59 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3971 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3971) = 243 * m + 59 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3971
  rw [data_3971.1, data_3971.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3971 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3971) < 16384 * m + 3971 := by
  apply descent_of_endpoint
  · rw [data_3971.1]; exact data_3971.2.2
  · rw [data_3971.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3973. -/
theorem data_3973 : oddCount 3973 14 = 8 ∧
    acceleratedOrbit 14 3973 = 1595 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3973 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3973) = 6561 * m + 1595 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3973
  rw [data_3973.1, data_3973.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3973 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3973) < 16384 * m + 3973 := by
  apply descent_of_endpoint
  · rw [data_3973.1]; exact data_3973.2.2
  · rw [data_3973.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3975. -/
theorem data_3975 : oddCount 3975 14 = 5 ∧
    acceleratedOrbit 14 3975 = 59 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3975 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3975) = 243 * m + 59 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3975
  rw [data_3975.1, data_3975.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3975 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3975) < 16384 * m + 3975 := by
  apply descent_of_endpoint
  · rw [data_3975.1]; exact data_3975.2.2
  · rw [data_3975.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3979. -/
theorem data_3979 : oddCount 3979 14 = 8 ∧
    acceleratedOrbit 14 3979 = 1595 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3979 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3979) = 6561 * m + 1595 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3979
  rw [data_3979.1, data_3979.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3979 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3979) < 16384 * m + 3979 := by
  apply descent_of_endpoint
  · rw [data_3979.1]; exact data_3979.2.2
  · rw [data_3979.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3981. -/
theorem data_3981 : oddCount 3981 14 = 4 ∧
    acceleratedOrbit 14 3981 = 20 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3981 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3981) = 81 * m + 20 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3981
  rw [data_3981.1, data_3981.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3981 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3981) < 16384 * m + 3981 := by
  apply descent_of_endpoint
  · rw [data_3981.1]; exact data_3981.2.2
  · rw [data_3981.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3983. -/
theorem data_3983 : oddCount 3983 14 = 7 ∧
    acceleratedOrbit 14 3983 = 532 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3983 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3983) = 2187 * m + 532 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3983
  rw [data_3983.1, data_3983.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3983 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3983) < 16384 * m + 3983 := by
  apply descent_of_endpoint
  · rw [data_3983.1]; exact data_3983.2.2
  · rw [data_3983.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3985. -/
theorem data_3985 : oddCount 3985 14 = 7 ∧
    acceleratedOrbit 14 3985 = 533 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3985 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3985) = 2187 * m + 533 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3985
  rw [data_3985.1, data_3985.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3985 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3985) < 16384 * m + 3985 := by
  apply descent_of_endpoint
  · rw [data_3985.1]; exact data_3985.2.2
  · rw [data_3985.2.1]; decide

end Collatz.Research.DescentAtlas.Batch177
