import Collatz.Research.DescentAtlas.Core

/-! Batch 36: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch036
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 811. -/
theorem data_811 : oddCount 811 14 = 7 ∧
    acceleratedOrbit 14 811 = 109 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_811 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 811) = 2187 * m + 109 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 811
  rw [data_811.1, data_811.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_811 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 811) < 16384 * m + 811 := by
  apply descent_of_endpoint
  · rw [data_811.1]; exact data_811.2.2
  · rw [data_811.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 813. -/
theorem data_813 : oddCount 813 14 = 6 ∧
    acceleratedOrbit 14 813 = 37 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_813 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 813) = 729 * m + 37 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 813
  rw [data_813.1, data_813.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_813 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 813) < 16384 * m + 813 := by
  apply descent_of_endpoint
  · rw [data_813.1]; exact data_813.2.2
  · rw [data_813.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 815. -/
theorem data_815 : oddCount 815 14 = 7 ∧
    acceleratedOrbit 14 815 = 109 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_815 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 815) = 2187 * m + 109 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 815
  rw [data_815.1, data_815.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_815 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 815) < 16384 * m + 815 := by
  apply descent_of_endpoint
  · rw [data_815.1]; exact data_815.2.2
  · rw [data_815.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 817. -/
theorem data_817 : oddCount 817 14 = 6 ∧
    acceleratedOrbit 14 817 = 37 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_817 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 817) = 729 * m + 37 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 817
  rw [data_817.1, data_817.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_817 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 817) < 16384 * m + 817 := by
  apply descent_of_endpoint
  · rw [data_817.1]; exact data_817.2.2
  · rw [data_817.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 819. -/
theorem data_819 : oddCount 819 14 = 6 ∧
    acceleratedOrbit 14 819 = 37 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_819 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 819) = 729 * m + 37 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 819
  rw [data_819.1, data_819.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_819 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 819) < 16384 * m + 819 := by
  apply descent_of_endpoint
  · rw [data_819.1]; exact data_819.2.2
  · rw [data_819.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 821. -/
theorem data_821 : oddCount 821 14 = 5 ∧
    acceleratedOrbit 14 821 = 13 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_821 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 821) = 243 * m + 13 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 821
  rw [data_821.1, data_821.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_821 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 821) < 16384 * m + 821 := by
  apply descent_of_endpoint
  · rw [data_821.1]; exact data_821.2.2
  · rw [data_821.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 825. -/
theorem data_825 : oddCount 825 14 = 8 ∧
    acceleratedOrbit 14 825 = 332 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_825 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 825) = 6561 * m + 332 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 825
  rw [data_825.1, data_825.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_825 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 825) < 16384 * m + 825 := by
  apply descent_of_endpoint
  · rw [data_825.1]; exact data_825.2.2
  · rw [data_825.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 827. -/
theorem data_827 : oddCount 827 14 = 6 ∧
    acceleratedOrbit 14 827 = 37 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_827 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 827) = 729 * m + 37 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 827
  rw [data_827.1, data_827.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_827 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 827) < 16384 * m + 827 := by
  apply descent_of_endpoint
  · rw [data_827.1]; exact data_827.2.2
  · rw [data_827.2.1]; decide

end Collatz.Research.DescentAtlas.Batch036
