import Collatz.Research.DescentAtlas.Core

/-! Batch 217: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch217
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 4877. -/
theorem data_4877 : oddCount 4877 14 = 6 ∧
    acceleratedOrbit 14 4877 = 218 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4877 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4877) = 729 * m + 218 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4877
  rw [data_4877.1, data_4877.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4877 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4877) < 16384 * m + 4877 := by
  apply descent_of_endpoint
  · rw [data_4877.1]; exact data_4877.2.2
  · rw [data_4877.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4879. -/
theorem data_4879 : oddCount 4879 14 = 6 ∧
    acceleratedOrbit 14 4879 = 218 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4879 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4879) = 729 * m + 218 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4879
  rw [data_4879.1, data_4879.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4879 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4879) < 16384 * m + 4879 := by
  apply descent_of_endpoint
  · rw [data_4879.1]; exact data_4879.2.2
  · rw [data_4879.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4881. -/
theorem data_4881 : oddCount 4881 14 = 6 ∧
    acceleratedOrbit 14 4881 = 218 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4881 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4881) = 729 * m + 218 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4881
  rw [data_4881.1, data_4881.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4881 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4881) < 16384 * m + 4881 := by
  apply descent_of_endpoint
  · rw [data_4881.1]; exact data_4881.2.2
  · rw [data_4881.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4883. -/
theorem data_4883 : oddCount 4883 14 = 8 ∧
    acceleratedOrbit 14 4883 = 1957 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4883 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4883) = 6561 * m + 1957 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4883
  rw [data_4883.1, data_4883.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4883 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4883) < 16384 * m + 4883 := by
  apply descent_of_endpoint
  · rw [data_4883.1]; exact data_4883.2.2
  · rw [data_4883.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4885. -/
theorem data_4885 : oddCount 4885 14 = 5 ∧
    acceleratedOrbit 14 4885 = 74 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4885 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4885) = 243 * m + 74 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4885
  rw [data_4885.1, data_4885.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4885 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4885) < 16384 * m + 4885 := by
  apply descent_of_endpoint
  · rw [data_4885.1]; exact data_4885.2.2
  · rw [data_4885.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4887. -/
theorem data_4887 : oddCount 4887 14 = 7 ∧
    acceleratedOrbit 14 4887 = 653 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4887 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4887) = 2187 * m + 653 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4887
  rw [data_4887.1, data_4887.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4887 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4887) < 16384 * m + 4887 := by
  apply descent_of_endpoint
  · rw [data_4887.1]; exact data_4887.2.2
  · rw [data_4887.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4889. -/
theorem data_4889 : oddCount 4889 14 = 7 ∧
    acceleratedOrbit 14 4889 = 653 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4889 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4889) = 2187 * m + 653 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4889
  rw [data_4889.1, data_4889.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4889 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4889) < 16384 * m + 4889 := by
  apply descent_of_endpoint
  · rw [data_4889.1]; exact data_4889.2.2
  · rw [data_4889.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4893. -/
theorem data_4893 : oddCount 4893 14 = 6 ∧
    acceleratedOrbit 14 4893 = 218 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4893 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4893) = 729 * m + 218 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4893
  rw [data_4893.1, data_4893.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4893 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4893) < 16384 * m + 4893 := by
  apply descent_of_endpoint
  · rw [data_4893.1]; exact data_4893.2.2
  · rw [data_4893.2.1]; decide

end Collatz.Research.DescentAtlas.Batch217
