import Collatz.Research.DescentAtlas.Core

/-! Batch 25: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch025
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 571. -/
theorem data_571 : oddCount 571 14 = 6 ∧
    acceleratedOrbit 14 571 = 26 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_571 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 571) = 729 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 571
  rw [data_571.1, data_571.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_571 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 571) < 16384 * m + 571 := by
  apply descent_of_endpoint
  · rw [data_571.1]; exact data_571.2.2
  · rw [data_571.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 573. -/
theorem data_573 : oddCount 573 14 = 8 ∧
    acceleratedOrbit 14 573 = 233 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_573 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 573) = 6561 * m + 233 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 573
  rw [data_573.1, data_573.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_573 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 573) < 16384 * m + 573 := by
  apply descent_of_endpoint
  · rw [data_573.1]; exact data_573.2.2
  · rw [data_573.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 575. -/
theorem data_575 : oddCount 575 14 = 7 ∧
    acceleratedOrbit 14 575 = 77 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_575 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 575) = 2187 * m + 77 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 575
  rw [data_575.1, data_575.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_575 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 575) < 16384 * m + 575 := by
  apply descent_of_endpoint
  · rw [data_575.1]; exact data_575.2.2
  · rw [data_575.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 577. -/
theorem data_577 : oddCount 577 14 = 7 ∧
    acceleratedOrbit 14 577 = 80 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_577 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 577) = 2187 * m + 80 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 577
  rw [data_577.1, data_577.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_577 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 577) < 16384 * m + 577 := by
  apply descent_of_endpoint
  · rw [data_577.1]; exact data_577.2.2
  · rw [data_577.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 579. -/
theorem data_579 : oddCount 579 14 = 7 ∧
    acceleratedOrbit 14 579 = 80 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_579 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 579) = 2187 * m + 80 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 579
  rw [data_579.1, data_579.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_579 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 579) < 16384 * m + 579 := by
  apply descent_of_endpoint
  · rw [data_579.1]; exact data_579.2.2
  · rw [data_579.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 581. -/
theorem data_581 : oddCount 581 14 = 8 ∧
    acceleratedOrbit 14 581 = 242 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 581) = 6561 * m + 242 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 581
  rw [data_581.1, data_581.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 581) < 16384 * m + 581 := by
  apply descent_of_endpoint
  · rw [data_581.1]; exact data_581.2.2
  · rw [data_581.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 583. -/
theorem data_583 : oddCount 583 14 = 6 ∧
    acceleratedOrbit 14 583 = 26 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_583 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 583) = 729 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 583
  rw [data_583.1, data_583.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_583 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 583) < 16384 * m + 583 := by
  apply descent_of_endpoint
  · rw [data_583.1]; exact data_583.2.2
  · rw [data_583.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 585. -/
theorem data_585 : oddCount 585 14 = 8 ∧
    acceleratedOrbit 14 585 = 236 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 585) = 6561 * m + 236 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 585
  rw [data_585.1, data_585.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 585) < 16384 * m + 585 := by
  apply descent_of_endpoint
  · rw [data_585.1]; exact data_585.2.2
  · rw [data_585.2.1]; decide

end Collatz.Research.DescentAtlas.Batch025
