import Collatz.Research.DescentAtlas.Core

/-! Batch 48: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch048
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1073. -/
theorem data_1073 : oddCount 1073 14 = 5 ∧
    acceleratedOrbit 14 1073 = 16 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1073 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1073) = 243 * m + 16 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1073
  rw [data_1073.1, data_1073.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1073 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1073) < 16384 * m + 1073 := by
  apply descent_of_endpoint
  · rw [data_1073.1]; exact data_1073.2.2
  · rw [data_1073.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1075. -/
theorem data_1075 : oddCount 1075 14 = 5 ∧
    acceleratedOrbit 14 1075 = 16 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1075 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1075) = 243 * m + 16 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1075
  rw [data_1075.1, data_1075.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1075 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1075) < 16384 * m + 1075 := by
  apply descent_of_endpoint
  · rw [data_1075.1]; exact data_1075.2.2
  · rw [data_1075.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1077. -/
theorem data_1077 : oddCount 1077 14 = 5 ∧
    acceleratedOrbit 14 1077 = 17 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1077 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1077) = 243 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1077
  rw [data_1077.1, data_1077.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1077 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1077) < 16384 * m + 1077 := by
  apply descent_of_endpoint
  · rw [data_1077.1]; exact data_1077.2.2
  · rw [data_1077.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1079. -/
theorem data_1079 : oddCount 1079 14 = 8 ∧
    acceleratedOrbit 14 1079 = 433 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1079 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1079) = 6561 * m + 433 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1079
  rw [data_1079.1, data_1079.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1079 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1079) < 16384 * m + 1079 := by
  apply descent_of_endpoint
  · rw [data_1079.1]; exact data_1079.2.2
  · rw [data_1079.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1081. -/
theorem data_1081 : oddCount 1081 14 = 7 ∧
    acceleratedOrbit 14 1081 = 145 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1081 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1081) = 2187 * m + 145 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1081
  rw [data_1081.1, data_1081.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1081 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1081) < 16384 * m + 1081 := by
  apply descent_of_endpoint
  · rw [data_1081.1]; exact data_1081.2.2
  · rw [data_1081.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1083. -/
theorem data_1083 : oddCount 1083 14 = 7 ∧
    acceleratedOrbit 14 1083 = 145 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1083 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1083) = 2187 * m + 145 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1083
  rw [data_1083.1, data_1083.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1083 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1083) < 16384 * m + 1083 := by
  apply descent_of_endpoint
  · rw [data_1083.1]; exact data_1083.2.2
  · rw [data_1083.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1085. -/
theorem data_1085 : oddCount 1085 14 = 6 ∧
    acceleratedOrbit 14 1085 = 49 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1085 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1085) = 729 * m + 49 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1085
  rw [data_1085.1, data_1085.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1085 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1085) < 16384 * m + 1085 := by
  apply descent_of_endpoint
  · rw [data_1085.1]; exact data_1085.2.2
  · rw [data_1085.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1087. -/
theorem data_1087 : oddCount 1087 14 = 8 ∧
    acceleratedOrbit 14 1087 = 436 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1087 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1087) = 6561 * m + 436 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1087
  rw [data_1087.1, data_1087.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1087 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1087) < 16384 * m + 1087 := by
  apply descent_of_endpoint
  · rw [data_1087.1]; exact data_1087.2.2
  · rw [data_1087.2.1]; decide

end Collatz.Research.DescentAtlas.Batch048
