import Collatz.Research.DescentAtlas.Core

/-! Batch 298: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch298
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 6685. -/
theorem data_6685 : oddCount 6685 14 = 6 ∧
    acceleratedOrbit 14 6685 = 298 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6685) = 729 * m + 298 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6685
  rw [data_6685.1, data_6685.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6685) < 16384 * m + 6685 := by
  apply descent_of_endpoint
  · rw [data_6685.1]; exact data_6685.2.2
  · rw [data_6685.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6689. -/
theorem data_6689 : oddCount 6689 14 = 6 ∧
    acceleratedOrbit 14 6689 = 298 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6689 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6689) = 729 * m + 298 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6689
  rw [data_6689.1, data_6689.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6689 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6689) < 16384 * m + 6689 := by
  apply descent_of_endpoint
  · rw [data_6689.1]; exact data_6689.2.2
  · rw [data_6689.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6691. -/
theorem data_6691 : oddCount 6691 14 = 6 ∧
    acceleratedOrbit 14 6691 = 299 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6691) = 729 * m + 299 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6691
  rw [data_6691.1, data_6691.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6691) < 16384 * m + 6691 := by
  apply descent_of_endpoint
  · rw [data_6691.1]; exact data_6691.2.2
  · rw [data_6691.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6693. -/
theorem data_6693 : oddCount 6693 14 = 8 ∧
    acceleratedOrbit 14 6693 = 2683 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6693) = 6561 * m + 2683 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6693
  rw [data_6693.1, data_6693.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6693) < 16384 * m + 6693 := by
  apply descent_of_endpoint
  · rw [data_6693.1]; exact data_6693.2.2
  · rw [data_6693.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6695. -/
theorem data_6695 : oddCount 6695 14 = 6 ∧
    acceleratedOrbit 14 6695 = 298 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6695 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6695) = 729 * m + 298 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6695
  rw [data_6695.1, data_6695.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6695 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6695) < 16384 * m + 6695 := by
  apply descent_of_endpoint
  · rw [data_6695.1]; exact data_6695.2.2
  · rw [data_6695.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6699. -/
theorem data_6699 : oddCount 6699 14 = 6 ∧
    acceleratedOrbit 14 6699 = 299 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6699 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6699) = 729 * m + 299 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6699
  rw [data_6699.1, data_6699.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6699 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6699) < 16384 * m + 6699 := by
  apply descent_of_endpoint
  · rw [data_6699.1]; exact data_6699.2.2
  · rw [data_6699.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6701. -/
theorem data_6701 : oddCount 6701 14 = 6 ∧
    acceleratedOrbit 14 6701 = 299 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6701 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6701) = 729 * m + 299 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6701
  rw [data_6701.1, data_6701.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6701 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6701) < 16384 * m + 6701 := by
  apply descent_of_endpoint
  · rw [data_6701.1]; exact data_6701.2.2
  · rw [data_6701.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6705. -/
theorem data_6705 : oddCount 6705 14 = 7 ∧
    acceleratedOrbit 14 6705 = 896 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6705 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6705) = 2187 * m + 896 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6705
  rw [data_6705.1, data_6705.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6705 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6705) < 16384 * m + 6705 := by
  apply descent_of_endpoint
  · rw [data_6705.1]; exact data_6705.2.2
  · rw [data_6705.2.1]; decide

end Collatz.Research.DescentAtlas.Batch298
