import Collatz.Research.DescentAtlas.Core

/-! Batch 249: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch249
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5581. -/
theorem data_5581 : oddCount 5581 14 = 5 ∧
    acceleratedOrbit 14 5581 = 83 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5581) = 243 * m + 83 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5581
  rw [data_5581.1, data_5581.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5581) < 16384 * m + 5581 := by
  apply descent_of_endpoint
  · rw [data_5581.1]; exact data_5581.2.2
  · rw [data_5581.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5585. -/
theorem data_5585 : oddCount 5585 14 = 5 ∧
    acceleratedOrbit 14 5585 = 83 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5585) = 243 * m + 83 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5585
  rw [data_5585.1, data_5585.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5585) < 16384 * m + 5585 := by
  apply descent_of_endpoint
  · rw [data_5585.1]; exact data_5585.2.2
  · rw [data_5585.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5589. -/
theorem data_5589 : oddCount 5589 14 = 4 ∧
    acceleratedOrbit 14 5589 = 28 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5589 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5589) = 81 * m + 28 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5589
  rw [data_5589.1, data_5589.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5589 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5589) < 16384 * m + 5589 := by
  apply descent_of_endpoint
  · rw [data_5589.1]; exact data_5589.2.2
  · rw [data_5589.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5593. -/
theorem data_5593 : oddCount 5593 14 = 7 ∧
    acceleratedOrbit 14 5593 = 749 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5593 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5593) = 2187 * m + 749 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5593
  rw [data_5593.1, data_5593.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5593 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5593) < 16384 * m + 5593 := by
  apply descent_of_endpoint
  · rw [data_5593.1]; exact data_5593.2.2
  · rw [data_5593.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5595. -/
theorem data_5595 : oddCount 5595 14 = 5 ∧
    acceleratedOrbit 14 5595 = 83 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5595 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5595) = 243 * m + 83 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5595
  rw [data_5595.1, data_5595.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5595 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5595) < 16384 * m + 5595 := by
  apply descent_of_endpoint
  · rw [data_5595.1]; exact data_5595.2.2
  · rw [data_5595.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5597. -/
theorem data_5597 : oddCount 5597 14 = 7 ∧
    acceleratedOrbit 14 5597 = 749 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5597 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5597) = 2187 * m + 749 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5597
  rw [data_5597.1, data_5597.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5597 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5597) < 16384 * m + 5597 := by
  apply descent_of_endpoint
  · rw [data_5597.1]; exact data_5597.2.2
  · rw [data_5597.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5601. -/
theorem data_5601 : oddCount 5601 14 = 7 ∧
    acceleratedOrbit 14 5601 = 748 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5601 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5601) = 2187 * m + 748 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5601
  rw [data_5601.1, data_5601.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5601 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5601) < 16384 * m + 5601 := by
  apply descent_of_endpoint
  · rw [data_5601.1]; exact data_5601.2.2
  · rw [data_5601.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5603. -/
theorem data_5603 : oddCount 5603 14 = 4 ∧
    acceleratedOrbit 14 5603 = 28 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5603 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5603) = 81 * m + 28 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5603
  rw [data_5603.1, data_5603.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5603 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5603) < 16384 * m + 5603 := by
  apply descent_of_endpoint
  · rw [data_5603.1]; exact data_5603.2.2
  · rw [data_5603.2.1]; decide

end Collatz.Research.DescentAtlas.Batch249
