import Collatz.Research.DescentAtlas.Core

/-! Batch 30: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch030
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 675. -/
theorem data_675 : oddCount 675 14 = 7 ∧
    acceleratedOrbit 14 675 = 91 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_675 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 675) = 2187 * m + 91 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 675
  rw [data_675.1, data_675.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_675 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 675) < 16384 * m + 675 := by
  apply descent_of_endpoint
  · rw [data_675.1]; exact data_675.2.2
  · rw [data_675.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 683. -/
theorem data_683 : oddCount 683 14 = 7 ∧
    acceleratedOrbit 14 683 = 92 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_683 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 683) = 2187 * m + 92 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 683
  rw [data_683.1, data_683.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_683 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 683) < 16384 * m + 683 := by
  apply descent_of_endpoint
  · rw [data_683.1]; exact data_683.2.2
  · rw [data_683.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 685. -/
theorem data_685 : oddCount 685 14 = 6 ∧
    acceleratedOrbit 14 685 = 31 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 685) = 729 * m + 31 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 685
  rw [data_685.1, data_685.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 685) < 16384 * m + 685 := by
  apply descent_of_endpoint
  · rw [data_685.1]; exact data_685.2.2
  · rw [data_685.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 687. -/
theorem data_687 : oddCount 687 14 = 7 ∧
    acceleratedOrbit 14 687 = 92 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_687 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 687) = 2187 * m + 92 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 687
  rw [data_687.1, data_687.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_687 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 687) < 16384 * m + 687 := by
  apply descent_of_endpoint
  · rw [data_687.1]; exact data_687.2.2
  · rw [data_687.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 689. -/
theorem data_689 : oddCount 689 14 = 7 ∧
    acceleratedOrbit 14 689 = 94 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_689 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 689) = 2187 * m + 94 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 689
  rw [data_689.1, data_689.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_689 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 689) < 16384 * m + 689 := by
  apply descent_of_endpoint
  · rw [data_689.1]; exact data_689.2.2
  · rw [data_689.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 691. -/
theorem data_691 : oddCount 691 14 = 7 ∧
    acceleratedOrbit 14 691 = 94 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 691) = 2187 * m + 94 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 691
  rw [data_691.1, data_691.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 691) < 16384 * m + 691 := by
  apply descent_of_endpoint
  · rw [data_691.1]; exact data_691.2.2
  · rw [data_691.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 693. -/
theorem data_693 : oddCount 693 14 = 5 ∧
    acceleratedOrbit 14 693 = 11 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 693) = 243 * m + 11 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 693
  rw [data_693.1, data_693.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 693) < 16384 * m + 693 := by
  apply descent_of_endpoint
  · rw [data_693.1]; exact data_693.2.2
  · rw [data_693.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 695. -/
theorem data_695 : oddCount 695 14 = 6 ∧
    acceleratedOrbit 14 695 = 31 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_695 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 695) = 729 * m + 31 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 695
  rw [data_695.1, data_695.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_695 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 695) < 16384 * m + 695 := by
  apply descent_of_endpoint
  · rw [data_695.1]; exact data_695.2.2
  · rw [data_695.2.1]; decide

end Collatz.Research.DescentAtlas.Batch030
