import Collatz.Research.DescentAtlas.Core

/-! Batch 299: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch299
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 6707. -/
theorem data_6707 : oddCount 6707 14 = 7 ∧
    acceleratedOrbit 14 6707 = 896 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6707 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6707) = 2187 * m + 896 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6707
  rw [data_6707.1, data_6707.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6707 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6707) < 16384 * m + 6707 := by
  apply descent_of_endpoint
  · rw [data_6707.1]; exact data_6707.2.2
  · rw [data_6707.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6709. -/
theorem data_6709 : oddCount 6709 14 = 5 ∧
    acceleratedOrbit 14 6709 = 101 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6709 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6709) = 243 * m + 101 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6709
  rw [data_6709.1, data_6709.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6709 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6709) < 16384 * m + 6709 := by
  apply descent_of_endpoint
  · rw [data_6709.1]; exact data_6709.2.2
  · rw [data_6709.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6713. -/
theorem data_6713 : oddCount 6713 14 = 8 ∧
    acceleratedOrbit 14 6713 = 2690 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6713 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6713) = 6561 * m + 2690 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6713
  rw [data_6713.1, data_6713.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6713 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6713) < 16384 * m + 6713 := by
  apply descent_of_endpoint
  · rw [data_6713.1]; exact data_6713.2.2
  · rw [data_6713.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6715. -/
theorem data_6715 : oddCount 6715 14 = 6 ∧
    acceleratedOrbit 14 6715 = 299 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6715 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6715) = 729 * m + 299 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6715
  rw [data_6715.1, data_6715.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6715 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6715) < 16384 * m + 6715 := by
  apply descent_of_endpoint
  · rw [data_6715.1]; exact data_6715.2.2
  · rw [data_6715.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6717. -/
theorem data_6717 : oddCount 6717 14 = 8 ∧
    acceleratedOrbit 14 6717 = 2693 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6717 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6717) = 6561 * m + 2693 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6717
  rw [data_6717.1, data_6717.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6717 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6717) < 16384 * m + 6717 := by
  apply descent_of_endpoint
  · rw [data_6717.1]; exact data_6717.2.2
  · rw [data_6717.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6719. -/
theorem data_6719 : oddCount 6719 14 = 6 ∧
    acceleratedOrbit 14 6719 = 299 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6719 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6719) = 729 * m + 299 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6719
  rw [data_6719.1, data_6719.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6719 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6719) < 16384 * m + 6719 := by
  apply descent_of_endpoint
  · rw [data_6719.1]; exact data_6719.2.2
  · rw [data_6719.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6721. -/
theorem data_6721 : oddCount 6721 14 = 5 ∧
    acceleratedOrbit 14 6721 = 100 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6721 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6721) = 243 * m + 100 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6721
  rw [data_6721.1, data_6721.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6721 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6721) < 16384 * m + 6721 := by
  apply descent_of_endpoint
  · rw [data_6721.1]; exact data_6721.2.2
  · rw [data_6721.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6723. -/
theorem data_6723 : oddCount 6723 14 = 5 ∧
    acceleratedOrbit 14 6723 = 100 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6723 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6723) = 243 * m + 100 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6723
  rw [data_6723.1, data_6723.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6723 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6723) < 16384 * m + 6723 := by
  apply descent_of_endpoint
  · rw [data_6723.1]; exact data_6723.2.2
  · rw [data_6723.2.1]; decide

end Collatz.Research.DescentAtlas.Batch299
