import Collatz.Research.DescentAtlas.Core

/-! Batch 116: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch116
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 2599. -/
theorem data_2599 : oddCount 2599 14 = 8 ∧
    acceleratedOrbit 14 2599 = 1043 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2599 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2599) = 6561 * m + 1043 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2599
  rw [data_2599.1, data_2599.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2599 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2599) < 16384 * m + 2599 := by
  apply descent_of_endpoint
  · rw [data_2599.1]; exact data_2599.2.2
  · rw [data_2599.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2603. -/
theorem data_2603 : oddCount 2603 14 = 7 ∧
    acceleratedOrbit 14 2603 = 350 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2603 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2603) = 2187 * m + 350 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2603
  rw [data_2603.1, data_2603.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2603 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2603) < 16384 * m + 2603 := by
  apply descent_of_endpoint
  · rw [data_2603.1]; exact data_2603.2.2
  · rw [data_2603.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2605. -/
theorem data_2605 : oddCount 2605 14 = 7 ∧
    acceleratedOrbit 14 2605 = 350 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2605 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2605) = 2187 * m + 350 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2605
  rw [data_2605.1, data_2605.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2605 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2605) < 16384 * m + 2605 := by
  apply descent_of_endpoint
  · rw [data_2605.1]; exact data_2605.2.2
  · rw [data_2605.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2609. -/
theorem data_2609 : oddCount 2609 14 = 8 ∧
    acceleratedOrbit 14 2609 = 1048 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2609 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2609) = 6561 * m + 1048 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2609
  rw [data_2609.1, data_2609.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2609 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2609) < 16384 * m + 2609 := by
  apply descent_of_endpoint
  · rw [data_2609.1]; exact data_2609.2.2
  · rw [data_2609.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2611. -/
theorem data_2611 : oddCount 2611 14 = 8 ∧
    acceleratedOrbit 14 2611 = 1048 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2611 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2611) = 6561 * m + 1048 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2611
  rw [data_2611.1, data_2611.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2611 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2611) < 16384 * m + 2611 := by
  apply descent_of_endpoint
  · rw [data_2611.1]; exact data_2611.2.2
  · rw [data_2611.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2613. -/
theorem data_2613 : oddCount 2613 14 = 5 ∧
    acceleratedOrbit 14 2613 = 40 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2613 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2613) = 243 * m + 40 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2613
  rw [data_2613.1, data_2613.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2613 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2613) < 16384 * m + 2613 := by
  apply descent_of_endpoint
  · rw [data_2613.1]; exact data_2613.2.2
  · rw [data_2613.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2619. -/
theorem data_2619 : oddCount 2619 14 = 8 ∧
    acceleratedOrbit 14 2619 = 1052 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2619 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2619) = 6561 * m + 1052 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2619
  rw [data_2619.1, data_2619.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2619 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2619) < 16384 * m + 2619 := by
  apply descent_of_endpoint
  · rw [data_2619.1]; exact data_2619.2.2
  · rw [data_2619.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2623. -/
theorem data_2623 : oddCount 2623 14 = 8 ∧
    acceleratedOrbit 14 2623 = 1052 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2623 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2623) = 6561 * m + 1052 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2623
  rw [data_2623.1, data_2623.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2623 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2623) < 16384 * m + 2623 := by
  apply descent_of_endpoint
  · rw [data_2623.1]; exact data_2623.2.2
  · rw [data_2623.2.1]; decide

end Collatz.Research.DescentAtlas.Batch116
