import Collatz.Research.DescentAtlas.Core

/-! Batch 92: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch092
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 2061. -/
theorem data_2061 : oddCount 2061 14 = 5 ∧
    acceleratedOrbit 14 2061 = 31 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2061 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2061) = 243 * m + 31 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2061
  rw [data_2061.1, data_2061.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2061 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2061) < 16384 * m + 2061 := by
  apply descent_of_endpoint
  · rw [data_2061.1]; exact data_2061.2.2
  · rw [data_2061.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2063. -/
theorem data_2063 : oddCount 2063 14 = 6 ∧
    acceleratedOrbit 14 2063 = 92 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2063 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2063) = 729 * m + 92 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2063
  rw [data_2063.1, data_2063.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2063 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2063) < 16384 * m + 2063 := by
  apply descent_of_endpoint
  · rw [data_2063.1]; exact data_2063.2.2
  · rw [data_2063.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2065. -/
theorem data_2065 : oddCount 2065 14 = 5 ∧
    acceleratedOrbit 14 2065 = 31 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2065 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2065) = 243 * m + 31 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2065
  rw [data_2065.1, data_2065.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2065 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2065) < 16384 * m + 2065 := by
  apply descent_of_endpoint
  · rw [data_2065.1]; exact data_2065.2.2
  · rw [data_2065.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2067. -/
theorem data_2067 : oddCount 2067 14 = 8 ∧
    acceleratedOrbit 14 2067 = 830 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2067 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2067) = 6561 * m + 830 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2067
  rw [data_2067.1, data_2067.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2067 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2067) < 16384 * m + 2067 := by
  apply descent_of_endpoint
  · rw [data_2067.1]; exact data_2067.2.2
  · rw [data_2067.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2069. -/
theorem data_2069 : oddCount 2069 14 = 6 ∧
    acceleratedOrbit 14 2069 = 94 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2069 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2069) = 729 * m + 94 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2069
  rw [data_2069.1, data_2069.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2069 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2069) < 16384 * m + 2069 := by
  apply descent_of_endpoint
  · rw [data_2069.1]; exact data_2069.2.2
  · rw [data_2069.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2071. -/
theorem data_2071 : oddCount 2071 14 = 5 ∧
    acceleratedOrbit 14 2071 = 31 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2071 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2071) = 243 * m + 31 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2071
  rw [data_2071.1, data_2071.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2071 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2071) < 16384 * m + 2071 := by
  apply descent_of_endpoint
  · rw [data_2071.1]; exact data_2071.2.2
  · rw [data_2071.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2073. -/
theorem data_2073 : oddCount 2073 14 = 8 ∧
    acceleratedOrbit 14 2073 = 832 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2073 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2073) = 6561 * m + 832 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2073
  rw [data_2073.1, data_2073.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2073 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2073) < 16384 * m + 2073 := by
  apply descent_of_endpoint
  · rw [data_2073.1]; exact data_2073.2.2
  · rw [data_2073.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2077. -/
theorem data_2077 : oddCount 2077 14 = 8 ∧
    acceleratedOrbit 14 2077 = 836 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2077 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2077) = 6561 * m + 836 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2077
  rw [data_2077.1, data_2077.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2077 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2077) < 16384 * m + 2077 := by
  apply descent_of_endpoint
  · rw [data_2077.1]; exact data_2077.2.2
  · rw [data_2077.2.1]; decide

end Collatz.Research.DescentAtlas.Batch092
