import Collatz.Research.DescentAtlas.Core

/-! Batch 4: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch004
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 61. -/
theorem data_61 : oddCount 61 14 = 5 ∧
    acceleratedOrbit 14 61 = 1 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_61 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 61) = 243 * m + 1 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 61
  rw [data_61.1, data_61.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_61 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 61) < 16384 * m + 61 := by
  apply descent_of_endpoint
  · rw [data_61.1]; exact data_61.2.2
  · rw [data_61.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 65. -/
theorem data_65 : oddCount 65 14 = 7 ∧
    acceleratedOrbit 14 65 = 10 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_65 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 65) = 2187 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 65
  rw [data_65.1, data_65.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_65 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 65) < 16384 * m + 65 := by
  apply descent_of_endpoint
  · rw [data_65.1]; exact data_65.2.2
  · rw [data_65.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 67. -/
theorem data_67 : oddCount 67 14 = 7 ∧
    acceleratedOrbit 14 67 = 10 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_67 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 67) = 2187 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 67
  rw [data_67.1, data_67.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_67 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 67) < 16384 * m + 67 := by
  apply descent_of_endpoint
  · rw [data_67.1]; exact data_67.2.2
  · rw [data_67.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 69. -/
theorem data_69 : oddCount 69 14 = 5 ∧
    acceleratedOrbit 14 69 = 2 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_69 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 69) = 243 * m + 2 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 69
  rw [data_69.1, data_69.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_69 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 69) < 16384 * m + 69 := by
  apply descent_of_endpoint
  · rw [data_69.1]; exact data_69.2.2
  · rw [data_69.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 75. -/
theorem data_75 : oddCount 75 14 = 5 ∧
    acceleratedOrbit 14 75 = 2 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_75 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 75) = 243 * m + 2 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 75
  rw [data_75.1, data_75.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_75 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 75) < 16384 * m + 75 := by
  apply descent_of_endpoint
  · rw [data_75.1]; exact data_75.2.2
  · rw [data_75.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 77. -/
theorem data_77 : oddCount 77 14 = 6 ∧
    acceleratedOrbit 14 77 = 4 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_77 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 77) = 729 * m + 4 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 77
  rw [data_77.1, data_77.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_77 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 77) < 16384 * m + 77 := by
  apply descent_of_endpoint
  · rw [data_77.1]; exact data_77.2.2
  · rw [data_77.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 79. -/
theorem data_79 : oddCount 79 14 = 7 ∧
    acceleratedOrbit 14 79 = 11 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_79 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 79) = 2187 * m + 11 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 79
  rw [data_79.1, data_79.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_79 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 79) < 16384 * m + 79 := by
  apply descent_of_endpoint
  · rw [data_79.1]; exact data_79.2.2
  · rw [data_79.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 81. -/
theorem data_81 : oddCount 81 14 = 6 ∧
    acceleratedOrbit 14 81 = 4 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_81 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 81) = 729 * m + 4 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 81
  rw [data_81.1, data_81.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_81 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 81) < 16384 * m + 81 := by
  apply descent_of_endpoint
  · rw [data_81.1]; exact data_81.2.2
  · rw [data_81.2.1]; decide

end Collatz.Research.DescentAtlas.Batch004
