import Collatz.Research.DescentAtlas.Core

/-! Batch 236: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch236
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5291. -/
theorem data_5291 : oddCount 5291 14 = 6 ∧
    acceleratedOrbit 14 5291 = 236 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5291 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5291) = 729 * m + 236 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5291
  rw [data_5291.1, data_5291.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5291 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5291) < 16384 * m + 5291 := by
  apply descent_of_endpoint
  · rw [data_5291.1]; exact data_5291.2.2
  · rw [data_5291.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5293. -/
theorem data_5293 : oddCount 5293 14 = 6 ∧
    acceleratedOrbit 14 5293 = 236 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5293 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5293) = 729 * m + 236 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5293
  rw [data_5293.1, data_5293.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5293 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5293) < 16384 * m + 5293 := by
  apply descent_of_endpoint
  · rw [data_5293.1]; exact data_5293.2.2
  · rw [data_5293.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5295. -/
theorem data_5295 : oddCount 5295 14 = 7 ∧
    acceleratedOrbit 14 5295 = 707 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5295 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5295) = 2187 * m + 707 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5295
  rw [data_5295.1, data_5295.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5295 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5295) < 16384 * m + 5295 := by
  apply descent_of_endpoint
  · rw [data_5295.1]; exact data_5295.2.2
  · rw [data_5295.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5297. -/
theorem data_5297 : oddCount 5297 14 = 8 ∧
    acceleratedOrbit 14 5297 = 2126 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5297 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5297) = 6561 * m + 2126 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5297
  rw [data_5297.1, data_5297.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5297 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5297) < 16384 * m + 5297 := by
  apply descent_of_endpoint
  · rw [data_5297.1]; exact data_5297.2.2
  · rw [data_5297.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5299. -/
theorem data_5299 : oddCount 5299 14 = 8 ∧
    acceleratedOrbit 14 5299 = 2126 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5299 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5299) = 6561 * m + 2126 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5299
  rw [data_5299.1, data_5299.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5299 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5299) < 16384 * m + 5299 := by
  apply descent_of_endpoint
  · rw [data_5299.1]; exact data_5299.2.2
  · rw [data_5299.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5301. -/
theorem data_5301 : oddCount 5301 14 = 5 ∧
    acceleratedOrbit 14 5301 = 80 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5301 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5301) = 243 * m + 80 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5301
  rw [data_5301.1, data_5301.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5301 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5301) < 16384 * m + 5301 := by
  apply descent_of_endpoint
  · rw [data_5301.1]; exact data_5301.2.2
  · rw [data_5301.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5305. -/
theorem data_5305 : oddCount 5305 14 = 8 ∧
    acceleratedOrbit 14 5305 = 2126 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5305 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5305) = 6561 * m + 2126 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5305
  rw [data_5305.1, data_5305.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5305 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5305) < 16384 * m + 5305 := by
  apply descent_of_endpoint
  · rw [data_5305.1]; exact data_5305.2.2
  · rw [data_5305.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5309. -/
theorem data_5309 : oddCount 5309 14 = 8 ∧
    acceleratedOrbit 14 5309 = 2128 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5309 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5309) = 6561 * m + 2128 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5309
  rw [data_5309.1, data_5309.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5309 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5309) < 16384 * m + 5309 := by
  apply descent_of_endpoint
  · rw [data_5309.1]; exact data_5309.2.2
  · rw [data_5309.2.1]; decide

end Collatz.Research.DescentAtlas.Batch236
