import Collatz.Research.DescentAtlas.Core

/-! Batch 234: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch234
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5245. -/
theorem data_5245 : oddCount 5245 14 = 7 ∧
    acceleratedOrbit 14 5245 = 701 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5245 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5245) = 2187 * m + 701 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5245
  rw [data_5245.1, data_5245.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5245 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5245) < 16384 * m + 5245 := by
  apply descent_of_endpoint
  · rw [data_5245.1]; exact data_5245.2.2
  · rw [data_5245.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5251. -/
theorem data_5251 : oddCount 5251 14 = 4 ∧
    acceleratedOrbit 14 5251 = 26 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5251 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5251) = 81 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5251
  rw [data_5251.1, data_5251.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5251 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5251) < 16384 * m + 5251 := by
  apply descent_of_endpoint
  · rw [data_5251.1]; exact data_5251.2.2
  · rw [data_5251.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5253. -/
theorem data_5253 : oddCount 5253 14 = 4 ∧
    acceleratedOrbit 14 5253 = 26 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5253 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5253) = 81 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5253
  rw [data_5253.1, data_5253.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5253 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5253) < 16384 * m + 5253 := by
  apply descent_of_endpoint
  · rw [data_5253.1]; exact data_5253.2.2
  · rw [data_5253.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5259. -/
theorem data_5259 : oddCount 5259 14 = 8 ∧
    acceleratedOrbit 14 5259 = 2108 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5259 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5259) = 6561 * m + 2108 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5259
  rw [data_5259.1, data_5259.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5259 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5259) < 16384 * m + 5259 := by
  apply descent_of_endpoint
  · rw [data_5259.1]; exact data_5259.2.2
  · rw [data_5259.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5261. -/
theorem data_5261 : oddCount 5261 14 = 6 ∧
    acceleratedOrbit 14 5261 = 236 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5261 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5261) = 729 * m + 236 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5261
  rw [data_5261.1, data_5261.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5261 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5261) < 16384 * m + 5261 := by
  apply descent_of_endpoint
  · rw [data_5261.1]; exact data_5261.2.2
  · rw [data_5261.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5263. -/
theorem data_5263 : oddCount 5263 14 = 7 ∧
    acceleratedOrbit 14 5263 = 703 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5263 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5263) = 2187 * m + 703 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5263
  rw [data_5263.1, data_5263.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5263 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5263) < 16384 * m + 5263 := by
  apply descent_of_endpoint
  · rw [data_5263.1]; exact data_5263.2.2
  · rw [data_5263.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5265. -/
theorem data_5265 : oddCount 5265 14 = 7 ∧
    acceleratedOrbit 14 5265 = 704 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5265 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5265) = 2187 * m + 704 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5265
  rw [data_5265.1, data_5265.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5265 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5265) < 16384 * m + 5265 := by
  apply descent_of_endpoint
  · rw [data_5265.1]; exact data_5265.2.2
  · rw [data_5265.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5267. -/
theorem data_5267 : oddCount 5267 14 = 7 ∧
    acceleratedOrbit 14 5267 = 704 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5267 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5267) = 2187 * m + 704 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5267
  rw [data_5267.1, data_5267.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5267 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5267) < 16384 * m + 5267 := by
  apply descent_of_endpoint
  · rw [data_5267.1]; exact data_5267.2.2
  · rw [data_5267.2.1]; decide

end Collatz.Research.DescentAtlas.Batch234
