import Collatz.Research.DescentAtlas.Core

/-! Batch 89: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch089
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1989. -/
theorem data_1989 : oddCount 1989 14 = 4 ∧
    acceleratedOrbit 14 1989 = 10 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1989 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1989) = 81 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1989
  rw [data_1989.1, data_1989.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1989 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1989) < 16384 * m + 1989 := by
  apply descent_of_endpoint
  · rw [data_1989.1]; exact data_1989.2.2
  · rw [data_1989.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1991. -/
theorem data_1991 : oddCount 1991 14 = 7 ∧
    acceleratedOrbit 14 1991 = 266 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1991 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1991) = 2187 * m + 266 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1991
  rw [data_1991.1, data_1991.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1991 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1991) < 16384 * m + 1991 := by
  apply descent_of_endpoint
  · rw [data_1991.1]; exact data_1991.2.2
  · rw [data_1991.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1993. -/
theorem data_1993 : oddCount 1993 14 = 8 ∧
    acceleratedOrbit 14 1993 = 800 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1993 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1993) = 6561 * m + 800 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1993
  rw [data_1993.1, data_1993.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1993 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1993) < 16384 * m + 1993 := by
  apply descent_of_endpoint
  · rw [data_1993.1]; exact data_1993.2.2
  · rw [data_1993.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1995. -/
theorem data_1995 : oddCount 1995 14 = 7 ∧
    acceleratedOrbit 14 1995 = 269 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1995 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1995) = 2187 * m + 269 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1995
  rw [data_1995.1, data_1995.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1995 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1995) < 16384 * m + 1995 := by
  apply descent_of_endpoint
  · rw [data_1995.1]; exact data_1995.2.2
  · rw [data_1995.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1997. -/
theorem data_1997 : oddCount 1997 14 = 7 ∧
    acceleratedOrbit 14 1997 = 269 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1997 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1997) = 2187 * m + 269 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1997
  rw [data_1997.1, data_1997.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1997 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1997) < 16384 * m + 1997 := by
  apply descent_of_endpoint
  · rw [data_1997.1]; exact data_1997.2.2
  · rw [data_1997.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1999. -/
theorem data_1999 : oddCount 1999 14 = 6 ∧
    acceleratedOrbit 14 1999 = 89 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1999 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1999) = 729 * m + 89 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1999
  rw [data_1999.1, data_1999.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1999 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1999) < 16384 * m + 1999 := by
  apply descent_of_endpoint
  · rw [data_1999.1]; exact data_1999.2.2
  · rw [data_1999.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2001. -/
theorem data_2001 : oddCount 2001 14 = 7 ∧
    acceleratedOrbit 14 2001 = 269 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2001 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2001) = 2187 * m + 269 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2001
  rw [data_2001.1, data_2001.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2001 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2001) < 16384 * m + 2001 := by
  apply descent_of_endpoint
  · rw [data_2001.1]; exact data_2001.2.2
  · rw [data_2001.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2005. -/
theorem data_2005 : oddCount 2005 14 = 6 ∧
    acceleratedOrbit 14 2005 = 91 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2005 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2005) = 729 * m + 91 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2005
  rw [data_2005.1, data_2005.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2005 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2005) < 16384 * m + 2005 := by
  apply descent_of_endpoint
  · rw [data_2005.1]; exact data_2005.2.2
  · rw [data_2005.2.1]; decide

end Collatz.Research.DescentAtlas.Batch089
