import Collatz.Research.DescentAtlas.Core

/-! Batch 188: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch188
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 4209. -/
theorem data_4209 : oddCount 4209 14 = 3 ∧
    acceleratedOrbit 14 4209 = 7 ∧ 27 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4209 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4209) = 27 * m + 7 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4209
  rw [data_4209.1, data_4209.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4209 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4209) < 16384 * m + 4209 := by
  apply descent_of_endpoint
  · rw [data_4209.1]; exact data_4209.2.2
  · rw [data_4209.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4211. -/
theorem data_4211 : oddCount 4211 14 = 6 ∧
    acceleratedOrbit 14 4211 = 188 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4211 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4211) = 729 * m + 188 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4211
  rw [data_4211.1, data_4211.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4211 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4211) < 16384 * m + 4211 := by
  apply descent_of_endpoint
  · rw [data_4211.1]; exact data_4211.2.2
  · rw [data_4211.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4213. -/
theorem data_4213 : oddCount 4213 14 = 7 ∧
    acceleratedOrbit 14 4213 = 566 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4213 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4213) = 2187 * m + 566 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4213
  rw [data_4213.1, data_4213.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4213 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4213) < 16384 * m + 4213 := by
  apply descent_of_endpoint
  · rw [data_4213.1]; exact data_4213.2.2
  · rw [data_4213.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4215. -/
theorem data_4215 : oddCount 4215 14 = 8 ∧
    acceleratedOrbit 14 4215 = 1691 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4215 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4215) = 6561 * m + 1691 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4215
  rw [data_4215.1, data_4215.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4215 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4215) < 16384 * m + 4215 := by
  apply descent_of_endpoint
  · rw [data_4215.1]; exact data_4215.2.2
  · rw [data_4215.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4219. -/
theorem data_4219 : oddCount 4219 14 = 8 ∧
    acceleratedOrbit 14 4219 = 1691 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4219 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4219) = 6561 * m + 1691 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4219
  rw [data_4219.1, data_4219.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4219 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4219) < 16384 * m + 4219 := by
  apply descent_of_endpoint
  · rw [data_4219.1]; exact data_4219.2.2
  · rw [data_4219.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4225. -/
theorem data_4225 : oddCount 4225 14 = 8 ∧
    acceleratedOrbit 14 4225 = 1694 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4225 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4225) = 6561 * m + 1694 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4225
  rw [data_4225.1, data_4225.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4225 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4225) < 16384 * m + 4225 := by
  apply descent_of_endpoint
  · rw [data_4225.1]; exact data_4225.2.2
  · rw [data_4225.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4227. -/
theorem data_4227 : oddCount 4227 14 = 8 ∧
    acceleratedOrbit 14 4227 = 1700 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4227 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4227) = 6561 * m + 1700 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4227
  rw [data_4227.1, data_4227.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4227 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4227) < 16384 * m + 4227 := by
  apply descent_of_endpoint
  · rw [data_4227.1]; exact data_4227.2.2
  · rw [data_4227.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4229. -/
theorem data_4229 : oddCount 4229 14 = 8 ∧
    acceleratedOrbit 14 4229 = 1700 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4229 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4229) = 6561 * m + 1700 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4229
  rw [data_4229.1, data_4229.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4229 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4229) < 16384 * m + 4229 := by
  apply descent_of_endpoint
  · rw [data_4229.1]; exact data_4229.2.2
  · rw [data_4229.2.1]; decide

end Collatz.Research.DescentAtlas.Batch188
