import Collatz.Research.DescentAtlas.Core

/-! Batch 31: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch031
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 697. -/
theorem data_697 : oddCount 697 14 = 7 ∧
    acceleratedOrbit 14 697 = 94 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_697 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 697) = 2187 * m + 94 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 697
  rw [data_697.1, data_697.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_697 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 697) < 16384 * m + 697 := by
  apply descent_of_endpoint
  · rw [data_697.1]; exact data_697.2.2
  · rw [data_697.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 699. -/
theorem data_699 : oddCount 699 14 = 8 ∧
    acceleratedOrbit 14 699 = 281 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_699 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 699) = 6561 * m + 281 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 699
  rw [data_699.1, data_699.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_699 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 699) < 16384 * m + 699 := by
  apply descent_of_endpoint
  · rw [data_699.1]; exact data_699.2.2
  · rw [data_699.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 701. -/
theorem data_701 : oddCount 701 14 = 8 ∧
    acceleratedOrbit 14 701 = 283 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_701 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 701) = 6561 * m + 283 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 701
  rw [data_701.1, data_701.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_701 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 701) < 16384 * m + 701 := by
  apply descent_of_endpoint
  · rw [data_701.1]; exact data_701.2.2
  · rw [data_701.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 705. -/
theorem data_705 : oddCount 705 14 = 5 ∧
    acceleratedOrbit 14 705 = 11 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_705 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 705) = 243 * m + 11 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 705
  rw [data_705.1, data_705.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_705 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 705) < 16384 * m + 705 := by
  apply descent_of_endpoint
  · rw [data_705.1]; exact data_705.2.2
  · rw [data_705.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 707. -/
theorem data_707 : oddCount 707 14 = 7 ∧
    acceleratedOrbit 14 707 = 95 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_707 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 707) = 2187 * m + 95 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 707
  rw [data_707.1, data_707.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_707 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 707) < 16384 * m + 707 := by
  apply descent_of_endpoint
  · rw [data_707.1]; exact data_707.2.2
  · rw [data_707.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 709. -/
theorem data_709 : oddCount 709 14 = 5 ∧
    acceleratedOrbit 14 709 = 11 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_709 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 709) = 243 * m + 11 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 709
  rw [data_709.1, data_709.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_709 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 709) < 16384 * m + 709 := by
  apply descent_of_endpoint
  · rw [data_709.1]; exact data_709.2.2
  · rw [data_709.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 711. -/
theorem data_711 : oddCount 711 14 = 8 ∧
    acceleratedOrbit 14 711 = 287 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_711 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 711) = 6561 * m + 287 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 711
  rw [data_711.1, data_711.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_711 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 711) < 16384 * m + 711 := by
  apply descent_of_endpoint
  · rw [data_711.1]; exact data_711.2.2
  · rw [data_711.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 713. -/
theorem data_713 : oddCount 713 14 = 6 ∧
    acceleratedOrbit 14 713 = 32 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_713 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 713) = 729 * m + 32 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 713
  rw [data_713.1, data_713.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_713 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 713) < 16384 * m + 713 := by
  apply descent_of_endpoint
  · rw [data_713.1]; exact data_713.2.2
  · rw [data_713.2.1]; decide

end Collatz.Research.DescentAtlas.Batch031
