import Collatz.Research.DescentAtlas.Core

/-! Batch 146: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch146
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 3271. -/
theorem data_3271 : oddCount 3271 14 = 7 ∧
    acceleratedOrbit 14 3271 = 437 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3271 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3271) = 2187 * m + 437 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3271
  rw [data_3271.1, data_3271.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3271 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3271) < 16384 * m + 3271 := by
  apply descent_of_endpoint
  · rw [data_3271.1]; exact data_3271.2.2
  · rw [data_3271.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3273. -/
theorem data_3273 : oddCount 3273 14 = 6 ∧
    acceleratedOrbit 14 3273 = 146 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3273 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3273) = 729 * m + 146 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3273
  rw [data_3273.1, data_3273.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3273 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3273) < 16384 * m + 3273 := by
  apply descent_of_endpoint
  · rw [data_3273.1]; exact data_3273.2.2
  · rw [data_3273.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3275. -/
theorem data_3275 : oddCount 3275 14 = 6 ∧
    acceleratedOrbit 14 3275 = 146 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3275 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3275) = 729 * m + 146 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3275
  rw [data_3275.1, data_3275.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3275 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3275) < 16384 * m + 3275 := by
  apply descent_of_endpoint
  · rw [data_3275.1]; exact data_3275.2.2
  · rw [data_3275.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3277. -/
theorem data_3277 : oddCount 3277 14 = 5 ∧
    acceleratedOrbit 14 3277 = 49 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3277 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3277) = 243 * m + 49 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3277
  rw [data_3277.1, data_3277.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3277 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3277) < 16384 * m + 3277 := by
  apply descent_of_endpoint
  · rw [data_3277.1]; exact data_3277.2.2
  · rw [data_3277.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3281. -/
theorem data_3281 : oddCount 3281 14 = 8 ∧
    acceleratedOrbit 14 3281 = 1316 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3281 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3281) = 6561 * m + 1316 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3281
  rw [data_3281.1, data_3281.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3281 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3281) < 16384 * m + 3281 := by
  apply descent_of_endpoint
  · rw [data_3281.1]; exact data_3281.2.2
  · rw [data_3281.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3283. -/
theorem data_3283 : oddCount 3283 14 = 8 ∧
    acceleratedOrbit 14 3283 = 1316 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3283 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3283) = 6561 * m + 1316 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3283
  rw [data_3283.1, data_3283.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3283 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3283) < 16384 * m + 3283 := by
  apply descent_of_endpoint
  · rw [data_3283.1]; exact data_3283.2.2
  · rw [data_3283.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3285. -/
theorem data_3285 : oddCount 3285 14 = 4 ∧
    acceleratedOrbit 14 3285 = 17 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3285 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3285) = 81 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3285
  rw [data_3285.1, data_3285.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3285 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3285) < 16384 * m + 3285 := by
  apply descent_of_endpoint
  · rw [data_3285.1]; exact data_3285.2.2
  · rw [data_3285.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3287. -/
theorem data_3287 : oddCount 3287 14 = 8 ∧
    acceleratedOrbit 14 3287 = 1318 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3287 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3287) = 6561 * m + 1318 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3287
  rw [data_3287.1, data_3287.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3287 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3287) < 16384 * m + 3287 := by
  apply descent_of_endpoint
  · rw [data_3287.1]; exact data_3287.2.2
  · rw [data_3287.2.1]; decide

end Collatz.Research.DescentAtlas.Batch146
