import Collatz.Research.DescentAtlas.Core

/-! Batch 108: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch108
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 2429. -/
theorem data_2429 : oddCount 2429 14 = 7 ∧
    acceleratedOrbit 14 2429 = 325 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2429 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2429) = 2187 * m + 325 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2429
  rw [data_2429.1, data_2429.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2429 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2429) < 16384 * m + 2429 := by
  apply descent_of_endpoint
  · rw [data_2429.1]; exact data_2429.2.2
  · rw [data_2429.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2431. -/
theorem data_2431 : oddCount 2431 14 = 8 ∧
    acceleratedOrbit 14 2431 = 974 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2431 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2431) = 6561 * m + 974 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2431
  rw [data_2431.1, data_2431.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2431 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2431) < 16384 * m + 2431 := by
  apply descent_of_endpoint
  · rw [data_2431.1]; exact data_2431.2.2
  · rw [data_2431.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2433. -/
theorem data_2433 : oddCount 2433 14 = 7 ∧
    acceleratedOrbit 14 2433 = 326 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2433 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2433) = 2187 * m + 326 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2433
  rw [data_2433.1, data_2433.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2433 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2433) < 16384 * m + 2433 := by
  apply descent_of_endpoint
  · rw [data_2433.1]; exact data_2433.2.2
  · rw [data_2433.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2435. -/
theorem data_2435 : oddCount 2435 14 = 6 ∧
    acceleratedOrbit 14 2435 = 109 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2435 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2435) = 729 * m + 109 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2435
  rw [data_2435.1, data_2435.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2435 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2435) < 16384 * m + 2435 := by
  apply descent_of_endpoint
  · rw [data_2435.1]; exact data_2435.2.2
  · rw [data_2435.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2437. -/
theorem data_2437 : oddCount 2437 14 = 6 ∧
    acceleratedOrbit 14 2437 = 109 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2437 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2437) = 729 * m + 109 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2437
  rw [data_2437.1, data_2437.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2437 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2437) < 16384 * m + 2437 := by
  apply descent_of_endpoint
  · rw [data_2437.1]; exact data_2437.2.2
  · rw [data_2437.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2439. -/
theorem data_2439 : oddCount 2439 14 = 6 ∧
    acceleratedOrbit 14 2439 = 109 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2439 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2439) = 729 * m + 109 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2439
  rw [data_2439.1, data_2439.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2439 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2439) < 16384 * m + 2439 := by
  apply descent_of_endpoint
  · rw [data_2439.1]; exact data_2439.2.2
  · rw [data_2439.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2443. -/
theorem data_2443 : oddCount 2443 14 = 8 ∧
    acceleratedOrbit 14 2443 = 980 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2443 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2443) = 6561 * m + 980 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2443
  rw [data_2443.1, data_2443.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2443 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2443) < 16384 * m + 2443 := by
  apply descent_of_endpoint
  · rw [data_2443.1]; exact data_2443.2.2
  · rw [data_2443.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2445. -/
theorem data_2445 : oddCount 2445 14 = 5 ∧
    acceleratedOrbit 14 2445 = 37 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2445 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2445) = 243 * m + 37 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2445
  rw [data_2445.1, data_2445.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2445 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2445) < 16384 * m + 2445 := by
  apply descent_of_endpoint
  · rw [data_2445.1]; exact data_2445.2.2
  · rw [data_2445.2.1]; decide

end Collatz.Research.DescentAtlas.Batch108
