import Collatz.Research.DescentAtlas.Core

/-! Batch 80: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch080
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1777. -/
theorem data_1777 : oddCount 1777 14 = 7 ∧
    acceleratedOrbit 14 1777 = 242 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1777 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1777) = 2187 * m + 242 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1777
  rw [data_1777.1, data_1777.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1777 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1777) < 16384 * m + 1777 := by
  apply descent_of_endpoint
  · rw [data_1777.1]; exact data_1777.2.2
  · rw [data_1777.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1781. -/
theorem data_1781 : oddCount 1781 14 = 8 ∧
    acceleratedOrbit 14 1781 = 719 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1781 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1781) = 6561 * m + 719 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1781
  rw [data_1781.1, data_1781.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1781 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1781) < 16384 * m + 1781 := by
  apply descent_of_endpoint
  · rw [data_1781.1]; exact data_1781.2.2
  · rw [data_1781.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1785. -/
theorem data_1785 : oddCount 1785 14 = 6 ∧
    acceleratedOrbit 14 1785 = 80 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1785 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1785) = 729 * m + 80 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1785
  rw [data_1785.1, data_1785.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1785 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1785) < 16384 * m + 1785 := by
  apply descent_of_endpoint
  · rw [data_1785.1]; exact data_1785.2.2
  · rw [data_1785.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1793. -/
theorem data_1793 : oddCount 1793 14 = 7 ∧
    acceleratedOrbit 14 1793 = 242 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1793 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1793) = 2187 * m + 242 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1793
  rw [data_1793.1, data_1793.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1793 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1793) < 16384 * m + 1793 := by
  apply descent_of_endpoint
  · rw [data_1793.1]; exact data_1793.2.2
  · rw [data_1793.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1795. -/
theorem data_1795 : oddCount 1795 14 = 8 ∧
    acceleratedOrbit 14 1795 = 722 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1795 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1795) = 6561 * m + 722 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1795
  rw [data_1795.1, data_1795.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1795 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1795) < 16384 * m + 1795 := by
  apply descent_of_endpoint
  · rw [data_1795.1]; exact data_1795.2.2
  · rw [data_1795.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1797. -/
theorem data_1797 : oddCount 1797 14 = 8 ∧
    acceleratedOrbit 14 1797 = 728 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1797 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1797) = 6561 * m + 728 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1797
  rw [data_1797.1, data_1797.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1797 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1797) < 16384 * m + 1797 := by
  apply descent_of_endpoint
  · rw [data_1797.1]; exact data_1797.2.2
  · rw [data_1797.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1799. -/
theorem data_1799 : oddCount 1799 14 = 8 ∧
    acceleratedOrbit 14 1799 = 722 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1799 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1799) = 6561 * m + 722 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1799
  rw [data_1799.1, data_1799.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1799 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1799) < 16384 * m + 1799 := by
  apply descent_of_endpoint
  · rw [data_1799.1]; exact data_1799.2.2
  · rw [data_1799.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1803. -/
theorem data_1803 : oddCount 1803 14 = 8 ∧
    acceleratedOrbit 14 1803 = 724 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1803 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1803) = 6561 * m + 724 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1803
  rw [data_1803.1, data_1803.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1803 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1803) < 16384 * m + 1803 := by
  apply descent_of_endpoint
  · rw [data_1803.1]; exact data_1803.2.2
  · rw [data_1803.2.1]; decide

end Collatz.Research.DescentAtlas.Batch080
