import Collatz.Research.DescentAtlas.Core

/-! Batch 257: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch257
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5771. -/
theorem data_5771 : oddCount 5771 14 = 6 ∧
    acceleratedOrbit 14 5771 = 257 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5771 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5771) = 729 * m + 257 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5771
  rw [data_5771.1, data_5771.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5771 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5771) < 16384 * m + 5771 := by
  apply descent_of_endpoint
  · rw [data_5771.1]; exact data_5771.2.2
  · rw [data_5771.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5773. -/
theorem data_5773 : oddCount 5773 14 = 5 ∧
    acceleratedOrbit 14 5773 = 86 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5773 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5773) = 243 * m + 86 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5773
  rw [data_5773.1, data_5773.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5773 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5773) < 16384 * m + 5773 := by
  apply descent_of_endpoint
  · rw [data_5773.1]; exact data_5773.2.2
  · rw [data_5773.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5777. -/
theorem data_5777 : oddCount 5777 14 = 7 ∧
    acceleratedOrbit 14 5777 = 773 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5777 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5777) = 2187 * m + 773 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5777
  rw [data_5777.1, data_5777.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5777 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5777) < 16384 * m + 5777 := by
  apply descent_of_endpoint
  · rw [data_5777.1]; exact data_5777.2.2
  · rw [data_5777.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5779. -/
theorem data_5779 : oddCount 5779 14 = 7 ∧
    acceleratedOrbit 14 5779 = 773 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5779 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5779) = 2187 * m + 773 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5779
  rw [data_5779.1, data_5779.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5779 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5779) < 16384 * m + 5779 := by
  apply descent_of_endpoint
  · rw [data_5779.1]; exact data_5779.2.2
  · rw [data_5779.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5781. -/
theorem data_5781 : oddCount 5781 14 = 5 ∧
    acceleratedOrbit 14 5781 = 86 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5781 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5781) = 243 * m + 86 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5781
  rw [data_5781.1, data_5781.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5781 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5781) < 16384 * m + 5781 := by
  apply descent_of_endpoint
  · rw [data_5781.1]; exact data_5781.2.2
  · rw [data_5781.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5783. -/
theorem data_5783 : oddCount 5783 14 = 5 ∧
    acceleratedOrbit 14 5783 = 86 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5783 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5783) = 243 * m + 86 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5783
  rw [data_5783.1, data_5783.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5783 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5783) < 16384 * m + 5783 := by
  apply descent_of_endpoint
  · rw [data_5783.1]; exact data_5783.2.2
  · rw [data_5783.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5787. -/
theorem data_5787 : oddCount 5787 14 = 8 ∧
    acceleratedOrbit 14 5787 = 2318 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5787 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5787) = 6561 * m + 2318 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5787
  rw [data_5787.1, data_5787.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5787 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5787) < 16384 * m + 5787 := by
  apply descent_of_endpoint
  · rw [data_5787.1]; exact data_5787.2.2
  · rw [data_5787.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5789. -/
theorem data_5789 : oddCount 5789 14 = 8 ∧
    acceleratedOrbit 14 5789 = 2321 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5789 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5789) = 6561 * m + 2321 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5789
  rw [data_5789.1, data_5789.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5789 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5789) < 16384 * m + 5789 := by
  apply descent_of_endpoint
  · rw [data_5789.1]; exact data_5789.2.2
  · rw [data_5789.2.1]; decide

end Collatz.Research.DescentAtlas.Batch257
