import Collatz.Research.DescentAtlas.Core

/-! Batch 227: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch227
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5095. -/
theorem data_5095 : oddCount 5095 14 = 8 ∧
    acceleratedOrbit 14 5095 = 2042 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5095 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5095) = 6561 * m + 2042 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5095
  rw [data_5095.1, data_5095.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5095 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5095) < 16384 * m + 5095 := by
  apply descent_of_endpoint
  · rw [data_5095.1]; exact data_5095.2.2
  · rw [data_5095.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5101. -/
theorem data_5101 : oddCount 5101 14 = 8 ∧
    acceleratedOrbit 14 5101 = 2045 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5101 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5101) = 6561 * m + 2045 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5101
  rw [data_5101.1, data_5101.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5101 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5101) < 16384 * m + 5101 := by
  apply descent_of_endpoint
  · rw [data_5101.1]; exact data_5101.2.2
  · rw [data_5101.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5103. -/
theorem data_5103 : oddCount 5103 14 = 8 ∧
    acceleratedOrbit 14 5103 = 2044 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5103 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5103) = 6561 * m + 2044 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5103
  rw [data_5103.1, data_5103.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5103 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5103) < 16384 * m + 5103 := by
  apply descent_of_endpoint
  · rw [data_5103.1]; exact data_5103.2.2
  · rw [data_5103.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5105. -/
theorem data_5105 : oddCount 5105 14 = 8 ∧
    acceleratedOrbit 14 5105 = 2051 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5105 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5105) = 6561 * m + 2051 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5105
  rw [data_5105.1, data_5105.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5105 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5105) < 16384 * m + 5105 := by
  apply descent_of_endpoint
  · rw [data_5105.1]; exact data_5105.2.2
  · rw [data_5105.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5107. -/
theorem data_5107 : oddCount 5107 14 = 8 ∧
    acceleratedOrbit 14 5107 = 2047 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5107 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5107) = 6561 * m + 2047 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5107
  rw [data_5107.1, data_5107.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5107 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5107) < 16384 * m + 5107 := by
  apply descent_of_endpoint
  · rw [data_5107.1]; exact data_5107.2.2
  · rw [data_5107.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5109. -/
theorem data_5109 : oddCount 5109 14 = 8 ∧
    acceleratedOrbit 14 5109 = 2051 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5109 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5109) = 6561 * m + 2051 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5109
  rw [data_5109.1, data_5109.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5109 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5109) < 16384 * m + 5109 := by
  apply descent_of_endpoint
  · rw [data_5109.1]; exact data_5109.2.2
  · rw [data_5109.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5111. -/
theorem data_5111 : oddCount 5111 14 = 7 ∧
    acceleratedOrbit 14 5111 = 683 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5111 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5111) = 2187 * m + 683 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5111
  rw [data_5111.1, data_5111.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5111 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5111) < 16384 * m + 5111 := by
  apply descent_of_endpoint
  · rw [data_5111.1]; exact data_5111.2.2
  · rw [data_5111.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5115. -/
theorem data_5115 : oddCount 5115 14 = 7 ∧
    acceleratedOrbit 14 5115 = 683 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5115 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5115) = 2187 * m + 683 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5115
  rw [data_5115.1, data_5115.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5115 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5115) < 16384 * m + 5115 := by
  apply descent_of_endpoint
  · rw [data_5115.1]; exact data_5115.2.2
  · rw [data_5115.2.1]; decide

end Collatz.Research.DescentAtlas.Batch227
