import Collatz.Research.DescentAtlas.Core

/-! Batch 264: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch264
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5925. -/
theorem data_5925 : oddCount 5925 14 = 5 ∧
    acceleratedOrbit 14 5925 = 88 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5925 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5925) = 243 * m + 88 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5925
  rw [data_5925.1, data_5925.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5925 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5925) < 16384 * m + 5925 := by
  apply descent_of_endpoint
  · rw [data_5925.1]; exact data_5925.2.2
  · rw [data_5925.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5931. -/
theorem data_5931 : oddCount 5931 14 = 5 ∧
    acceleratedOrbit 14 5931 = 88 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5931 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5931) = 243 * m + 88 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5931
  rw [data_5931.1, data_5931.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5931 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5931) < 16384 * m + 5931 := by
  apply descent_of_endpoint
  · rw [data_5931.1]; exact data_5931.2.2
  · rw [data_5931.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5933. -/
theorem data_5933 : oddCount 5933 14 = 6 ∧
    acceleratedOrbit 14 5933 = 265 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5933 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5933) = 729 * m + 265 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5933
  rw [data_5933.1, data_5933.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5933 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5933) < 16384 * m + 5933 := by
  apply descent_of_endpoint
  · rw [data_5933.1]; exact data_5933.2.2
  · rw [data_5933.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5935. -/
theorem data_5935 : oddCount 5935 14 = 8 ∧
    acceleratedOrbit 14 5935 = 2378 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5935 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5935) = 6561 * m + 2378 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5935
  rw [data_5935.1, data_5935.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5935 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5935) < 16384 * m + 5935 := by
  apply descent_of_endpoint
  · rw [data_5935.1]; exact data_5935.2.2
  · rw [data_5935.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5937. -/
theorem data_5937 : oddCount 5937 14 = 6 ∧
    acceleratedOrbit 14 5937 = 265 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5937 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5937) = 729 * m + 265 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5937
  rw [data_5937.1, data_5937.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5937 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5937) < 16384 * m + 5937 := by
  apply descent_of_endpoint
  · rw [data_5937.1]; exact data_5937.2.2
  · rw [data_5937.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5939. -/
theorem data_5939 : oddCount 5939 14 = 6 ∧
    acceleratedOrbit 14 5939 = 265 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5939 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5939) = 729 * m + 265 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5939
  rw [data_5939.1, data_5939.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5939 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5939) < 16384 * m + 5939 := by
  apply descent_of_endpoint
  · rw [data_5939.1]; exact data_5939.2.2
  · rw [data_5939.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5941. -/
theorem data_5941 : oddCount 5941 14 = 5 ∧
    acceleratedOrbit 14 5941 = 89 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5941 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5941) = 243 * m + 89 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5941
  rw [data_5941.1, data_5941.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5941 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5941) < 16384 * m + 5941 := by
  apply descent_of_endpoint
  · rw [data_5941.1]; exact data_5941.2.2
  · rw [data_5941.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5943. -/
theorem data_5943 : oddCount 5943 14 = 7 ∧
    acceleratedOrbit 14 5943 = 794 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5943 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5943) = 2187 * m + 794 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5943
  rw [data_5943.1, data_5943.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5943 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5943) < 16384 * m + 5943 := by
  apply descent_of_endpoint
  · rw [data_5943.1]; exact data_5943.2.2
  · rw [data_5943.2.1]; decide

end Collatz.Research.DescentAtlas.Batch264
