import Collatz.Research.DescentAtlas.Core

/-! Batch 229: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch229
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5137. -/
theorem data_5137 : oddCount 5137 14 = 7 ∧
    acceleratedOrbit 14 5137 = 688 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5137 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5137) = 2187 * m + 688 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5137
  rw [data_5137.1, data_5137.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5137 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5137) < 16384 * m + 5137 := by
  apply descent_of_endpoint
  · rw [data_5137.1]; exact data_5137.2.2
  · rw [data_5137.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5139. -/
theorem data_5139 : oddCount 5139 14 = 6 ∧
    acceleratedOrbit 14 5139 = 229 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5139 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5139) = 729 * m + 229 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5139
  rw [data_5139.1, data_5139.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5139 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5139) < 16384 * m + 5139 := by
  apply descent_of_endpoint
  · rw [data_5139.1]; exact data_5139.2.2
  · rw [data_5139.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5141. -/
theorem data_5141 : oddCount 5141 14 = 4 ∧
    acceleratedOrbit 14 5141 = 26 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5141 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5141) = 81 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5141
  rw [data_5141.1, data_5141.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5141 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5141) < 16384 * m + 5141 := by
  apply descent_of_endpoint
  · rw [data_5141.1]; exact data_5141.2.2
  · rw [data_5141.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5143. -/
theorem data_5143 : oddCount 5143 14 = 7 ∧
    acceleratedOrbit 14 5143 = 688 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5143 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5143) = 2187 * m + 688 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5143
  rw [data_5143.1, data_5143.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5143 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5143) < 16384 * m + 5143 := by
  apply descent_of_endpoint
  · rw [data_5143.1]; exact data_5143.2.2
  · rw [data_5143.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5145. -/
theorem data_5145 : oddCount 5145 14 = 8 ∧
    acceleratedOrbit 14 5145 = 2062 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5145 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5145) = 6561 * m + 2062 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5145
  rw [data_5145.1, data_5145.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5145 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5145) < 16384 * m + 5145 := by
  apply descent_of_endpoint
  · rw [data_5145.1]; exact data_5145.2.2
  · rw [data_5145.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5149. -/
theorem data_5149 : oddCount 5149 14 = 8 ∧
    acceleratedOrbit 14 5149 = 2065 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5149 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5149) = 6561 * m + 2065 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5149
  rw [data_5149.1, data_5149.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5149 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5149) < 16384 * m + 5149 := by
  apply descent_of_endpoint
  · rw [data_5149.1]; exact data_5149.2.2
  · rw [data_5149.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5155. -/
theorem data_5155 : oddCount 5155 14 = 4 ∧
    acceleratedOrbit 14 5155 = 26 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5155 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5155) = 81 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5155
  rw [data_5155.1, data_5155.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5155 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5155) < 16384 * m + 5155 := by
  apply descent_of_endpoint
  · rw [data_5155.1]; exact data_5155.2.2
  · rw [data_5155.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5157. -/
theorem data_5157 : oddCount 5157 14 = 8 ∧
    acceleratedOrbit 14 5157 = 2069 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5157 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5157) = 6561 * m + 2069 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5157
  rw [data_5157.1, data_5157.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5157 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5157) < 16384 * m + 5157 := by
  apply descent_of_endpoint
  · rw [data_5157.1]; exact data_5157.2.2
  · rw [data_5157.2.1]; decide

end Collatz.Research.DescentAtlas.Batch229
