import Collatz.Research.DescentAtlas.Core

/-! Batch 275: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch275
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 6163. -/
theorem data_6163 : oddCount 6163 14 = 8 ∧
    acceleratedOrbit 14 6163 = 2470 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6163 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6163) = 6561 * m + 2470 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6163
  rw [data_6163.1, data_6163.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6163 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6163) < 16384 * m + 6163 := by
  apply descent_of_endpoint
  · rw [data_6163.1]; exact data_6163.2.2
  · rw [data_6163.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6165. -/
theorem data_6165 : oddCount 6165 14 = 5 ∧
    acceleratedOrbit 14 6165 = 92 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6165 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6165) = 243 * m + 92 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6165
  rw [data_6165.1, data_6165.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6165 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6165) < 16384 * m + 6165 := by
  apply descent_of_endpoint
  · rw [data_6165.1]; exact data_6165.2.2
  · rw [data_6165.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6167. -/
theorem data_6167 : oddCount 6167 14 = 5 ∧
    acceleratedOrbit 14 6167 = 92 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6167 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6167) = 243 * m + 92 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6167
  rw [data_6167.1, data_6167.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6167 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6167) < 16384 * m + 6167 := by
  apply descent_of_endpoint
  · rw [data_6167.1]; exact data_6167.2.2
  · rw [data_6167.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6169. -/
theorem data_6169 : oddCount 6169 14 = 7 ∧
    acceleratedOrbit 14 6169 = 824 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6169 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6169) = 2187 * m + 824 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6169
  rw [data_6169.1, data_6169.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6169 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6169) < 16384 * m + 6169 := by
  apply descent_of_endpoint
  · rw [data_6169.1]; exact data_6169.2.2
  · rw [data_6169.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6173. -/
theorem data_6173 : oddCount 6173 14 = 6 ∧
    acceleratedOrbit 14 6173 = 275 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6173 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6173) = 729 * m + 275 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6173
  rw [data_6173.1, data_6173.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6173 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6173) < 16384 * m + 6173 := by
  apply descent_of_endpoint
  · rw [data_6173.1]; exact data_6173.2.2
  · rw [data_6173.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6177. -/
theorem data_6177 : oddCount 6177 14 = 6 ∧
    acceleratedOrbit 14 6177 = 275 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6177 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6177) = 729 * m + 275 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6177
  rw [data_6177.1, data_6177.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6177 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6177) < 16384 * m + 6177 := by
  apply descent_of_endpoint
  · rw [data_6177.1]; exact data_6177.2.2
  · rw [data_6177.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6179. -/
theorem data_6179 : oddCount 6179 14 = 5 ∧
    acceleratedOrbit 14 6179 = 92 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6179 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6179) = 243 * m + 92 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6179
  rw [data_6179.1, data_6179.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6179 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6179) < 16384 * m + 6179 := by
  apply descent_of_endpoint
  · rw [data_6179.1]; exact data_6179.2.2
  · rw [data_6179.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6181. -/
theorem data_6181 : oddCount 6181 14 = 7 ∧
    acceleratedOrbit 14 6181 = 827 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6181 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6181) = 2187 * m + 827 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6181
  rw [data_6181.1, data_6181.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6181 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6181) < 16384 * m + 6181 := by
  apply descent_of_endpoint
  · rw [data_6181.1]; exact data_6181.2.2
  · rw [data_6181.2.1]; decide

end Collatz.Research.DescentAtlas.Batch275
