import Collatz.Research.DescentAtlas.Core

/-! Batch 13: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch013
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 301. -/
theorem data_301 : oddCount 301 14 = 4 ∧
    acceleratedOrbit 14 301 = 2 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_301 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 301) = 81 * m + 2 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 301
  rw [data_301.1, data_301.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_301 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 301) < 16384 * m + 301 := by
  apply descent_of_endpoint
  · rw [data_301.1]; exact data_301.2.2
  · rw [data_301.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 303. -/
theorem data_303 : oddCount 303 14 = 8 ∧
    acceleratedOrbit 14 303 = 122 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_303 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 303) = 6561 * m + 122 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 303
  rw [data_303.1, data_303.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_303 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 303) < 16384 * m + 303 := by
  apply descent_of_endpoint
  · rw [data_303.1]; exact data_303.2.2
  · rw [data_303.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 305. -/
theorem data_305 : oddCount 305 14 = 6 ∧
    acceleratedOrbit 14 305 = 14 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_305 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 305) = 729 * m + 14 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 305
  rw [data_305.1, data_305.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_305 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 305) < 16384 * m + 305 := by
  apply descent_of_endpoint
  · rw [data_305.1]; exact data_305.2.2
  · rw [data_305.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 307. -/
theorem data_307 : oddCount 307 14 = 6 ∧
    acceleratedOrbit 14 307 = 14 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_307 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 307) = 729 * m + 14 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 307
  rw [data_307.1, data_307.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_307 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 307) < 16384 * m + 307 := by
  apply descent_of_endpoint
  · rw [data_307.1]; exact data_307.2.2
  · rw [data_307.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 309. -/
theorem data_309 : oddCount 309 14 = 5 ∧
    acceleratedOrbit 14 309 = 5 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_309 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 309) = 243 * m + 5 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 309
  rw [data_309.1, data_309.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_309 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 309) < 16384 * m + 309 := by
  apply descent_of_endpoint
  · rw [data_309.1]; exact data_309.2.2
  · rw [data_309.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 315. -/
theorem data_315 : oddCount 315 14 = 7 ∧
    acceleratedOrbit 14 315 = 44 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_315 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 315) = 2187 * m + 44 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 315
  rw [data_315.1, data_315.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_315 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 315) < 16384 * m + 315 := by
  apply descent_of_endpoint
  · rw [data_315.1]; exact data_315.2.2
  · rw [data_315.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 317. -/
theorem data_317 : oddCount 317 14 = 7 ∧
    acceleratedOrbit 14 317 = 44 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_317 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 317) = 2187 * m + 44 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 317
  rw [data_317.1, data_317.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_317 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 317) < 16384 * m + 317 := by
  apply descent_of_endpoint
  · rw [data_317.1]; exact data_317.2.2
  · rw [data_317.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 321. -/
theorem data_321 : oddCount 321 14 = 5 ∧
    acceleratedOrbit 14 321 = 5 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_321 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 321) = 243 * m + 5 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 321
  rw [data_321.1, data_321.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_321 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 321) < 16384 * m + 321 := by
  apply descent_of_endpoint
  · rw [data_321.1]; exact data_321.2.2
  · rw [data_321.2.1]; decide

end Collatz.Research.DescentAtlas.Batch013
