import Collatz.Research.DescentAtlas.Core

/-! Batch 88: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch088
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1967. -/
theorem data_1967 : oddCount 1967 14 = 7 ∧
    acceleratedOrbit 14 1967 = 263 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1967 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1967) = 2187 * m + 263 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1967
  rw [data_1967.1, data_1967.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1967 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1967) < 16384 * m + 1967 := by
  apply descent_of_endpoint
  · rw [data_1967.1]; exact data_1967.2.2
  · rw [data_1967.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1969. -/
theorem data_1969 : oddCount 1969 14 = 4 ∧
    acceleratedOrbit 14 1969 = 10 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1969 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1969) = 81 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1969
  rw [data_1969.1, data_1969.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1969 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1969) < 16384 * m + 1969 := by
  apply descent_of_endpoint
  · rw [data_1969.1]; exact data_1969.2.2
  · rw [data_1969.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1971. -/
theorem data_1971 : oddCount 1971 14 = 4 ∧
    acceleratedOrbit 14 1971 = 10 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1971 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1971) = 81 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1971
  rw [data_1971.1, data_1971.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1971 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1971) < 16384 * m + 1971 := by
  apply descent_of_endpoint
  · rw [data_1971.1]; exact data_1971.2.2
  · rw [data_1971.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1973. -/
theorem data_1973 : oddCount 1973 14 = 6 ∧
    acceleratedOrbit 14 1973 = 89 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1973 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1973) = 729 * m + 89 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1973
  rw [data_1973.1, data_1973.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1973 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1973) < 16384 * m + 1973 := by
  apply descent_of_endpoint
  · rw [data_1973.1]; exact data_1973.2.2
  · rw [data_1973.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1975. -/
theorem data_1975 : oddCount 1975 14 = 6 ∧
    acceleratedOrbit 14 1975 = 88 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1975 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1975) = 729 * m + 88 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1975
  rw [data_1975.1, data_1975.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1975 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1975) < 16384 * m + 1975 := by
  apply descent_of_endpoint
  · rw [data_1975.1]; exact data_1975.2.2
  · rw [data_1975.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1977. -/
theorem data_1977 : oddCount 1977 14 = 7 ∧
    acceleratedOrbit 14 1977 = 265 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1977 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1977) = 2187 * m + 265 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1977
  rw [data_1977.1, data_1977.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1977 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1977) < 16384 * m + 1977 := by
  apply descent_of_endpoint
  · rw [data_1977.1]; exact data_1977.2.2
  · rw [data_1977.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1979. -/
theorem data_1979 : oddCount 1979 14 = 7 ∧
    acceleratedOrbit 14 1979 = 265 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1979 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1979) = 2187 * m + 265 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1979
  rw [data_1979.1, data_1979.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1979 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1979) < 16384 * m + 1979 := by
  apply descent_of_endpoint
  · rw [data_1979.1]; exact data_1979.2.2
  · rw [data_1979.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1985. -/
theorem data_1985 : oddCount 1985 14 = 6 ∧
    acceleratedOrbit 14 1985 = 89 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1985 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1985) = 729 * m + 89 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1985
  rw [data_1985.1, data_1985.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1985 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1985) < 16384 * m + 1985 := by
  apply descent_of_endpoint
  · rw [data_1985.1]; exact data_1985.2.2
  · rw [data_1985.2.1]; decide

end Collatz.Research.DescentAtlas.Batch088
