import Collatz.Research.DescentAtlas.Core

/-! Batch 187: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch187
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 4185. -/
theorem data_4185 : oddCount 4185 14 = 7 ∧
    acceleratedOrbit 14 4185 = 560 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4185 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4185) = 2187 * m + 560 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4185
  rw [data_4185.1, data_4185.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4185 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4185) < 16384 * m + 4185 := by
  apply descent_of_endpoint
  · rw [data_4185.1]; exact data_4185.2.2
  · rw [data_4185.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4189. -/
theorem data_4189 : oddCount 4189 14 = 6 ∧
    acceleratedOrbit 14 4189 = 188 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4189 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4189) = 729 * m + 188 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4189
  rw [data_4189.1, data_4189.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4189 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4189) < 16384 * m + 4189 := by
  apply descent_of_endpoint
  · rw [data_4189.1]; exact data_4189.2.2
  · rw [data_4189.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4191. -/
theorem data_4191 : oddCount 4191 14 = 8 ∧
    acceleratedOrbit 14 4191 = 1679 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4191 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4191) = 6561 * m + 1679 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4191
  rw [data_4191.1, data_4191.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4191 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4191) < 16384 * m + 4191 := by
  apply descent_of_endpoint
  · rw [data_4191.1]; exact data_4191.2.2
  · rw [data_4191.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4195. -/
theorem data_4195 : oddCount 4195 14 = 7 ∧
    acceleratedOrbit 14 4195 = 562 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4195 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4195) = 2187 * m + 562 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4195
  rw [data_4195.1, data_4195.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4195 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4195) < 16384 * m + 4195 := by
  apply descent_of_endpoint
  · rw [data_4195.1]; exact data_4195.2.2
  · rw [data_4195.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4197. -/
theorem data_4197 : oddCount 4197 14 = 7 ∧
    acceleratedOrbit 14 4197 = 562 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4197 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4197) = 2187 * m + 562 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4197
  rw [data_4197.1, data_4197.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4197 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4197) < 16384 * m + 4197 := by
  apply descent_of_endpoint
  · rw [data_4197.1]; exact data_4197.2.2
  · rw [data_4197.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4199. -/
theorem data_4199 : oddCount 4199 14 = 8 ∧
    acceleratedOrbit 14 4199 = 1682 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4199 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4199) = 6561 * m + 1682 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4199
  rw [data_4199.1, data_4199.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4199 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4199) < 16384 * m + 4199 := by
  apply descent_of_endpoint
  · rw [data_4199.1]; exact data_4199.2.2
  · rw [data_4199.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4201. -/
theorem data_4201 : oddCount 4201 14 = 6 ∧
    acceleratedOrbit 14 4201 = 187 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4201 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4201) = 729 * m + 187 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4201
  rw [data_4201.1, data_4201.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4201 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4201) < 16384 * m + 4201 := by
  apply descent_of_endpoint
  · rw [data_4201.1]; exact data_4201.2.2
  · rw [data_4201.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4203. -/
theorem data_4203 : oddCount 4203 14 = 8 ∧
    acceleratedOrbit 14 4203 = 1684 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4203 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4203) = 6561 * m + 1684 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4203
  rw [data_4203.1, data_4203.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4203 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4203) < 16384 * m + 4203 := by
  apply descent_of_endpoint
  · rw [data_4203.1]; exact data_4203.2.2
  · rw [data_4203.2.1]; decide

end Collatz.Research.DescentAtlas.Batch187
