import Collatz.Research.DescentAtlas.Core

/-! Batch 259: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch259
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5815. -/
theorem data_5815 : oddCount 5815 14 = 8 ∧
    acceleratedOrbit 14 5815 = 2330 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5815 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5815) = 6561 * m + 2330 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5815
  rw [data_5815.1, data_5815.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5815 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5815) < 16384 * m + 5815 := by
  apply descent_of_endpoint
  · rw [data_5815.1]; exact data_5815.2.2
  · rw [data_5815.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5817. -/
theorem data_5817 : oddCount 5817 14 = 6 ∧
    acceleratedOrbit 14 5817 = 259 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5817 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5817) = 729 * m + 259 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5817
  rw [data_5817.1, data_5817.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5817 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5817) < 16384 * m + 5817 := by
  apply descent_of_endpoint
  · rw [data_5817.1]; exact data_5817.2.2
  · rw [data_5817.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5819. -/
theorem data_5819 : oddCount 5819 14 = 6 ∧
    acceleratedOrbit 14 5819 = 259 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5819 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5819) = 729 * m + 259 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5819
  rw [data_5819.1, data_5819.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5819 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5819) < 16384 * m + 5819 := by
  apply descent_of_endpoint
  · rw [data_5819.1]; exact data_5819.2.2
  · rw [data_5819.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5821. -/
theorem data_5821 : oddCount 5821 14 = 7 ∧
    acceleratedOrbit 14 5821 = 778 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5821 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5821) = 2187 * m + 778 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5821
  rw [data_5821.1, data_5821.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5821 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5821) < 16384 * m + 5821 := by
  apply descent_of_endpoint
  · rw [data_5821.1]; exact data_5821.2.2
  · rw [data_5821.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5825. -/
theorem data_5825 : oddCount 5825 14 = 6 ∧
    acceleratedOrbit 14 5825 = 260 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5825 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5825) = 729 * m + 260 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5825
  rw [data_5825.1, data_5825.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5825 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5825) < 16384 * m + 5825 := by
  apply descent_of_endpoint
  · rw [data_5825.1]; exact data_5825.2.2
  · rw [data_5825.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5829. -/
theorem data_5829 : oddCount 5829 14 = 4 ∧
    acceleratedOrbit 14 5829 = 29 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5829 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5829) = 81 * m + 29 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5829
  rw [data_5829.1, data_5829.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5829 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5829) < 16384 * m + 5829 := by
  apply descent_of_endpoint
  · rw [data_5829.1]; exact data_5829.2.2
  · rw [data_5829.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5831. -/
theorem data_5831 : oddCount 5831 14 = 6 ∧
    acceleratedOrbit 14 5831 = 260 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5831 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5831) = 729 * m + 260 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5831
  rw [data_5831.1, data_5831.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5831 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5831) < 16384 * m + 5831 := by
  apply descent_of_endpoint
  · rw [data_5831.1]; exact data_5831.2.2
  · rw [data_5831.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5833. -/
theorem data_5833 : oddCount 5833 14 = 8 ∧
    acceleratedOrbit 14 5833 = 2339 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5833 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5833) = 6561 * m + 2339 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5833
  rw [data_5833.1, data_5833.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5833 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5833) < 16384 * m + 5833 := by
  apply descent_of_endpoint
  · rw [data_5833.1]; exact data_5833.2.2
  · rw [data_5833.2.1]; decide

end Collatz.Research.DescentAtlas.Batch259
