import Collatz.Research.DescentAtlas.Core

/-! Batch 204: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch204
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 4577. -/
theorem data_4577 : oddCount 4577 14 = 8 ∧
    acceleratedOrbit 14 4577 = 1835 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4577 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4577) = 6561 * m + 1835 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4577
  rw [data_4577.1, data_4577.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4577 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4577) < 16384 * m + 4577 := by
  apply descent_of_endpoint
  · rw [data_4577.1]; exact data_4577.2.2
  · rw [data_4577.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4579. -/
theorem data_4579 : oddCount 4579 14 = 6 ∧
    acceleratedOrbit 14 4579 = 206 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4579 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4579) = 729 * m + 206 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4579
  rw [data_4579.1, data_4579.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4579 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4579) < 16384 * m + 4579 := by
  apply descent_of_endpoint
  · rw [data_4579.1]; exact data_4579.2.2
  · rw [data_4579.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4581. -/
theorem data_4581 : oddCount 4581 14 = 8 ∧
    acceleratedOrbit 14 4581 = 1838 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4581) = 6561 * m + 1838 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4581
  rw [data_4581.1, data_4581.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4581) < 16384 * m + 4581 := by
  apply descent_of_endpoint
  · rw [data_4581.1]; exact data_4581.2.2
  · rw [data_4581.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4585. -/
theorem data_4585 : oddCount 4585 14 = 8 ∧
    acceleratedOrbit 14 4585 = 1837 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4585) = 6561 * m + 1837 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4585
  rw [data_4585.1, data_4585.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4585) < 16384 * m + 4585 := by
  apply descent_of_endpoint
  · rw [data_4585.1]; exact data_4585.2.2
  · rw [data_4585.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4589. -/
theorem data_4589 : oddCount 4589 14 = 7 ∧
    acceleratedOrbit 14 4589 = 614 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4589 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4589) = 2187 * m + 614 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4589
  rw [data_4589.1, data_4589.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4589 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4589) < 16384 * m + 4589 := by
  apply descent_of_endpoint
  · rw [data_4589.1]; exact data_4589.2.2
  · rw [data_4589.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4593. -/
theorem data_4593 : oddCount 4593 14 = 6 ∧
    acceleratedOrbit 14 4593 = 206 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4593 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4593) = 729 * m + 206 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4593
  rw [data_4593.1, data_4593.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4593 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4593) < 16384 * m + 4593 := by
  apply descent_of_endpoint
  · rw [data_4593.1]; exact data_4593.2.2
  · rw [data_4593.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4595. -/
theorem data_4595 : oddCount 4595 14 = 7 ∧
    acceleratedOrbit 14 4595 = 614 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4595 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4595) = 2187 * m + 614 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4595
  rw [data_4595.1, data_4595.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4595 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4595) < 16384 * m + 4595 := by
  apply descent_of_endpoint
  · rw [data_4595.1]; exact data_4595.2.2
  · rw [data_4595.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4597. -/
theorem data_4597 : oddCount 4597 14 = 6 ∧
    acceleratedOrbit 14 4597 = 205 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4597 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4597) = 729 * m + 205 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4597
  rw [data_4597.1, data_4597.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4597 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4597) < 16384 * m + 4597 := by
  apply descent_of_endpoint
  · rw [data_4597.1]; exact data_4597.2.2
  · rw [data_4597.2.1]; decide

end Collatz.Research.DescentAtlas.Batch204
