import Collatz.Research.DescentAtlas.Core

/-! Batch 64: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch064
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1427. -/
theorem data_1427 : oddCount 1427 14 = 6 ∧
    acceleratedOrbit 14 1427 = 64 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1427 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1427) = 729 * m + 64 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1427
  rw [data_1427.1, data_1427.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1427 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1427) < 16384 * m + 1427 := by
  apply descent_of_endpoint
  · rw [data_1427.1]; exact data_1427.2.2
  · rw [data_1427.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1429. -/
theorem data_1429 : oddCount 1429 14 = 5 ∧
    acceleratedOrbit 14 1429 = 22 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1429 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1429) = 243 * m + 22 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1429
  rw [data_1429.1, data_1429.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1429 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1429) < 16384 * m + 1429 := by
  apply descent_of_endpoint
  · rw [data_1429.1]; exact data_1429.2.2
  · rw [data_1429.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1431. -/
theorem data_1431 : oddCount 1431 14 = 6 ∧
    acceleratedOrbit 14 1431 = 64 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1431 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1431) = 729 * m + 64 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1431
  rw [data_1431.1, data_1431.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1431 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1431) < 16384 * m + 1431 := by
  apply descent_of_endpoint
  · rw [data_1431.1]; exact data_1431.2.2
  · rw [data_1431.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1433. -/
theorem data_1433 : oddCount 1433 14 = 6 ∧
    acceleratedOrbit 14 1433 = 64 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1433 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1433) = 729 * m + 64 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1433
  rw [data_1433.1, data_1433.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1433 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1433) < 16384 * m + 1433 := by
  apply descent_of_endpoint
  · rw [data_1433.1]; exact data_1433.2.2
  · rw [data_1433.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1437. -/
theorem data_1437 : oddCount 1437 14 = 8 ∧
    acceleratedOrbit 14 1437 = 577 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1437 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1437) = 6561 * m + 577 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1437
  rw [data_1437.1, data_1437.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1437 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1437) < 16384 * m + 1437 := by
  apply descent_of_endpoint
  · rw [data_1437.1]; exact data_1437.2.2
  · rw [data_1437.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1441. -/
theorem data_1441 : oddCount 1441 14 = 7 ∧
    acceleratedOrbit 14 1441 = 193 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1441 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1441) = 2187 * m + 193 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1441
  rw [data_1441.1, data_1441.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1441 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1441) < 16384 * m + 1441 := by
  apply descent_of_endpoint
  · rw [data_1441.1]; exact data_1441.2.2
  · rw [data_1441.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1443. -/
theorem data_1443 : oddCount 1443 14 = 6 ∧
    acceleratedOrbit 14 1443 = 65 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1443 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1443) = 729 * m + 65 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1443
  rw [data_1443.1, data_1443.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1443 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1443) < 16384 * m + 1443 := by
  apply descent_of_endpoint
  · rw [data_1443.1]; exact data_1443.2.2
  · rw [data_1443.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1445. -/
theorem data_1445 : oddCount 1445 14 = 6 ∧
    acceleratedOrbit 14 1445 = 65 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1445 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1445) = 729 * m + 65 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1445
  rw [data_1445.1, data_1445.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1445 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1445) < 16384 * m + 1445 := by
  apply descent_of_endpoint
  · rw [data_1445.1]; exact data_1445.2.2
  · rw [data_1445.2.1]; decide

end Collatz.Research.DescentAtlas.Batch064
