import Collatz.Research.DescentAtlas.Core

/-! Batch 206: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch206
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 4625. -/
theorem data_4625 : oddCount 4625 14 = 4 ∧
    acceleratedOrbit 14 4625 = 23 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4625 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4625) = 81 * m + 23 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4625
  rw [data_4625.1, data_4625.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4625 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4625) < 16384 * m + 4625 := by
  apply descent_of_endpoint
  · rw [data_4625.1]; exact data_4625.2.2
  · rw [data_4625.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4627. -/
theorem data_4627 : oddCount 4627 14 = 6 ∧
    acceleratedOrbit 14 4627 = 206 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4627 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4627) = 729 * m + 206 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4627
  rw [data_4627.1, data_4627.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4627 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4627) < 16384 * m + 4627 := by
  apply descent_of_endpoint
  · rw [data_4627.1]; exact data_4627.2.2
  · rw [data_4627.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4629. -/
theorem data_4629 : oddCount 4629 14 = 4 ∧
    acceleratedOrbit 14 4629 = 23 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4629 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4629) = 81 * m + 23 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4629
  rw [data_4629.1, data_4629.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4629 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4629) < 16384 * m + 4629 := by
  apply descent_of_endpoint
  · rw [data_4629.1]; exact data_4629.2.2
  · rw [data_4629.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4631. -/
theorem data_4631 : oddCount 4631 14 = 7 ∧
    acceleratedOrbit 14 4631 = 620 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4631 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4631) = 2187 * m + 620 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4631
  rw [data_4631.1, data_4631.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4631 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4631) < 16384 * m + 4631 := by
  apply descent_of_endpoint
  · rw [data_4631.1]; exact data_4631.2.2
  · rw [data_4631.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4633. -/
theorem data_4633 : oddCount 4633 14 = 7 ∧
    acceleratedOrbit 14 4633 = 620 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4633 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4633) = 2187 * m + 620 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4633
  rw [data_4633.1, data_4633.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4633 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4633) < 16384 * m + 4633 := by
  apply descent_of_endpoint
  · rw [data_4633.1]; exact data_4633.2.2
  · rw [data_4633.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4637. -/
theorem data_4637 : oddCount 4637 14 = 8 ∧
    acceleratedOrbit 14 4637 = 1862 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4637 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4637) = 6561 * m + 1862 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4637
  rw [data_4637.1, data_4637.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4637 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4637) < 16384 * m + 4637 := by
  apply descent_of_endpoint
  · rw [data_4637.1]; exact data_4637.2.2
  · rw [data_4637.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4641. -/
theorem data_4641 : oddCount 4641 14 = 8 ∧
    acceleratedOrbit 14 4641 = 1862 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4641 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4641) = 6561 * m + 1862 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4641
  rw [data_4641.1, data_4641.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4641 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4641) < 16384 * m + 4641 := by
  apply descent_of_endpoint
  · rw [data_4641.1]; exact data_4641.2.2
  · rw [data_4641.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 4643. -/
theorem data_4643 : oddCount 4643 14 = 4 ∧
    acceleratedOrbit 14 4643 = 23 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_4643 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4643) = 81 * m + 23 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 4643
  rw [data_4643.1, data_4643.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_4643 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 4643) < 16384 * m + 4643 := by
  apply descent_of_endpoint
  · rw [data_4643.1]; exact data_4643.2.2
  · rw [data_4643.2.1]; decide

end Collatz.Research.DescentAtlas.Batch206
