import Collatz.Research.DescentAtlas.Core

/-! Batch 291: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch291
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 6523. -/
theorem data_6523 : oddCount 6523 14 = 7 ∧
    acceleratedOrbit 14 6523 = 871 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6523 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6523) = 2187 * m + 871 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6523
  rw [data_6523.1, data_6523.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6523 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6523) < 16384 * m + 6523 := by
  apply descent_of_endpoint
  · rw [data_6523.1]; exact data_6523.2.2
  · rw [data_6523.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6525. -/
theorem data_6525 : oddCount 6525 14 = 7 ∧
    acceleratedOrbit 14 6525 = 872 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6525 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6525) = 2187 * m + 872 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6525
  rw [data_6525.1, data_6525.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6525 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6525) < 16384 * m + 6525 := by
  apply descent_of_endpoint
  · rw [data_6525.1]; exact data_6525.2.2
  · rw [data_6525.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6529. -/
theorem data_6529 : oddCount 6529 14 = 8 ∧
    acceleratedOrbit 14 6529 = 2618 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6529 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6529) = 6561 * m + 2618 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6529
  rw [data_6529.1, data_6529.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6529 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6529) < 16384 * m + 6529 := by
  apply descent_of_endpoint
  · rw [data_6529.1]; exact data_6529.2.2
  · rw [data_6529.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6531. -/
theorem data_6531 : oddCount 6531 14 = 5 ∧
    acceleratedOrbit 14 6531 = 97 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6531 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6531) = 243 * m + 97 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6531
  rw [data_6531.1, data_6531.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6531 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6531) < 16384 * m + 6531 := by
  apply descent_of_endpoint
  · rw [data_6531.1]; exact data_6531.2.2
  · rw [data_6531.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6533. -/
theorem data_6533 : oddCount 6533 14 = 5 ∧
    acceleratedOrbit 14 6533 = 97 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6533 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6533) = 243 * m + 97 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6533
  rw [data_6533.1, data_6533.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6533 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6533) < 16384 * m + 6533 := by
  apply descent_of_endpoint
  · rw [data_6533.1]; exact data_6533.2.2
  · rw [data_6533.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6535. -/
theorem data_6535 : oddCount 6535 14 = 5 ∧
    acceleratedOrbit 14 6535 = 97 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6535 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6535) = 243 * m + 97 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6535
  rw [data_6535.1, data_6535.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6535 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6535) < 16384 * m + 6535 := by
  apply descent_of_endpoint
  · rw [data_6535.1]; exact data_6535.2.2
  · rw [data_6535.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6539. -/
theorem data_6539 : oddCount 6539 14 = 8 ∧
    acceleratedOrbit 14 6539 = 2620 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6539 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6539) = 6561 * m + 2620 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6539
  rw [data_6539.1, data_6539.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6539 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6539) < 16384 * m + 6539 := by
  apply descent_of_endpoint
  · rw [data_6539.1]; exact data_6539.2.2
  · rw [data_6539.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 6541. -/
theorem data_6541 : oddCount 6541 14 = 5 ∧
    acceleratedOrbit 14 6541 = 98 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_6541 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6541) = 243 * m + 98 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 6541
  rw [data_6541.1, data_6541.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_6541 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 6541) < 16384 * m + 6541 := by
  apply descent_of_endpoint
  · rw [data_6541.1]; exact data_6541.2.2
  · rw [data_6541.2.1]; decide

end Collatz.Research.DescentAtlas.Batch291
