import Collatz.Research.DescentAtlas.Core

/-! Batch 118: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch118
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 2645. -/
theorem data_2645 : oddCount 2645 14 = 6 ∧
    acceleratedOrbit 14 2645 = 121 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2645 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2645) = 729 * m + 121 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2645
  rw [data_2645.1, data_2645.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2645 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2645) < 16384 * m + 2645 := by
  apply descent_of_endpoint
  · rw [data_2645.1]; exact data_2645.2.2
  · rw [data_2645.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2647. -/
theorem data_2647 : oddCount 2647 14 = 6 ∧
    acceleratedOrbit 14 2647 = 118 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2647 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2647) = 729 * m + 118 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2647
  rw [data_2647.1, data_2647.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2647 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2647) < 16384 * m + 2647 := by
  apply descent_of_endpoint
  · rw [data_2647.1]; exact data_2647.2.2
  · rw [data_2647.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2649. -/
theorem data_2649 : oddCount 2649 14 = 8 ∧
    acceleratedOrbit 14 2649 = 1063 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2649 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2649) = 6561 * m + 1063 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2649
  rw [data_2649.1, data_2649.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2649 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2649) < 16384 * m + 2649 := by
  apply descent_of_endpoint
  · rw [data_2649.1]; exact data_2649.2.2
  · rw [data_2649.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2653. -/
theorem data_2653 : oddCount 2653 14 = 5 ∧
    acceleratedOrbit 14 2653 = 40 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2653 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2653) = 243 * m + 40 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2653
  rw [data_2653.1, data_2653.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2653 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2653) < 16384 * m + 2653 := by
  apply descent_of_endpoint
  · rw [data_2653.1]; exact data_2653.2.2
  · rw [data_2653.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2655. -/
theorem data_2655 : oddCount 2655 14 = 8 ∧
    acceleratedOrbit 14 2655 = 1064 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2655 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2655) = 6561 * m + 1064 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2655
  rw [data_2655.1, data_2655.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2655 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2655) < 16384 * m + 2655 := by
  apply descent_of_endpoint
  · rw [data_2655.1]; exact data_2655.2.2
  · rw [data_2655.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2657. -/
theorem data_2657 : oddCount 2657 14 = 8 ∧
    acceleratedOrbit 14 2657 = 1066 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2657 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2657) = 6561 * m + 1066 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2657
  rw [data_2657.1, data_2657.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2657 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2657) < 16384 * m + 2657 := by
  apply descent_of_endpoint
  · rw [data_2657.1]; exact data_2657.2.2
  · rw [data_2657.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2659. -/
theorem data_2659 : oddCount 2659 14 = 6 ∧
    acceleratedOrbit 14 2659 = 119 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2659 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2659) = 729 * m + 119 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2659
  rw [data_2659.1, data_2659.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2659 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2659) < 16384 * m + 2659 := by
  apply descent_of_endpoint
  · rw [data_2659.1]; exact data_2659.2.2
  · rw [data_2659.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2661. -/
theorem data_2661 : oddCount 2661 14 = 6 ∧
    acceleratedOrbit 14 2661 = 119 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2661 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2661) = 729 * m + 119 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2661
  rw [data_2661.1, data_2661.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2661 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2661) < 16384 * m + 2661 := by
  apply descent_of_endpoint
  · rw [data_2661.1]; exact data_2661.2.2
  · rw [data_2661.2.1]; decide

end Collatz.Research.DescentAtlas.Batch118
