import Collatz.Research.DescentAtlas.Core

/-! Batch 230: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch230
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5159. -/
theorem data_5159 : oddCount 5159 14 = 7 ∧
    acceleratedOrbit 14 5159 = 689 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5159 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5159) = 2187 * m + 689 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5159
  rw [data_5159.1, data_5159.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5159 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5159) < 16384 * m + 5159 := by
  apply descent_of_endpoint
  · rw [data_5159.1]; exact data_5159.2.2
  · rw [data_5159.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5163. -/
theorem data_5163 : oddCount 5163 14 = 6 ∧
    acceleratedOrbit 14 5163 = 230 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5163 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5163) = 729 * m + 230 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5163
  rw [data_5163.1, data_5163.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5163 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5163) < 16384 * m + 5163 := by
  apply descent_of_endpoint
  · rw [data_5163.1]; exact data_5163.2.2
  · rw [data_5163.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5165. -/
theorem data_5165 : oddCount 5165 14 = 7 ∧
    acceleratedOrbit 14 5165 = 692 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5165 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5165) = 2187 * m + 692 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5165
  rw [data_5165.1, data_5165.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5165 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5165) < 16384 * m + 5165 := by
  apply descent_of_endpoint
  · rw [data_5165.1]; exact data_5165.2.2
  · rw [data_5165.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5169. -/
theorem data_5169 : oddCount 5169 14 = 7 ∧
    acceleratedOrbit 14 5169 = 692 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5169 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5169) = 2187 * m + 692 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5169
  rw [data_5169.1, data_5169.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5169 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5169) < 16384 * m + 5169 := by
  apply descent_of_endpoint
  · rw [data_5169.1]; exact data_5169.2.2
  · rw [data_5169.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5171. -/
theorem data_5171 : oddCount 5171 14 = 7 ∧
    acceleratedOrbit 14 5171 = 692 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5171 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5171) = 2187 * m + 692 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5171
  rw [data_5171.1, data_5171.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5171 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5171) < 16384 * m + 5171 := by
  apply descent_of_endpoint
  · rw [data_5171.1]; exact data_5171.2.2
  · rw [data_5171.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5173. -/
theorem data_5173 : oddCount 5173 14 = 6 ∧
    acceleratedOrbit 14 5173 = 233 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5173 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5173) = 729 * m + 233 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5173
  rw [data_5173.1, data_5173.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5173 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5173) < 16384 * m + 5173 := by
  apply descent_of_endpoint
  · rw [data_5173.1]; exact data_5173.2.2
  · rw [data_5173.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5175. -/
theorem data_5175 : oddCount 5175 14 = 7 ∧
    acceleratedOrbit 14 5175 = 691 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5175 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5175) = 2187 * m + 691 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5175
  rw [data_5175.1, data_5175.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5175 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5175) < 16384 * m + 5175 := by
  apply descent_of_endpoint
  · rw [data_5175.1]; exact data_5175.2.2
  · rw [data_5175.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5177. -/
theorem data_5177 : oddCount 5177 14 = 7 ∧
    acceleratedOrbit 14 5177 = 692 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5177 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5177) = 2187 * m + 692 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5177
  rw [data_5177.1, data_5177.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5177 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5177) < 16384 * m + 5177 := by
  apply descent_of_endpoint
  · rw [data_5177.1]; exact data_5177.2.2
  · rw [data_5177.2.1]; decide

end Collatz.Research.DescentAtlas.Batch230
