import Collatz.Research.DescentAtlas.Core

/-! Batch 17: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch017
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 389. -/
theorem data_389 : oddCount 389 14 = 8 ∧
    acceleratedOrbit 14 389 = 161 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_389 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 389) = 6561 * m + 161 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 389
  rw [data_389.1, data_389.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_389 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 389) < 16384 * m + 389 := by
  apply descent_of_endpoint
  · rw [data_389.1]; exact data_389.2.2
  · rw [data_389.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 391. -/
theorem data_391 : oddCount 391 14 = 8 ∧
    acceleratedOrbit 14 391 = 161 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_391 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 391) = 6561 * m + 161 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 391
  rw [data_391.1, data_391.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_391 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 391) < 16384 * m + 391 := by
  apply descent_of_endpoint
  · rw [data_391.1]; exact data_391.2.2
  · rw [data_391.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 397. -/
theorem data_397 : oddCount 397 14 = 6 ∧
    acceleratedOrbit 14 397 = 20 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_397 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 397) = 729 * m + 20 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 397
  rw [data_397.1, data_397.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_397 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 397) < 16384 * m + 397 := by
  apply descent_of_endpoint
  · rw [data_397.1]; exact data_397.2.2
  · rw [data_397.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 401. -/
theorem data_401 : oddCount 401 14 = 4 ∧
    acceleratedOrbit 14 401 = 2 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_401 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 401) = 81 * m + 2 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 401
  rw [data_401.1, data_401.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_401 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 401) < 16384 * m + 401 := by
  apply descent_of_endpoint
  · rw [data_401.1]; exact data_401.2.2
  · rw [data_401.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 403. -/
theorem data_403 : oddCount 403 14 = 4 ∧
    acceleratedOrbit 14 403 = 2 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_403 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 403) = 81 * m + 2 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 403
  rw [data_403.1, data_403.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_403 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 403) < 16384 * m + 403 := by
  apply descent_of_endpoint
  · rw [data_403.1]; exact data_403.2.2
  · rw [data_403.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 405. -/
theorem data_405 : oddCount 405 14 = 6 ∧
    acceleratedOrbit 14 405 = 20 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_405 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 405) = 729 * m + 20 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 405
  rw [data_405.1, data_405.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_405 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 405) < 16384 * m + 405 := by
  apply descent_of_endpoint
  · rw [data_405.1]; exact data_405.2.2
  · rw [data_405.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 407. -/
theorem data_407 : oddCount 407 14 = 7 ∧
    acceleratedOrbit 14 407 = 56 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_407 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 407) = 2187 * m + 56 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 407
  rw [data_407.1, data_407.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_407 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 407) < 16384 * m + 407 := by
  apply descent_of_endpoint
  · rw [data_407.1]; exact data_407.2.2
  · rw [data_407.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 409. -/
theorem data_409 : oddCount 409 14 = 7 ∧
    acceleratedOrbit 14 409 = 56 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_409 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 409) = 2187 * m + 56 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 409
  rw [data_409.1, data_409.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_409 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 409) < 16384 * m + 409 := by
  apply descent_of_endpoint
  · rw [data_409.1]; exact data_409.2.2
  · rw [data_409.2.1]; decide

end Collatz.Research.DescentAtlas.Batch017
