import Collatz.Research.DescentAtlas.Core

/-! Batch 71: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch071
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1579. -/
theorem data_1579 : oddCount 1579 14 = 6 ∧
    acceleratedOrbit 14 1579 = 71 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1579 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1579) = 729 * m + 71 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1579
  rw [data_1579.1, data_1579.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1579 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1579) < 16384 * m + 1579 := by
  apply descent_of_endpoint
  · rw [data_1579.1]; exact data_1579.2.2
  · rw [data_1579.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1581. -/
theorem data_1581 : oddCount 1581 14 = 8 ∧
    acceleratedOrbit 14 1581 = 638 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1581) = 6561 * m + 638 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1581
  rw [data_1581.1, data_1581.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1581 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1581) < 16384 * m + 1581 := by
  apply descent_of_endpoint
  · rw [data_1581.1]; exact data_1581.2.2
  · rw [data_1581.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1585. -/
theorem data_1585 : oddCount 1585 14 = 8 ∧
    acceleratedOrbit 14 1585 = 638 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1585) = 6561 * m + 638 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1585
  rw [data_1585.1, data_1585.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1585 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1585) < 16384 * m + 1585 := by
  apply descent_of_endpoint
  · rw [data_1585.1]; exact data_1585.2.2
  · rw [data_1585.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1587. -/
theorem data_1587 : oddCount 1587 14 = 8 ∧
    acceleratedOrbit 14 1587 = 638 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1587 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1587) = 6561 * m + 638 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1587
  rw [data_1587.1, data_1587.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1587 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1587) < 16384 * m + 1587 := by
  apply descent_of_endpoint
  · rw [data_1587.1]; exact data_1587.2.2
  · rw [data_1587.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1589. -/
theorem data_1589 : oddCount 1589 14 = 5 ∧
    acceleratedOrbit 14 1589 = 26 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1589 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1589) = 243 * m + 26 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1589
  rw [data_1589.1, data_1589.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1589 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1589) < 16384 * m + 1589 := by
  apply descent_of_endpoint
  · rw [data_1589.1]; exact data_1589.2.2
  · rw [data_1589.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1593. -/
theorem data_1593 : oddCount 1593 14 = 6 ∧
    acceleratedOrbit 14 1593 = 71 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1593 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1593) = 729 * m + 71 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1593
  rw [data_1593.1, data_1593.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1593 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1593) < 16384 * m + 1593 := by
  apply descent_of_endpoint
  · rw [data_1593.1]; exact data_1593.2.2
  · rw [data_1593.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1595. -/
theorem data_1595 : oddCount 1595 14 = 8 ∧
    acceleratedOrbit 14 1595 = 641 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1595 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1595) = 6561 * m + 641 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1595
  rw [data_1595.1, data_1595.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1595 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1595) < 16384 * m + 1595 := by
  apply descent_of_endpoint
  · rw [data_1595.1]; exact data_1595.2.2
  · rw [data_1595.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1597. -/
theorem data_1597 : oddCount 1597 14 = 7 ∧
    acceleratedOrbit 14 1597 = 215 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1597 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1597) = 2187 * m + 215 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1597
  rw [data_1597.1, data_1597.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1597 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1597) < 16384 * m + 1597 := by
  apply descent_of_endpoint
  · rw [data_1597.1]; exact data_1597.2.2
  · rw [data_1597.2.1]; decide

end Collatz.Research.DescentAtlas.Batch071
