import Collatz.Research.DescentAtlas.Core

/-! Batch 50: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch050
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1111. -/
theorem data_1111 : oddCount 1111 14 = 5 ∧
    acceleratedOrbit 14 1111 = 17 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1111 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1111) = 243 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1111
  rw [data_1111.1, data_1111.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1111 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1111) < 16384 * m + 1111 := by
  apply descent_of_endpoint
  · rw [data_1111.1]; exact data_1111.2.2
  · rw [data_1111.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1113. -/
theorem data_1113 : oddCount 1113 14 = 8 ∧
    acceleratedOrbit 14 1113 = 449 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1113 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1113) = 6561 * m + 449 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1113
  rw [data_1113.1, data_1113.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1113 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1113) < 16384 * m + 1113 := by
  apply descent_of_endpoint
  · rw [data_1113.1]; exact data_1113.2.2
  · rw [data_1113.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1117. -/
theorem data_1117 : oddCount 1117 14 = 7 ∧
    acceleratedOrbit 14 1117 = 152 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1117 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1117) = 2187 * m + 152 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1117
  rw [data_1117.1, data_1117.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1117 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1117) < 16384 * m + 1117 := by
  apply descent_of_endpoint
  · rw [data_1117.1]; exact data_1117.2.2
  · rw [data_1117.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1121. -/
theorem data_1121 : oddCount 1121 14 = 6 ∧
    acceleratedOrbit 14 1121 = 50 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1121 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1121) = 729 * m + 50 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1121
  rw [data_1121.1, data_1121.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1121 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1121) < 16384 * m + 1121 := by
  apply descent_of_endpoint
  · rw [data_1121.1]; exact data_1121.2.2
  · rw [data_1121.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1123. -/
theorem data_1123 : oddCount 1123 14 = 7 ∧
    acceleratedOrbit 14 1123 = 152 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1123 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1123) = 2187 * m + 152 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1123
  rw [data_1123.1, data_1123.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1123 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1123) < 16384 * m + 1123 := by
  apply descent_of_endpoint
  · rw [data_1123.1]; exact data_1123.2.2
  · rw [data_1123.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1125. -/
theorem data_1125 : oddCount 1125 14 = 7 ∧
    acceleratedOrbit 14 1125 = 152 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1125 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1125) = 2187 * m + 152 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1125
  rw [data_1125.1, data_1125.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1125 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1125) < 16384 * m + 1125 := by
  apply descent_of_endpoint
  · rw [data_1125.1]; exact data_1125.2.2
  · rw [data_1125.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1129. -/
theorem data_1129 : oddCount 1129 14 = 7 ∧
    acceleratedOrbit 14 1129 = 151 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1129 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1129) = 2187 * m + 151 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1129
  rw [data_1129.1, data_1129.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1129 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1129) < 16384 * m + 1129 := by
  apply descent_of_endpoint
  · rw [data_1129.1]; exact data_1129.2.2
  · rw [data_1129.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1131. -/
theorem data_1131 : oddCount 1131 14 = 8 ∧
    acceleratedOrbit 14 1131 = 454 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1131 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1131) = 6561 * m + 454 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1131
  rw [data_1131.1, data_1131.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1131 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1131) < 16384 * m + 1131 := by
  apply descent_of_endpoint
  · rw [data_1131.1]; exact data_1131.2.2
  · rw [data_1131.2.1]; decide

end Collatz.Research.DescentAtlas.Batch050
