import Collatz.Research.DescentAtlas.Core

/-! Batch 164: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch164
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 3677. -/
theorem data_3677 : oddCount 3677 14 = 5 ∧
    acceleratedOrbit 14 3677 = 55 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3677 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3677) = 243 * m + 55 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3677
  rw [data_3677.1, data_3677.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3677 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3677) < 16384 * m + 3677 := by
  apply descent_of_endpoint
  · rw [data_3677.1]; exact data_3677.2.2
  · rw [data_3677.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3679. -/
theorem data_3679 : oddCount 3679 14 = 8 ∧
    acceleratedOrbit 14 3679 = 1475 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3679 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3679) = 6561 * m + 1475 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3679
  rw [data_3679.1, data_3679.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3679 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3679) < 16384 * m + 3679 := by
  apply descent_of_endpoint
  · rw [data_3679.1]; exact data_3679.2.2
  · rw [data_3679.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3681. -/
theorem data_3681 : oddCount 3681 14 = 6 ∧
    acceleratedOrbit 14 3681 = 164 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3681 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3681) = 729 * m + 164 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3681
  rw [data_3681.1, data_3681.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3681 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3681) < 16384 * m + 3681 := by
  apply descent_of_endpoint
  · rw [data_3681.1]; exact data_3681.2.2
  · rw [data_3681.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3683. -/
theorem data_3683 : oddCount 3683 14 = 5 ∧
    acceleratedOrbit 14 3683 = 55 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3683 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3683) = 243 * m + 55 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3683
  rw [data_3683.1, data_3683.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3683 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3683) < 16384 * m + 3683 := by
  apply descent_of_endpoint
  · rw [data_3683.1]; exact data_3683.2.2
  · rw [data_3683.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3685. -/
theorem data_3685 : oddCount 3685 14 = 5 ∧
    acceleratedOrbit 14 3685 = 55 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3685) = 243 * m + 55 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3685
  rw [data_3685.1, data_3685.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3685) < 16384 * m + 3685 := by
  apply descent_of_endpoint
  · rw [data_3685.1]; exact data_3685.2.2
  · rw [data_3685.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3687. -/
theorem data_3687 : oddCount 3687 14 = 8 ∧
    acceleratedOrbit 14 3687 = 1477 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3687 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3687) = 6561 * m + 1477 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3687
  rw [data_3687.1, data_3687.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3687 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3687) < 16384 * m + 3687 := by
  apply descent_of_endpoint
  · rw [data_3687.1]; exact data_3687.2.2
  · rw [data_3687.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3691. -/
theorem data_3691 : oddCount 3691 14 = 7 ∧
    acceleratedOrbit 14 3691 = 493 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3691) = 2187 * m + 493 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3691
  rw [data_3691.1, data_3691.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3691) < 16384 * m + 3691 := by
  apply descent_of_endpoint
  · rw [data_3691.1]; exact data_3691.2.2
  · rw [data_3691.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3693. -/
theorem data_3693 : oddCount 3693 14 = 7 ∧
    acceleratedOrbit 14 3693 = 494 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3693) = 2187 * m + 494 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3693
  rw [data_3693.1, data_3693.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3693) < 16384 * m + 3693 := by
  apply descent_of_endpoint
  · rw [data_3693.1]; exact data_3693.2.2
  · rw [data_3693.2.1]; decide

end Collatz.Research.DescentAtlas.Batch164
