import Collatz.Research.DescentAtlas.Core

/-! Batch 237: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch237
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5313. -/
theorem data_5313 : oddCount 5313 14 = 8 ∧
    acceleratedOrbit 14 5313 = 2132 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5313 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5313) = 6561 * m + 2132 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5313
  rw [data_5313.1, data_5313.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5313 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5313) < 16384 * m + 5313 := by
  apply descent_of_endpoint
  · rw [data_5313.1]; exact data_5313.2.2
  · rw [data_5313.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5315. -/
theorem data_5315 : oddCount 5315 14 = 8 ∧
    acceleratedOrbit 14 5315 = 2132 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5315 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5315) = 6561 * m + 2132 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5315
  rw [data_5315.1, data_5315.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5315 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5315) < 16384 * m + 5315 := by
  apply descent_of_endpoint
  · rw [data_5315.1]; exact data_5315.2.2
  · rw [data_5315.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5317. -/
theorem data_5317 : oddCount 5317 14 = 6 ∧
    acceleratedOrbit 14 5317 = 238 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5317 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5317) = 729 * m + 238 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5317
  rw [data_5317.1, data_5317.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5317 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5317) < 16384 * m + 5317 := by
  apply descent_of_endpoint
  · rw [data_5317.1]; exact data_5317.2.2
  · rw [data_5317.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5319. -/
theorem data_5319 : oddCount 5319 14 = 8 ∧
    acceleratedOrbit 14 5319 = 2132 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5319 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5319) = 6561 * m + 2132 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5319
  rw [data_5319.1, data_5319.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5319 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5319) < 16384 * m + 5319 := by
  apply descent_of_endpoint
  · rw [data_5319.1]; exact data_5319.2.2
  · rw [data_5319.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5321. -/
theorem data_5321 : oddCount 5321 14 = 5 ∧
    acceleratedOrbit 14 5321 = 79 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5321 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5321) = 243 * m + 79 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5321
  rw [data_5321.1, data_5321.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5321 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5321) < 16384 * m + 5321 := by
  apply descent_of_endpoint
  · rw [data_5321.1]; exact data_5321.2.2
  · rw [data_5321.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5323. -/
theorem data_5323 : oddCount 5323 14 = 5 ∧
    acceleratedOrbit 14 5323 = 79 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5323 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5323) = 243 * m + 79 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5323
  rw [data_5323.1, data_5323.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5323 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5323) < 16384 * m + 5323 := by
  apply descent_of_endpoint
  · rw [data_5323.1]; exact data_5323.2.2
  · rw [data_5323.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5325. -/
theorem data_5325 : oddCount 5325 14 = 6 ∧
    acceleratedOrbit 14 5325 = 238 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5325 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5325) = 729 * m + 238 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5325
  rw [data_5325.1, data_5325.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5325 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5325) < 16384 * m + 5325 := by
  apply descent_of_endpoint
  · rw [data_5325.1]; exact data_5325.2.2
  · rw [data_5325.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5327. -/
theorem data_5327 : oddCount 5327 14 = 8 ∧
    acceleratedOrbit 14 5327 = 2134 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5327 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5327) = 6561 * m + 2134 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5327
  rw [data_5327.1, data_5327.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5327 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5327) < 16384 * m + 5327 := by
  apply descent_of_endpoint
  · rw [data_5327.1]; exact data_5327.2.2
  · rw [data_5327.2.1]; decide

end Collatz.Research.DescentAtlas.Batch237
