import Collatz.Research.DescentAtlas.Core

/-! Batch 86: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch086
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1911. -/
theorem data_1911 : oddCount 1911 14 = 7 ∧
    acceleratedOrbit 14 1911 = 256 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1911 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1911) = 2187 * m + 256 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1911
  rw [data_1911.1, data_1911.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1911 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1911) < 16384 * m + 1911 := by
  apply descent_of_endpoint
  · rw [data_1911.1]; exact data_1911.2.2
  · rw [data_1911.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1913. -/
theorem data_1913 : oddCount 1913 14 = 8 ∧
    acceleratedOrbit 14 1913 = 767 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1913 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1913) = 6561 * m + 767 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1913
  rw [data_1913.1, data_1913.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1913 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1913) < 16384 * m + 1913 := by
  apply descent_of_endpoint
  · rw [data_1913.1]; exact data_1913.2.2
  · rw [data_1913.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1921. -/
theorem data_1921 : oddCount 1921 14 = 7 ∧
    acceleratedOrbit 14 1921 = 257 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1921 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1921) = 2187 * m + 257 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1921
  rw [data_1921.1, data_1921.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1921 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1921) < 16384 * m + 1921 := by
  apply descent_of_endpoint
  · rw [data_1921.1]; exact data_1921.2.2
  · rw [data_1921.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1923. -/
theorem data_1923 : oddCount 1923 14 = 6 ∧
    acceleratedOrbit 14 1923 = 86 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1923 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1923) = 729 * m + 86 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1923
  rw [data_1923.1, data_1923.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1923 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1923) < 16384 * m + 1923 := by
  apply descent_of_endpoint
  · rw [data_1923.1]; exact data_1923.2.2
  · rw [data_1923.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1925. -/
theorem data_1925 : oddCount 1925 14 = 6 ∧
    acceleratedOrbit 14 1925 = 86 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1925 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1925) = 729 * m + 86 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1925
  rw [data_1925.1, data_1925.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1925 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1925) < 16384 * m + 1925 := by
  apply descent_of_endpoint
  · rw [data_1925.1]; exact data_1925.2.2
  · rw [data_1925.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1927. -/
theorem data_1927 : oddCount 1927 14 = 6 ∧
    acceleratedOrbit 14 1927 = 86 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1927 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1927) = 729 * m + 86 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1927
  rw [data_1927.1, data_1927.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1927 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1927) < 16384 * m + 1927 := by
  apply descent_of_endpoint
  · rw [data_1927.1]; exact data_1927.2.2
  · rw [data_1927.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1933. -/
theorem data_1933 : oddCount 1933 14 = 4 ∧
    acceleratedOrbit 14 1933 = 10 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1933 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1933) = 81 * m + 10 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1933
  rw [data_1933.1, data_1933.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1933 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1933) < 16384 * m + 1933 := by
  apply descent_of_endpoint
  · rw [data_1933.1]; exact data_1933.2.2
  · rw [data_1933.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1935. -/
theorem data_1935 : oddCount 1935 14 = 8 ∧
    acceleratedOrbit 14 1935 = 776 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1935 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1935) = 6561 * m + 776 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1935
  rw [data_1935.1, data_1935.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1935 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1935) < 16384 * m + 1935 := by
  apply descent_of_endpoint
  · rw [data_1935.1]; exact data_1935.2.2
  · rw [data_1935.2.1]; decide

end Collatz.Research.DescentAtlas.Batch086
