import Collatz.Research.DescentAtlas.Core

/-! Batch 232: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch232
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5199. -/
theorem data_5199 : oddCount 5199 14 = 7 ∧
    acceleratedOrbit 14 5199 = 695 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5199 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5199) = 2187 * m + 695 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5199
  rw [data_5199.1, data_5199.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5199 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5199) < 16384 * m + 5199 := by
  apply descent_of_endpoint
  · rw [data_5199.1]; exact data_5199.2.2
  · rw [data_5199.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5201. -/
theorem data_5201 : oddCount 5201 14 = 7 ∧
    acceleratedOrbit 14 5201 = 695 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5201 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5201) = 2187 * m + 695 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5201
  rw [data_5201.1, data_5201.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5201 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5201) < 16384 * m + 5201 := by
  apply descent_of_endpoint
  · rw [data_5201.1]; exact data_5201.2.2
  · rw [data_5201.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5205. -/
theorem data_5205 : oddCount 5205 14 = 5 ∧
    acceleratedOrbit 14 5205 = 80 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5205 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5205) = 243 * m + 80 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5205
  rw [data_5205.1, data_5205.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5205 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5205) < 16384 * m + 5205 := by
  apply descent_of_endpoint
  · rw [data_5205.1]; exact data_5205.2.2
  · rw [data_5205.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5207. -/
theorem data_5207 : oddCount 5207 14 = 6 ∧
    acceleratedOrbit 14 5207 = 233 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5207 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5207) = 729 * m + 233 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5207
  rw [data_5207.1, data_5207.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5207 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5207) < 16384 * m + 5207 := by
  apply descent_of_endpoint
  · rw [data_5207.1]; exact data_5207.2.2
  · rw [data_5207.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5209. -/
theorem data_5209 : oddCount 5209 14 = 6 ∧
    acceleratedOrbit 14 5209 = 232 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5209 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5209) = 729 * m + 232 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5209
  rw [data_5209.1, data_5209.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5209 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5209) < 16384 * m + 5209 := by
  apply descent_of_endpoint
  · rw [data_5209.1]; exact data_5209.2.2
  · rw [data_5209.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5213. -/
theorem data_5213 : oddCount 5213 14 = 6 ∧
    acceleratedOrbit 14 5213 = 233 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5213 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5213) = 729 * m + 233 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5213
  rw [data_5213.1, data_5213.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5213 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5213) < 16384 * m + 5213 := by
  apply descent_of_endpoint
  · rw [data_5213.1]; exact data_5213.2.2
  · rw [data_5213.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5215. -/
theorem data_5215 : oddCount 5215 14 = 8 ∧
    acceleratedOrbit 14 5215 = 2089 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5215 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5215) = 6561 * m + 2089 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5215
  rw [data_5215.1, data_5215.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5215 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5215) < 16384 * m + 5215 := by
  apply descent_of_endpoint
  · rw [data_5215.1]; exact data_5215.2.2
  · rw [data_5215.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5217. -/
theorem data_5217 : oddCount 5217 14 = 7 ∧
    acceleratedOrbit 14 5217 = 697 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5217 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5217) = 2187 * m + 697 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5217
  rw [data_5217.1, data_5217.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5217 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5217) < 16384 * m + 5217 := by
  apply descent_of_endpoint
  · rw [data_5217.1]; exact data_5217.2.2
  · rw [data_5217.2.1]; decide

end Collatz.Research.DescentAtlas.Batch232
