import Collatz.Research.DescentAtlas.Core

/-! Batch 109: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch109
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 2447. -/
theorem data_2447 : oddCount 2447 14 = 6 ∧
    acceleratedOrbit 14 2447 = 109 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2447 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2447) = 729 * m + 109 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2447
  rw [data_2447.1, data_2447.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2447 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2447) < 16384 * m + 2447 := by
  apply descent_of_endpoint
  · rw [data_2447.1]; exact data_2447.2.2
  · rw [data_2447.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2449. -/
theorem data_2449 : oddCount 2449 14 = 6 ∧
    acceleratedOrbit 14 2449 = 110 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2449 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2449) = 729 * m + 110 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2449
  rw [data_2449.1, data_2449.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2449 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2449) < 16384 * m + 2449 := by
  apply descent_of_endpoint
  · rw [data_2449.1]; exact data_2449.2.2
  · rw [data_2449.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2451. -/
theorem data_2451 : oddCount 2451 14 = 6 ∧
    acceleratedOrbit 14 2451 = 110 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2451 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2451) = 729 * m + 110 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2451
  rw [data_2451.1, data_2451.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2451 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2451) < 16384 * m + 2451 := by
  apply descent_of_endpoint
  · rw [data_2451.1]; exact data_2451.2.2
  · rw [data_2451.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2453. -/
theorem data_2453 : oddCount 2453 14 = 5 ∧
    acceleratedOrbit 14 2453 = 37 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2453 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2453) = 243 * m + 37 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2453
  rw [data_2453.1, data_2453.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2453 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2453) < 16384 * m + 2453 := by
  apply descent_of_endpoint
  · rw [data_2453.1]; exact data_2453.2.2
  · rw [data_2453.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2455. -/
theorem data_2455 : oddCount 2455 14 = 6 ∧
    acceleratedOrbit 14 2455 = 110 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2455 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2455) = 729 * m + 110 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2455
  rw [data_2455.1, data_2455.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2455 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2455) < 16384 * m + 2455 := by
  apply descent_of_endpoint
  · rw [data_2455.1]; exact data_2455.2.2
  · rw [data_2455.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2457. -/
theorem data_2457 : oddCount 2457 14 = 6 ∧
    acceleratedOrbit 14 2457 = 110 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2457 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2457) = 729 * m + 110 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2457
  rw [data_2457.1, data_2457.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2457 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2457) < 16384 * m + 2457 := by
  apply descent_of_endpoint
  · rw [data_2457.1]; exact data_2457.2.2
  · rw [data_2457.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2461. -/
theorem data_2461 : oddCount 2461 14 = 7 ∧
    acceleratedOrbit 14 2461 = 329 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2461 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2461) = 2187 * m + 329 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2461
  rw [data_2461.1, data_2461.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2461 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2461) < 16384 * m + 2461 := by
  apply descent_of_endpoint
  · rw [data_2461.1]; exact data_2461.2.2
  · rw [data_2461.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 2465. -/
theorem data_2465 : oddCount 2465 14 = 8 ∧
    acceleratedOrbit 14 2465 = 989 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_2465 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2465) = 6561 * m + 989 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 2465
  rw [data_2465.1, data_2465.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_2465 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 2465) < 16384 * m + 2465 := by
  apply descent_of_endpoint
  · rw [data_2465.1]; exact data_2465.2.2
  · rw [data_2465.2.1]; decide

end Collatz.Research.DescentAtlas.Batch109
