import Collatz.Research.DescentAtlas.Core

/-! Batch 6: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch006
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 115. -/
theorem data_115 : oddCount 115 14 = 7 ∧
    acceleratedOrbit 14 115 = 17 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_115 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 115) = 2187 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 115
  rw [data_115.1, data_115.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_115 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 115) < 16384 * m + 115 := by
  apply descent_of_endpoint
  · rw [data_115.1]; exact data_115.2.2
  · rw [data_115.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 117. -/
theorem data_117 : oddCount 117 14 = 5 ∧
    acceleratedOrbit 14 117 = 2 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_117 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 117) = 243 * m + 2 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 117
  rw [data_117.1, data_117.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_117 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 117) < 16384 * m + 117 := by
  apply descent_of_endpoint
  · rw [data_117.1]; exact data_117.2.2
  · rw [data_117.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 119. -/
theorem data_119 : oddCount 119 14 = 7 ∧
    acceleratedOrbit 14 119 = 17 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_119 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 119) = 2187 * m + 17 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 119
  rw [data_119.1, data_119.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_119 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 119) < 16384 * m + 119 := by
  apply descent_of_endpoint
  · rw [data_119.1]; exact data_119.2.2
  · rw [data_119.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 131. -/
theorem data_131 : oddCount 131 14 = 7 ∧
    acceleratedOrbit 14 131 = 20 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_131 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 131) = 2187 * m + 20 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 131
  rw [data_131.1, data_131.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_131 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 131) < 16384 * m + 131 := by
  apply descent_of_endpoint
  · rw [data_131.1]; exact data_131.2.2
  · rw [data_131.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 133. -/
theorem data_133 : oddCount 133 14 = 7 ∧
    acceleratedOrbit 14 133 = 20 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_133 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 133) = 2187 * m + 20 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 133
  rw [data_133.1, data_133.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_133 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 133) < 16384 * m + 133 := by
  apply descent_of_endpoint
  · rw [data_133.1]; exact data_133.2.2
  · rw [data_133.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 135. -/
theorem data_135 : oddCount 135 14 = 8 ∧
    acceleratedOrbit 14 135 = 56 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_135 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 135) = 6561 * m + 56 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 135
  rw [data_135.1, data_135.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_135 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 135) < 16384 * m + 135 := by
  apply descent_of_endpoint
  · rw [data_135.1]; exact data_135.2.2
  · rw [data_135.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 139. -/
theorem data_139 : oddCount 139 14 = 7 ∧
    acceleratedOrbit 14 139 = 19 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_139 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 139) = 2187 * m + 19 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 139
  rw [data_139.1, data_139.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_139 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 139) < 16384 * m + 139 := by
  apply descent_of_endpoint
  · rw [data_139.1]; exact data_139.2.2
  · rw [data_139.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 141. -/
theorem data_141 : oddCount 141 14 = 4 ∧
    acceleratedOrbit 14 141 = 1 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_141 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 141) = 81 * m + 1 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 141
  rw [data_141.1, data_141.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_141 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 141) < 16384 * m + 141 := by
  apply descent_of_endpoint
  · rw [data_141.1]; exact data_141.2.2
  · rw [data_141.2.1]; decide

end Collatz.Research.DescentAtlas.Batch006
