import Collatz.Research.DescentAtlas.Core

/-! Batch 157: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch157
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 3513. -/
theorem data_3513 : oddCount 3513 14 = 6 ∧
    acceleratedOrbit 14 3513 = 157 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3513 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3513) = 729 * m + 157 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3513
  rw [data_3513.1, data_3513.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3513 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3513) < 16384 * m + 3513 := by
  apply descent_of_endpoint
  · rw [data_3513.1]; exact data_3513.2.2
  · rw [data_3513.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3515. -/
theorem data_3515 : oddCount 3515 14 = 7 ∧
    acceleratedOrbit 14 3515 = 470 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3515 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3515) = 2187 * m + 470 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3515
  rw [data_3515.1, data_3515.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3515 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3515) < 16384 * m + 3515 := by
  apply descent_of_endpoint
  · rw [data_3515.1]; exact data_3515.2.2
  · rw [data_3515.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3517. -/
theorem data_3517 : oddCount 3517 14 = 7 ∧
    acceleratedOrbit 14 3517 = 470 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3517 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3517) = 2187 * m + 470 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3517
  rw [data_3517.1, data_3517.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3517 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3517) < 16384 * m + 3517 := by
  apply descent_of_endpoint
  · rw [data_3517.1]; exact data_3517.2.2
  · rw [data_3517.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3525. -/
theorem data_3525 : oddCount 3525 14 = 6 ∧
    acceleratedOrbit 14 3525 = 161 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3525 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3525) = 729 * m + 161 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3525
  rw [data_3525.1, data_3525.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3525 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3525) < 16384 * m + 3525 := by
  apply descent_of_endpoint
  · rw [data_3525.1]; exact data_3525.2.2
  · rw [data_3525.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3527. -/
theorem data_3527 : oddCount 3527 14 = 6 ∧
    acceleratedOrbit 14 3527 = 157 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3527 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3527) = 729 * m + 157 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3527
  rw [data_3527.1, data_3527.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3527 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3527) < 16384 * m + 3527 := by
  apply descent_of_endpoint
  · rw [data_3527.1]; exact data_3527.2.2
  · rw [data_3527.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3529. -/
theorem data_3529 : oddCount 3529 14 = 7 ∧
    acceleratedOrbit 14 3529 = 472 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3529 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3529) = 2187 * m + 472 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3529
  rw [data_3529.1, data_3529.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3529 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3529) < 16384 * m + 3529 := by
  apply descent_of_endpoint
  · rw [data_3529.1]; exact data_3529.2.2
  · rw [data_3529.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3531. -/
theorem data_3531 : oddCount 3531 14 = 8 ∧
    acceleratedOrbit 14 3531 = 1417 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3531 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3531) = 6561 * m + 1417 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3531
  rw [data_3531.1, data_3531.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3531 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3531) < 16384 * m + 3531 := by
  apply descent_of_endpoint
  · rw [data_3531.1]; exact data_3531.2.2
  · rw [data_3531.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 3533. -/
theorem data_3533 : oddCount 3533 14 = 5 ∧
    acceleratedOrbit 14 3533 = 53 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_3533 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3533) = 243 * m + 53 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 3533
  rw [data_3533.1, data_3533.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_3533 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 3533) < 16384 * m + 3533 := by
  apply descent_of_endpoint
  · rw [data_3533.1]; exact data_3533.2.2
  · rw [data_3533.2.1]; decide

end Collatz.Research.DescentAtlas.Batch157
