import Collatz.Research.DescentAtlas.Core

/-! Batch 56: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch056
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 1251. -/
theorem data_1251 : oddCount 1251 14 = 5 ∧
    acceleratedOrbit 14 1251 = 20 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1251 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1251) = 243 * m + 20 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1251
  rw [data_1251.1, data_1251.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1251 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1251) < 16384 * m + 1251 := by
  apply descent_of_endpoint
  · rw [data_1251.1]; exact data_1251.2.2
  · rw [data_1251.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1253. -/
theorem data_1253 : oddCount 1253 14 = 8 ∧
    acceleratedOrbit 14 1253 = 506 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1253 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1253) = 6561 * m + 506 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1253
  rw [data_1253.1, data_1253.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1253 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1253) < 16384 * m + 1253 := by
  apply descent_of_endpoint
  · rw [data_1253.1]; exact data_1253.2.2
  · rw [data_1253.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1257. -/
theorem data_1257 : oddCount 1257 14 = 6 ∧
    acceleratedOrbit 14 1257 = 56 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1257 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1257) = 729 * m + 56 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1257
  rw [data_1257.1, data_1257.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1257 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1257) < 16384 * m + 1257 := by
  apply descent_of_endpoint
  · rw [data_1257.1]; exact data_1257.2.2
  · rw [data_1257.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1259. -/
theorem data_1259 : oddCount 1259 14 = 8 ∧
    acceleratedOrbit 14 1259 = 505 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1259 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1259) = 6561 * m + 505 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1259
  rw [data_1259.1, data_1259.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1259 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1259) < 16384 * m + 1259 := by
  apply descent_of_endpoint
  · rw [data_1259.1]; exact data_1259.2.2
  · rw [data_1259.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1261. -/
theorem data_1261 : oddCount 1261 14 = 5 ∧
    acceleratedOrbit 14 1261 = 19 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1261 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1261) = 243 * m + 19 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1261
  rw [data_1261.1, data_1261.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1261 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1261) < 16384 * m + 1261 := by
  apply descent_of_endpoint
  · rw [data_1261.1]; exact data_1261.2.2
  · rw [data_1261.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1265. -/
theorem data_1265 : oddCount 1265 14 = 5 ∧
    acceleratedOrbit 14 1265 = 19 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1265 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1265) = 243 * m + 19 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1265
  rw [data_1265.1, data_1265.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1265 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1265) < 16384 * m + 1265 := by
  apply descent_of_endpoint
  · rw [data_1265.1]; exact data_1265.2.2
  · rw [data_1265.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1267. -/
theorem data_1267 : oddCount 1267 14 = 7 ∧
    acceleratedOrbit 14 1267 = 170 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1267 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1267) = 2187 * m + 170 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1267
  rw [data_1267.1, data_1267.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1267 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1267) < 16384 * m + 1267 := by
  apply descent_of_endpoint
  · rw [data_1267.1]; exact data_1267.2.2
  · rw [data_1267.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 1269. -/
theorem data_1269 : oddCount 1269 14 = 5 ∧
    acceleratedOrbit 14 1269 = 19 ∧ 243 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_1269 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1269) = 243 * m + 19 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 1269
  rw [data_1269.1, data_1269.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_1269 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 1269) < 16384 * m + 1269 := by
  apply descent_of_endpoint
  · rw [data_1269.1]; exact data_1269.2.2
  · rw [data_1269.2.1]; decide

end Collatz.Research.DescentAtlas.Batch056
