import Collatz.Research.DescentAtlas.Core

/-! Batch 253: eight disjoint odd residue classes modulo 16384.
Generated by scripts/descent_atlas.py. Every numerical claim uses kernel decide.
These are finite-horizon certificates, not a proof of universal descent. -/
namespace Collatz.Research.DescentAtlas.Batch253
open Collatz.Research.DescentAtlas

/-- Exact parity count, endpoint, and contracting multiplier for residue 5681. -/
theorem data_5681 : oddCount 5681 14 = 8 ∧
    acceleratedOrbit 14 5681 = 2278 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5681 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5681) = 6561 * m + 2278 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5681
  rw [data_5681.1, data_5681.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5681 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5681) < 16384 * m + 5681 := by
  apply descent_of_endpoint
  · rw [data_5681.1]; exact data_5681.2.2
  · rw [data_5681.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5683. -/
theorem data_5683 : oddCount 5683 14 = 8 ∧
    acceleratedOrbit 14 5683 = 2278 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5683 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5683) = 6561 * m + 2278 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5683
  rw [data_5683.1, data_5683.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5683 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5683) < 16384 * m + 5683 := by
  apply descent_of_endpoint
  · rw [data_5683.1]; exact data_5683.2.2
  · rw [data_5683.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5685. -/
theorem data_5685 : oddCount 5685 14 = 4 ∧
    acceleratedOrbit 14 5685 = 29 ∧ 81 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5685) = 81 * m + 29 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5685
  rw [data_5685.1, data_5685.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5685 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5685) < 16384 * m + 5685 := by
  apply descent_of_endpoint
  · rw [data_5685.1]; exact data_5685.2.2
  · rw [data_5685.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5689. -/
theorem data_5689 : oddCount 5689 14 = 7 ∧
    acceleratedOrbit 14 5689 = 760 ∧ 2187 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5689 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5689) = 2187 * m + 760 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5689
  rw [data_5689.1, data_5689.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5689 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5689) < 16384 * m + 5689 := by
  apply descent_of_endpoint
  · rw [data_5689.1]; exact data_5689.2.2
  · rw [data_5689.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5691. -/
theorem data_5691 : oddCount 5691 14 = 8 ∧
    acceleratedOrbit 14 5691 = 2281 ∧ 6561 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5691) = 6561 * m + 2281 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5691
  rw [data_5691.1, data_5691.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5691 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5691) < 16384 * m + 5691 := by
  apply descent_of_endpoint
  · rw [data_5691.1]; exact data_5691.2.2
  · rw [data_5691.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5693. -/
theorem data_5693 : oddCount 5693 14 = 6 ∧
    acceleratedOrbit 14 5693 = 254 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5693) = 729 * m + 254 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5693
  rw [data_5693.1, data_5693.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5693 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5693) < 16384 * m + 5693 := by
  apply descent_of_endpoint
  · rw [data_5693.1]; exact data_5693.2.2
  · rw [data_5693.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5697. -/
theorem data_5697 : oddCount 5697 14 = 6 ∧
    acceleratedOrbit 14 5697 = 254 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5697 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5697) = 729 * m + 254 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5697
  rw [data_5697.1, data_5697.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5697 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5697) < 16384 * m + 5697 := by
  apply descent_of_endpoint
  · rw [data_5697.1]; exact data_5697.2.2
  · rw [data_5697.2.1]; decide

/-- Exact parity count, endpoint, and contracting multiplier for residue 5699. -/
theorem data_5699 : oddCount 5699 14 = 6 ∧
    acceleratedOrbit 14 5699 = 254 ∧ 729 < 16384 := by
  decide

/-- The orbit formula covers every member of this infinite arithmetic progression. -/
theorem affine_5699 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5699) = 729 * m + 254 := by
  have h := Congruence.accOrbit_pow_two_mul_add 14 m 5699
  rw [data_5699.1, data_5699.2.1] at h
  exact h

/-- Strict descent for all class indices, including the representative itself. -/
theorem descent_5699 (m : Nat) :
    acceleratedOrbit 14 (16384 * m + 5699) < 16384 * m + 5699 := by
  apply descent_of_endpoint
  · rw [data_5699.1]; exact data_5699.2.2
  · rw [data_5699.2.1]; decide

end Collatz.Research.DescentAtlas.Batch253
